### ISSUE TITLE
Autowalk changes 4.4-4.5

### ISSUE THREAD

**Issue by vilacelestin** [ImpactDevelopment/ImpactClient#1001]
I've noticed that with the new changes to Autowalk from 4.4 to 4.5 AFK auto-walking no longer  works for extended periods. I.e after 20-30 min or so AFK autowalk just switches off. I originally though this might be an issue with the server or new computer, but confirmed it was an issue with impact version by reverting to 4.4.  This doesn't depend on whether autowalk is basic or smart.   Hope this can be addressed for 4.6.

Server - (2b2t)

**Comment by lemonsucks** [comment]
thanks for the issue we will resolve it eventually

**Comment by leijurv** [comment]
i don't believe you that it doesn't depend on whether it's basic or smart

**Comment by leijurv** [comment]
4.4 would just keep calculating a path even when it failed, 4.5 lets you know in chat and stops

**Comment by leijurv** [comment]
but only in smart

**Comment by leijurv** [comment]
ok i will add an option "persistent" to auto walk smart where it will literally never stop pathing

**Comment by leijurv** [comment]
Added it in 4.6

**Comment by leijurv** [comment]
This should be helpful on servers that are unimaginably laggy and let you walk all the way to the edge of loaded chunks
