### ISSUE TITLE
Anti-GhostBlock

### ISSUE THREAD

**Issue by usereewrjrjeejr** [ImpactDevelopment/ImpactClient#1004]
Add A dynamic mode for Anti-GhostBlock that turns on/off based on the TPS

**Comment by leijurv** [comment]
Anti Desync has been completely revamped in 4.6, and works properly now. https://impactdevelopment.github.io/changelog

**Comment by usereewrjrjeejr** [comment]
Will it be dynamic tho?

**Comment by leijurv** [comment]
no, but it's no longer necessary. the old one was really fucked and would have benefitted from something like that
