### ISSUE TITLE
Baritone and .commands problems

### ISSUE THREAD

**Issue by TheGamingTitan11** [ImpactDevelopment/ImpactClient#1005]
So Im having alot of trouble on Mineplex because # is used for team chat, but baritone blocks that. Any way to change the starting key of Baritone so this issue doesnt happen? Also, alot of people constatnly ask me to type .say to prove I dont hack, but I cant because the commands always come up. Any way to get around this? I know there used to be .say "yada yada" but that isnt there anymore. thanks, would really appreciate it.

**Comment by ZeroMemes** [comment]
To do the equivalent of ``.say``, start the message with a backslash ``\``. For example ``\.legit`` would say ``.legit`` in the chat.

As for baritone, use the command ``.b prefixControl`` to disable the usage of the **#** prefix.
