### ISSUE TITLE
Allowplace message

### ISSUE THREAD

**Issue by Michael3038** [ImpactDevelopment/ImpactClient#1006]
If you have allowplace under baritone DISABLED, blocks in your inventory, but not in your hotbar, enabling Auto Walk (at least on Smart) will bring up the message "allowplace is on..." and the rest of the hotbar inventory thing. Simple bug.

**Comment by usereewrjrjeejr** [comment]
So passive aggressive 😍😍😍

**Comment by leijurv** [comment]
@zeromemes throw in a `&& BaritoneAPI.getSettings().allowPlace.value` in Baritone.java

**Comment by SuperOP535** [comment]
BREAKING NEWS: impcat source code #leaked by baritone creator

**Comment by leijurv** [comment]
done in 4.6 or whatever
