### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by lemonsucks** [ImpactDevelopment/ImpactClient#1008]
![acacia_boat](https://user-images.githubusercontent.com/25157685/54648049-39a41c00-4a7b-11e9-8055-faf0866d3cfb.png)
![spruce_boat](https://user-images.githubusercontent.com/25157685/54648061-41fc5700-4a7b-11e9-9824-e3be458972ef.png)
![destroy_stage_9](https://user-images.githubusercontent.com/25157685/54648071-4b85bf00-4a7b-11e9-9654-fdc99a01d901.png) BOAT MACHINE BROKE
![dropper_front_horizontal](https://user-images.githubusercontent.com/25157685/54648108-5e988f00-4a7b-11e9-9e2c-762760993f8d.png)

**Comment by ZeroMemes** [comment]
literally shut the fuck up
