### ISSUE TITLE
Old Coordinates System

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#101]
Please add the Old Coordinates System again, the new takes up too much space, and is really messy.

New:
XYZ: x, y, z
XYZ: netherx, nethery, netherz

Old (wanted):
X: x (netherx)
Y: y (nethery)
Z: z (netherz)

Especially when the Coords are really high, it takes up too much space.

Example:

XYZ: 7428521, 254, 9582256
XYZ: 59428168, 254, 76658048

Old System:

X: 7428521 (59428168)
Y: 254 (254)
Z: 9582256 (76658048)

Over all, the old System is much more clear, and overall more userfriendly, and since this Client is made to be userfriendy, i'd like to see this old system again, or atleast, an switch so you can switch between the old or new coordinates system.

**Comment by ZeroMemes** [comment]
Added in 4.1 as coordinate display modes
