### ISSUE TITLE
cant launch impact

### ISSUE THREAD

**Issue by ZombieAssassin5** [ImpactDevelopment/ImpactClient#1010]
I can't launch impact 4.5, i keep getting the  error message "Failed to download file. discord-rpc-release-v3.3.0.jar" I tried redownloading impact but that didn't work

- Impact Version:  4.5
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods:  none 
- Operating System:  windows 10 64bit

**Comment by LeafHacker** [comment]
This is caused by Bintray's maven repo having some issues. Should work fine when they sort their server out, just retry in a few mins.
