### ISSUE TITLE
Main Menu background scuffed in 1.13

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#1013]
Something is broke in either GuiMixinMainMenu or elsewhere in the render loop, except when `custom` is true and `background` false the background is black.

**Comment by leijurv** [comment]
not 4 me

**Comment by LeafHacker** [comment]
Hm maybe it is platform dependant too...

**Comment by LeafHacker** [comment]
I can reproduce on the beta release.

- Launch game
- Custom menu with vanilla panorama background shows
  - Panorama renders correctly
- Open ClickGUI
- Toggle `background`
  - nothing happens...
- Toggle `custom`
  - Switches to vanilla main menu
  - Background is black
- Toggle `background` again
  - Background still black.
- Toggle `custom` again
  - Menu switches to Custom
  - Background renders the vanilla panorama

**Comment by LeafHacker** [comment]
Fixed by ImpactDevelopment/Impact@0b413c7ff75eb97c6c6333dc816816a384cc37fd thx @leijurv
