### ISSUE TITLE
Why does the GUI look so weird now?

### ISSUE THREAD

**Issue by TheGamingTitan11** [ImpactDevelopment/ImpactClient#1021]
Hello, Im playing impact as regular on my PC but when I open up the latest version )4.5) it looks extremely weird. When i go to multiplayer, it has a brown brick theme in the background. I click on any server and the crosshair is a circular snowflake looking icon. I don't like this look, please someone help me on how to fix it, thank you :)

**Comment by EmeraldSnorlax** [comment]
its your texturepack fag

**Comment by SuperOP535** [comment]
😂
