### ISSUE TITLE
Cant open containers

### ISSUE THREAD

**Issue by BolbiBoi** [ImpactDevelopment/ImpactClient#1025]
I can't open any GUI's with items in my hand, I can't shoot bows, and when I try to open GUI's with a block it will just place it. (When I say GUI's I mean chests, crafting tables, furnaces etc.)

I have not crashed yet

I am using Impact 1.12.2

No optifine
No lite loader
No additional clients

I have the mods Anti Hunger (Effective), Middle click friend, Auto Reconnect, Criticals (packet), Velocity 0%0%, Auto Totem 0, Log Position, Radar (static), Camera clip, ESP (Shader),
 Storage ESP, Nametags, Anti Blind, Auto Eat, Respawn, No push, No slow, Tracers, Sneak, Light
 
I am using Windows 10 64 bit

**Comment by ZeroMemes** [comment]
What Impact version was this experienced on?

**Comment by leijurv** [comment]
bet ur holding shift

**Comment by 0-x-2-2** [comment]
![image](https://user-images.githubusercontent.com/9968651/54877278-9e040a00-4df2-11e9-8f0e-3b426f467a5f.png)
based

**Comment by leijurv** [comment]
bro ur sneak module is holding shift. you're shift right clicking. lol
