### ISSUE TITLE
Let velocity go beyond 100 and below 0

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#1026]
### What is your suggestion?
 The title.

### Why is it useful?
When fighting you actually want to take more KB in 1.9. Makes it easier to get out of the combo and punish fools.
Could also be used to jump further and get away from people.

**Comment by ZeroMemes** [comment]
This is why the sub-option for both "Horizontal" and "Vertical" called "Multiplier" exists.
