### ISSUE TITLE
1.13.2 Optifine Skin Customisation bugged buttons

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#1028]
### What happens?
Impact messes up the new button which was added in 1.13.2 Optifine.

![image](https://user-images.githubusercontent.com/23565638/55041536-63ce7e80-5025-11e9-91ae-88962f141ec1.png)

### Exact steps to reproduce?
Go into skin customisation.

### Yes.
- Impact Version: 1.13.2 4.6 beta
- Using Optifine? Yes, sir
- Using LiteLoader? No, sir
- Enabled mods: None, sir
- Operating System: Windows 10

**Comment by LeafHacker** [comment]
This is actuary two separate issues. Cape toggle crash and optifine button bug

**Comment by MastaNub** [comment]
Not anymore.

**Comment by LeafHacker** [comment]
Fixed in 4.6
