### ISSUE TITLE
4.6, Cape missing

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactClient#1029]
### What happens?
Can't see my cape that I paid real money for.
https://i.imgur.com/hpwRTof.png
### Exact steps to reproduce?
Join a game and F5

- Impact Version: 4.6 1.13
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: https://i.imgur.com/fbTBcae.png
- Operating System: Windows 10

</details>

**Comment by ZeroMemes** [comment]
Must be an issue with the texture loading, it's changed in 4.6 and my attempted fix might not have worked.

**Comment by MastaNub** [comment]
Also optifine cape is missing for some odd reason in 1.13 too.

**Comment by ZeroMemes** [comment]
This was fixed at release for 4.6, but the textures were scaled wrong. The scaling has been fixed in 4.6 patch 3.
