### ISSUE TITLE
Clicking period opens chat and puts two ".." in chat.

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#1031]
### What happens?
The title.

### Exact steps to reproduce?

Hit period.

**Comment by LeafHacker** [comment]
Intended behaviour is that it opens chat and types a single `.`. Are you sure you're not somehow double clicking or holding down the key?

**Comment by LeafHacker** [comment]
Never mind, able to reproduce on my machine

**Comment by LeafHacker** [comment]
Caused by a 1.13 change to how key events are handled. We now need to cancel key events we've handled or Minecraft will handle them after us too.

**Comment by LeafHacker** [comment]
Fixed in 4.6 (next beta patch or whatever)
