### ISSUE TITLE
Freecam crashing

### ISSUE THREAD

**Issue by Slimerblue22** [ImpactDevelopment/ImpactClient#1046]
Freecam will crash when enabled in some situations. Not sure exactly what but it seems to depend on what's in the world you have loaded. For example it would work with some singleplayer worlds and then crash on others. Same with multiplayer, nothing else is on mod wise (other than some hud things like cords)
Crash report: 
[crash-2019-03-28_22.30.51-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3020867/crash-2019-03-28_22.30.51-client.txt)

**Comment by leijurv** [comment]
have seen this a whole bunch of times, only once myself though. seems totally random

**Comment by ZeroMemes** [comment]
What version was this on? @Slimerblue22

**Comment by Slimerblue22** [comment]
4.5

**Comment by LeafHacker** [comment]
Can this be reproduced in 4.6?

**Comment by Slimerblue22** [comment]
Seems to be fixed in 4.6
