### ISSUE TITLE
Options for CrystalAura. Airjump & LiquidVision.

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#105]
>Add options for CrystalAura so we can modify the Fov, Reach and Speed.

>You should add AirJump, it's a very useful module... especially on servers that use NCP, because if you take damage, AirJump becomes a flight.

>And you could re-add the liquidvision... it's very useful.

**Comment by LeafHacker** [comment]
Please see the [README](https://github.com/ImpactDevelopment/ImpactClient#bugs).

Closing as invalid because multiple topics are covered, but please feel free to open separate issues.
