### ISSUE TITLE
Nametag SUGGESTION

### ISSUE THREAD

**Issue by Zane4077** [ImpactDevelopment/ImpactClient#1051]
Make nametag size relative to player size. Ideally this would be an optional though the GUI.

To prevent it from bring unreadable, you could add a min and Max size the nametag could be.

Also to make it more customizable, you could add a customizable scaling factor

**Comment by LeafHacker** [comment]
yeah tbh having all nametags the same size no matter how far away the entity is gets pretty cluttered pretty fast

**Comment by Zane4077** [comment]
Awesome! Thanks!

**Comment by leijurv** [comment]
Note that this is already the case for item nametags and tamed nametags.

**Comment by LeafHacker** [comment]
Is it worth having the option for the current behaviour or should it just be changed to relative sizing?

**Comment by leijurv** [comment]
I just realized that the "min dist" and "max dist" options are suboptions under Items while they really affect both Items and Tamed... whoops.

I think we should move "min dist" and "max dist" to be top level options under nametags, and add a boolean option of "scale player tags" which is just whether it scales like items or if it stays at constant size. And add suboptions under items and tamed to respect this as well.

**Comment by LeafHacker** [comment]
In the interest of avoiding cluttered UI, is it worth dumbing it down to just a single option shared between all nametag variants?

**Comment by leijurv** [comment]
Added in 4.7
