### ISSUE TITLE
Wither names not appearing

### ISSUE THREAD

**Issue by Relidom** [ImpactDevelopment/ImpactClient#1056]
In the newest version of Impact, 4.6, I noticed that wither names & health bar weren't appearing on screen, and so I switched versions just to see if it was either the version or the server I was in, and in fact it was the updated version of impact. I mean, it's not a CRAZY HUGE issue, but it's something I think should be at least noticed.

[Suggestion as well involving said topic]
Hey, but I got an idea from this. Since some servers, like anarchy server, may spam withers and your screen can get cluttered with wither bars like what I mentioned, if it's not already a feature, maybe make it where you can enable and disable wither names, put the wither names somewhere where they aren't cluttering the screen, stack wither names on each other if there's more than 1 with the same name, or even all of the above.

Whatever can be done, i hope that whatever bugs get fixed and maybe this as well, if it wasn't intended to happen or is just a test, since this version is in beta at the moment. Thanks for bringing such a useful client, especially how it's free.

**Comment by LeafHacker** [comment]
Please open the bossbar collate/antispam as a new issue, I've actually been planning on adding that for a while.

Double check you AntiOverlay settings, as that is the intended behaviour of the anti bossbar option. If you don't have it enabled there may be a bug where it is always on or something.

**Comment by leijurv** [comment]
Yes, added in 4.6 is an option on AntiOverlay to also remove boss bars. Just turn it off lol. (where "it" refers to either Anti Overlay or the Boss Bars suboption)
