### ISSUE TITLE
Update the MultiMC wiki article

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ImpactDevelopment/ImpactClient#1059]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Installation#installing-impact-with-multimc

Add that it works fine with 4.6 as long as you use Common Sense (tm) and replace all mentions of 4.5 with 4.6

**Comment by LeafHacker** [comment]
Feel free to open a PR ;-)

**Comment by zPeanut** [comment]
this has been done now, closing
