### ISSUE TITLE
Cape texture bug

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactClient#1060]
### What happens?
The cape's texture is different in 1.13 compare to 1.12.
Paid over $5 for a broken cape 😭
1.13.2 - https://i.imgur.com/vmxnvN2.png
1.12.2 - https://i.imgur.com/VIJNvuv.png
### Exact steps to reproduce?

- Join game
- F5
- Use eyes

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 1.13.2
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods: 
```
ESP
Crosshair+
HUD
Auto chest
Anti Desync
Anti vanish
Auto cheat
Discord RPC
Criticals
Hitbox
Velocity
Franky
```
- Operating System:  Win10

</details>

**Comment by 0-x-2-2** [comment]
😻

**Comment by leijurv** [comment]
@ZeroMemes this is fixed i believe?

**Comment by ZeroMemes** [comment]
Yeah I fixed this
