### ISSUE TITLE
Potion Effects icons in the top right corner are invisible

### ISSUE THREAD

**Issue by 1butler1** [ImpactDevelopment/ImpactClient#1064]
### What happens?
The potion effects are not visible in the upper right hand corner, therefor creating a space above the module list, if you have any potion effects.

1.13.2: http://i.imgur.com/z2VbT7w.png
1.12.2: http://i.imgur.com/VQxWZn6.png

### Exact steps to reproduce?

- Join a server/singleplayer world in which you have potion effects
- You won't see the potion effects in the corner and there's about a half inch gap above your module list in the HUD

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.13.2
- Using Optifine? Yes
- Using LiteLoader?  No
- Enabled mods: Hud, StorageESP, Nametags, AutoTool, Light
- Operating System: Windows 10 64-bit

</details>

**Comment by LeafHacker** [comment]
The gap is intended\*, the bug is that the effect icons aren't rendered for some reason.

\* We make a gap whenever the player has any effects active so that the HUD doesn't draw over the icons.

**Comment by 1butler1** [comment]
Yeah I figured that, the gap just looks ugly without the rendered icons.

**Comment by ZeroMemes** [comment]
Found the issue. While the method we were using before, ``doesShowParticles``, exists in 1.13.2, it is no longer used in the code for rendering the potion effect icons. Rather, ``isShowIcon`` is used. This has been fixed in the upcoming patch for 4.6.
