### ISSUE TITLE
ClickGUI search

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#1068]
Just an idea, not sure if this will actually happen.

The idea is when you open ClickGUI it functions as normal, but when you type normally (i.e. not in chat or in the process of setting a keybind) it will filter out modules that don't match what's typed so far. This could be in the form of removing them, or just darkening their text color. Perhaps it could also search for options? Or maybe it could even auto scroll each pane down to the first match?

**Comment by ScanmanTM** [comment]
Duplicate of #160?

**Comment by leijurv** [comment]
thank you good point
