### ISSUE TITLE
Getting ouched on blocks' corners likely due to speed & going downward

### ISSUE THREAD

**Issue by DeeFeeCee** [ImpactDevelopment/ImpactClient#1072]
Ugghhhhh
I made this whole thing on mobile only for the browser to throw an hour away. Yay. Dumb stupid bluh.

Short: 1.12.2 Windows 10 64 newest version Optifine added but problem persists without it

Spider & step may conflict
Jesus & no slow (water) may conflict
Baritone doesn't know how to deal with speed mods or work with no fall smartly.
I heard anti hunger messed with health? What's up with that? Is that why falling down diagonally kills me sometimes?

Make mods toggle-able to be all visible or only what's selected to be visible to make troubleshooting easier
Make mod list text & position customizable to actually display all the mods
Make it easier to select which blocks are displayed with xray, which can be tossed away with Baritone, which can be sought, etc.
List the commands for Baritone, etc. somewhere within Impact (#help, or something)—goto & stop aren't noted clearly (or maybe I'm just tired & forgot how I know these things. Let me know if I'm delusional on this one or just ignorant (chances are, if I don't know where to find it, going through all the options & editing JSON files to integrate Optifine into Impact in what I dubbed "Optipact", there are others))

No slow in water makes too many bubbles
Flying got me killed in single player vanilla
-Maybe I'll elaborate once I'm not still up at 5 am

**Comment by ScanmanTM** [comment]
Please make one issue per feature/bug. This is too hard to keep track of.

**Comment by leijurv** [comment]
Please make individual issues for your many suggestions and issues.

**Comment by DeeFeeCee** [comment]
Can I update a closed issue?

**Comment by ScanmanTM** [comment]
Create a new one, one feature/bug per issue.
