### ISSUE TITLE
Waypoints

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#1080]
Simple, just a module which lets you add or remove waypoints, (((maybe?))) baritone integration, and show tracers to the goal.

**Comment by uwuplant** [comment]
(this might not be what you mean)

Baritone can already do that with the command `save`.

**Comment by EvilSourcerer** [comment]
no it needs to have tracers 🦍

**Comment by uwuplant** [comment]
a

**Comment by TotallyNotLeet** [comment]
+1

**Comment by LeafHacker** [comment]
Duplicate of #203
