### ISSUE TITLE
-Baritone Suggestion- Death Waypoints

### ISSUE THREAD

**Issue by HidekiTojo** [ImpactDevelopment/ImpactClient#1081]
I would love to have a death waypoint added to waypoints in baritone. This, which is self explanatory, would allow you to go back to your death if you were doing a ".b goto 10000000" in the nether and fall into lava.

**Comment by LeafHacker** [comment]
Is there a reason this is here an not over at [baritone](https://github.com/cabaletta/baritone/)?

**Comment by leijurv** [comment]
This exists? `.b goto death`?
Also `.b list deaths` will show coords?
