### ISSUE TITLE
#Help not that helpful

### ISSUE THREAD

**Issue by DeeFeeCee** [ImpactDevelopment/ImpactClient#1085]
### What happens?

Default chat (unaltered by Optifine) cuts off some (most?) of the text in #help. What's kind of annoying is that aliases like #list & such are listed on separate lines.
Instead of this:
#abc does bluh
#def (same as abc)

Do this:
#abc #def does bluh

### Exact steps to reproduce?

Startup Vanilla MC with only Impact
Go in game
#help
<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 for 1.12.2
- Using Optifine?  Yes (doesn't matter)
- Using LiteLoader?  No
- Enabled mods:  Doesn't matter
- Operating System:  Windows 10 64bit
- Screen Resolution: 1366 by 768

</details>

**Comment by LeafHacker** [comment]
#help is a baritone thing, should be reported there not here.

Also chat is able to scroll so....

**Comment by DeeFeeCee** [comment]
You can scroll chat? How? Is that a Vanilla thing?

**Comment by 0-x-2-2** [comment]
yes

**Comment by DeeFeeCee** [comment]
Tried it just now. I've played Bedrock for so long… thanks for the tip.
