### ISSUE TITLE
How do new users know how to use Impact?

### ISSUE THREAD

**Issue by DeeFeeCee** [ImpactDevelopment/ImpactClient#1088]
### What happens:

Boi goes to get hack
Finds one with good reviews on Yelp
Downloads it
Selects blocks for Xray
*Wonders how to select blocks to eject, throw away (Baritone), etc.*
*Wonders what the syntax is to find the way back to where he died*
Wants to add Optifine because it sounds cool
"Literally a tutorial can be found **here**† and you would of [sic] seen optifine.md or if you're in the [D]iscord you [sic] and asked the bot would of [sic] replied."
†link to https://github.com/ImpactDevelopment/ImpactClient
Link (at least on mobile) doesn't seem to have anything on Optifine. It isn't obvious & I had to edit JSON files to get it done. It's not that difficult, but not everyone knows to do that, or where to find what, or what the difference is between WiFi & internet.
### Exact steps to reproduce?
1) find a mate
2) consent

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2 & 1.13.2 (doesn't matter)
- Using Optifine?  Yes (luckily)
- Using LiteLoader?  No (I don't know what it is, so should I?)
- Enabled mods:  n/a
- Operating System:  Win10 64b (doesn't matter)
- GitHub Main Access: iPhone 8 iOS 12.2
- Cool name for MC profile that merges Impact & Optifine: Optipact

</details>

**Comment by ScanmanTM** [comment]
What even is this suggestion/bug? There is a wiki telling how to install optifine and such. 
Like even on the website there is a discord link where people can join and get help.

> or what the difference is between WiFi & internet.

What does this even have to do with impact?

<sub><sub>This post seems lowest of the lowest of quality<sub><sub>

**Comment by usereewrjrjeejr** [comment]
Meme

**Comment by LeafHacker** [comment]
This is the kinda thing that could lead to blocking from the ImpactDevelopment github...

**Comment by leijurv** [comment]
LOL

**Comment by 0-x-2-2** [comment]
wtf
