### ISSUE TITLE
Re:#1088

### ISSUE THREAD

**Issue by DeeFeeCee** [ImpactDevelopment/ImpactClient#1089]
OK, I guess I memed a little too hard there. My point is, how do *new* users know how to use Impact? It's not entirely obvious *from the hack* that there are more options. I know there's a wiki. But simply putting "Discord" & "Website" in the Impact Menu is not, from the layman's perspective, particularly descriptive.

"Like even on the website there is a discord link where people can join and get help." This seems obvious to us; if you need help, go to Discord. The point of this suggestion isn't for those on GitHub, but for those who are not. Discord isn't known as a help center to most people. & having a website next to "donate" doesn't scream "documentation & wiki".

Although I memed a bit, I wasn't trolling. For those who have experience, it's common sense to try every avenue to get help. Others aren't so persistent—if they've got an issue, "it's the mod's fault". "If it's broken, just replace it."

Again, I'm not referring to myself or to those on here, since we already have access to what we need. Random people who haven't heard of GitHub won't associate it as a place to find help for their problems; many will give up. I'm trying to think like Microsoft & other developers who have a huge influx of people asking sometimes dumb & obvious questions, so they include extra help within the apps. (Just don't go as far as to make a paperclip sentient.)

*Please don't ban me.*

**Comment by SuperOP535** [comment]
Use the Discord

**Comment by DeeFeeCee** [comment]
This suggestion is Impact-related?

**Comment by SuperOP535** [comment]
I'm sorry.

**Comment by LeafHacker** [comment]
While I agree we could make it easier to find help and documentation, IMO this issue is to abstract to track. That said we would really appreciate more specific issues such as "rename Website button to..." or "Add a button in xyz menu that does abc".

I'm going to close as invalid for the reasons above.
