### ISSUE TITLE
Customizable home screen

### ISSUE THREAD

**Issue by kekkekek** [ImpactDevelopment/ImpactClient#109]
Able to change the main menu to the ~~3.0 mode or~~ normal minecraft mode

**Comment by LeafHacker** [comment]
I agree some may prefer to use the vanilla main menu (with an extra Impact Menu button, like the pause menu).

I think adding back the 3.0/2.7 main menu, however is needlessly adding redundant code. The 4.0 menu is more of an evolution from the 3.0 one, with better scaling (no buttons off the screen) and tweaked styling.

In any case, I only see the need for one "custom" main menu, and possibly an option for a tweaked vanilla main menu.

**Comment by LeafHacker** [comment]
Following the changes in #590, it will be trivial to make the custom Main Menu optional, as well as the custom background (separately). This issue will be closed when we have a usable way of configuring this implemented.

**Comment by LeafHacker** [comment]
Added a Main Menu module with config options in 4.3
