### ISSUE TITLE
Editing Friends Crashes Game

### ISSUE THREAD

**Issue by DeeFeeCee** [ImpactDevelopment/ImpactClient#1090]
### What happens?

When I was on 2b2t, I met a nice guy & friended him under the alias "Nice guy". I realized Impact doesn't differentiate friends from others in the chat, & with all the text that shows up, I wouldn't know if he was chatting unless I paid attention to the convo. I decided to rename the alias.
Crash.
I tried this off the server in the main menu & whether I typed "_", "-", or any letters, it crashed.
### Workaround:
Delete friend & try it again.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2 
- Using Optifine? Y 
- Using LiteLoader? N 
- Enabled mods: n/a 
- Operating System: W10 64b

</details>

**Comment by LeafHacker** [comment]
On 4.6 for 1.12.2 I can reproduce a crash when hitting `Done` in the edit dialogue, however in 1.13.2 (4.6 and latest master) this has disappeared, so closing as fixed. As a work around on 1.12, using the `.friend` should work.
