### ISSUE TITLE
Impact 1.13.2 bug? I guess?

### ISSUE THREAD

**Issue by maxobe** [ImpactDevelopment/ImpactClient#1095]
When I try to play on Impact 1.13.2, my Minecraft Launcher just says "Failed to download file. 1.13.2.jar
Name: 1.13.2.jar
URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.13.2/1.13.2.jar
Error details: HTTP 403: Forbidden
Filename on disk: 9dd6-001e-0242-8ce5
Path: C:\Users\myname\AppData\Local\Temp\9dd6-001e-0242-8ce5
Exists: file
![qdqwdqwd](https://user-images.githubusercontent.com/49370407/55685882-08579700-5929-11e9-84eb-e40ca5cf01e2.png)

**Comment by LeafHacker** [comment]
This is either an issue with your firewall (most likely), internet connection or the vanilla launcher.

You should get the same error running vanilla. If you are able to launch any 1.13.2 based version, then this error should go away as the jar will be cached offline.
