### ISSUE TITLE
storage ESP don't work with shaders

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactClient#1096]
### What happens?
Storage esp doesn't work when shaders are on.
https://i.imgur.com/12FjAdo.jpg
### Exact steps to reproduce?

- Use shader
- Use storage esp

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 for 1.12.2
- Using Optifine?  Yes [Using Seus PTGI shaders]
- Using LiteLoader?  No 
- Enabled mods:  
ESP 2D, Name tags, Storage ESP, anti-desync
- Operating System:  W10

</details>

**Comment by EmeraldSnorlax** [comment]
you uh, do realise youre standing too close to the chests for ESP to take effect?
besides, shaders conflict with a lot of render hacks, and the multitude of shaders makes it impractical for the devs to implement anyway. just turn off shaders, and use a decent texturepack

**Comment by ScanmanTM** [comment]
Uh I have fade off.
 I guess its too niche to fix.
