### ISSUE TITLE
AutoFarm with baritone

### ISSUE THREAD

**Issue by AutoKaspersky** [ImpactDevelopment/ImpactClient#1101]
Not just adding autofarm, but an autofarm that automatically walks around, harvesting and replanting crops.

Lots of clients have an autofarm, but none of them actually
move you around so you can be afk.

**Comment by ZeroMemes** [comment]
Suggestions that relate to Baritone itself should be made on [its GitHub page](https://github.com/cabaletta/baritone/issues).
