### ISSUE TITLE
Changing module categories

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#1103]
Some things that should maybe be moved, but I'm not certain of... looking for feedback / reactions

Move Anti Hazard from Misc to Movement

Move RainbowEnchant from Misc to Render

Move Timer from Player to World (or maybe Misc?)

Move XRay from World to Render

Move Velocity from Combat to Movement

Move ItemSaver from Misc to Player

Move Inventory from Misc to Player

Move Scaffold from World to Player (or maybe Movement?)

Move SkinBlinker from Misc to Player

Capitalize Hud to HUD

Determine why some modules have a space in their name and some don't? Why is there no space between Rainbow and Enchant?  Why is Kill Aura two words but BowAimbot is one? etc

**Comment by ZeroMemes** [comment]
Made all of the proposed changes in 4.6

**Comment by leijurv** [comment]
4.7?

**Comment by ZeroMemes** [comment]
So basically, whoops.

**Comment by LeafHacker** [comment]
Where should freecam go? Player doesn't feel right...

**Comment by SuperOP535** [comment]
In my opinion it feels right

**Comment by LeafHacker** [comment]
Maybe `Movement` instead?
