### ISSUE TITLE
Inventory > Move Around

### ISSUE THREAD

**Issue by aomajn** [ImpactDevelopment/ImpactClient#1104]
### What happens?
Move Around is not working - can't move while having the inventory open.

### Exact steps to reproduce?

- Turn on Inventory module
- Click on the Move Around
- Open your inventory and try to move

<strong>Additional Client Info</strong>
 

- Impact Version: 4.6 for 1.12.2 Forge
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods: Middle Click Friend, Criticals, Velocity, Trajectories, Tracers, ESP, Auto Totem, Inventory
- Operating System: W8

</details>

**Comment by leijurv** [comment]
forge is p fucked lmao

**Comment by 0-x-2-2** [comment]
forge is 🦍
