### ISSUE TITLE
Automatically download background.jpg on first start

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#1105]
Save the server storage for nighly releases ;)

**Comment by leijurv** [comment]
Literally did this less than a minute before you filed this, wild https://github.com/ImpactDevelopment/Impact/commit/c84b9bceb25e392bd0a48eeee42b1120b71bc8f1

**Comment by leijurv** [comment]
<img width="1031" alt="Screen Shot 2019-04-09 at 11 21 13 AM" src="https://user-images.githubusercontent.com/3837873/55824876-9cf0ff00-5ab9-11e9-8d62-9f08bbff3e34.png">
literally 5 lines

**Comment by SuperOP535** [comment]
L E I J U R V I P L O G G E R ! ! !

**Comment by leijurv** [comment]
yeah this is changed, it's now https://impactdevelopment.github.io/Resources/images/background.jpg

**Comment by SuperOP535** [comment]
thanks mr ipunlogger
