### ISSUE TITLE
suggestions/fixes for future updates

### ISSUE THREAD

**Issue by niggish** [ImpactDevelopment/ImpactClient#1108]
### hope these can be added 😍

**what is your suggestion**

- add infinite chat history w/ slider
- add min/max delay for antiafk options
- add nuker mode delay min/max + yaw/pitch between switching to another block to break(basically aura but for blocks), option to right click and select that block to break
- add build option delay min/max + yaw/pitch
- add waypoint w/ option to set a waypoint of where the destination is of the map your holding, color, name, death, coords(x,y,z format), option to show /home waypoint
- add fly option to customize horizontal/vertical speed
- add unfocused module with option to limit desired fps when MC is tabbed out/minimized
- add search option to set individual block colors
- add levitation control option crouch, goes down when crouched
- add spawner finder with options to show type/distance/esp color of spawner
- add macro system with options to bind a msg to a key etc.

**bugs to fix**
- fix xray not working with optifine, only blocks that are shown, show up on xray and not hidden ones
- fix antivanish not working on vanilla servers
- fix middleclickfriend adding/unadding if right/left clicked the player

**Comment by SuperOP535** [comment]
make 1 issue for every problem/suggestion and make sure these don't already exist
