### ISSUE TITLE
Freecam moves the schematic

### ISSUE THREAD

**Issue by mastatrue** [ImpactDevelopment/ImpactClient#1109]
I load a schematic and when I try to view it on freecam, the schematic moves with the camera. It happens on the forge version. I tried with no hacks and it's still doing it

**Comment by 0-x-2-2** [comment]
Is this schematica?

**Comment by mastatrue** [comment]
It happens only with impact so I don't think is schematica related

**Comment by 0-x-2-2** [comment]
>I don't think is schematica related. 
How are you loading a schematic then?

**Comment by mastatrue** [comment]
I said in the first posts, it happens only with impact forge. For example the freecam in forgehax doesn't interfere with schematica

**Comment by 0-x-2-2** [comment]
I am just asking if you are using schematica or not.

**Comment by ZeroMemes** [comment]
Duplicate of #1107

**Comment by leijurv** [comment]
https://discordapp.com/channels/208753003996512258/378646935302701070/614274322596364298
