### ISSUE TITLE
Autoeat doesn't work with chat open

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#1110]
1. start autoeat
2. turn on baritone
3. open chat and switch to another window
4. watch in despair as baritone waits for impcat to eat food.

**Comment by leijurv** [comment]
user error in step 3. use f3+p to disable pause on lost focus.

or, you know, use ESC instead of chat before alt tabbing

**Comment by LeafHacker** [comment]
Or `F3` + `P`

**Comment by ZeroMemes** [comment]
Fixed in 4.7 😎
