### ISSUE TITLE
Can't start impact

### ISSUE THREAD

**Issue by PhoenixNamedPixel** [ImpactDevelopment/ImpactClient#1114]
**Describe the bug**
I have downloaded 4.6 for 1.13.2 twice but every time I try and load the profile it comes up with the below error message saying it can't download mixin-0.7.11-SNAPSHOT.jar. What I think this is, is liteloader.com no longer works (at the moment) so it can't get the info it needs. I don't know how to solve this as I can't get that info downloaded so can you please help. Thanks.

**To Reproduce**
Steps to reproduce the behaviour:
1. delete impact 
2. download impact again and follow installation steps 
3. try to load the profile 
4. below error message comes up

**Expected behaviour**
It starts to download the files needed when loading profile, it gets half way, it comes up with the error message and that's it.

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Failed to download file. mixin-0.7.11-SNAPSHOT.jar
Name: mixin-0.7.11-SNAPSHOT.jar
URL: http://dl.liteloader.com/versions/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar
Error details: HTTP 500: Internal Server Error
Filename on disk: e6c8-5e8e-73dc-2d85
Path: C:\Users\(my real name)\AppData\Local\Temp\e6c8-5e8e-73dc-2d85
Exists: file
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Didn't crash
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.13.2
- Using Optifine?  No 
- Using LiteLoader?  No 
- Enabled mods:  Cant load Impact to use the mods
- Operating System: Windows 10 pro 64bit

</details>

**Additional context**
No, that's about it.

**Comment by ScanmanTM** [comment]
The site is having issues, I'm sure it will be back soon. In the meanwhile if you're in the discord the jar can be found in there and I'm sure someone can direct you on where to place it.

**Comment by ScanmanTM** [comment]
The site is having issues, I'm sure it will be back soon. In the meanwhile if you're in the discord the jar can be found in there and I'm sure someone can direct you on where to place it.

**Comment by PhoenixNamedPixel** [comment]
Ok, thanks. Now just have to get in the discord server.

**Comment by PhoenixNamedPixel** [comment]
Ok, thanks. Now just have to get in the discord server.

**Comment by PhoenixNamedPixel** [comment]
It works now, thank you.

**Comment by usereewrjrjeejr** [comment]
Yw
