### ISSUE TITLE
4.6 Forge w/ AppleSkin Mod

### ISSUE THREAD

**Issue by GamerGuyD3** [ImpactDevelopment/ImpactClient#1115]
Okay so I feel pretty certain this might have to do with impact (as I've used the mod that I'm having trouble with in many other packs with no issue) but anyways, when using AppleSkin with impact, any time I hover over any food (to show food value information) it crashes my game. I have a temporary fix by just disabling the tooltips in AppleSkin settings, but I still want to be able to see them. If anyone knows how to fix this it would be very much appreciated. I'm using impact 4.6 forge version with the following mods:
- AppleSkin
- Earthcomputer's Client Command Mod
- Impact
- JourneyMap
- Optifine
- ReAuth
- ShulkerBoxViewer
- World Tooltips
- WorldEdit
- WorldEdit CUI

Steps to reproduce:
1. Install Impact 4.6 Forge Version w/ AppleSkin
2. Open AppleSkin mod config to make sure the food value tooltips are on.
3. Hover over a food item while your inventory is open.
4. Congratulations. Your game has crashed.

https://paste.ee/p/982d8

- Impact Version: 4.6 for Minecraft Forge 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Yes
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
Probably a conflict with one of our tooltip hooks, if disabling `Inventory` doesn't help then idk

**Comment by 0-x-2-2** [comment]
multimc 😻

**Comment by GamerGuyD3** [comment]
> Probably a conflict with one of our tooltip hooks, if disabling `Inventory` doesn't help then idk

nah that never did help. I guess I can just live without it. thanks anyways :D
