### ISSUE TITLE
Alts Button in Main Menu Doesn't Work (Forge 4.6)

### ISSUE THREAD

**Issue by GamerGuyD3** [ImpactDevelopment/ImpactClient#1116]
Yeah that. Stumbled on it randomly. Might have to do with mods I have or MultiMC but I highly doubt it. Here's a list just in case:
- AppleSkin
- Earthcomputer's Client Command Mod
- Impact
- JourneyMap
- Optifine
- ReAuth
- ShulkerBoxViewer
- World Tooltips
- WorldEdit
- WorldEdit CUI

**Comment by usereewrjrjeejr** [comment]
What impact mods?

**Comment by 0-x-2-2** [comment]
Try to reproduce without any forge-mods.
