### ISSUE TITLE
Fell from high place (water instant death!)

### ISSUE THREAD

**Issue by josephkentcraig** [ImpactDevelopment/ImpactClient#1117]
**Describe the bug**
Die instantly when touch water or lava and receive a "fell from high place" death message.

**To Reproduce**
1. Go to 'water or lava'
2. Die...
3. Profit???

**Expected behavior**
not to die 

Though it does seem random, i will be safe for a while decide to try out baritone again and then... BAM. death by water

**Comment by ScanmanTM** [comment]
I'm guessing you have anti hunger on...

**Comment by josephkentcraig** [comment]
Yes, I do have/had anti hunger one. Should I just starve? That's a better temporary solution than getting killed by water.

**Comment by ScanmanTM** [comment]
Just get food or don't touch any liquids or if you have to disable it before you do.

**Comment by leijurv** [comment]
This is intrinsic to how Anti Hunger works. Disable Anti Hunger before going in water, or leave it off entirely.

**Comment by Cerbiac** [comment]
Duplicate of #242

**Comment by 0-x-2-2** [comment]
>commenting on a closed issue when the last comment was from months ago

🤡
