### ISSUE TITLE
Liteloader.com website is down and it is causing Impact to not be able to install itself, when launching for the first time

### ISSUE THREAD

**Issue by ynngdd** [ImpactDevelopment/ImpactClient#1124]
**Describe the bug**
I can't start my Impact Client for the first time after downloading, since one of the url's in the impact.json file in not working.
"Failed to download file. mixin-0.7.11-SNAPSHOT.jar"
**To Reproduce**
Installing a fresh Impact Client 

**Screenshots**
![1](https://user-images.githubusercontent.com/37640141/56069405-94374c00-5d8b-11e9-8614-fa203256051e.png)
![2](https://user-images.githubusercontent.com/37640141/56069406-94374c00-5d8b-11e9-96ad-5ccd281d45d8.png)
![3](https://user-images.githubusercontent.com/37640141/56069407-94374c00-5d8b-11e9-8661-a8f341bf5df8.png)

- Impact Version: "4.6 for 1.12.2"
- Using Optifine? Yes
- Using LiteLoader? Yes
- Operating System: "Windows 10" -->

**Comment by aaronfranke** [comment]
If I download the jar file manually, where do I place it? I'm just wondering if the problem can worked around.

**Comment by Ben3874** [comment]
Current workaround:

Download the file from: https:\\cdn.discordapp.com\attachments\222120655594848256%2F566314033989550091\mixin-0.7.11-SNAPSHOT.jar

Go to your %appdata%\.minecraft\libraries\org\spongepowered\mixin\0.7.11-SNAPSHOT folder (If the folders don't exist yet, create them) and place the file in there.

**Comment by LeafHacker** [comment]
The download on the website has been updated to use [sponge](/SpongePowered)'s maven instead of liteloader's
