### ISSUE TITLE
amazing autofarm module

### ISSUE THREAD

**Issue by niggish** [ImpactDevelopment/ImpactClient#1126]
### hope this can be added 😍

**what is your suggestion**

- an `autofarm` module that farms automatically for you, has multiple options and sub options like `wheat, carrot, potato, beetroot, pumpkin, melon, sugar cane, cactus, kelp, nether wart, cocoa bean, chorus fruit, snow` all under a food sub option w/ `plant/harvest/bone meal/ESP` options, option for `autotool`, sub option `animals` w/ `wheat, seeds, carrots, milk, wool, etc.`,
`place/harvest/bone meal` w/ `min/max CPS`, with `min/max + yaw/pitch + delay` for switching through one block to another to farm(basically aura but for blocks). Would be so helpful in impact since its a customizable client

**Comment by usereewrjrjeejr** [comment]
just yonk the code from wurst

**Comment by niggish** [comment]
> just yonk the code from wurst

no skid!

**Comment by leijurv** [comment]
https://youtu.be/5BYfWHgGW5E

**Comment by SylveonBottle** [comment]
> https://youtu.be/5BYfWHgGW5E

LOL it jumped over water and landed on farmland, breaking it. 
Should probably make it not do that.

**Comment by ZeroMemes** [comment]
Considering this a Baritone issue, of which this is a duplicate. https://github.com/cabaletta/baritone/issues/381

**Comment by leijurv** [comment]
https://youtu.be/6Ej5UOK6jus
