### ISSUE TITLE
freecam chunk border bug

### ISSUE THREAD

**Issue by niggish** [ImpactDevelopment/ImpactClient#1128]
**Describe the bug**
When chunk borders(f3+g) are on and freecam is toggled while chunk borders are on, your main player camera copies the same position of the borders on your screen and makes it static on freecam.

**Video**
https://streamable.com/trxlp

- Impact Version: e.g. "4.6-beta for 1.13.2"
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Freecam
- Operating System: Windows 10 64bit

**Comment by 0-x-2-2** [comment]
rofl

**Comment by leijurv** [comment]
kek

**Comment by 0-x-2-2** [comment]
prob kinda related to #1109

**Comment by ZeroMemes** [comment]
Fixed in 4.7
