### ISSUE TITLE
MCLeaks should be brought back as in the older versions

### ISSUE THREAD

**Issue by VincentCCandela** [ImpactDevelopment/ImpactClient#113]
In Impact 3.0 and below, there was MCLeaks support built into the Multiplayer menu.

This should be re-added as it was very useful and made the use of MCLeaks much faster.

**Comment by LeafHacker** [comment]
IMO It should be added as a button in the Alt Manager instead of the Multiplayer menu, similar to how it worked in original pepsimod.

Hers's an [imgur album](http://imgur.com/a/PFFbK) with screenshots. @ZeroMemes also has code access to old pepsimod.

**Comment by SuperOP535** [comment]
double as in title

**Comment by ZeroMemes** [comment]
Added in 4.2
