### ISSUE TITLE
Phase,and fastbow

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactClient#1132]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LeafHacker** [comment]
One issue per idea, please actually fill out the template too. Also, be sure to [search](https://github.com/ImpactDevelopment/ImpactClient/issues?utf8=%E2%9C%93&q=phase) for duplicates
