### ISSUE TITLE
Launching Minecraft Using impact and crashes saying "Using moddifed version" 

### ISSUE THREAD

**Issue by DevinMods666** [ImpactDevelopment/ImpactClient#1136]
I simply just crash when ever I launch Minecraft, I get the  The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

https://cdn.discordapp.com/attachments/222120655594848256/567142499856941057/unknown.png
https://cdn.discordapp.com/attachments/222120655594848256/567144319228837909/crash-2019-04-14_20.28.30-client.txt

First link is my error message second link is my crash report. crashes the moment the screen turns from Mojang to the main menu selection

**Comment by ZeroMemes** [comment]
4.6 is released, the beta was only available to donators, so this is an expected crash.
