### ISSUE TITLE
Strange Client Crashes on Linux [4.6 / 1.12.2]

### ISSUE THREAD

**Issue by GabrielRRussell** [ImpactDevelopment/ImpactClient#1137]
Impact crashes when trying to open. This is completely unrelated to the mixin issues, as I've already placed the Jar in the correct folder and no longer receive that issue.

**To Reproduce**
1. Place the Default Folder for Impact in ~/.minecraft/versions/
2. Set the custom profile for Impact 4_6
3. Run it. It'll crash with the default error.

**Expected behavior**
Typically it'd be expected for the game to start. The launcher closes, then re-opens to display the error.

**Screenshots**
There's nothing to screenshot. It's just the default error.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
**GAME CRASH**  
An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.  
[No further message]
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
No crash report was created. I DID take some relevant contents from the launcher log txt file, and put it in a hastebin.

https://hastebin.com/ducofufimi.sql
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: "4.6 for 1.12.2" 
- Using Optifine?  No 
- Using LiteLoader? No
- Enabled mods: N/A
- Operating System: "Linux Mint 19.1 "Tessa" / Cinnamon / Kernel 5.0.4 "

</details>

**Additional context**
Strangely, I've had a similar issue when installing Optifine or Forge. The main problem with this is that I definitely have the latest version of the launcher installed.

**Comment by ZeroMemes** [comment]
This is caused by running Minecraft on the latest Java version, try running it on JDK 8.
