### ISSUE TITLE
Alt manager should parse username:password syntax

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactClient#114]
When logging in via the Alt Manager, it should be possible to paste in `username:password` strings somewhere and have them split internally, similar to SSH and other URLs containing passwords.

Edited by @LeafHacker for clarity

**Comment by ZeroMemes** [comment]
Can you please elaborate?

**Comment by Bircko** [comment]
a direct login with emai:password format so you don't need to copy password and email seperat

**Comment by LeafHacker** [comment]
Edited for clarity.

**Comment by ZeroMemes** [comment]
If you wanted to import alts into the manager using the ``email:password`` format, you could create a new text file and put the alts in the format on new lines. (Shown below) and then use the "Import" button in the alt manager to select the file.

```
test@123.com:password123
test@456.com:password456
```

**Comment by LeafHacker** [comment]
Maybe allowing imports to be pasted into a text box (as an alternative to a file) would be a good target to set this issue to? Otherwise probably just mark it as WONTFIX.

**Comment by LeafHacker** [comment]
Although he was talking about direct login, so for that maybe if only one field is populated, maybe check if it matches username:password format?

**Comment by ZeroMemes** [comment]
That could work

**Comment by Bircko** [comment]
I mean like this
![alt](https://user-images.githubusercontent.com/29576723/29742759-d7a493d4-8a84-11e7-8bde-c06cacf5c171.PNG)
![alt2](https://user-images.githubusercontent.com/29576723/29742758-d77bd5c0-8a84-11e7-80b2-0e183d27a8c8.PNG)

**Comment by LeafHacker** [comment]
I'd prefer to avoid cluttering the UI with extra text boxes, but I don't
mind adding it as a "hidden" feature when only one box is used.

**Comment by ZeroMemes** [comment]
Added to 4.2.
