### ISSUE TITLE
Crystal Aura uses selected Hotbar Slot

### ISSUE THREAD

**Issue by blockparole** [ImpactDevelopment/ImpactClient#1140]
Crystal Aura uses the selected Hotbar slot before switching to the Crystal slot.

Example:
When the selected Hotbar slot contains a Block, Crystal Aura places that Block before switching to the Crystal slot.

[screenshots](https://imgur.com/a/1XXKWft)

Impact 4.6 1.12.2

**Comment by EvilSourcerer** [comment]
this is cursed, impcat guys please fix

**Comment by usereewrjrjeejr** [comment]
This tbh

**Comment by ZeroMemes** [comment]
INSANE DESYNC??
