### ISSUE TITLE
Jesus incredibly slow going up flowing water, Jesus stops working when opening inventory or tabbing out

### ISSUE THREAD

**Issue by ThebesAndSound** [ImpactDevelopment/ImpactClient#1142]
Jesus incredibly slow going up 1x1 flowing water, Jesus stops working when opening inventory or tabbing out. I expect it not pausing whilst tabbing out is an easy fix, regarding it being slow idk what to say except ask the Future devs what they do as theirs is faster.

I was using Impact forge version here

As demonstrated in video. 
https://www.youtube.com/watch?v=GmDLNI0qTW4

**Comment by ThebesAndSound** [comment]
Also stops working when opening chat

**Comment by 0-x-2-2** [comment]
😻

**Comment by leijurv** [comment]
Under Jesus -> Solid enable the Flowing setting to fix this
