### ISSUE TITLE
Please unhide enchantments in the enchantment tables 

### ISSUE THREAD

**Issue by ngt1133** [ImpactDevelopment/ImpactClient#1143]
Please  unhide enchantments in the enchantment tables, because i want to enchant my sword to max level (I think that and other players this, too, will need)
P.S. Sorry for my english.
![2019-04-16_22 05 17](https://user-images.githubusercontent.com/49693657/56234209-dca97f00-6095-11e9-996d-1d1ea9c1a016.png)

**Comment by SuperOP535** [comment]
There are texture packs for this though

**Comment by ngt1133** [comment]
> There are resource packs for this though, and that hint is completely useless I think.
> 
> I'm not sure what you are talking about.

im mean unhide

**Comment by ngt1133** [comment]
because my eng sorry

**Comment by SuperOP535** [comment]
you can't unhide the dots, they're not hidden

**Comment by ngt1133** [comment]
oh

**Comment by ngt1133** [comment]
> you can't unhide the dots, they're not hidden

I meant show the enchantments that are hidden behind these dots.

**Comment by SuperOP535** [comment]
Only the server knows about that, these stuff:
![image](https://user-images.githubusercontent.com/27556391/56235318-7e759f80-6087-11e9-87ea-6427da519e2e.png)
can be "translated" but they'd be meaningless words.

**Comment by ngt1133** [comment]
> Only the server knows about that, these stuff:
> ![image](https://user-images.githubusercontent.com/27556391/56235318-7e759f80-6087-11e9-87ea-6427da519e2e.png)
> can be "translated" but they'd be meaningless words.

you sure what only server know about that??

**Comment by ngt1133** [comment]
I don't think so

**Comment by ScanmanTM** [comment]
Show where is it not server stuff mr coder

**Comment by usereewrjrjeejr** [comment]
https://gaming.stackexchange.com/questions/129696/whats-the-minecraft-enchantment-alphabet

**Comment by SuperOP535** [comment]
I already told you there are resource packs for this and the result is quite meaningless anyways.

**Comment by SuperOP535** [comment]
You said unhide the dots not translate the alphabet

**Comment by ScanmanTM** [comment]
Even if you translate it. 

> The symbols in the enchanting table have no relation to the actual enchant it yields; they are randomized.

**Comment by EvilSourcerer** [comment]
just add a builtin enchantment seed cracker :P

**Comment by usereewrjrjeejr** [comment]
Yes this when

**Comment by hqics** [comment]
this (1.12.x) client can do it:
https://github.com/Earthcomputer/clientcommands/releases
1. /ctemprule set enchantingPrediction true
2. put different items in the enchantment table
https://youtu.be/hfiTZF0hlzw

**Comment by ngt1133** [comment]
> this (1.12.x) client can do it:
> https://github.com/Earthcomputer/clientcommands/releases
> 
> 1. /ctemprule set enchantingPrediction true
> 2. put different items in the enchantment table
>    https://youtu.be/hfiTZF0hlzw

thanks

**Comment by SuperOP535** [comment]
this seems to complicated to do as a mod

**Comment by SuperOP535** [comment]
however you should make a new issue with the new details

**Comment by ngt1133** [comment]
> this seems a bit complicated to do as a mod, however you should make a new issue with the new details

thanks, but i resolve my problem

**Comment by SuperOP535** [comment]
kk
