### ISSUE TITLE
FastBow

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#1152]
Many clients with _utility mods_ used to have a "FastBow" module. I don't know why, but nowadays most _utility mod_ clients don't have this feature anymore. I'd like to see this feature in a Minecraft client again. It's really useful for annoying other players on PvP xD

### How it works:

[![FastBow](http://img.youtube.com/vi/rQLaj2o9TrA/0.jpg)](https://www.youtube.com/watch?v=rQLaj2o9TrA "FastBow")

[![FastBow](http://img.youtube.com/vi/f1kenJOIw-E/0.jpg)](https://www.youtube.com/watch?v=f1kenJOIw-E "FastBow")

**Comment by 0-x-2-2** [comment]
maybe because it don't work since 1.9? lol

**Comment by ZeroMemes** [comment]
Closing for the reason addressed by @0-x-2-2
