### ISSUE TITLE
I want to set AntiAFK swing speed lower than 1.0

### ISSUE THREAD

**Issue by ThebesAndSound** [ImpactDevelopment/ImpactClient#1157]
punching air every second isn't necessary, setting to 0.02 speed would be every 30 seconds and I wouldn't have to see it constantly swinging.

using '.set antiafk swingspeed 0.02' sets the speed to 1.0, seemingly the lowest it can go

![image](https://user-images.githubusercontent.com/24740347/56470939-3ddda380-6444-11e9-9a77-f64de8170692.png)

**Comment by leijurv** [comment]
Changed in 4.7
