### ISSUE TITLE
Anti-Hunger improvements 

### ISSUE THREAD

**Issue by usereewrjrjeejr** [ImpactDevelopment/ImpactClient#1159]
Anti-Hunger should warn you that going onto water will kill you

**Comment by LeafHacker** [comment]
\*may - the amount of damage dealt depends on the amount of fall damage you accrue and how much armour you are wearing. Its also likely that some servers are affected differently, e.g. some may not deal any damage.

**Comment by usereewrjrjeejr** [comment]
So no?

**Comment by SylveonBottle** [comment]
Maybe anti-hunger could auto-disable when you're breaking a block? Causes baritone to, like, not be able to break blocks.

**Comment by usereewrjrjeejr** [comment]
>Maybe anti-hunger could auto-disable when you're breaking a block? 
 
Would use too many resources 

>Causes baritone to, like, not be able to break blocks.

What?
