### ISSUE TITLE
Minestrike Bomb ESP

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactClient#116]
Minestrike Bomb ESP

**Comment by ZeroMemes** [comment]
I assume you mean planted bomb?

**Comment by Bircko** [comment]
Yes maybe a Player Bomb ESP also so you can see who has the Bomb

**Comment by ZeroMemes** [comment]
You can only see who has the bomb if they are holding it in their hand

**Comment by ZeroMemes** [comment]
Added in 4.1
