### ISSUE TITLE
Criticals module disables sweeping edge

### ISSUE THREAD

**Issue by SebbyLaw** [ImpactDevelopment/ImpactClient#1162]
**Description**
When the module `Criticals` is on `packet` mode, sweeping edge doesn't work on any sword.

**To Reproduce**
1. Turn on `Criticals`, `packet` mode
2. Find a group of closely packed mobs
3. Attack the mobs
4. Only the mob targeted gets damaged

**Client info**

- Impact Version: `4.6` for `1.13.2`
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: `Criticals`, `packet` mode

**Comment by VitorISs** [comment]
this isn't a bug, the Sweeping Edge enchantment doesn't work when you give a critical hit
you can only damage more than one entity with the enchantment when you hit the entity without giving a critical hit (and also without sprinting i think)

this isn't related to impact
