### ISSUE TITLE
Velocity completely broken.

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#1168]
**Describe the bug**
Velocity is completely broken. I don't even know what's happening but it's entertaining.

**To Reproduce**
Just turn it on. Default settings.

**Expected behavior**
Should work like it did back in 1.12.2 4.4.

**Videos**
https://youtu.be/oDt61NehT4w
https://youtu.be/tsGfz_wbuyo
<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 for 1.13.2
- Using Optifine? Yes
- Using LiteLoader?  No
- Enabled mods:  Velocity on 100% 100% Yes Yes 100%
- Operating System: windw10

</details>

**Comment by leijurv** [comment]
This is a combination of one bug, and one user error. The user error is that those sliders are what percentage of knockback you take, if you want the Velocity module to do anything they need to be at not 100%. 100% means it does nothing. The actual bug that I'm going to fix is that knockback inversion (like reverse knockback) setting defaults on, which is extremely confusing and a bad decision. Gonna make it default off.

**Comment by leijurv** [comment]
Fixed in 4.7
