### ISSUE TITLE
This is cursed...

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#1173]
Steps to reproduce
================
1. start impact
2. look at logs
3. look how it's posting chat messages while the chat gui doesn't exist

![image](https://user-images.githubusercontent.com/32974335/56839186-6eac4700-684f-11e9-9461-04848c2aa102.png)

**Comment by zPeanut** [comment]
this is not critical

**Comment by leijurv** [comment]
I also fail to see how this is a bug?

**Comment by LeafHacker** [comment]
Intended behaviour
