### ISSUE TITLE
Hotkey Save

### ISSUE THREAD

**Issue by Susul-1337** [ImpactDevelopment/ImpactClient#1176]
**Is your feature request related to a problem? Please describe.**
Every time I go to another PC I have to setup all my hotkeys again.

**Describe the solution you'd like**
I would like to have a simple small file wich I can export to save my hotkeys and import again to put them into the new Impact. It would also be great to make it also save the active ~~Cheat~~ Utilities.

**Describe alternatives you've considered**
It would also be okay if you had to paste in a string, wich you have to save manually

**Additional context**
I dont have additional context.

**Comment by usereewrjrjeejr** [comment]
Use Google cloud ™

**Comment by ScanmanTM** [comment]
If you go to this location AppData\Roaming\.minecraft\Impact\config there is a file called default.json which contains all your settings.

<sub>Also posting about Google cloud, nothing to do with his suggestion just a LQ post which deserves you to get banned from the issues.<sub>

**Comment by leijurv** [comment]
There is an Impact Files button inside Impact's options that opens this folder. It's config/default.json.
