### ISSUE TITLE
Suggestions for donators 

### ISSUE THREAD

**Issue by suggestionmonster** [ImpactDevelopment/ImpactClient#1179]
Auto Build with .schematic file for donators ( like schmatica & litematica mod )
we can use .schematic files for building, its very good function for faction/vanilla/creative servers. 
Auto Tree for donators 
we can use it for vanilla server
Auto plant & harves for donators  ( with auto bonemeal )
we can use it for vanilla server 
Better game fonts for donators ( I prefer comic sans ms )
as u know minecraft's fonts are really bad, u can improve it I guess :)

**Comment by WaffleTraits** [comment]
1. One suggestion/bug per case.
2. Automatically building schematics is already a Baritone feature (which is included with the latest versions of Impact).
3. You can change the font by replacing the one inside of the Impact jar. (ask in Discord for more details.)
As far as the harvesting and planting stuff goes, either shorten this issue or make a separate one.

**Comment by suggestionmonster** [comment]
oh I see, thanks for quick reply :) u are best ^^
