### ISSUE TITLE
Bypass server provided Texture Pack

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactClient#118]
If possible add a mode to bypass Texturepack from Mineplex(Minestrike) and other servers since when you decline you get kicked. So you can play with your own Texturepack

**Comment by LeafHacker** [comment]
Are you able to manually change your texturepack load order after accepting it?

i.e. Accept the server pack, but then disable it in the menu later.

**Comment by Bircko** [comment]
for 1.11.2 i don't know but in 1.12 it's not possible

**Comment by ZeroMemes** [comment]
Added in 4.4 as a module called **No SRP**
