### ISSUE TITLE
Mainmenu Backgrounds

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#1180]
We have alot of backgrounds in https://github.com/ImpactDevelopment/Resources/tree/master/images that could be used for Impacts Main Menu Background. So why not use them? I suggest a function that cycles through the pictures every 1 minute or so, or the background changes everytime you open the client or go back to the mainmenu gui.

**Comment by EvilSourcerer** [comment]
someone please add light background support which I have outlined in [this PR](https://github.com/ImpactDevelopment/Resources/pull/17). I'm pretty sure this can be done with a simple ternary operator.

**Comment by leijurv** [comment]
yes this is already written?

cycling through every minute is not something you want, the ram usage is wild.

so theres a Randomize setting that randomizes on startup, or you can turn that off and cycle through em urself

**Comment by EvilSourcerer** [comment]
the ram usage? oh huh... i have two dumb ideas for how to make it use less ram

1. set old background downloads to null ( and if that's not the reason use the intellij debugger )
2. needs more jpeg

**Comment by leijurv** [comment]
no its the ram usage of the minecraft texture handler

**Comment by EvilSourcerer** [comment]
> imagine not making your own texture handler
