### ISSUE TITLE
Freecam should display camera coordinates not player coordinates

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#1184]
Freecam should display the coordinates of the camera not the player, because if you wanted to know your player's coordinates you can just disable freecam to see them.

**Comment by EvilSourcerer** [comment]
oh yeah it should be a toggleable option (thanks spicybigdaddy)

**Comment by leijurv** [comment]
Real question is should that toggle be an option under freecam or under hud>coords

**Comment by EvilSourcerer** [comment]
it would make more sense because i like to use F3 more than the hud coords (idk why, maybe the font is more readable or something, or maybe just the position in the screen)

**Comment by ThebesAndSound** [comment]
I too have wanted this, being able to see freecam cords is useful for aligning and measuring.

**Comment by leijurv** [comment]
https://discordapp.com/channels/208753003996512258/208753003996512258/573621597487759367

**Comment by VitorISs** [comment]
i'm pretty sure that if you use freecam and press F3, the coordinates that show up are the camera ones

**Comment by ThebesAndSound** [comment]
> i'm pretty sure that if you use freecam and press F3, the coordinates that show up are the camera ones

I don’t think you are understanding what we are talking about here because it doesn’t, thats the entire point of this issue.

**Comment by rebane2001** [comment]
If I use freecam and press F3, the x and y are correct, but the y is not

**Comment by MastaNub** [comment]
Using F3+G while in freecam is also bugged.

**Comment by leijurv** [comment]
Done in 4.7
