### ISSUE TITLE
Discord invite link does not work

### ISSUE THREAD

**Issue by coin4215** [ImpactDevelopment/ImpactClient#1185]
**Describe the bug**
The discord invite links in the title screen and the "Impact" settings button are invalid.

- Impact Version: 4.6
- Using Optifine? No
- Using LiteLoader? I don't think so
- Operating System: Windows 10 64-bit

**Comment by usereewrjrjeejr** [comment]
bready quick

**Comment by coin4215** [comment]
oh wait nvm it works now im retarded

**Comment by usereewrjrjeejr** [comment]
K
