### ISSUE TITLE
Tracer bug

### ISSUE THREAD

**Issue by usereewrjrjeejr** [ImpactDevelopment/ImpactClient#1189]
**Describe the bug**
Tracers not drawing to friends

**To Reproduce**
1. Add someone to middle click friend 
2. Turn on tracers
3. Tracers don't draw to all friends 

**Expected behavior**
Tracers don't draw to both players

**Screenshots**
![2019-05-04_19 39 10](https://user-images.githubusercontent.com/36968617/57195838-22cf6100-6f25-11e9-94b2-24ba1aa53543.png)

- Impact Version: "4.6 for 1.12.2"
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Middle click friends 
- Operating System: "Windows 10 64bit"

**Comment by LeafHacker** [comment]
do you have the Friends option under tracers enabled or not?

**Comment by usereewrjrjeejr** [comment]
![2019-05-05_12 03 39](https://user-images.githubusercontent.com/36968617/57196766-fec44d80-6f2d-11e9-93cf-a5248d4c989d.png)

yes

**Comment by leijurv** [comment]
?
