### ISSUE TITLE
Size of windows is not editable (maybe after fullscreen)

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactClient#119]
Size of windows is not editable (maybe after fullscreen)

**Comment by ZeroMemes** [comment]
This is a vanilla issue, not an Impact issue.

**Comment by Bircko** [comment]
Isn't Impact coded in mcp so you could still fix it?

**Comment by LeafHacker** [comment]
Impact is based on [ClientAPI](/ImpactDevelopment/ClientAPI). Also I can't reproduce on Linux, sounds like a Windows WM bug or a Windows specific java/lwjgl issue

**Comment by Bircko** [comment]
I figured out that this bug is since 1.8.2 Here is a Video that i uploaded https://www.youtube.com/watch?v=eakKLWnMA_I

**Comment by Bircko** [comment]
Fixed by using Optifine
