### ISSUE TITLE
A bunch of hacks on Impact Forge don't work.

### ISSUE THREAD

**Issue by Discusser** [ImpactDevelopment/ImpactClient#1194]
**Describe the bug**
If you try a bunch of hacks while using forge, you'll see that for example, item ESP doesn't work.
I forgot what other hacks don't work sorry.

**To Reproduce**
1. Put Impact Forge v4.6 for 1.12.2 in mods folder.
2. Open Impact
3. Try out a bunch of hacks.
4. Some won't work.

**Expected behavior**
I expected the hacks to behave normally and work.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
literally nothing
```

</details>
<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2
- Using Optifine? Yes
- Using Forge? Yes
- Enabled mods: No Fall, Criticals, Chams, Anti Hunger etc...
- Operating System: Windows 10 64 Bit
- Mods Installed: Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, Earthcomputer's Client Command Mod, LunatriusCore, Schematica, WorldEdit

</details>

**Additional context**
The problem might be caused due to the mods I have installed, I still haven't tried without the mods.

**Comment by SuperOP535** [comment]
It would be nice if you provided a full list of the modules that don't work

**Comment by 0-x-2-2** [comment]
🤡

**Comment by SuperOP535** [comment]
🦍

**Comment by muurablyat** [comment]
Inventory move is one that doesn't work

**Comment by LeafHacker** [comment]
TBH it is pointless keeping bugs on the Forge version open, since we will likely never update the 1.12 forge client.
