### ISSUE TITLE
Baritone not working properly on Impact Forge 1.12.2

### ISSUE THREAD

**Issue by 0xx06** [ImpactDevelopment/ImpactClient#1195]
**Describe the bug**
I started minecraft using forge impact (to check if it works fine with opti) and baritone seems to be broken. Baritone features didnt work and when typing .b version it said "no version detected, either dev environment or broken install".

**To Reproduce**
1. Use forge impact 1.12.2
2. Join a server
3. Check baritone

**Expected behavior**
Broken install

**Comment by leijurv** [comment]
lol wtf does "seems to be broken" mean

it responds to chat commands, what doesnt work?

no version detected is expected since baritone is shadowed and doesnt have its meta-inf

**Comment by 0xx06** [comment]
It means some features don't work, no .b tunnel or .b backfill (for example) it all comes up with invalid syntax. Didn't test too many other commands but pathing for autowalk works for example.

After switching back to the normal impact profile it all went back to working properly.

**Comment by leijurv** [comment]
yeah this is expected and not fixable

the outdated baritone inside impact's forge release can theoretically be updated if you really want, by replacing the baritone folder with one from a more recent release

but a new impact forge 1.12 will not be released
