### ISSUE TITLE
an auto log feature to any teleport related feature.

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactClient#1196]
**Is your feature request related to a problem? Please describe.**
I notice that when i play on some servers, they would have an anti cheat, no biggie. u just cant fly or use click tp. it just snaps u back to your last place on the ground. But ive noticed that when using flight and jumping off a cliff, toggling flight mid air and relogging will have u suspended in the air. no snapback, so what i was thinking is if logging prevents mc from knowing ur last place on the ground, maybe adding an auto log feature to something like clicktp or .clip could be a feasable way to tp without getting snapped back. 

(I know this works with flight, 100%. ive done it with click tp a couple times but its really hard to do it manually, i havent been able to do it with clip just due to how fast you get snapped back, adding an auto log feature or tricking the game into thinking u logged out might not even get around this snap back problem. It may not even be possible. its a theoretical suggestion.)

**Describe the solution you'd like**
the most desirable solution would be something that tricks the game that you logged out and relogged onto the server, as that seems much faster than it actually logging u out and making u rejoin. this way you can use .clip or clicktp and not get snapped back to your original location.

**Describe alternatives you've considered**
fucking none, theres literally no other way of teleporting and keeping ur position.

**Additional context**
This is theoretical, test if it can be done, if not then nvm, but if it does. that would be pretty gucci

**Comment by leijurv** [comment]
So you're saying that you do something would cause anticheat to lagback, such as clicktp or toggling flight in midair, but you log out before you can get lagged back. Then when you log back in, you're at that new position?

:thinking:

**Comment by KxngCartier** [comment]
yea, at least with flight. i haven't tested it with .clip and click tp cuz
of the literal inhuman inputs needed. i think it does this because mc keeps
track of where you are, think of it like a really long string that tracks
where you walked, but when you fly it snaps you back to the last place u
were on the ground. logging out seems to break this string, so the server
doesn't have a place to send u to. if u are in the air with fly. u will
just get kicked for flying. but if u click tp somewhere and log and relog,
you might remain there due to said string breaking. if this does work you
should add a thing that tricks the server into thinking you logged out
without actually logging out, so it will save ur cords u tped to.

**Comment by 0-x-2-2** [comment]
wat

**Comment by 0-x-2-2** [comment]
yeah this is not how it works at all

**Comment by 0-x-2-2** [comment]
> think it does this because mc keeps
track of where you are, think of it like a really long string that tracks
where you walked, but when you fly it snaps you back to the last place u
were on the ground.

yeah this don't work at all how you think it works. if ncp has no last onground location it will use your last move that was not illegal. 

> if this does work you
should add a thing that tricks the server into thinking you logged out
without actually logging out.

this is impossible.
