### ISSUE TITLE
Installed Optifine and LOST premium  

### ISSUE THREAD

**Issue by Baumbeezy** [ImpactDevelopment/ImpactClient#1197]
ok so i tweeked impact to install optifine and lost my premium account status but still have my cape w/ no access to ignite , i reverted to see if maybe it was the optifine and it was the same result no more premium , i love impact and will keep using it just hope to see this fixed and hopefully future support for optifine  

**Additional context**
![2019-05-07_04 59 05](https://user-images.githubusercontent.com/50422395/57399464-e440dd00-7196-11e9-98db-d9d4d9968b03.png)
![2019-05-07_04 59 05](https://user-images.githubusercontent.com/50422395/57399500-f7ec4380-7196-11e9-9312-10545160df90.png)

**Comment by MastaNub** [comment]
donate again!

**Comment by usereewrjrjeejr** [comment]
@zeromemes

**Comment by Baumbeezy** [comment]
> donate again! also why are you using beta?
again ? and its the latest version on there website

**Comment by leijurv** [comment]
What premium features are missing?

It looks like you still have the cape in both images. Do you have the premium text on the main menu? Can you activate the Ignite module?

**Comment by Baumbeezy** [comment]
> What premium features are missing?
> 
> It looks like you still have the cape in both images. Do you have the premium text on the main menu? Can you activate the Ignite module?
the ignite wont work and the premium text is missing
![2019-05-08_14 03 55](https://user-images.githubusercontent.com/50422395/57400960-464f1180-719a-11e9-940f-69fd44787b83.png)
![2019-05-08_14 04 52](https://user-images.githubusercontent.com/50422395/57400962-4818d500-719a-11e9-95d5-6d08e0d173b1.png)

**Comment by Baumbeezy** [comment]
@leijurv 
![2019-05-08_14 03 55](https://user-images.githubusercontent.com/50422395/57402203-64b60c80-719c-11e9-9e4d-8fb138c01d7b.png)
![2019-05-08_14 04 52](https://user-images.githubusercontent.com/50422395/57402205-64b60c80-719c-11e9-9696-f328b0cfa500.png)

**Comment by leijurv** [comment]
wow this is actually unepic

**Comment by leijurv** [comment]
(also turn on main menu background :wink:)

**Comment by Baumbeezy** [comment]
how ? @leijurv

**Comment by leijurv** [comment]
it wont help with your issue its just a random suggesiton lol

its like render -> main menu -> custom -> background or something idk

**Comment by Baumbeezy** [comment]
done anyways lol , also cant use shaders (assuming cuz its not supported) 
Not a big deal just miss the red & gold letters and burning ppl @Baumbeezy

**Comment by leijurv** [comment]
thats really weird, optifine shaders like seus work for me with impact 4.6 1.12...

i just need to have impact ESP off

maybe its the specific version? try optifine `1.12.2_HD_U_E2` thats what i have

**Comment by MastaNub** [comment]
Make sure you launch Minecraft as the account which Premium Impact is assigned to. 
**Don't** jus't log in with any account and then use an alt manager.

**Comment by Baumbeezy** [comment]
.i only have one account @ @MastaNub  and it works with ESP off thanks @leijurv

**Comment by Baumbeezy** [comment]
and hey you can use ESP with shaders you just have to change ESP > mode>Box @leijurv

**Comment by usereewrjrjeejr** [comment]
@MastaNub 
![Screenshot_20190506-150413_Discord](https://user-images.githubusercontent.com/36968617/57409012-3264d900-71b5-11e9-8d37-af4482bca2ff.jpg)

**Comment by usereewrjrjeejr** [comment]
Wtf discord ruined the image quality lol
