### ISSUE TITLE
Bartitone while riding mobs so i can go afk and beat off

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactClient#1198]
**Is your feature request related to a problem? Please describe.**
Timer and baritone is fast. But Its not fast enough, i know riding can reach retarded ammounts of speed, but it requires me to be actively moving my horse, and im too much of a lazy peice of shit to do that. 

**Describe the solution you'd like**
to be able to use baritone while riding mobs. so i can turn on riding, timer and baritone and let imapct do all the work. that way i can do more productive stuff like, eating cheetos till my fingers look like cheetos, beating off with said cheeto fingers and not have to worry about having to move my player there manually.

**Describe alternatives you've considered**
timer, speed:boost, baritone
getting the perfect angle on my horse, turning on timer, and placing 34 quarters on my W key.
click tp, and a mouse spam macro.
clicky boat chain with macro
packetfly and timer 200

**Additional context**

**Comment by usereewrjrjeejr** [comment]
No

**Comment by Cerbiac** [comment]
Baritone issue, please go to [their github](https://github.com/cabaletta/baritone/issues).
