### ISSUE TITLE
baritone should be able to use enderpearls

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactClient#1199]
**Is your feature request related to a problem? Please describe.**
baritone is a fucking beast, i love it. i thought it was a shitty auto walker until i saw it parkour up 2 nether fortress walls while placing blocks where the player would land. (it literally looked like my guy was wallkicking off the walls.) But you know what would make it better? the ability to use enderpearls with baritone. It would remove human error from the throws. hell if this gets added maybe baritone could have an option to calculate the throw angle needed to clip through the block its hitting. 

**Describe the solution you'd like**
the ability for baritone to use enderpearls to cross short gaps, drop down from high cliffs, throw them into blocks to allow a blockclip and not have to worry about it fucking up.(it still might fuck up but it would prolly be like a 1 in a couple thousand if its made right) 

**Describe alternatives you've considered**
actually throwing ender pearls
scaffolding like a little beta bitch
just giving up on my destination and wallow in my own self inflicted failure.

**Additional context**

**Comment by usereewrjrjeejr** [comment]
Use the baritone GitHub for baritone issues

**Comment by leijurv** [comment]
yes this should be filed on the baritone repo, thanks

**Comment by KxngCartier** [comment]
makes sense.

**Comment by usereewrjrjeejr** [comment]
WhT
