### ISSUE TITLE
Fishing Broken? in 1.11.2

### ISSUE THREAD

**Issue by weegee721** [ImpactDevelopment/ImpactClient#12]
AutoFish the rod doesn't want to stay cast, might be because a 1.11 client is running on a 1.11.2 server, because Wurst doesn't have this problem. https://www.youtube.com/watch?v=XjhLYbT3kZU

**Comment by ZeroMemes** [comment]
This issue has been patched in the latest version (3.1) release will be shortly.

**Comment by bmintz** [comment]
>shortly

**Comment by ZeroMemes** [comment]
3.1 would've gotten a release if the artifact wasn't getting Client Thread Exception errors when run. The issue has been fixed and once the ClientAPI has a fully working build and all features are confirmed fully functional, there will be a release.
