### ISSUE TITLE
let beefhaxor develop impact

### ISSUE THREAD

**Issue by jefferyw08** [ImpactDevelopment/ImpactClient#120]
he's a super cool dude and you can already trust him since he's ton a ton of stuff for capi. impact is DEAD and needs a new developer to help it become not dead

**Comment by LeafHacker** [comment]
> he's a super cool dude

Obviously :D

> he's ton a ton of stuff for capi

A small bit, mostly on the build system

> DEAD and needs a new developer to help it become not dead

wow rude :-P

---

Anyway, closing as invalid as this isn't a real issue - thanks for the support though.

**Comment by ZeroMemes** [comment]
brb adding to gitlab, actually this time
