### ISSUE TITLE
Add Egyptian hieroglyphics to fancychat

### ISSUE THREAD

**Issue by KxngCartier** [ImpactDevelopment/ImpactClient#1200]
**Is your feature request related to a problem? Please describe.**
not related to a problem, i just want this

**Describe the solution you'd like**
adding Egyptian hieroglyphics to fancychat. Its Unicode, it should work

**Describe alternatives you've considered**
copypasting them myself

**Additional context**

**Comment by usereewrjrjeejr** [comment]
https://en.wikipedia.org/wiki/Egyptian_Hieroglyphs_(Unicode_block)

**Comment by leijurv** [comment]
Literally cannot fathom a higher priority issue

**Comment by 0-x-2-2** [comment]
These wont show up in chat. 
![image](https://user-images.githubusercontent.com/9968651/58692316-5fdc1700-835c-11e9-919f-41e6b1d2e6fb.png)

**Comment by usereewrjrjeejr** [comment]
Well make it show up
