### ISSUE TITLE
Respawn spam

### ISSUE THREAD

**Issue by usereewrjrjeejr** [ImpactDevelopment/ImpactClient#1204]
Respawn module puts cords in chat more the 1x

1. Turn on respawn
2. die

**Expected behavior**
Respawn module should only put cords in chat 1x

**Screenshots**
![2019-05-13_16 18 19](https://user-images.githubusercontent.com/36968617/57653998-315eed80-75a1-11e9-90e1-fd9723305da6.png)

- Impact Version: "4.6 for 1.12.2" 
- "Windows 10 64bit"

**Comment by leijurv** [comment]
Fixed by https://github.com/ImpactDevelopment/Impact/commit/da51ac8538873967cfd897e478d3ff37eeda8c3c
