### ISSUE TITLE
Baritone crash on server load

### ISSUE THREAD

**Issue by MostlyOp** [ImpactDevelopment/ImpactClient#1207]
The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.util.math.Vec3i.field_177962_a from class baritone.af
 

- Impact Version: 1.12.2 4.6 forge
- Using Optifine?   Yes
- Using LiteLoader? NO
- Enabled mods: None
- Operating System: Windows 10 64bit

**Comment by usereewrjrjeejr** [comment]
Use the baritone GitHub

**Comment by usereewrjrjeejr** [comment]
♿

**Comment by ZeroMemes** [comment]
Closing because this is an issue that is exclusively cause by Baritone. Please use the Baritone GitHub repo to report issues regarding Baritone alone. https://github.com/cabaletta/baritone/issues
