### ISSUE TITLE
[Closed]

### ISSUE THREAD

**Issue by cyruscook** [ImpactDevelopment/ImpactClient#1215]
.

**Comment by cyruscook** [comment]
Could a dev please look at this? I'm happy to help with writing the actual code.

**Comment by cyruscook** [comment]
I've started writing an implementation of this myself. Here is my current code (This is literally my first ever program in Java, pls don't hate):
```Java
	// Map of each known player and their last known position
	private HashMap<Entity, Vec3d> knownPlayers = new HashMap<Entity, Vec3d>();
	
	// Number of ticks since we last calculated if any players had teleported
	private int numTicks = 0;

	@Override
	public void onUpdate()
	{
		if(!this.isToggled())
		{
			return;
		}
		if(numTicks >= 10)
		{
			numTicks = 0;
			for(Entity entity: mc.world.entityList)
			{
				if(entity instanceof EntityPlayer && entity.getName() != mc.player.getName())
				{

					Vec3d playerPos = new Vec3d(entity.posX, entity.posY, entity.posZ);
					if(knownPlayers.containsKey(entity))
					{
						if(Math.abs(knownPlayers.get(entity).distanceTo(playerPos)) > 20)
						{
							// This player teleported, alert the user
							Client.addChatMessage("Player \"" + entity.getName() + "\" teleported to " + playerPos.toString());
						}
						
						// Update the stored location of the player
						knownPlayers.put(entity, playerPos);
					}
					else
					{
						knownPlayers.put(entity, playerPos);
						Client.addChatMessage("Added new player: \"" + entity.getName() + "\" with position: " + playerPos.toString());
					}
				}
			}
		}
		else
		{
			numTicks++;
		}
	}
```

Annoyingly I am hitting two different road blocks:
1. It is, of course, very bad performance wise to be looping through every single entity on every frame. Sadly this is unavoidable, but I have lowered the significance of this by allowing the hack to be toggled and by only running it every 10 frames.
2. For some reason this simply isn't working. Although the array I am using is the exact same one as the one being used by the crash log generator, it seems that mine does not hang on to the coordinates of player's that teleport away. I'm not sure how to fix this, but I'm still looking into it.

I'd really appreciate any help! Feel free to also use my code in your client, however please give me credit.

**Comment by usereewrjrjeejr** [comment]
What?

**Comment by cyruscook** [comment]
Dw about it @usereewrjrjeejr

**Comment by ZeroMemes** [comment]
???

**Comment by ZeroMemes** [comment]
Reopened from the latest revision https://github.com/ImpactDevelopment/ImpactClient/issues/1227
