### ISSUE TITLE
MCLeaks.net : "No authentification with Minecraft"

### ISSUE THREAD

**Issue by AstragoYT** [ImpactDevelopment/ImpactClient#1219]
1.13.2
 
Newest version

**Comment by usereewrjrjeejr** [comment]
Old news

**Comment by AstragoYT** [comment]
What can I do to fix it?

**Comment by usereewrjrjeejr** [comment]
Buy alts elsewhere

**Comment by AstragoYT** [comment]
where?

**Comment by Haxified** [comment]
>authentification

**Comment by ZeroMemes** [comment]
Closing due to lack of following template which resulted in little to no actual information to solve the issue. Make a new issue using the template.
