### ISSUE TITLE
Scaffold Tower

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactClient#122]
https://hastebin.com/piqovucoba.java
Source by LiquidDev
https://www.youtube.com/watch?v=UIZ6EY5DnDg

**Comment by ZeroMemes** [comment]
Sounds like something that would fit in with "Scaffold"

**Comment by zPeanut** [comment]
add a smooth mode please

**Comment by Bircko** [comment]
You could add in Scaffold but there exist multiple modes for tower like packet tower, teleport tower, motion tower usw. scaffold also have multiple mode since some anticheats have checks for it so legit eagle, expand, slow scaffold

**Comment by VitorISs** [comment]
it should be like this:

[Scaffold] (module)
-Tower (option button)
--NCP, packet, teleport, etc.. (tower modes)

**Comment by VitorISs** [comment]
![impact-hacked-client2](https://user-images.githubusercontent.com/30983029/42413092-a1d4ff1a-81ef-11e8-8ce4-630cfa2cac85.jpg)

it should be like in this pic that i made using my extremely professional windows paint skills ;)

**Comment by LeafHacker** [comment]
I'd prefer mode being a sub-option of Tower

**Comment by VitorISs** [comment]
do you mean make scaffold and tower as separate modules?

**Comment by ZeroMemes** [comment]
4.3 released, bumping to 4.4.

**Comment by ZeroMemes** [comment]
Added to 4.4. Tested and confirmed to work on latest NCP.

**Comment by VitorISs** [comment]
YEEEES

**Comment by VitorISs** [comment]
There should be Different tower modes, like a super fast one called "Vanilla", and then the bypass modes, like "NCP", "AAC", etc

**Comment by LeafHacker** [comment]
@VitorISs feel free to request that in a new issue
