### ISSUE TITLE
Light does not work

### ISSUE THREAD

**Issue by coin4215** [ImpactDevelopment/ImpactClient#1220]
**Describe the bug**
Fade does not turn on fullbright. It does the same thing as brighten. Today, I tried using light again, and fade did literally nothing. I have no idea what's causing this problem.

**To Reproduce**
Turn on fade/brighten in light.

**Screenshots**
![2019-05-22_19 12 05](https://user-images.githubusercontent.com/50219974/58374824-3e190500-7f02-11e9-908b-4516a33fc2c4.png)
![2019-05-22_19 11 59](https://user-images.githubusercontent.com/50219974/58374823-35c0ca00-7f02-11e9-83e8-ece49e138c6a.png)
![2019-05-22_19 12 09](https://user-images.githubusercontent.com/50219974/58374826-55f08900-7f02-11e9-9dee-f78292ef5dc6.png)
![2019-05-22_19 12 11](https://user-images.githubusercontent.com/50219974/58374828-5a1ca680-7f02-11e9-83c2-bb151361aab5.png)
![2019-05-25_15 29 05](https://user-images.githubusercontent.com/50219974/58374830-61dc4b00-7f02-11e9-8a75-e138662a19bc.png)
![2019-05-25_15 29 08](https://user-images.githubusercontent.com/50219974/58374831-643ea500-7f02-11e9-8be9-fd012a60319d.png)
![2019-05-25_15 29 16](https://user-images.githubusercontent.com/50219974/58374834-66a0ff00-7f02-11e9-8c59-adf3cc5dca85.png)
![2019-05-25_15 29 27](https://user-images.githubusercontent.com/50219974/58374836-69035900-7f02-11e9-8ade-34c51f79b77c.png)

- Impact Version: 4.6 for 1.12.2
- Using Optifine? yes
- Using LiteLoader? i dont think so
- Enabled mods: No Push, No Slow, Terrain, AntiBlind, AntiOverlay, CameraClip, ClickGui, Hud, Light, Main Menu, Nametags, StorageESP, Tracers, Trajectories, AutoTotem, Criticals, Velocity, Auto Eat, Anti Desync, Auto Reconnect, Inventory, Lag Meter, Lag Position, Middle Click Friend, Anti Hunger
- Operating System: Windows 10 Pro 64-bit

**Comment by usereewrjrjeejr** [comment]
Does the same happen without optifine?

**Comment by coin4215** [comment]
> 
> 
> Does the same happen without optifine?

I don't know, I'll try it out.

**Comment by coin4215** [comment]
> 
> 
> > Does the same happen without optifine?
> 
> I don't know, I'll try it out.

Light still didn't work without OF, it did the exact same thing.

**Comment by leijurv** [comment]
Fixed in 4.7

**Comment by ZeroMemes** [comment]
To fix for now, turn on the Fade option
