### ISSUE TITLE
Issue with self destruct feature

### ISSUE THREAD

**Issue by alimansfield2016** [ImpactDevelopment/ImpactClient#123]
After activating self destruct, if someone were to screen share you, they could open the debug menu F3, and see that ur using impact 4.0

**Comment by w-o-a-h** [comment]
this is not a bug you have to rename the version yourself

**Comment by ZeroMemes** [comment]
@w-o-a-h Self Destruct should change it by itself.

**Comment by ZeroMemes** [comment]
Fixed

**Comment by alimansfield2016** [comment]
still broken, just tried it

**Comment by ZeroMemes** [comment]
Fixed as in fixed in 4.1...

**Comment by w-o-a-h** [comment]
@ZeroMemes except the can just dump the args and jvm args or just use snooper settings
