### ISSUE TITLE
Baritone x*x tunnel option

### ISSUE THREAD

**Issue by 0xx06** [ImpactDevelopment/ImpactClient#1230]
It would be nice if baritone's tunnel feature could be expanded by a parameter to dictate the area that should be tunnelled.

An example:

.b tunnel 2 * 2
.b tunnel 2 * 3

That way it would be easier to e.g. create a tunnel which you can ride a horse in.

**Comment by ZeroMemes** [comment]
Baritone specific suggestions should go [here](https://github.com/cabaletta/baritone/issues).

**Comment by ZeroMemes** [comment]
After looking into it, Baritone's tunnel actually creates a goal that follows a "strict direction" heuristic. This means that baritone will do whatever it can to go in the direction of the original goal, if possible, but will never attempt to do anything more than that. Creating a customizable tunnel dimension parameter would require tunnel to be completely rewritten by the looks of it.

@leijurv thoughts?

**Comment by IronException** [comment]
there could be a seperate process for it tbh. But it would do the same as cleararea as far as I get your problem

**Comment by leijurv** [comment]
Making something bigger than 1x2 would require some Frankenstein child of tunnel and cleararea, idk how it would work lol
