### ISSUE TITLE
Strange behavior with Riding + Jesus

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#1233]
**Describe the bug**
Horses bounce and don't stand entirely on top of water IF the player is standing on land not water while mounting the horse. It doesn't matter where the horse is standing.

**To Reproduce**
1. Have Riding enabled, including Swim. Have Jesus enabled.
2. Mount a horse while standing on land
3. The horse bobs in the water and doesn't walk on top of it. Toggling any of these modules doesn't change this (except obviously turning off Swim in Riding causes you to dismount due to drowning).
--
1. Having Riding enabled, including Swim. Have Jesus enabled.
2. Mount a horse while standing on water
3. The horse walks on water. This continues to work even if you go onto land then back onto water, or if you jump, or anything.

**Expected behavior**
Regardless of the circumstances of mounting the horse, it walks on water.

**Video**
https://youtu.be/JMGu56-5KXc

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2 
- Using Optifine? Yes 
- Using LiteLoader? No 
- Enabled mods: 
- Operating System: 

</details>

**Comment by leijurv** [comment]
@ZeroMemes JesusSolid updates according to MotionUpdateEvent and sets isLiquidSolid. When you're riding a horse, MotionUpdateEvent doesn't fire. So that does explain this, in how the water is only solid if you were standing on it right before getting on the horse. I'm not sure the best way to fix tho?

**Comment by ZeroMemes** [comment]
Fixed in 4.7
