### ISSUE TITLE
Tipped arrows displayed separately when viewing a shulkers contents

### ISSUE THREAD

**Issue by Infernopickaxe** [ImpactDevelopment/ImpactClient#1236]
![unknown-59](https://user-images.githubusercontent.com/48775141/58682683-30ff7a00-8337-11e9-914a-fa62f592bec1.png)
Should show 64 weakness arrows and 128 harming 2 arrows 
(Same thing with items that have different names)

**Comment by ZeroMemes** [comment]
What are your respective shulker settings for the Inventory module?

**Comment by blockparole** [comment]
Same happens with heads of different Players, just the first heads name shows.
(Default Settings, 4.6, 1.12.2)

**Comment by ZeroMemes** [comment]
Does this just happen when Inventory is enabled? @blockparole

**Comment by LeafHacker** [comment]
Looks like a collate bug, maybe I didn't check the display name of the stack is different.

With collate disabled each stack will show separately.

**Comment by LeafHacker** [comment]
Fixed in the next release - our name comparison was broken for itemstacks without a custom name
