### ISSUE TITLE
Music control mod

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ImpactDevelopment/ImpactClient#1244]
A way to manage currently playing songs (like in badlion client https://www.badlion.net/forum/thread/225418)

A way to manage songs, not just for spotify but for whatever music player you have (clementine, musicbee etc)

Perhaps show an overlay at the top of screen or smth

shittily made concept art i threw together in gimp in about 30 seconds:

![concept](https://i.imgur.com/ekR5zsj.png)

**Comment by leijurv** [comment]
this is the epitome of feature creep
