### ISSUE TITLE
Impact is not loading right

### ISSUE THREAD

**Issue by JeffGoldblumLaw** [ImpactDevelopment/ImpactClient#1245]
**Describe the bug**
when I load in on the 1.12.2 Impact version The screen turns black before it gets to the main menu in Minecraft.

**To Reproduce**
1. Minecraft Launcher 
2. Load Impact 1.12.2
3.  Mojang Page loads up
4. Mojang Page disappears and screen turns black. (Minecraft does unresponsive.)

**Expected behavior**
Before this happened I loaded impact perfectly fine about 5 times, so my expectation was it was going to be load fine again.

**Screenshots**
Well if you want to see a black screen let me know

<details> 
  Right before this started to happen I did a full scan with Avast. The results of the full scan showed two files that where suspected of being viruses. Avast gave me the option to delete them so I did. After I did that loaded Impact and that's where the problem started. Just to clarify I did nothing else to Impact before hand. I suspected that Avast deleted it so I uninstalled and reinstalled Impact ,but the same issue occurred. 
 

``` Don't know where to find this ,but I can guess. 
-Preparing
-unpacking
I saw this on the load bar on the launcher. It stopped loading when it got to unpacking and went strait to the Mojang page.

No crash report was given besides the launcher telling me that they where sorry that it did crash.
```

- Impact Version: 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: No mods
- Operating System: Windows 10

**Comment by JeffGoldblumLaw** [comment]
Not only this ,but I just now noticed that my forge after using it for a couple of months is now magically broken too. I never even intended on using it in forge. I just want it for 2b2t. I just retried launching forge after uninstalling impact and is still not working. Does impact have any correlation with forge?

**Comment by JeffGoldblumLaw** [comment]
This is ridiculous not only has this been happening to just impact it's now happening to all of my other versions in Minecraft. What did I just download from you guys? I don't want a fix to this anymore, I want a fix to whatever this has done to my game.

**Comment by leijurv** [comment]
`Before this happened I loaded impact perfectly fine about 5 times, so my expectation was it was going to be load fine again.`

this really makes me think this is not impact's fault

**Comment by JeffGoldblumLaw** [comment]
> Before this happened I loaded impact perfectly fine about 5 times, so my expectation was it was going to be load fine again.
> this really makes me think this is not impact's fault

Then what other thing can cause this? After all this all happened on the same day I got impact.

**Comment by leijurv** [comment]
And you're saying that when you make an new profile in a random version of minecraft, it crashes in the same way? You got any crash logs, logs at all? Logs folder?

**Comment by JeffGoldblumLaw** [comment]
Yeah the same issue is occurring on other versions. I went through and deleted all my versions, went back created copies of the version (not exact copies.) This didn't fix the problem.

**Comment by leijurv** [comment]
Logs

**Comment by JeffGoldblumLaw** [comment]
all of my crash reports are dated months ago

**Comment by JeffGoldblumLaw** [comment]
very weird

**Comment by usereewrjrjeejr** [comment]
It's organized oldest ----> newest

**Comment by JeffGoldblumLaw** [comment]
I know that already. I only have five crash reports and they're dated months ago

**Comment by JeffGoldblumLaw** [comment]
I found no simple solution to this. If I don't find anything in files in the next hour I am just going to uninstall and reinstall minecraft

**Comment by leijurv** [comment]
lol ok, if it were me i would have already `rm -rf .minecraft` an hour ago but ok

**Comment by JeffGoldblumLaw** [comment]
> lol ok, if it were me i would have already rm -rf .minecraft an hour ago but ok

what does that do?

**Comment by leijurv** [comment]
deletes the folder lmao

**Comment by JeffGoldblumLaw** [comment]
You mean the Impact folder? If so I already deleted it when the problem began to spread.

**Comment by leijurv** [comment]
I would have said Impact if I'd meant that folder

**Comment by JeffGoldblumLaw** [comment]
than what folder

**Comment by leijurv** [comment]
`.minecraft` you idiot

**Comment by JeffGoldblumLaw** [comment]
Well it doesn't matter anymore I managed to fix whatever was killing my game. So thanks for calling me an idiot, real encouraging.

**Comment by leijurv** [comment]
Glad to hear you fixed it
