### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by DesertFox2** [ImpactDevelopment/ImpactClient#1249]
**Describe the bug**

**To Reproduce**
1. Go to 'Minecraft'
2. Click on '1.12.2 Impact'
3. Scroll down to 'N/A'
4. See error (Error for me)

**Expected behavior**
At first when I was installing, I expected it to go fine. But now it's saying failed to download asm-all-5.2.jar

**Screenshots**

![Captureee](https://user-images.githubusercontent.com/51294417/58763638-5a80f700-852b-11e9-9c7f-ce0bbcc98309.PNG)

<details> 
  <summary><strong>Game output</strong></summary>
 

```
Name: asm-all-5.2.jar
URL: http://repo1.maven.org/maven2/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
Error details: UNKNOWN/-118
Filename on disk: asm-all-5.2.jar
Path: C:\Users\Sydney\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar
Exists: false
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: . "4.6 for 1.12.2" 
- Using Optifine? Tried with both, same error.
- Using LiteLoader? No
- Enabled mods: None.
- Operating System: ]"Windows 10 64bit"
</details>

**Additional context**

**Comment by leijurv** [comment]
Click `Show more details`

**Comment by leijurv** [comment]
Confirmed that that URL is serving a jar with the hash we expect, this was just a temporary 403 or 504 or wifi hiccup or whatever. Try again later, and reopen if it continues to fail.
