### ISSUE TITLE
Unable to go further when I hit "play".

### ISSUE THREAD

**Issue by Bran3** [ImpactDevelopment/ImpactClient#1252]
So I have installed Impact 1.13.2 on minecraft and it doesn't work.
It shows up in "version" menu, and I can select it, but when I try to run it, launcher tries to load something and can't start game.

It tries to download few things every time but never does.

P.S. : I am using Shiginima launcher.

![1](https://user-images.githubusercontent.com/20133224/58804693-c2f6d380-8612-11e9-9912-758ba3f14076.png)
![2](https://user-images.githubusercontent.com/20133224/58804694-c38f6a00-8612-11e9-953c-47ff4ec9ca5f.png)
![3](https://user-images.githubusercontent.com/20133224/58804695-c38f6a00-8612-11e9-95fc-b83f652fc05f.png)

**Comment by usereewrjrjeejr** [comment]
Impact doesn't work with cracked launchers

**Comment by Bran3** [comment]
Thanks :D is there a hack similar to impact that is for cracked launchers?

**Comment by usereewrjrjeejr** [comment]
No clue just buy the game
