### ISSUE TITLE
Have smart auto-walk take jesus into account

### ISSUE THREAD

**Issue by BobbyRaduloff** [ImpactDevelopment/ImpactClient#1253]
I'm always frustrated when I put on smart auto-walk for long periods of time and the algorithm avoids water even though I have jesus turned on.

It would be cool if the pathing algorithm checked if Jesus was enabled and took that into account.

I can use dumb auto-walk but this is risky so inefficient smart autowalk gets used.

**Comment by leijurv** [comment]
It already does this, it just penalizes walking on water since it uses up hunger extremely quickly. Also it can't walk on flowing water in any event.

**Comment by leijurv** [comment]
To see this for yourself, go on an island and turn on auto walk, and notice that it's fine with walking on water if it's the only option

**Comment by Cerbiac** [comment]
This is a baritone issue. You can change the penalty for walking on water with `.b walkOnWaterOnePenalty <Value>`.
