### ISSUE TITLE
Hud does not display in minecraft font

### ISSUE THREAD

**Issue by RogueParadox** [ImpactDevelopment/ImpactClient#1264]
Whenever I go to HUD and disable the TTF font it will never display the minecraft font for the whole Impact HUD.

**To Reproduce**
ClickGui > Render > Hud > Toggle TTF-Font

**Expected behavior**
Revert back to default minecraft font.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Hud, Tracers, ESP, Criticals, Inventory, Auto Totem
- Operating System: Windows 10 64bit

</details>

**Additional context**
I've tried to use optifine and forge and even rescaling the gui just to see if there was a change but still none.
I have been experincing this issue for three weeks now and made a github account just to report this.

**Comment by bfalmc** [comment]
i had the same issue
