### ISSUE TITLE
Use Hotkey to Close ClickGUI

### ISSUE THREAD

**Issue by Cerbiac** [ImpactDevelopment/ImpactClient#1266]
**Is your feature request related to a problem? Please describe.**
The keybind for ClickGUI only turns it on, and not off. So you have to use Esc to escape the ClickGUI as opposed to using the same button. Kind of awkward sometimes until you get used to it.

**Describe the solution you'd like**
Simply allow the keybind for ClickGUI to work like other keybinds: toggles the module on and off.

**Describe alternatives you've considered**
One issue might be that it interferes with creating a Keybind as it would close the ClickGUI if you try to bind another key to the ClickGUI hotkey, but I realized that when creating one, it already ignores Keybindings, so not issue.

**Additional context**
I saw an issue opened that was closed despite this not working, so I presume creating a new issue is better than bumping a closed issue.

**Comment by LeafHacker** [comment]
The intended behaviour is that the keybind will close clickgui while it is open. If it doesn't that is a bug.

Which impact and minecraft versions are you using?

**Comment by LeafHacker** [comment]
Can't reproduce this on 4.6 for 1.12.2 or 1.13.2, perhaps you are using an older version before we added the feature.

**Comment by LeafHacker** [comment]
My bad, this is a duplicate of #1258
