### ISSUE TITLE
"Impact Files" Button Not Working

### ISSUE THREAD

**Issue by Cerbiac** [ImpactDevelopment/ImpactClient#1268]
**Describe the bug**
The "Impact Files" button in "Impact" does nothing, but does play a click sound when pressed and becomes highlighted when hovered over.

**To Reproduce**
1. Go to the Main Menu or Title Screen. (Both Work.)
2. Click on "Impact".
3. Click on "Impact Files".
4. Notice it doesn't work.

**Expected behavior**
I expected it to open `%appdata%\.minecraft\Impact` in Windows Explorer.

**Screenshots**
Impact Folder: https://i.imgur.com/pq2BPVh.png
Impact Menu w/ "Impact Files" Highlighted: https://i.imgur.com/ylvQKsc.png

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.6 for 1.13.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Default (Hud, Main Menu)
- Operating System: Windows 10 64bit

</details>

**Comment by leijurv** [comment]
This is the same underlying issue as #1151 (it applies to 1.13.2 only), and was fixed in 4.7 (in commit https://github.com/ImpactDevelopment/Impact/commit/5b02a26fac7f4352d92f560d3b936ac17cb36c4a).
