### ISSUE TITLE
The title font causes weird dots to be rendered

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#127]
![image](https://user-images.githubusercontent.com/23565638/29486535-0377616c-84e0-11e7-93e5-a8b12d37b346.png)
![image](https://user-images.githubusercontent.com/23565638/29486543-592732a4-84e0-11e7-86af-3569d12b7325.png)

**Comment by ZeroMemes** [comment]
I hadn't figured out the solution before releasing 4.1, so I cheaply placed rectangles over the dots to cover it all up :(

**Comment by LeafHacker** [comment]
oh I removed them lol oops

**Comment by ZeroMemes** [comment]
yeaaa

**Comment by ZeroMemes** [comment]
Fixed in 4.2
