### ISSUE TITLE
Crash/Bug - Forge and Mods compatibility

### ISSUE THREAD

**Issue by FawkesOficial** [ImpactDevelopment/ImpactClient#1271]
### So my game crashed...

_Note that I'm very bad at making an issue but I will try my best._

I was playing in a server when my game crashed after hovering my mouse on a Shulker.
Note that I tested it in singleplayer as well and same issue.

The crash was: 

> java.lang.NullPointerException: Rendering screen
net.minecraft.client.gui.inventory.GuiContainerCreative 
> 

And the crash report was this:
[crash-2019-06-09_22.31.19-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3270098/crash-2019-06-09_22.31.19-client.txt)

Forge Version:
1.12.2-forge1.12.2-14.23.5.2768

Mods that I was using:
![Screenshot_1](https://user-images.githubusercontent.com/45067011/59165562-ce1b9900-8b15-11e9-86cc-6d8f96906eb8.png)

My Impact CFG(_coverted to .txt for this post_):
[default.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3270107/default.txt)

This issue is not urgent. I am currently playing just using Impact alone but would be good to have some help on this.

If there is anything else that I can provide for this issue let me know.

Thanks!

**Comment by usereewrjrjeejr** [comment]
Forge be like crashing noises

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/FAQ#impact-crashes--does-something-weird-when-i-run-it-with-x-other-forge-mod
