### ISSUE TITLE
clickgui blur position bug

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactClient#1272]
**Describe the bug**

**To Reproduce**
1. open clickgui
2. navigate to render tab->clickgui
3. set scale to anything else than 1
4. enable blur

**Expected behavior**
blur should cover entire clickgui but when you scale it, blur always stays in the same position as if clickgui wasnt scaled at all

**Screenshots**
![image](https://i.imgur.com/acqEV5W.jpg)
 
- Impact Version: 4.6 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: [click](https://i.imgur.com/oTU8U9P.png)
- Operating System: Win 10 Pro x64 1903

**Comment by leijurv** [comment]
Fixed in 4.7, **but** its still a little laggy while dragging the scale slider. Once you let go of the slider it is correct though. See https://youtu.be/5lHHEql6RR0
