### ISSUE TITLE
SafeWalk bug

### ISSUE THREAD

**Issue by A-Zalt** [ImpactDevelopment/ImpactClient#1276]
**About**
When there is comparator or repeater on a block you can fall down if it's close to the pit and if there is block with no repeater or comparator (bug doesnt work on edges)

**Expected behavior**
It definetely should not let you fall down

**Comment by A-Zalt** [comment]
My settings:
Impact Version: 4.6 for 1.12.2
Using Optifine? Yes
Using LiteLoader? No
Using Forge? Yes
Enabled mods: Infinity Item Editor, Shulker Box Viewer, In-game Account Switcher, SinglePlayer WorldEdit, JEI & NEI
Operating System: Win 10 Pro x64 1903

**Comment by Cerbiac** [comment]
Not only happens with `Safewalk`, but also with Minecraft's crouch. If you could automatically step back up the block you fell, you will fall (which is like 0.5 blocks), so it both A) makes sense, and B) not an Impact issue.
<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2 
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods: SafeWalk 
- Operating System: Windows 10 64bit 

</details>

**Comment by ZeroMemes** [comment]
SafeWalk simply activates the logic for sneaking on the edge of blocks when you aren't sneaking, I am not interested in fixing this given that it's an edge case scenario and would require me to do a bit of rewriting of minecraft's handling of sneaking.
