### ISSUE TITLE
Spam IDs bug

### ISSUE THREAD

**Issue by A-Zalt** [ImpactDevelopment/ImpactClient#1277]
**Describe the bug**
It allows you to name ID of spam with spaces but not set them

**To Reproduce**
1. Type .spam setup
2. Enter any ID (it must have spaces)
3. Set it up in any way
4. Try to enter the ID

**Expected behavior**
I expected it to not allow to setup such ID or to allow to set this ID

**Comment by Cerbiac** [comment]
Surround the id in parentheses. It works.
i.e. `.spam setup "foo bar"`

**Comment by ZeroMemes** [comment]
I'm going to leave this issue on the cmment from @Cerbiac, however I won't be explicitly adding quotations. For further reference, `String` arguments (any piece of text) for commands should be surrounded by quotes when they contain spaces.
