### ISSUE TITLE
Soup can't be toggled

### ISSUE THREAD

**Issue by AstragoYT** [ImpactDevelopment/ImpactClient#1278]
**Describe the bug**
I can't turn 'Soup' on

**To Reproduce**
-/-

**Expected behavior**
toggle the soup feature 

**Screenshots**
-/-

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by Cerbiac** [comment]
Can confirm.
The state can't even be forced on via the file. (I closed the game while doing this.)
<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.13.2 
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods: None 
- Operating System: Windows 10 64bit 

</details>

**Comment by ZeroMemes** [comment]
Soup and Pot are both modules that are basically a keybind activated action. Soup will drink soup on your hotbar. Pot will throw a health potion if it's on your hotbar. It does both of these actions in a legit manner, and they are not fully automated.

With that stated, I will close this issue and investigate the issue referenced by @Cerbiac.

**Comment by Cerbiac** [comment]
Actually, I don't remember if I tested it with my food low or not, but I presumed I did.
