### ISSUE TITLE
breadcrumbs height calculation on snow covered blocks

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactClient#1280]
**Describe the bug**
Breadcrumbs render height is too low on snow covered blocks. 

**To Reproduce**
1. enable render->breadcrumbs (without walls)
2. walk on snow covered blocks

**Expected behavior**
Breadcrumbs should appear visibly (above snow)

**Video**
https://streamable.com/ftv70

**Setup**
- Impact Version: 4.6 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: [click](https://i.imgur.com/T27BocP.png)
- Operating System: Win 10 Pro x64 1903

**Additional context**
I do realize that one can use walls option to make it visible. But snow is not wall. Also this problem makes breadcrumbs (without walls) useless on snowy terrain assuming you are walking on the ground.

**Comment by Cerbiac** [comment]
You sink into 1/16 of a block. That's just how snow blocks work. ;-;

**Comment by leijurv** [comment]
As a workaround, try adding another layer of snow or two to that biome. I think you start standing on top of it at layer 2 or 3. You'll be able to see your breadcrumbs just fine then :+1:

**Comment by Cerbiac** [comment]
@leijurv You' always sinky 1/16 into snow layers, no matter the actual height. I.e. 2 layers (2/16) means you'll walk 1/16 up. This also means adding all 16 layers may look like a full snow block, but isn't.

**Comment by ZeroMemes** [comment]
I suppose the way that breadcrumbs would gauge where to record the player's position could be determined by the max height of whatever block they are currently standing in.

**Comment by leijurv** [comment]
well we dont really want the max height, we want the difference between rendered height and collided height I guess? 

is there any block except snow thats like this...?

oh soul sand

so we could do some cancer with operating on voxel shapes.......... orrrrrrrrrr we could pull a gooooood ol' +0.1251

**Comment by leijurv** [comment]
Added in 4.7
