### ISSUE TITLE
Auto Armor's "Inventory Open" is Backwards

### ISSUE THREAD

**Issue by Cerbiac** [ImpactDevelopment/ImpactClient#1283]
**Describe the bug**
With `Inventory Open` value enabled under `Auto Armor`, it only equips items when the inventory is closed, as opposed to open, despite the wording suggesting the opposite.

**To Reproduce**
1. Enable `Auto Armor` w/ `Inventory Open` enabled.
2. Put armor in your inventory w/ it open.
3. Notice it doesn't auto-equip.
4. Close inventory.
5. Notice it auto-equips.

**Expected behavior**
Armor should only auto-equip with the *inventory open*, as opposed to closed.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2 
- Using Optifine? No 
- Using LiteLoader? No 
- Enabled mods: `Auto Armor` with `Inventory Open` 
- Operating System: Windows 10 64bit 

</details>

**Additional context**
Intentionally tested it in singleplayer.

**Comment by leijurv** [comment]
Fixed in 4.7
