### ISSUE TITLE
Game not loading? (Mainly a minecraft problem but also happens with Impact)

### ISSUE THREAD

**Issue by OreoZ-Z** [ImpactDevelopment/ImpactClient#1288]
So whenever i open my launcher it all works then i pick my version (1.14(Not 1.14.2 or 1.14.1)) and i click play then it closes the launcher (normal) then i wait like 5 seconds and then i go onto a white screen then if i try clicking around the top switches from "Minecraft 1.14" to "Minecraft 1.14 (Not Responding)" and i tried to reinstall everything even the files but it just never works.(Picture below i think)
and i don't know what to do or how to fix it. Thats all, Bye!
![McHelp2](https://user-images.githubusercontent.com/51468238/59302897-a124ce80-8c5a-11e9-8949-87d2e7036118.PNG)

and i already tries redownloading, removing ALL FILES and redownloading. ive tried a lot of other stuff

**Comment by leijurv** [comment]
You're having an issue launching vanilla minecraft 1.14, the issues for a client that's still on 1.13.2 is not the place to report this.....

**Comment by usereewrjrjeejr** [comment]
♿
