### ISSUE TITLE
Can't leave empty FriendTab in 1.12

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactClient#129]
![friends](https://user-images.githubusercontent.com/29576723/29489313-2ba75e1a-851e-11e7-9aab-7ede093a446b.PNG)

**Comment by LeafHacker** [comment]
Press `Esc`

Or just close the client.

What bug are you reporting or is this a help request?

**Comment by ZeroMemes** [comment]
Closing because a solution to the issue was posted
