### ISSUE TITLE
The drowning bubbles appear when the freecam is in water, not when the player is

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#1290]
1.12.2

**Comment by ngt1133** [comment]
who cares?

**Comment by LeafHacker** [comment]
I wonder if we can get the entire ingamegui drawn from the player's perspective rather than the camera's? Either that or force F1 mode when in freecam like we force non-F5 mode.

**Comment by a6d6061ed1** [comment]
> I wonder if we can get the entire ingamegui drawn from the player's perspective rather than the camera's? Either that or force F1 mode when in freecam like we force non-F5 mode.

that'd be really useful especially when using mods like schematica or debug viewing of chunk borders

**Comment by leijurv** [comment]
> who cares?

You don't know if your main player is drowning

**Comment by usereewrjrjeejr** [comment]
Oxygen meter time

**Comment by 0-x-2-2** [comment]
> > I wonder if we can get the entire ingamegui drawn from the player's perspective rather than the camera's? Either that or force F1 mode when in freecam like we force non-F5 mode.
> 
> that'd be really useful especially when using mods like schematica or debug viewing of chunk borders

both of these are not even rendered with the ingamegui 🤔

**Comment by a6d6061ed1** [comment]
> > > I wonder if we can get the entire ingamegui drawn from the player's perspective rather than the camera's? Either that or force F1 mode when in freecam like we force non-F5 mode.
> > 
> > 
> > that'd be really useful especially when using mods like schematica or debug viewing of chunk borders
> 
> both of these are not even rendered with the ingamegui 🤔

I misunderstood then. My point was that things like chunk borders / schematica overlays move with freecam which is annoying

**Comment by ZeroMemes** [comment]
> I misunderstood then. My point was that things like chunk borders / schematica overlays move with freecam which is annoying

I'll look at the schematica code to see if we can create a Mixin which can soft-fail on trying to patch it. Luckily, the chunk border issue has been fixed in 4.7.

**Comment by ZeroMemes** [comment]
This affected all of the players general stats: armor, health, food, and air bubbles.

Fixed in 4.7
