### ISSUE TITLE
freecam moving on its own while being pushed by water with jesus solid

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactClient#1291]
**Describe the bug**
Freecam starts flying upwards on its own if enabled along with jesus (solid) while being pushed by water. It keeps going up (and you can't move it back down, you can only stop it temporarily or look around). This persists as long as you're being pushed by water.

**To Reproduce**
1. Enable jesus solid
2. Position your player so that water is pushing you constantly
3. Go into free camera

**Expected behavior**
You should be able to control freecam behavior, instead its moving on its own

**Video**
[https://streamable.com/rc8eo](https://streamable.com/rc8eo)

**Setup**
- Impact Version: 4.6 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: only jesus (solid) and freecam
- Operating System: Win 10 Pro x64 1903

**Comment by Cerbiac** [comment]
`Flowing` must be off for this to work.

**Comment by Cerbiac** [comment]
It seems to literally hold space to make you float. I mean. IG it works. kek

**Comment by ZeroMemes** [comment]
It's effectively holding space for your actual player AND the freecam player.

**Comment by ZeroMemes** [comment]
Okay actually turns out that this issue only affects the 1.12.2 version because I rewrote the majority of Jesus in the 1.13.2 update and didn't bother to transfer the compatibility changes that went with it.

**Comment by ZeroMemes** [comment]
Actually fixed this time!
