### ISSUE TITLE
Tracer colors

### ISSUE THREAD

**Issue by ItsEkyx1** [ImpactDevelopment/ImpactClient#1293]
Recently I found a problem. Using tracer you can't tell is it a player or a mob. I found this really annoying on survival servers. You're scared because you're new to the server and don't have any gear and you at the first look tell is this a player or just a sheep coming in your direction.

My solution for this is just add colors to tracer that will let you know is it a player or a mob in your distance. Colors can be same as they are on radar. Thanks a lot ;3

**Comment by DanCuber** [comment]
The same could be set for esp: different colors for passive, hostile, neutral mobs, players and items

**Comment by Cerbiac** [comment]
Player already has colored tracers ♿, but @DanCuber has a good point.

**Comment by leijurv** [comment]
You want to differentiate hostile vs passive?

I mean I guess

**Comment by Shyrogan** [comment]
> You want to differentiate hostile vs passive?
> 
> I mean I guess

Yeah or customizable colors for animals, players, monsters etc...

**Comment by leijurv** [comment]
Players is already customizable so it would be just hostile vs passive

**Comment by leijurv** [comment]
Yeah I'll reorganize this and have three different colors instead of one main color and one override for players.

**Comment by Cerbiac** [comment]
Interesting idea that takes this to the next _next_ level. The ability to have custom hexa (or similar format) based on entity ID using a file. The code could be wrriten in .json like this:```json
[
    {
        "id": "minecraft:pig",
        "color": "#FF69B4CC"  // Hot Pink at 80% Transparency
    }
]

**Comment by 2b2tQueueProject** [comment]
Not everyone is a JSON hacker you know.

**Comment by Cerbiac** [comment]
That implies json is difficult and requires a experienced hacker. I mean, all of the other files are written in `.json` as well. What other solution is there. :/

**Comment by 2b2tQueueProject** [comment]
![image](https://user-images.githubusercontent.com/27324728/59970824-7893b300-953d-11e9-98fb-81eddb052897.png)

**Comment by Cerbiac** [comment]
Propose a solution besides an in-game interface. And tell me why someone that intelligent would care to think about something like this.

**Comment by leijurv** [comment]
Added in 4.7
