### ISSUE TITLE
Add End Crystals to ESP

### ISSUE THREAD

**Issue by DanCuber** [ImpactDevelopment/ImpactClient#1294]
**Describe the bug**
When using ESP, entities such as ender crystals, boats and armor stands won't be outlined/have a box around them

**To Reproduce**
Enable esp, then spawn in the previously listed entities, and you'll see the behaviour described above.

**Expected behavior**
The entities should show up on esp according to the mode chosen in esp settings

**Comment by leijurv** [comment]
adding crystals to esp is probably a very good idea

**Comment by leijurv** [comment]
Added in 4.7
