### ISSUE TITLE
Settings local save

### ISSUE THREAD

**Issue by VirxEC** [ImpactDevelopment/ImpactClient#1298]
**Is your feature request related to a problem? Please describe.**
I hate it when I have to use MultiMC to save my Impact settings for different servers. WHY? I shouldn't have to create a profile for every server.

**Describe the solution you'd like**
There should be a command, like **.localsettings save *savename*** which will save all settings and keybinds to a file on your computer. Then, you can just use **.localsettings load *savename*** and all settings and keybinds will be loaded from the file, overriding everything else. (It will override ALL settings, as you could just save those settings, too.) The file could be placed in a Impact folder, called something like *savename.imp*

**Comment by Cerbiac** [comment]
The config is already saved in a folder as it is, but yeah. Being able to change midgame w/o renaming a file would be nice.

**Comment by ZeroMemes** [comment]
uh, what? Impact settings are stored in the minecraft installation directory that they are ran in.

**Comment by VirxEC** [comment]
Like, the Impact client can store different groups of settings in, idk, a zip file, or something like a .imp (for Impact) file. It would contain data for, I guess you could say another profile. These different settings could be swapped out. For example, you could have one group of settings for say, Hypixel, then you hope over to CubeCraft, and you load up another bunch of settings in-game, no hassle. If you want a reference, [LiquidBounce](liquidbounce.net) has implemented very well. They have the command ".localsettings save" and ".localsettings load". They also have other things, like preset configurations for different servers, but Impact doesn't need that because it has the Auto-Hack module.

**Comment by Cerbiac** [comment]
Presets made from multiple settings files, basically.

**Comment by leijurv** [comment]
Config is already in a folder, and it's called default.json, we could add support for just switching to a different file. And maybe for switching to a given one based on server.

**Comment by leijurv** [comment]
Better/simpler idea. Just a simple preset save/load system. Like, `.save presetname` would save your current settings to Impact/config/presetname.json. Any further changes you make afterwards, however, wouldn't be saved there, only to the standard default.json (so, it doesn't change your save location). Then you could load it with `.load presetname`. The idea for servers would be that you save it with the name being the server IP. For example, `.save hypixel.net`. Then, when you join a server, it would load the preset for that IP if you have it.

**Comment by VirxEC** [comment]
> The idea for servers would be that you save it with the name being the server IP. For example, `.save hypixel.net`. Then, when you join a server, it would load the preset for that IP if you have it.

Yes, that's exactly what I was getting at, but I didn't think of it auto-loading... That's a good idea. then if you didn't want it to auto-load, you just don't set it the server IP, you just set it to the server name or something.

**Comment by leijurv** [comment]
Added in 4.7
