### ISSUE TITLE
Typo on safewalk

### ISSUE THREAD

**Issue by Zipdox** [ImpactDevelopment/ImpactClient#1299]
There's a typo in the UI
[https://imgur.com/a/eIzHmYQ](https://imgur.com/a/eIzHmYQ)

**Comment by EmeraldSnorlax** [comment]
zipdox biome

**Comment by EvilSourcerer** [comment]
PREVIEW
![image](https://user-images.githubusercontent.com/32974335/59556406-13b1e900-8f90-11e9-80df-08cb65e961cc.png)

This is critical

Zipdox Biome

**Comment by leijurv** [comment]
whats the typo

**Comment by leijurv** [comment]
oh my god im blind

**Comment by leijurv** [comment]
oh this has already been fixed in 4.7 btw

**Comment by EvilSourcerer** [comment]
what's the issue?

**Comment by EvilSourcerer** [comment]
i can't see it

**Comment by EmeraldSnorlax** [comment]
![Zipdox Biome](https://cdn.discordapp.com/attachments/568008310033219592/585552419174350942/image0.jpg)

**Comment by EvilSourcerer** [comment]
zipdox biome

**Comment by EvilSourcerer** [comment]
OMFG I AM BLIND WHAT THE FUCK

**Comment by leijurv** [comment]
the typo is fro`n` vs fro`m`

**Comment by EmeraldSnorlax** [comment]
the typo is zipdox existing

**Comment by jvyden420** [comment]
zipdox biome

**Comment by usereewrjrjeejr** [comment]
9b9t is better

**Comment by Zipdox** [comment]
@EmeraldSnorlax @jvyden420 What the frick are you doing on my GitHub you filthy stalkers

**Comment by EmeraldSnorlax** [comment]
@Zipdox Zipdox Biome

**Comment by EvilSourcerer** [comment]
@Zipdox Biome

**Comment by EmeraldSnorlax** [comment]
@Zipdox Biome
