### ISSUE TITLE
UI Scaling issues

### ISSUE THREAD

**Issue by shepanator** [ImpactDevelopment/ImpactClient#13]
The impact UI scales terribly on anything but 'normal' UI scale setting on a 1440p screen. It's blurry and sometimes hangs over the edges of the screen.
This carries over into the in-game HUD too.
![untitled](https://cloud.githubusercontent.com/assets/25123228/21957219/2e956e46-da92-11e6-8a11-b3619640f275.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/25123228/21957237/9ca340c0-da92-11e6-98e5-fed8f15b1537.jpg)

**Comment by ZeroMemes** [comment]
Will look into it.

**Comment by ZeroMemes** [comment]
Main menu has been redone, and the unicode font in the hud has been given an option. (3.1)
