### ISSUE TITLE
POI finder (baritone?)

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactClient#1300]
**Is your feature request related to a problem? Please describe.**
Sometimes I struggle to find mansions or end cities

**Describe the solution you'd like**
Add new mod that'd allow to locate points of interest like end cities after entering map seed

**Additional context**
If map seed is known its possible to calculate exact position of randomly generated locations such as mansions, end cities etc. Example implementation: https://chunkbase.com/apps/

Additionally I think **seed bruteforcer** would be quite cool feature to go along with above suggestion in case seed isnt publicly available. I do realize it takes some time to resolve map's seed and it may even take days with cheap hardware but it's just something to think about.

**Comment by EmeraldSnorlax** [comment]
.locate is already a thing

**Comment by a6d6061ed1** [comment]
> .locate is already a thing

ok I feel embarrassed now. what about seed resolver?

**Comment by EmeraldSnorlax** [comment]
seed resolving will take an such an incredibly long time to resolve that it's really not worth doing imo, but ask the devs anwyay

**Comment by a6d6061ed1** [comment]
> seed resolving will take an such an incredibly long time to resolve that it's really not worth doing imo, but ask the devs anwyay

Well I think that depends on your hardware and how well optimized resolving algorithm is. Im pretty sure it can be either fast or slow depending on those conditions.

I know this question probably doesn't belong here but can you tell me what am I doing wrong querying locate mod like that:
`.locate Village -4172144997902289642`
it says that "Server seed must be provided" even though its provided

**Comment by EmeraldSnorlax** [comment]
create a world in singleplayer with that seed, tp to your current server coords then run that command

**Comment by a6d6061ed1** [comment]
> create a world in singleplayer with that seed, tp to your current server coords then run that command

that doesn't make much sense. in singleplayer I can use minecraft's `locate` command normally so what's the point in that mod (assuming it only works in SP)?

**Comment by VirxEC** [comment]
The .locate command is currently broken. Also, adding such a feature to baritone would be nice, too.

**Comment by usereewrjrjeejr** [comment]
.locate is getting removed in 4.7

**Comment by leijurv** [comment]
on the contrary, i managed to fix `.locate` on 1.12.2 only.

https://impactdevelopment.github.io/Impact/changelog

it's too fucknig scuffed on 1.13.2 to make work on multiplayer, would have to create a wholly new world object and generate it and its wayyyyyyyyy too cancer.

**Comment by leijurv** [comment]
For bruteforcing seeds, I highly recommend https://github.com/Badel2/slime_seed_finder

With that and `.locate` I'm going to close this -- there are so many different ways to brute force a seed, and there's really no reason why it needs to be built into your client, it's such a one time operation.
