### ISSUE TITLE
Remove Tutorial Part with Moving

### ISSUE THREAD

**Issue by Bircko** [ImpactDevelopment/ImpactClient#131]
It's annoying af when this appears and you can't get it away

**Comment by LeafHacker** [comment]
I think impact should go the opposite route and add to the tutorial in an attempt to reduce frequently asked questions on discord.

**Comment by Bircko** [comment]
Ignore these if someone is too retarded to put a file in the version folder he probably shouldn't use a pc

**Comment by ZeroMemes** [comment]
Not removing vanilla features like this for user convenience.
