### ISSUE TITLE
Terrain --> Ladder Speed Doesn't Work

### ISSUE THREAD

**Issue by pullup** [ImpactDevelopment/ImpactClient#1313]
Build: Latest

How to reproduce:
Enable ladder speed multiplier and climb a ladder

Unexpected behavior, speed is not multiplied or changed in anyway

**Comment by usereewrjrjeejr** [comment]
Might be the anticheat

**Comment by ZeroMemes** [comment]
`Build: Latest` please refer to the specific Impact version and Minecraft version. I'm assuming you're using 4.6 for 1.13.2.

That being said, I found what is causing the issue and it should be very easy to fix.

**Comment by leijurv** [comment]
@ZeroMemes still needs fix uwu, it was commented

**Comment by ZeroMemes** [comment]
Fixed in 4.7.
