### ISSUE TITLE
Impact Latest on forge crashes

### ISSUE THREAD

**Issue by reed123** [ImpactDevelopment/ImpactClient#1319]
I have installed impact forge using the installer (v4.6,exe) and upon launching the game it crashes before it can show the main window. I am also using a few other mods as well as multi mc, and everything works fine without impact. Here is the log:

[log removed as it was the wrong one]

**Comment by usereewrjrjeejr** [comment]
Forge bad

**Comment by ZeroMemes** [comment]
This is likely a conflict with another mod. Please verify that a mod is causing the issue and not forge itself.

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

**Comment by reed123** [comment]
Hello There! I am very sorry for using wrong log, as that was multimc log. I have uploaded new log to paste. Previously, i was getting a mixin version error, but solved it by modifying the mixin file in the Impact-4.6-1.12.2.jar file, as the version in the mixins.capi.json was too high, and by decreasing that number I now have reduced the number of errors. I understand a little bit of java, and it seems like there is some sort of issue in the order that the mixins(note: i still have no idea what a mixin is) are being loaded. Something else worth noting is that I can verify that it is an Impact issue, as there is something that says "~[Impact-4.6-1.12.2.jar:?]" after each line. Please also note that this error suddenly started happening, and my current setup worked fine before.

Log: https://pastebin.com/ptKq5peM

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods

**Comment by leijurv** [comment]
sorry.

**Comment by babbaj** [comment]
mixin problem
🦍 
mixin problem
🦍 
mixin problem
🦍 
mixin problem
🦍 
mixin problem
🦍 
mixin problem
🦍 
mixin problem
🦍 
mixin problem
🦍

**Comment by 2b2tQueueProject** [comment]
Are you guys using `@Overwrite`...

**Comment by leijurv** [comment]
no?

**Comment by 0-x-2-2** [comment]
pozzed coremod detected loaded da class.....
