### ISSUE TITLE
Impact causes buildcraft to fail to load when installed together in a FML modpack.

### ISSUE THREAD

**Issue by xXG0DLessXx** [ImpactDevelopment/ImpactClient#1322]
**Describe the bug**
When installing impact in a modpack that has buildcraft installed, it will cause buildcraft to fail to load, thus stopping the game from starting at all.

**To Reproduce**

Install Impact on any 1.12.2 modpack that has buildcraft.

**Expected behavior**
I expect my game to load...

**Screenshots**
N/A

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 Minecraft 1.12.2
- Using Optifine?: No
- Using LiteLoader?: Not sure...
- Enabled mods: None
- Operating System: Tested on both macOS Mojave and Windows 10

</details>

**Additional context**

**Comment by usereewrjrjeejr** [comment]
Forge version is buggy

**Comment by xXG0DLessXx** [comment]
I mean, it works great with all the other mods I’ve tried so far. Only buildcraft breaks. Unfortunately, a lot of mod packs have buildcraft, and you need all the mods in order to join a server.

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
