### ISSUE TITLE
Baritone based area miner

### ISSUE THREAD

**Issue by Proximal** [ImpactDevelopment/ImpactClient#1326]
**Is your feature request related to a problem? Please describe.**
No not a problem

**Describe the solution you'd like**
I would like a feature that mines an area that is defined by the player. The feature should not only be able to pathfind to that area if not already in it, but also be able to avoid hazards while excavating the area. 

**Describe alternatives you've considered**
Considered using things such as nuker or giving baritone a list of commands, but having this as a standalone feature would be incredible for large scale mc projects. 

**Additional context**
Most features in modern clients are built around the same things (pvp, griefing) This is one of the few clients that stands out in any way. Would be great to have more features that other clients do not have.

**Comment by 2b2tQueueProject** [comment]
.b click
