### ISSUE TITLE
#1084 is back again

### ISSUE THREAD

**Issue by DerShendi** [ImpactDevelopment/ImpactClient#1327]
**Well its #1084 again but this time it wont work even online**

**To Reproduce**
This happend since MC got the new Launcher
1. just do the usual installing of impact
2. try to start that instance
3. this mess happens
**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
Failed to download file.
Name: discord-rpc-release-v3.3.0.jar
URL: https://jcenter.bintray.com/club/minnced/discord-rpc-release/v3.3.0/discord-rpc-release-v3.3.0.jar
Error details: schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
Filename on disk: discord-rpc-release-v3.3.0.jar
Path: C:\Users\shend\AppData\Roaming\.minecraft\libraries\club\minnced\discord-rpc-release\v3.3.0\discord-rpc-release-v3.3.0.jar
Exists: Nonexistent
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by leijurv** [comment]
This is so sad can we host all our dependencies

**Comment by EmeraldSnorlax** [comment]
its cloudflare taking a poopoo

**Comment by leijurv** [comment]
this was fixed by hosting all our dependencies

**Comment by 0-x-2-2** [comment]
> this was fixed by hosting all our dependencies

this github went down LOOOOOOOOOOOOOOOOOOL
