### ISSUE TITLE
password getting leaked

### ISSUE THREAD

**Issue by lolzhunter** [ImpactDevelopment/ImpactClient#1328]
password keeps getting changed on my mc account, i have to regularly reset it, this only started happening when i got impact, is there something in impact that does this, would like to remove it so my minecraft account stops getting hacked all the time

**To Reproduce**
just wait long enough, worked for me

**Expected behavior**
i expect for it not to change my mc password

- Impact Version: 4.6 for 1.13.2
- Using Optifine? yes
- Using LiteLoader? No
- Enabled mods: <!-- N/A
- Operating System: Windows 10 64bit

**Comment by ScanmanTM** [comment]
There's nothing in impact that does that.

**Comment by Cerbiac** [comment]
Nothing to do with Impact. Add security questions to your account and/or 2 factor authentication. I promise you we were not the ones who hacked your account, but someone (or a family member, which means everything is fine) has.

**Comment by Cerbiac** [comment]
Add me on Discord if you need help with it: Cerbiac#7148.
