### ISSUE TITLE
1.12.2. downloading errors

### ISSUE THREAD

**Issue by Bone4Crusher** [ImpactDevelopment/ImpactClient#1329]
So a few months ago my PC had issues downloading Steam updates, and Minecraft Impact updates, and a few other things. Then the power went out and it reset the UEFI settings, such as the XMP settings, and the AMD-V (Virtualization) settings. Now I say all that to say that it fixed the Steam issue, however the Minecraft issue still remained. I've restarted my PC, uninstalled and reinstalled Minecraft, I've tried downloading the update on multiple network connections, and even downloaded the update on the family PC. The family PC updated perfectly though and it ran Impact fine. There is a website blocker on my PC that my mother put there by the name of "Bluecoat K9 Web protection" however I've gone into task manager and ended the task along with any  affiliated programs.

Any help would be appreciated
-Bone4Crusher

**Screenshots**
![image](https://user-images.githubusercontent.com/52543419/60680604-ef904c00-9e59-11e9-870c-0bbd4319c2f5.png)

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2
- Using Optifine? No
-Using LiteLoader? No
- Enabled mods: 
- Operating System: Windows 10, 64bit

</details>

**Additional context**

**Comment by ScanmanTM** [comment]
Try retry installing impact, there was a recent URL change about 1hr ago.

**Comment by leijurv** [comment]
Yeah, changed the url for this dependency to be self hosted so that cloudflare having a bruh moment doesn't break the client, rerun the installer and it'll update the download url

**Comment by 0-x-2-2** [comment]
> Yeah, changed the url for this dependency to be self hosted so that cloudflare having a bruh moment doesn't break the client, rerun the installer and it'll update the download url

wow this is bigot cloudflare did nothing wrong

**Comment by leijurv** [comment]
Well..... They did.

They literally did?

**Comment by 0-x-2-2** [comment]
wrong it was verizon and aws and other things also did not work

**Comment by Bone4Crusher** [comment]
I booted Impact up about 2 minutes ago and it worked I guess the URL change was what it needed.
Many thanks
-Bone4Crusher
