### ISSUE TITLE
ElytraFly 

### ISSUE THREAD

**Issue by kekkekek** [ImpactDevelopment/ImpactClient#133]
I love impact but switch to clients like xdolf and future for elytrafly which bypasses aac on 2b2t and most anarchy servers. Basically it lets you fly with elytra on. Here is an example https://www.youtube.com/watch?v=MYxZqfP6XD8 (skip to 1:37)

**Comment by LeafHacker** [comment]
This still works? I guess I can add it when I get chance.

While we're talking elytra, how do other hacks like impact's elytra+, wurst/xdolf's ExtraElytra/EltraPlus, etc cope with anticheats nowadays?

**Comment by kekkekek** [comment]
@LeafHacker impact's elytraplus works on 2b and 3b3t going downward, which you can use to gain momentum and get higher up than when you started. Impact's definitely works the best, then xdolf and wurst.

**Comment by VitorISs** [comment]
or.. you can just turn on the "Creative" flight when you open your elytra... (works on NCP)

**Comment by ZeroMemes** [comment]
Added as a new ElytraPlus mode. Existing ElytraPlus has been put into "Control" mode, this has been put into "Flight" mode.
