### ISSUE TITLE
Can't see anything when I join a server or single player world.

### ISSUE THREAD

**Issue by Conflee** [ImpactDevelopment/ImpactClient#1330]
When I join a a game (singleplayer or multiplayer) with the latest 1.12.2 or 1.13 versions, my screen only shows the dirt background and the "cancel" button. I can hear sounds when I move etc, but I cant see the menu if I hit escape etc.

**Comment by usereewrjrjeejr** [comment]
Turn off freecam

**Comment by Conflee** [comment]
> Turn off freecam

Its not on.

**Comment by usereewrjrjeejr** [comment]
Do you know what you have on?

**Comment by Cerbiac** [comment]
Go to [`help`](https://discord.gg/V472wkN) on Discord. ;-;

**Comment by ScanmanTM** [comment]
Do you have shaders enabled? If so, disable it or turn ESP to box mode.

**Comment by zPeanut** [comment]
refer to #help on the official discord
