### ISSUE TITLE
Using forge Impact 4.6 alt manager crashes game.

### ISSUE THREAD

**Issue by Hackerokuz** [ImpactDevelopment/ImpactClient#1333]
**Describe the bug**
When I open Vanilla version of Impact 4.6 alt manager works fine but forge version crashes

**To Reproduce**
1. Go to 'impact'
2. Click on 'Alts'
3. Game crash happens

**Expected behavior**
I expected to open alt manager when I press on Alts button

**Screenshots**
Screenshots are useless in this case so here is a video:
https://anonfile.com/UbUbe4ycn4/Impact_4.6_crash_report_mp4

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[Game output Imapct 4.6.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3362908/Game.output.Imapct.4.6.txt)

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
[crash-2019-07-05_13.50.59-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3362903/crash-2019-07-05_13.50.59-client.txt)

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**
Java used,
Java Version: 1.8.0_211

**Comment by 0-x-2-2** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ#impact-crashesdoes-something-weird-when-i-run-it-with-insert-amount-here-other-forge-mods
