### ISSUE TITLE
Devs if you would be kind enough to steal Sigmas/Exhi module.

### ISSUE THREAD

**Issue by Hackerokuz** [ImpactDevelopment/ImpactClient#1342]
Devs if you would be kind enough to steal Sigmas and Exhibitions modules I'll be really grateful for it.
Riquests:
Batter scaffold
AutoClatch
Infinite Aura
Batter Teleport
Batter TeleportHit
and other modules if possible 😃
Video:
https://www.youtube.com/watch?v=tWcWA...

Downloads SRC:
Exhi: https://www77.zippyshare.com/v/Qz1SAr...
Sigma: https://www70.zippyshare.com/v/lvvidN...
and maybe add baritone from Impact client...

**Comment by usereewrjrjeejr** [comment]
Both links 404

**Comment by Hackerokuz** [comment]
Sorry for broken links
Video:
https://www.youtube.com/watch?v=tWcWAqvOL_g

Downloads SRC:
Exhi: https://www77.zippyshare.com/v/Qz1SArLj/file.html
Sigma: https://www70.zippyshare.com/v/lvvidNfq/file.html

**Comment by leijurv** [comment]
`and maybe add baritone from Impact client...`

wew lad

**Comment by 0-x-2-2** [comment]
add baritone from impact to impact

**Comment by Cerbiac** [comment]
Make seperate suggestion posts.
Also, skidding is not exactly cash money.
