### ISSUE TITLE
It won't install

### ISSUE THREAD

**Issue by alexzander700** [ImpactDevelopment/ImpactClient#1344]
Every time I try to install Impact, it bugs out and gives me a screen that looks like this. 
(I can't get it to load, so click the link...)
https://drive.google.com/open?id=1oRFRbubsgpRX8QWIcwi889hHl22GseQL

**Comment by Cerbiac** [comment]
Are you using Installer 3.0? Try redownloading it, or using Installer 2.0.

**Comment by Cerbiac** [comment]
Sidenote. You dragging that window was beautiful.

**Comment by 0-x-2-2** [comment]
Looks like a corrupted file.

**Comment by alexzander700** [comment]
I've tried reinstalling multiple times. I don't know how to access the older installer.

**Comment by alexzander700** [comment]
Should i try to manually install? If so, how would I do that?

**Comment by alexzander700** [comment]
I just went into the launcher and manually configured it.

**Comment by Cerbiac** [comment]
Please go to [`#help`](https://discord.gg/V472wkN).
