### ISSUE TITLE
Set freecam coords to baritone goal

### ISSUE THREAD

**Issue by impactuser1** [ImpactDevelopment/ImpactClient#1345]
Hey, it would be really cool if you could set your Freecam coords as baritone's goal!
(i.e. i fly somewhere with freecam and then real me walks/mines/parcours there)

**Comment by mrphax0r** [comment]
Can't you do that yourself ? :thinking:

**Comment by leijurv** [comment]
Already exists. Use `.b come` or `.b click`. =)
