### ISSUE TITLE
Remove org.json src dependancy

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#135]
Currently the `org.json` package is included in impact's source tree, I assume because something had to be patched.

We should remove it and port any json code over to gson.

![image](https://user-images.githubusercontent.com/23565638/29496451-bf0c62f2-85ca-11e7-9d42-1d6124f751f5.png)

**Comment by ZeroMemes** [comment]
I agree. GSON would probably yield a cleaner result. I've just always used ``org.json``, which is the only reason why it is in the source tree.

**Comment by LeafHacker** [comment]
Can probably use the `UUIDs.getPlayerUUID()` as an example of using gson, though there's a lot of error handling in that method to cater for different http responses and edge cases.

**Comment by ZeroMemes** [comment]
Removed the last usages of ``org.json`` in ``ModConfigLoader``, closing this issue.
