### ISSUE TITLE
Anti DeathScreen

### ISSUE THREAD

**Issue by Cadaver1337** [ImpactDevelopment/ImpactClient#1350]
A Feature that doesn't display the death screen, during crystal pvp having the deathscreen pop up when your still alive is extremely annoying

**Comment by ZeroMemes** [comment]
If the death screen shows, you're dead.

**Comment by Cadaver1337** [comment]
> If the death screen shows, you're dead.

that's where your wrong bud

**Comment by 0-x-2-2** [comment]
> > If the death screen shows, you're dead.
> 
> that's where your wrong bud

Unless you are playing on a broken server this is the case.

**Comment by Cadaver1337** [comment]
> > > If the death screen shows, you're dead.
> > 
> > 
> > that's where your wrong bud
> 
> Unless you are playing on a broken server this is the case.

turn on auto totem and go do some crystal pvp on 2b2tpvp, eventually you'll get the glitch

**Comment by babbaj** [comment]
📸

**Comment by Zamazenta** [comment]
video proof or it never happened

**Comment by 0-x-2-2** [comment]
> > > > If the death screen shows, you're dead.
> > > 
> > > 
> > > that's where your wrong bud
> > 
> > 
> > Unless you are playing on a broken server this is the case.
> 
> turn on auto totem and go do some crystal pvp on 2b2tpvp, eventually you'll get the glitch

yeah its a shit and broken server.

**Comment by LeafHacker** [comment]
The are only two cases in all of minecraft (none in impact code) where `GuiGameOver` is constructed.

- When `displayGuiScreen` is called with a null argument AND the player health is ≤ 0
- When `SPacketCombatEvent` with type `ENTITY_DIED` is received AND the specified player ID matches `mc.player`'s

The second can only happen incorrectly if the server is _really_ broken. However the first could potentially happen if the client thinks the player health is less than 0 and tries to open a null gui at the same time, however this seems unlikely without some _very_ buggy client code.

**Comment by ZeroMemes** [comment]
The issue is because of a plugin on a specific server that displays a death screen when you use a totem.
