### ISSUE TITLE
I don't know how to install impact on windows 10 (latest minecraft version available).

### ISSUE THREAD

**Issue by TangerineJuice1** [ImpactDevelopment/ImpactClient#1355]
I was following a guide on a website and i hit a roadblock in stuck and wherever i search it says nothing i need some help . :(

**Comment by StijnSimons** [comment]
Download installer from [here](http://impactdevelopment.github.io/) and run with Java.

**Comment by LeafHacker** [comment]
Use the exe version of the installer and it will find java for you, assuming it is installed somewhere
