### ISSUE TITLE
Add "category" option to HUD's list colors

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#136]
Impact used to colour HUD's module list based on the category of the mod. This got replaced by random colours, rainbow and other effects. It would be nice to add the old behaviour back as an option.

**Comment by LeafHacker** [comment]
I've added this to 4.1, but @ZeroMemes still needs to set the actual category colours.

**Comment by ZeroMemes** [comment]
Category colors have been set, closing.
