### ISSUE TITLE
[FEATURE] Add more customizability to stealing from chests

### ISSUE THREAD

**Issue by mrphax0r** [ImpactDevelopment/ImpactClient#1363]
↑

**Comment by ScanmanTM** [comment]
So are you going to give information on what could be customised? This deserves to be closed.

**Comment by StijnSimons** [comment]
Very detailed, much clear. uwu

**Comment by ZeroMemes** [comment]
Closing due to lack of following the template that would've made this issue actually have value.

**Comment by mrphax0r** [comment]
e.g. Delay, randomness, which items are to be stolen etc. pp

**Comment by mrphax0r** [comment]
_invalid_

**Comment by StijnSimons** [comment]
You're about 9 minutes late with that lol
