### ISSUE TITLE
Nametags don't render when enabled

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#137]
When I turned nametags or tracers on, it didn't work... 

- The vanilla nametags just disappeared, so I couldn't see the names of other players. 
- The tracer lines that should point to players didn't appear

@ZeroMemes said it may be an issue with world to screen conversion.

**Comment by LeafHacker** [comment]
This is another bug caused by OptiFine's "Fast Render" setting. Turning off Fast Render is the only known work around for this.

**Comment by ZeroMemes** [comment]
Bumping to 4.1 milestone

**Comment by LeafHacker** [comment]
Remove milestone since this is WontFix/Upstream
