### ISSUE TITLE
Auto Eject Crash-Please Fix

### ISSUE THREAD

**Issue by SaiBot-YT** [ImpactDevelopment/ImpactClient#1371]
Minecraft is crashing when looking in an inventory and collecting an unwanted item.
Please Stop this.

Tested in a furnace. 
Thank you! #

**Comment by ZeroMemes** [comment]
Please provide the crashlog so the issue can be pinpointed.

**Comment by SaiBot-YT** [comment]
[crash-2019-07-21_10.11.19-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3414418/crash-2019-07-21_10.11.19-client.txt)
I reproduced this crash by having one diamond_word and 10 iron_sword in my inventory and opening the furnace in the right moment.

**Comment by ZeroMemes** [comment]
Fixed in 4.7
