### ISSUE TITLE
Please add Auto Collect item

### ISSUE THREAD

**Issue by SaiBot-YT** [ImpactDevelopment/ImpactClient#1372]
If an specific item is dropped, The player should walk toward and collect it(in a specific range)

For me it would be useful to farm apples.

**Comment by Thunder33345** [comment]
probably something useful for baritone integration 
baritone seems to be able to scan and collect dropped items 
if it could expose a command to do so, that would be nice

**Comment by ZeroMemes** [comment]
This is ideally something that could be added to Baritone’s chat control. I would suggest making an issue [there](http://github.com/cabaletta/baritone).
