### ISSUE TITLE
auto tree cutter

### ISSUE THREAD

**Issue by youri123456** [ImpactDevelopment/ImpactClient#1374]
i want a tree cutter that does it fully automaticly that will automaticly walk to trees and cut them, i would like on there a feature on there that i can select a cooldown because on a server i play on there is like a 1,5 second cooldown for breaking blocks. (i also would like that on automine)

**Comment by StijnSimons** [comment]
Player>Auto Mine>Bot Mode>Logs????????????????????????????????????????????????

**Comment by Rindula** [comment]
Also, in Chat `.b mine [BlockID1] <BlockID2> ...` works

**Comment by youri123456** [comment]
ow didnt see that, is there also a thing already for a cooldown

**Comment by youri123456** [comment]
because there is a cooldown on a server where i play on and it now my pickaxe will break very fast because it want to break the block but the server will place them back

**Comment by StijnSimons** [comment]
This probably wont effect your durability. They’re probably using a BreakBlockEvent and cancelling that, which doesn’t take away durability. Let me know if i’m wrong.

**Comment by youri123456** [comment]
that could be true, thanks so much

**Comment by ZeroMemes** [comment]
I’m considering this resolved
