### ISSUE TITLE
Wall through walls

### ISSUE THREAD

**Issue by WobblierDog15** [ImpactDevelopment/ImpactClient#1376]
I would like an option to noclip through walls or at least teleport myself a certain amount of blocks forward to get through walls. Thanks.

**Comment by usereewrjrjeejr** [comment]
`>Wall through walls`

**Comment by ScanmanTM** [comment]
.clip ??

**Comment by Thunder33345** [comment]
probably meant something like active phasing?
like just enable the hack and if the wall is <x thickness and you bump into it,
client will phase it for you without you having to spam clip everytime you near a wall

**Comment by WobblierDog15** [comment]
.clip doesn’t work for me. Is there something I’m supposed to do after it?

**Comment by WobblierDog15** [comment]
Ok nvm I’ll just make a new thread
