### ISSUE TITLE
Alts Crashing On Forge

### ISSUE THREAD

**Issue by ChillSheep** [ImpactDevelopment/ImpactClient#1377]
Describe the bug
The game keeps crashing on this version with forge and NOTHING ELSE... in fullscreen or windowed mode. On the normal 1.12.2 verision of minecraft and impact 4.6 the alt manager works.

To Reproduce

    Go to 'the mc starting screen'
    Click on 'Impact in the right corner below multiplayer'
    Scroll down to 'ALTS'
    See error: Game instant crashes

Expected behavior
The Alt manager should open like in all the other version of impact

Crash report

The game crashed whilst updating screen events
Error: java.lang.NoSuchFieldError: field_181546_a

Additional Client Info

    Impact Version: 4.6 for 1.12.2
    Using Optifine? No
    Using LiteLoader? No
    Enabled mods: /
    Operating System: Windows Server 2019

**Comment by leijurv** [comment]
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ
<img width="838" alt="Screen Shot 2019-07-18 at 10 43 47 AM" src="https://user-images.githubusercontent.com/3837873/61479569-f1253e00-a948-11e9-91a2-3359fd3b6c41.png">

Sorry.
