### ISSUE TITLE
Xray render bugs

### ISSUE THREAD

**Issue by lolw0tm8** [ImpactDevelopment/ImpactClient#1378]
**Xray doesn't render ANY blocks, ONLY entities and items.** - Using forge 1.12.2
I use Optifine and LabyMod mods with your utility mod.
Please, let me know when it is fixed and when i should download newest installer.

**Comment by ZeroMemes** [comment]
What is the specific version of Forge, Optifine, and LabyMod that you are using? Have you experienced the same issues when you are, for example, not using one or any of those?

Also the Installer is automatically populated with new versions, whenever a new Impact version one is released you will be notified upon launching it.

**Comment by lolw0tm8** [comment]
Optifine 1.12.2 HD U E2
LabyMod 3
forge 1.12.2-14.23.0.2512

**Comment by ZeroMemes** [comment]
>Have you experienced the same issues when you are, for example, not using one or any of those?

**Comment by lolw0tm8** [comment]
No, didn't test it yet
I will try and tell you

**Comment by lolw0tm8** [comment]
Tried removing LabyMod and Optifine, still same, renders only entities

**Comment by ZeroMemes** [comment]
I forgot one thing: can you confirm you actually have blocks to show up in Xray? `.xray list`

**Comment by lolw0tm8** [comment]
Oh that was the issue? I thought that ores are added to the list automatically!
Tysm for your help
