### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Derekbgzz** [ImpactDevelopment/ImpactClient#1379]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by zPeanut** [comment]
invalid isssue

**Comment by usereewrjrjeejr** [comment]
Good issue
