### ISSUE TITLE
When ever I use storage esp my game crashes

### ISSUE THREAD

**Issue by Derekbgzz** [ImpactDevelopment/ImpactClient#1380]
**Describe the bug**
When ever i enable storage esp my game crashes and it says it was some kind of unexpected behavior

**To Reproduce**
Just enable storage esp

**Screenshots**
![github](https://user-images.githubusercontent.com/52985744/61502746-b51ac900-a99a-11e9-8ad1-2dd31b6d1af5.PNG)

And i am not using any mods im using 1.13.2 that is all

**Comment by Rindula** [comment]
Works for me 🤔 no crash, just chests ... Maybe you could try to reinstall it ...

**Comment by ZeroMemes** [comment]
Please provide the entirety of the crashlog.

**Comment by ZeroMemes** [comment]
I've gotten a crashlog from somebody that also had this issue, and am working to fix it now.

**Comment by ZeroMemes** [comment]
Fixed in 4.7
