### ISSUE TITLE
Alt Manager crash problem

### ISSUE THREAD

**Issue by lolw0tm8** [ImpactDevelopment/ImpactClient#1381]
**Describe the bug**
If i click "Alt(s)" button it instantly closes my game, i have to reopen it and there is no alt manager
opened.

**To Reproduce**
Click the button

**Expected behavior**
A nice list with button to MCLeaks, button adding your own cracked/premium account...

- Impact Version: 4.6
- Using Optifine? Yes, 1.12.2 HD U E2
- Using LiteLoader? No
- Operating System: Windows 10 64bit

**Comment by ZeroMemes** [comment]
Please provide a crashlog.

**Comment by lolw0tm8** [comment]
[crash-2019-07-19_09.19.42-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3409896/crash-2019-07-19_09.19.42-client.txt)

**Comment by ScanmanTM** [comment]
Shouldn't this be closed since its a forge issue and dupe of #1377
https://github.com/ImpactDevelopment/ImpactClient/wiki/Usage-FAQ

**Comment by lolw0tm8** [comment]
I really need it fixed, i am using LabyMod and Optifine with Impact which gives me alot
important features. Working Alt manager would be really awesome.

**Comment by lolw0tm8** [comment]
I wonder if i ever get a response anymore :/

**Comment by StijnSimons** [comment]
If devs are busy; wait.

**Comment by 0-x-2-2** [comment]
https://github.com/ImpactDevelopment/ImpactClient/issues/1377#issuecomment-512917667
