### ISSUE TITLE
Suggestion - Break/ Place offset

### ISSUE THREAD

**Issue by Sonicaii** [ImpactDevelopment/ImpactClient#1384]
Have an option that you can change that varies the breaking and placing offset in Baritone. For each of them, make sure that the random offset is still within the hitbox or placing radius of the target thing.

**Comment by StijnSimons** [comment]
Should be posted in [cabaletta/baritone](https://github.com/cabaletta/baritone)w

**Comment by ZeroMemes** [comment]
Indeed, migrate this issue to the proper repo.
