### ISSUE TITLE
A mod similar to rusherhack's rHackontop

### ISSUE THREAD

**Issue by ephility** [ImpactDevelopment/ImpactClient#1385]
A mod similar to rHackOnTop would be pretty cool, and if it was customizable, i'd really like that. (rHackOnTop basically adds '| rUsHeRhAcK' to the end of any chat messages you say)

**Comment by Thunder33345** [comment]
probably named "message signature" or something like that

**Comment by usereewrjrjeejr** [comment]
Cringe

**Comment by zPeanut** [comment]
i dont see why you would want this but a suggestion is a suggestion

**Comment by ZeroMemes** [comment]
I’m not going to add this.
