### ISSUE TITLE
Add a 'Save world' option

### ISSUE THREAD

**Issue by Aaron2550** [ImpactDevelopment/ImpactClient#1386]
_This may fit better into baritone, not sure_

The title says it all I guess, It just saves the Chunks into a local world so u can basically steal the world from the Server. I don't know how hard this would be but I think it would be useful to some ppl.

**Comment by Thunder33345** [comment]
liteloader world downloader?

**Comment by Aaron2550** [comment]
Yes like that. But as a part of impact.

**Comment by ZeroMemes** [comment]
With the availability of using World Downloader, a much more refined and developed mod that works fine, this will not be added to Impact.
