### ISSUE TITLE
Automine Quartz Option

### ISSUE THREAD

**Issue by Rindula** [ImpactDevelopment/ImpactClient#1389]
**Is your feature request related to a problem? Please describe.**
I have to farm Netherquartz _relatively_ long-winded

**Describe the solution you'd like**
Mining Overworld Ores and Wood is simplified in the Automine section below Bot Mode. I'm missing something for the Nether like the Netherquartz and maybe even Glowstone.

**Additional context**
I know I can do this via Chatcommands like `.b mine nether_quartz`, but it would be more handy to have this as an option in the Menu.

**Comment by usereewrjrjeejr** [comment]
🤡

**Comment by leijurv** [comment]
lol

honestly, fine. it doesn't make to have a preset for every ore but one. will add quartz i guess.

**Comment by leijurv** [comment]
Added in 4.7
