### ISSUE TITLE
autobuild / schematic

### ISSUE THREAD

**Issue by youri123456** [ImpactDevelopment/ImpactClient#1391]
hello, i really want a 1.13 autobuild/schematica.

**Comment by StijnSimons** [comment]
[cabaletta/baritone](https://github.com/cabaletta/baritone), bud

**Comment by 0-x-2-2** [comment]
This is a issue with Baritone.

**Comment by youri123456** [comment]
but can i build a building that i downloaded on internet with baritone??

**Comment by Cerbiac** [comment]
In 1.12, yes.
