### ISSUE TITLE
schematica

### ISSUE THREAD

**Issue by youri123456** [ImpactDevelopment/ImpactClient#1394]
can anyone explain me how to use the autobuild because i can do .b build (name of schematic) but what than i cant see any schematic or something are there buttons or commands for toggle rendereing or for toggle printer (how its called on schematica) please help

**Comment by zPeanut** [comment]
this is not an issue. please refer to #help on the official discord server.

**Comment by ZeroMemes** [comment]
Rather you should find answers at the baritone repository, https://github.com/cabaletta/baritone
