### ISSUE TITLE
Auto Mine: instead of choosing one ore, select which automine should mine + cooperation with Auto Food

### ISSUE THREAD

**Issue by Jan-Intelkor** [ImpactDevelopment/ImpactClient#1396]
**Is your feature request related to a problem? Please describe.**
When I want to leave auto mine to mine for a long time, I would need to switch ores it can mine.
Maybe add a option to select which ores should it mine. Also, the bot doesn't work with Auto Food. It can be done also in this way: Select primary ore and secondary. It will mine primary, like diamonds, but when it will collect enough, or will encounter that secondary ore is close, it will temporary switch to it.

**Describe the solution you'd like**
Change Auto mine menu, make it cooperate with Auto Food

**Describe alternatives you've considered**
Add option to just mine everything, expect logs.

**Additional context**
Nothing

**Comment by Aaron2550** [comment]
Maybe add a condition system like: _if 64 diamonds in inventory switch to gold_ that would be nice

**Comment by Jan-Intelkor** [comment]
> Maybe add a condition system like: _if 64 diamonds in inventory switch to gold_ that would be nice

yeah good idea

**Comment by Cerbiac** [comment]
Baritone: cabaletta/baritone

**Comment by ZeroMemes** [comment]
Auto Food works fine now on 4.7, that was an issue with impact. However, @cerbiac is correct, the mine conditioning is a baritone issue and should be opened there.
