### ISSUE TITLE
baritone build crash

### ISSUE THREAD

**Issue by youri123456** [ImpactDevelopment/ImpactClient#1397]
hello if i use #build (schematic name) with even a small schematic the game will crash. 

the crash report that i see on the mc launcher is:

The game crashed whilst keypressed event handler
Error: java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo

the crash report i see when opening that file is: 
 ---- Minecraft Crash Report ----
// I feel sad now :(

Time: 20-7-19 13:52
Description: keyPressed event handler

java.lang.UnsupportedOperationException: 1.13 be like: numeric IDs btfo
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$3452/1800766250.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zeg000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at net.optifine.gui.GuiChatOF.e(GuiChatOF.java:41)
	at cjg.keyPressed(SourceFile:131)
	at cfq.lambda$onKeyEvent$4(KeyboardListener.java:378)
	at cfq$$Lambda$3450/2134400190.run(Unknown Source)
	at ckd.a(SourceFile:430)
	at cfq.a(KeyboardListener.java:368)
	at cfq$$Lambda$842/169505492.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at cgd.a(MainWindow.java:458)
	at cft.c(SourceFile:875)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baritone.dx.<init>(Unknown Source)
	at baritone.bs.build(Unknown Source)
	at baritone.api.process.IBuilderProcess.build(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.runCommand(Unknown Source)
	at baritone.api.utils.ExampleBaritoneControl.onSendChatMessage(Unknown Source)
	at baritone.x.a(Unknown Source)
	at baritone.x$$Lambda$3452/1800766250.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at baritone.x.onSendChatMessage(Unknown Source)
	at ctj.handler$sendChatMessage$zeg000(SourceFile)
	at ctj.f(SourceFile)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at net.optifine.gui.GuiChatOF.e(GuiChatOF.java:41)
	at cjg.keyPressed(SourceFile:131)
	at cfq.lambda$onKeyEvent$4(KeyboardListener.java:378)
	at cfq$$Lambda$3450/2134400190.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.optifine.gui.GuiChatOF
Stacktrace:
	at ckd.a(SourceFile:430)
	at cfq.a(KeyboardListener.java:368)
	at cfq$$Lambda$842/169505492.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['youribro2003'/184, l='MpServer', x=-64.23, y=97.11, z=188.78]]
	Chunk stats: MultiplayerChunkCache: 685, 685
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-16,65,-32), Chunk: (at 0,4,0 in -1,-2; contains blocks -16,0,-32 to -1,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 18990 game time, 18990 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 94 total; [aka['Pig'/256, l='MpServer', x=-2.49, y=64.00, z=237.22], aka['Pig'/257, l='MpServer', x=-1.34, y=63.00, z=241.42], aka['Pig'/258, l='MpServer', x=5.35, y=63.00, z=234.75], aka['Pig'/259, l='MpServer', x=-1.15, y=63.00, z=242.69], anq['Spider'/260, l='MpServer', x=-3.50, y=64.00, z=244.50], amt['Creeper'/261, l='MpServer', x=0.50, y=17.00, z=187.50], ajl['Bat'/262, l='MpServer', x=15.43, y=17.46, z=187.72], amt['Creeper'/263, l='MpServer', x=0.42, y=46.00, z=181.30], amt['Creeper'/264, l='MpServer', x=0.50, y=46.00, z=185.50], aka['Pig'/265, l='MpServer', x=12.28, y=69.00, z=183.70], aka['Pig'/266, l='MpServer', x=9.72, y=67.00, z=191.49], amt['Creeper'/267, l='MpServer', x=3.50, y=18.00, z=197.50], ajr['Chicken'/268, l='MpServer', x=7.50, y=70.00, z=221.45], ajr['Chicken'/269, l='MpServer', x=12.79, y=66.00, z=222.50], ajs['Cod'/17, l='MpServer', x=-137.94, y=62.17, z=116.05], anw['Zombie'/27, l='MpServer', x=-102.50, y=68.00, z=110.50], anq['Spider'/28, l='MpServer', x=-107.30, y=73.00, z=122.00], amt['Creeper'/32, l='MpServer', x=-87.50, y=65.00, z=121.50], anw['Zombie'/33, l='MpServer', x=-83.23, y=71.00, z=164.50], akf['Sheep'/34, l='MpServer', x=-92.26, y=80.00, z=168.45], ctj['youribro2003'/184, l='MpServer', x=-64.23, y=97.11, z=188.78], anw['Zombie'/45, l='MpServer', x=-74.50, y=64.00, z=144.50], anq['Spider'/47, l='MpServer', x=-57.50, y=47.00, z=122.50], anw['Zombie'/48, l='MpServer', x=-52.50, y=15.00, z=146.50], amm['Birch Sapling'/49, l='MpServer', x=-51.76, y=71.00, z=156.83], amt['Creeper'/51, l='MpServer', x=-53.48, y=67.00, z=148.39], ann['Skeleton'/53, l='MpServer', x=-38.50, y=53.00, z=122.50], ann['Skeleton'/54, l='MpServer', x=-37.51, y=53.00, z=124.66], amt['Creeper'/55, l='MpServer', x=-46.57, y=48.00, z=127.23], ann['Skeleton'/56, l='MpServer', x=-35.78, y=49.00, z=148.50], anw['Zombie'/185, l='MpServer', x=-73.97, y=61.00, z=178.30], ann['Skeleton'/57, l='MpServer', x=-41.50, y=50.00, z=154.28], anw['Zombie'/186, l='MpServer', x=-69.95, y=61.00, z=175.96], amt['Creeper'/58, l='MpServer', x=-37.21, y=49.00, z=149.50], amt['Creeper'/187, l='MpServer', x=-69.25, y=61.00, z=175.30], amm['Birch Sapling'/59, l='MpServer', x=-37.19, y=73.00, z=161.51], amm['Birch Sapling'/60, l='MpServer', x=-34.77, y=74.00, z=173.66], amw['Enderman'/195, l='MpServer', x=-137.50, y=66.00, z=232.50], ajt['Cow'/196, l='MpServer', x=-114.57, y=83.00, z=180.51], ajt['Cow'/197, l='MpServer', x=-116.00, y=82.00, z=182.00], ajt['Cow'/198, l='MpServer', x=-120.48, y=81.00, z=189.18], anw['Zombie'/199, l='MpServer', x=-116.22, y=64.00, z=245.46], ajt['Cow'/200, l='MpServer', x=-112.50, y=83.00, z=171.84], anw['Zombie'/201, l='MpServer', x=-104.50, y=72.00, z=207.50], ajl['Bat'/202, l='MpServer', x=-92.12, y=21.98, z=251.51], ajl['Bat'/75, l='MpServer', x=-30.53, y=50.10, z=156.25], aka['Pig'/205, l='MpServer', x=-90.26, y=76.00, z=188.48], amt['Creeper'/206, l='MpServer', x=-84.50, y=68.00, z=213.50], ann['Skeleton'/462, l='MpServer', x=-116.50, y=80.00, z=191.50], amt['Creeper'/207, l='MpServer', x=-88.47, y=70.00, z=209.77], amt['Creeper'/208, l='MpServer', x=-89.58, y=70.00, z=210.84], ann['Skeleton'/209, l='MpServer', x=-89.50, y=67.00, z=228.50], ajl['Bat'/81, l='MpServer', x=-4.40, y=66.85, z=124.39], anw['Zombie'/210, l='MpServer', x=-80.50, y=15.00, z=251.50], anw['Zombie'/82, l='MpServer', x=-1.50, y=64.00, z=139.50], ajl['Bat'/211, l='MpServer', x=-86.69, y=21.48, z=245.57], anw['Zombie'/83, l='MpServer', x=-3.50, y=64.00, z=131.50], ajl['Bat'/212, l='MpServer', x=-79.53, y=21.98, z=242.49], amm['Birch Sapling'/84, l='MpServer', x=-14.05, y=65.00, z=152.40], ann['Skeleton'/469, l='MpServer', x=14.50, y=69.00, z=192.50], anw['Zombie'/470, l='MpServer', x=-49.50, y=19.00, z=252.50], ann['Skeleton'/215, l='MpServer', x=-64.46, y=69.00, z=196.85], amt['Creeper'/216, l='MpServer', x=-74.58, y=65.00, z=211.81], anw['Zombie'/472, l='MpServer', x=-49.50, y=19.00, z=253.50], amt['Creeper'/217, l='MpServer', x=-76.01, y=65.00, z=212.64], ajl['Bat'/218, l='MpServer', x=-64.64, y=25.10, z=238.64], anw['Zombie'/475, l='MpServer', x=4.50, y=63.00, z=236.50], amt['Creeper'/221, l='MpServer', x=-56.50, y=60.00, z=203.22], amt['Creeper'/93, l='MpServer', x=4.50, y=64.00, z=110.50], ann['Skeleton'/222, l='MpServer', x=-60.27, y=59.00, z=196.43], amt['Creeper'/94, l='MpServer', x=6.50, y=64.00, z=110.50], amt['Creeper'/223, l='MpServer', x=-58.69, y=67.00, z=203.90], ake['Salmon'/95, l='MpServer', x=14.52, y=62.69, z=120.76], ajl['Bat'/224, l='MpServer', x=-61.51, y=30.10, z=253.79], ake['Salmon'/96, l='MpServer', x=14.36, y=60.48, z=119.75], ajl['Bat'/225, l='MpServer', x=-54.25, y=23.00, z=255.48], ajl['Bat'/97, l='MpServer', x=-3.53, y=15.17, z=166.41], ann['Skeleton'/98, l='MpServer', x=2.50, y=76.00, z=160.50], aka['Pig'/231, l='MpServer', x=-35.29, y=76.00, z=203.55], aka['Pig'/232, l='MpServer', x=-33.69, y=75.00, z=202.10], anw['Zombie'/233, l='MpServer', x=-39.46, y=36.00, z=221.28], anw['Zombie'/234, l='MpServer', x=-34.37, y=37.00, z=220.70], ajl['Bat'/235, l='MpServer', x=-47.56, y=27.12, z=267.35], anw['Zombie'/244, l='MpServer', x=-21.50, y=15.00, z=179.50], ajl['Bat'/246, l='MpServer', x=-16.19, y=15.68, z=184.15], ajl['Bat'/247, l='MpServer', x=-9.10, y=20.10, z=190.06], ajl['Bat'/248, l='MpServer', x=-1.92, y=14.05, z=174.72], amt['Creeper'/249, l='MpServer', x=2.53, y=44.00, z=176.77], aka['Pig'/250, l='MpServer', x=-6.53, y=67.00, z=181.76], aka['Pig'/251, l='MpServer', x=1.49, y=68.00, z=200.22], amt['Creeper'/252, l='MpServer', x=-10.50, y=16.00, z=198.50], ajl['Bat'/253, l='MpServer', x=-7.32, y=18.99, z=186.36], anw['Zombie'/254, l='MpServer', x=-5.50, y=72.00, z=219.50], anq['Spider'/255, l='MpServer', x=-7.50, y=72.00, z=223.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at crg.a(WorldClient.java:576)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 827585840 bytes (789 MB) / 1644167168 bytes (1568 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6-OptiFine_HD_U_E7
	LWJGL: 3.1.6 build 14
	OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 21.20.16.4821, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/planetcraft
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz

**Comment by StijnSimons** [comment]
If you would've done like the slightest bit of research in [cabaletta/baritone](https://github.com/cabaletta/baritone) you woul've seen that IT. DOESNT. WORK. FOR. 1.13.

**Comment by youri123456** [comment]
wil it work for versions higher than 1.13?

**Comment by StijnSimons** [comment]
No, unless they change how schematic files are made. They currently still use numeric ID's which got removed in 1.13 and above.

**Comment by youri123456** [comment]
so if i search a schematic file 1.13+ on internet i will find one without numeric id's and that will work?

**Comment by StijnSimons** [comment]
> so if i search a schematic file 1.13+ on internet i will find one without numeric id's and that will work?

No cause they are use numeric ids.

**Comment by youri123456** [comment]
is it hard to make one for 1.13.2 and if it isnt, how?

**Comment by StijnSimons** [comment]
> is it hard to make one for 1.13.2 and if it isnt, how?

Mate, the norm of schematics are to use numeric id's. __You can't make one currently using full name id's.__ Either cabaletta will make their own schematic format or will wait until they've changed the norm.

**Comment by youri123456** [comment]
okay thx

**Comment by ZeroMemes** [comment]
1) this is a baritone exclusive issue, it belongs on the cabaletta/baritone repository

2) 1.13.2 Baritone doesn’t support schematics because of the removal of numeric ids at the moment.
