### ISSUE TITLE
Schematica support

### ISSUE THREAD

**Issue by WobblierDog15** [ImpactDevelopment/ImpactClient#1403]
Before you close this thread yeah I know you can already use baritone `.build` but it's very time consuming compared to schematica where "print" actually builds a lot faster then `.build`. Schematica also shows you how much material the build uses. I already have Schematica but it would be much easier to have Impact and Schematica together instead of having to swap between them and not being able to use both.

**Comment by 0-x-2-2** [comment]
You are able to use Impact with Forge but any issues you have will not be fixed.

**Comment by WobblierDog15** [comment]
What do you mean? It’s not an issue it’s a suggestion. Also why would not of my issues be fixed

**Comment by ZeroMemes** [comment]
We usually will not fix issues that only occur on forge due to the vast amount of potential issues that can occur.

As far as schematica goes, we’re never going to ship it with Impact, just use impact with forge.

**Comment by WobblierDog15** [comment]
Understood
