### ISSUE TITLE
[QUESTION] How does impact's Boost speed mode work? 

### ISSUE THREAD

**Issue by mrphax0r** [ImpactDevelopment/ImpactClient#1407]
Does it work similar to:
```
public void onEnable() {
	  mc.timer.timerSpeed = 2.0F;
}
public void onUpdate() {
if (mc.player.onGround() && !mc.timer.timerSpeed == 1.0F()){
  mc.timer.timerSpeed -= 0.05F;
  }
}
if (mc.timer.timerSpeed == 1.0F;) {
  mc.timer.timerSpeed = 2.0F
}
```
Or am i completely wrong? Please explain.

**Comment by StijnSimons** [comment]
Do i smell..... a skid?

**Comment by ZeroMemes** [comment]
Top secret information

**Comment by mrphax0r** [comment]
@ZeroMemes okay, two last questions:
Does the speed alter during speeding and does it involve anything else than altering speed/timer?

**Comment by mrphax0r** [comment]
@StijnSimons Yes you do sir, i just wanted to know how it works to maybe get it to bypass better on 6b6t.

**Comment by StijnSimons** [comment]
Yhyh

**Comment by mrphax0r** [comment]
@StijnSimons

**Comment by StijnSimons** [comment]
@mrphax0r
