### ISSUE TITLE
Entity Jesus

### ISSUE THREAD

**Issue by SilentDrag** [ImpactDevelopment/ImpactClient#141]
Could you guys make a Jesus for the horse

**Comment by kekkekek** [comment]
This is in xdolf and future as well this would be very useful as it works on 2b2t and pretty much any anarchy server

**Comment by SilentDrag** [comment]
Only reason why I suggested it is because it would be vary useful

**Comment by LeafHacker** [comment]
The version in xdolf is a small patch on @w-o-a-h's jesus

**Comment by w-o-a-h** [comment]
aka futures jesus AAAAAAAAAAAAAAAAAAAAAAAA

**Comment by SilentDrag** [comment]
We need it

**Comment by Slimerblue22** [comment]
I think it works if you walk on the water then get on the horse. It worked in 3.0 anyways, haven't tested it on 4.0
