### ISSUE TITLE
FastBreak, FastPlace, Bridge

### ISSUE THREAD

**Issue by lolw0tm8** [ImpactDevelopment/ImpactClient#1416]
**Is your feature request related to a problem? Please describe.**
Block breaking is slow
Placing blocks is slow
Making bridges is hard

**Describe the solution you'd like**
FastBreak - _Break blocks faster_
FastPlace - _Place blocks faster_
Bridge - _If you move with blocks in hand it will place them below you, makes bridge_

**Describe alternatives you've considered**
*

**Additional context**
*

**Comment by mrphax0r** [comment]
@lolw0tm8 There is a scaffold you blind person

**Comment by lolw0tm8** [comment]
Ok
what about the FastBreak and FastPlace

**Comment by Thunder33345** [comment]
fast interact

**Comment by lolw0tm8** [comment]
Ok thanks
