### ISSUE TITLE
Show a tutorial toast notification about ClickGUI

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#142]
On a user's first time using impact, show a toast tutorial prompting them to press ClickGUI's keybind.

We could use the config file to track if the toast has been completed before, by setting a `tutorialStage` value in the user config.

I'm thinking a stage int instead of a completed boolean in case we want to add extra stages later.

It is probably not necessary to make use of the actual advancements system for this, since we can track the keybind and config file ourselves.

**Comment by zPeanut** [comment]
toast??????????????????????????

**Comment by LeafHacker** [comment]
@zPeanut https://t.co/2CU6XOUAP6?amp=1

**Comment by LeafHacker** [comment]
Added in 4.1

![tutorial](https://media.discordapp.net/attachments/208753003996512258/351053900578553857/Screenshot_from_2017-08-26_18-22-33.png)
