### ISSUE TITLE
auto mmine broke

### ISSUE THREAD

**Issue by tyrion05** [ImpactDevelopment/ImpactClient#1420]
the autominer is avoiding all diamonds near me, and yes I have it on diamonds

i dont know what happened

![image](https://user-images.githubusercontent.com/53230637/61729072-54d5af80-ad2b-11e9-9479-95f3f23352d1.png)

 

 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System:

**Comment by usereewrjrjeejr** [comment]
https://github.com/cabaletta/baritone post the issue here
