### ISSUE TITLE
[4.7 Beta]Cobblestone and Netherrack Stuck in Hotbar

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactClient#1421]
**Describe the bug**
When cobble or netherrack is in your hotbar, you cannot put it in your inventory (it just reappears back in original spot).

**To Reproduce**
1. Get cobble or netherrack in hotbar.
2. Try to put in inventory

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.7.0-20190721-nightly for 1,12.2 (also affects 1.13.2)
- Using Optifine?  no
- Using LiteLoader?  no
- Enabled mods: Middle click friends, Anti Sound Lag, No Fall, Velocity, Weather, Trajectories, Auto Totem, Anti Overlay, Log Position, Anti Hazard,  Camera Clip, Anti Vanish,  Animations, Inventory, Nametags, Anti Blind,  Auto Eat, Respawn, Tracers, ESP, No Push,  No Slow, Portals, Riding, Light.
- Operating System:  Windows 10 64bit

</details>
https://streamable.com/tq38e

**Comment by leijurv** [comment]
`.b allowInventory`
