### ISSUE TITLE
Baritone

### ISSUE THREAD

**Issue by Dreamotaye** [ImpactDevelopment/ImpactClient#1426]
Is their a way to get baritone to work on minecraft realms or is this impossible?

**Comment by zPeanut** [comment]
yes this is possible on realms. please refer to #help on the discord next time you have a question about impact. thanks!

**Comment by Dreamotaye** [comment]
this wasnt about impact it was about baritone and i asked yesterday in help and i was told it doesnt work and i even installed it and tried so ya.

**Comment by zPeanut** [comment]
you can ask about baritone help on discord too. alternatively you can go to the baritone github to submit issues there. sorry if ive been wrong about this. last time i checked impact worked on realms. maybe its changed im not sure.

baritone github: https://github.com/cabaletta/baritone/issues

**Comment by Dreamotaye** [comment]
okay thank you.
