### ISSUE TITLE
Avoidance doesnt appear to be working 1.14.4

### ISSUE THREAD

**Issue by realflow100** [ImpactDevelopment/ImpactClient#1427]
Avoidance doesnt seem to work. walks right into creepers killing me. tried changing the settings from default but no difference. happens when automining

**To Reproduce**
1. enable avoidance
2. it doesnt seem to work.

**Expected behavior**
Avoidance should path me away from hostile mobs any chance it gets.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: none.
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: just baritone 1.14.4
- Operating System: windows 7 pro 64-bit
- Minecraft version: 1.14.4

</details>

**Comment by zPeanut** [comment]
closed on users demand.
