### ISSUE TITLE
Add an autocrafter 

### ISSUE THREAD

**Issue by acesblue** [ImpactDevelopment/ImpactClient#1428]
I am trying to automate the entire process of producing iron/gold blocks.

While looking at a workbench/crafting table be able to run a command "#craft gold_block number" it checks your inventory if you have enough then crafts how many you requested.

While workbench is in hotbar/items in hotbar, but in inventory would be much appreciated 

That's all

**Comment by ZeroMemes** [comment]
Sounds like a good addition to baritone, and given your usage of the "#" prefix in your example I'm going to make the assumption that's the intent. Please move the issue [here](https://github.com/cabaletta/baritone).

**Comment by acesblue** [comment]
already moved

**Comment by DARKESTSOULER** [comment]
That would be nice
