### ISSUE TITLE
MineStrike Bug

### ISSUE THREAD

**Issue by scorixear** [ImpactDevelopment/ImpactClient#143]
Hi,
I want to report a bug with the mod MineStrike.
At some point, Minestrike does not select some players  (no red/blue cubes arround them, no shooting at them) and they don't get reselected when I reactivate it couple of times.
I am playing MineStrike on mineplex of course

**Comment by daggerdig** [comment]
Yeah I have had this issue as well and i have a fix for it. All you have to do is have it on before the other team renders into view. However this fix is impractical.

**Comment by scorixear** [comment]
Well, the bug also occurs with my team. And that is not fixable from my site ;)

**Comment by LeafHacker** [comment]
Bugs aren't about providing user support anyway, so even if the user finds
a workaround the issue stays open until it is fixed or we decide we can't
fix it.

**Comment by ZeroMemes** [comment]
Fixed in 4.1
