### ISSUE TITLE
Auto-place water on lava when Baritone is mining Obsidian

### ISSUE THREAD

**Issue by zSnowyV** [ImpactDevelopment/ImpactClient#1437]
Well, if someone does .b mine Obsidian and Baritone finds lava, it'll place water above lava and make obsidian, that would be a nice thing to have on baritone since it is not that easy to find natural obsidian.

**Comment by ZeroMemes** [comment]
Issues relating to Baritone and Baritone alone belong [here](https://github.com/cabaletta/baritone).
