### ISSUE TITLE
Pepsi edition

### ISSUE THREAD

**Issue by digmorepaka** [ImpactDevelopment/ImpactClient#144]
It should make pepsi edition users nametag blue white red on all editions.

**Comment by LeafHacker** [comment]
Added to 4.1

![image](https://user-images.githubusercontent.com/23565638/29633429-28cd26c0-883e-11e7-969f-8e36ad29f1ff.png)

**Comment by LeafHacker** [comment]
Alternative possibility 1
![image](https://user-images.githubusercontent.com/23565638/29633747-2f79fff6-883f-11e7-99c7-5fd3effa19e5.png)

Alternative possibility 2
![image](https://user-images.githubusercontent.com/23565638/29633792-5e5fa32a-883f-11e7-8516-5cff27f71778.png)

**Comment by LeafHacker** [comment]
Going with Alternative 2.
