### ISSUE TITLE
NCP Flight acts like Freecam

### ISSUE THREAD

**Issue by lolw0tm8** [ImpactDevelopment/ImpactClient#1441]
**Describe the bug**
NCP Mode for Flight acts like freecam, that means you don't really fly and if you disable it it returns you to your previous position + players see you standing still

**To Reproduce**
1. Turn on Flight
2. Enable NCP mode

**Expected behavior**
Flight mode just like others (working fly) but bypassing NCP kicking/glitching

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.7.2 for 1.12.2 Vanilla
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Flight, NoFall, Jesus, AutoCheat, AntiVanish, Animations
- Operating System: Windows 10 64bit

</details>

**Additional context**
Question:
Is it meant to be Freecam 2.0, is it bug or just another glitch made by Optifine or another enabled mod?

**Comment by leijurv** [comment]
It either works or it doesn't, I believe.

**Comment by 0-x-2-2** [comment]
It only works on 1.9+ servers.

**Comment by lolw0tm8** [comment]
what do you mean? 1.12.2 = 1.9+
the base server version is 1.9+
