### ISSUE TITLE
Infinite Reach/TP Reach/TPAura

### ISSUE THREAD

**Issue by Optimalgitit** [ImpactDevelopment/ImpactClient#1447]
Basically, a **Teleportation Based reach** would be awesome and very useful. Make a **module** for it which will allow you to customize the **steps, delay and maximum distance** and maybe others. Also, make it a **kill aura option** but have it **use the settings set inside of the standalone module.**

**Comment by Thunder33345** [comment]
what IS tp aura? and how would that work

**Comment by Optimalgitit** [comment]
Put simply, teleport to the player, hit them, and teleport back to your original location - all in one tick. Instant teleport though wouldn't be very efficient so instead, using steps (teleporting [step number step] forward each time) would work better. Delay would be how much delay would be between each step in ms. And maximum distance would be the maximum distance the player can be that you can hit them (this option can be set to infinite).

**Comment by Optimalgitit** [comment]
Shoot i accidentally closed it

**Comment by EPICSAURUSS** [comment]
that's what I want

**Comment by StijnSimons** [comment]
#1456

**Comment by Optimalgitit** [comment]
I'm also describing what options i want and that post is about TP-aura, my post is about both a seperate reach desinged for it, the options i want, etc.
