### ISSUE TITLE
Add Tp-Aura

### ISSUE THREAD

**Issue by EPICSAURUSS** [ImpactDevelopment/ImpactClient#1456]
I want there to be Tp-Aura mod so that I can pvp with ease. Tp-Aura is an aura that has the person using it teleport in random directions at a player and hit them.

Here is what I mean https://youtu.be/9q9S8axp4VI?t=47

**Comment by StijnSimons** [comment]
My man thats from 2016. Its been patched on almost EVERY server.

**Comment by 0-x-2-2** [comment]
You can only move 10 blocks in a server tick on 1.9+ this is no longer possible.

**Comment by EPICSAURUSS** [comment]
> My man thats from 2016. Its been patched on almost EVERY server.

my dude... WURST OF ALL CLIENTS is able to do it, its one of the only that work these day what you talkin about xd

**Comment by StijnSimons** [comment]
On a server without an anticheat...

**Comment by EPICSAURUSS** [comment]
> On a server without an anticheat...

It works on a few servers with anticheat, it just cant be a strong one
Also, there are features that only work without anticheat but are still in the client
- Flight
- ClickTP
- Speed
- Jesus
- NoFall

**Comment by StijnSimons** [comment]
Not a single doubt in my mind makes me think this will work.

```java
	// teleport
		mc.thePlayer.setPosition(entity.posX + random.nextInt(3) * 2 - 2,
			entity.posY, entity.posZ + random.nextInt(3) * 2 - 2);
```
on a server with anti-cheat

**Comment by 0-x-2-2** [comment]
> Not a single doubt in my mind makes me think this will work on a server with an anticheat.
> 
> ```java
> 	// teleport
> 		mc.thePlayer.setPosition(entity.posX + random.nextInt(3) * 2 - 2,
> 			entity.posY, entity.posZ + random.nextInt(3) * 2 - 2);
> ```

This won't even work on vanilla servers if the player is > 10 blocks away.
