### ISSUE TITLE
Auto-Respawn doesn't work (EntityDeathEvent not triggered)

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#147]
When I have auto-respawn active and I die, it doesn't respawn me..
The screen "You died!" remains.

**Comment by LeafHacker** [comment]
Looks like this is caused by `EntityDeathEvent` not being fired on death. Needs some further investigation for now, we'll try and get this fixed in time for 4.1 today.

**Comment by LeafHacker** [comment]
Fixed in 4.1.

This was caused by ImpactDevelopment/ClientAPI/issues/25. For now we work around the issue by listening to `TickEvent` instead and checking if the player is dead every tick.
