### ISSUE TITLE
Please add a brief but descriptive title

### ISSUE THREAD

**Issue by Jakaboii** [ImpactDevelopment/ImpactClient#1473]
**Describe the bug**
Download link doesn't work with Norton Security

**To Reproduce**
1. Go to: https://impactdevelopment.github.io
2. Click on: Download (on the navbar)
3. Click on: Impact Installer for Windows
4. See error: 
![Click for image.](https://user-images.githubusercontent.com/50416254/62011919-02efb800-b177-11e9-9806-195c0e75209e.png)

**Expected behavior**
I expected it to download the file.

- Impact Version: I want 1.12.2
- Using Optifine? yes
- Using LiteLoader?I don't know
- Enabled mods: None
- Operating System: Windows 10 64bit

**Additional context**
When I tried to install it from mc-hacks I got a txt file saying that mc-hacks is outdated and sucks, so that didn't help me.

**Comment by leijurv** [comment]
This is norton sucking not us sucking lol.

https://impactdevelopment.github.io/?brady-money-grubbing-completed=true
