### ISSUE TITLE
Baritone mining obsidian but buggy

### ISSUE THREAD

**Issue by TheCompieter** [ImpactDevelopment/ImpactClient#1484]
When i try too mine obsidian with .b mine obsidian it sometime works and it mostly just dont work
what i will get when there's water it completely freaks out and stops mining also it sometimes doesn't detect the obsidian and even more stuff like that.

**Comment by WaffleTraits** [comment]
This is the wrong issue, please take this to the Baritone repository.

**Comment by TheCompieter** [comment]
ok ty
