### ISSUE TITLE
Chat Mute/Lock

### ISSUE THREAD

**Issue by ButterCreep** [ImpactDevelopment/ImpactClient#1487]
My cousins parents are worried about him getting on a server because they are afraid of what might be said in chat and that he could be a target. I was wondering if it would be possible to add a chat mute feature into impact so the chat would be fully hidden. I also think it would be useful to add an option to lock certain or all features using a password so the chat mute cant just be undone. (This is my first suggestion and i hope its actually useful)

**Comment by leijurv** [comment]
set chat scale to 0 this is a vanilla feature lol

**Comment by ZeroMemes** [comment]
You can also set the chat display setting from “All” to “Hidden” I believe
