### ISSUE TITLE
Module: Schematica Printer Bypass

### ISSUE THREAD

**Issue by Orange65** [ImpactDevelopment/ImpactClient#1489]
**Is your feature request related to a problem? Please describe.**
Whenever using schematica's printer on servers it doesn't work as the blocks placed get removed or turn into ghost blocks. It only works when I am facing in the correct direction. 

**Describe the solution you'd like**
I would like a module called something like "printer bypass". This would allow printer to work on servers, with the correct settings (such as a higher placement delay). I think the correct way to do this is make the player to rotate towards the correct direction of the block that is about to be placed. So for example, the player would rotate (server side) to face exactly where the next block will be placed.

**Describe alternatives you've considered**
Trying to predict and face where the block will be placed. Sort of works

**Additional context**
N/A

**Comment by 0-x-2-2** [comment]
Use the Baritone build feature.
