### ISSUE TITLE
Crystal Aura and AutoCrystal as different modules

### ISSUE THREAD

**Issue by DanCuber** [ImpactDevelopment/ImpactClient#1494]
Rn autocrystal is just a sub-module of crystal aura, making it kind of annoying to have to open the gui each time you want to toggle placement. 

A solution would be having them as different modules, or even better have the ability to add keybinds to toggle/cycle through module sub-modules/settings i.e. have a keybind that toggles baritone settings.

(Ik its more of a quality of life improvement but it would make changing settings on the go much easier)

**Comment by leijurv** [comment]
Not going to do this, you can use macros to toggle suboptions
