### ISSUE TITLE
Impact 1.13.2 with forge ?

### ISSUE THREAD

**Issue by Aixtaz** [ImpactDevelopment/ImpactClient#1499]
**Describe the bug**
I can't install Impact 1.13.2 with forge ...

**To Reproduce**
Just download 1.13 and forge 1.13 and try to install Impact 1.13 with forge.
The installer doesn't show the "1.13.2" version ...

**Expected behavior**
How can I install it ?

**Screenshots**
https://prnt.sc/oo7ad2

**Additional context**
I don't know why it doesn't work.
I works for 1.12.2 version but not 1.13.2 ...

**Comment by usereewrjrjeejr** [comment]
FORGE BAD!

**Comment by WaffleTraits** [comment]
Impact for Minecraft 1.13.2 is not available for   Minecraft forge. Only the 1.12.2 version of Impact has compatibly with forge. You can install it via the launcher.
