### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Flick3r** [ImpactDevelopment/ImpactClient#15]
The client has been crashing on launch, with it loading the Mojang screen for 3 or 4 seconds, then crashing and giving one of these two messages;

Completely ignored arguments: [--nativeLauncherVersion, 1206]
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
16:40:56.301 [Thread-5] ERROR Âµ?Â¢ç?’ê…¨Â¢ê…€â‚¬ê…¦Ã¦ê…€é?³Æ’Å’Å Ã¸ÂµÂ¢ç’„â‚¬ê…¦Å Ã¦Â¢Ã¦ê…€ê…¨Å ÂºÂ£Âºê…€æ?’ÂªÂ£ê…¨Â£Â¥ê…«ê…¨æ?’Â¥é?³Â£ç?’Å é?³ê…¡Ã¸Âµê…€èš‡ê„°ê…€?ê„°Â¢ç’„ê…€Â£ - Error in class 'LibraryLWJGLOpenAL'
16:40:56.302 [Thread-5] ERROR Âµ?Â¢ç?’ê…¨Â¢ê…€â‚¬ê…¦Ã¦ê…€é?³Æ’Å’Å Ã¸ÂµÂ¢ç’„â‚¬ê…¦Å Ã¦Â¢Ã¦ê…€ê…¨Å ÂºÂ£Âºê…€æ?’ÂªÂ£ê…¨Â£Â¥ê…«ê…¨æ?’Â¥é?³Â£ç?’Å é?³ê…¡Ã¸Âµê…€èš‡ê„°ê…€?ê„°Â¢ç’„ê…€Â£ - Unable to initialize OpenAL.  Probable cause: OpenAL not supported.

or

Completely ignored arguments: [--nativeLauncherVersion, 1206]

I've tried doing a hard reinstall of Minecraft and this issue still continued. I can show you my .minecraft folder, or send any information you need, I just want to get this working :)
edit: I've been told to delete the shaders folder, then try it and that still hasn't worked.
also: there is no impact folder in the .minecraft directory

**Comment by ZeroMemes** [comment]
This issue is caused by the latest Nvidia driver, you need to go into your GeForce Experience application and uninstall the 3D Vision feature
