### ISSUE TITLE
Armour HUD

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#150]
Probably the oldest suggestion around!

Future:
![image](https://user-images.githubusercontent.com/23565638/29644890-dda2e106-8871-11e7-83f1-630016e471e1.png)

[BetterPVP](https://www.planetminecraft.com/mod/1710forge-better-pvp-fair-play-mod-v117---minimap-gui-keybinds/) Mod:
![image](https://user-images.githubusercontent.com/23565638/29644925-1343a048-8872-11e7-9243-f1f9fe7ec5a7.png)

**Comment by ZeroMemes** [comment]
Added in 4.2
