### ISSUE TITLE
let us be able to translate the client to other language by ourselves

### ISSUE THREAD

**Issue by lupohan44** [ImpactDevelopment/ImpactClient#1504]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
let us be able to translate the client to other language by ourselves.Like server plugins,it always has a language file,so we can translate it to other language by ourselves.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mrphax0r** [comment]
As suggested my me

**Comment by StijnSimons** [comment]
Duplicate of #508
