### ISSUE TITLE
Make a link with auto tools and auto mine 

### ISSUE THREAD

**Issue by DarkLine70** [ImpactDevelopment/ImpactClient#1506]
I'm french excuse my english 
I don't know how really explain but i will say an exemple :
You mine with auto mine and auto tools, you search diamond, so you mine stone, dirt etc
but you keep the same tool to mine stone and diamond, so i think there is a possibility to mine with a pickaxe effiency and/or solidity to mine stone and with auto tools take an other pickaxe with effiency and/or solidity AND fortune or silk touch to mine diamond or other ore

**Comment by 0-x-2-2** [comment]
Use the baritone setting `allowInventory`. You can enable it by doing `#allowInventory` in chat.
