### ISSUE TITLE
Choose your block with auto mine

### ISSUE THREAD

**Issue by DarkLine70** [ImpactDevelopment/ImpactClient#1507]
When i want mine logs, i can't choise between oak, birch or other wood, so i think there is a possibility to choise the item we want mine with the id and not the name

**Comment by realflow100** [comment]
Try #mine oak_log or #mine spruce_log2 or spruce_log
depending on minecraft version it will be  spruce_log or spruce_log2
try that when mining it might need to be log or log2 depending on minecraft version and what logs you want to mine

**Comment by 0-x-2-2** [comment]
#mine oak_log spruce_log

🤔
