### ISSUE TITLE
Elytra plus doesnt vvork for me

### ISSUE THREAD

**Issue by VVaveFlakz** [ImpactDevelopment/ImpactClient#1509]
so like vvhen i use elytra plus on oldfag.org, it doesnt vvork and like i thought it vvas just disabled but i asked my friend and they said that it vvorks for them on the client vvvve , so like is there a vvay to fix it? Also i tried elytra plus on a single player vvorld and it vvorks but it doesnt vvork on the server

**Comment by StijnSimons** [comment]
w

**Comment by StijnSimons** [comment]
This is not a bug, there is stuff like anti-cheats.
