### ISSUE TITLE
Impact 4.7 1.12.2 bug

### ISSUE THREAD

**Issue by DaGameGamer** [ImpactDevelopment/ImpactClient#1510]
When I join a server with impact 4.7 in 1.12.2 and try to move, I keep getting teleported to the spot I spawned and I also can't break anything or place blocks or move my rotation but when I log on to the same server on vanilla i can move

also here's a video
[video.zip](https://github.com/ImpactDevelopment/ImpactClient/files/3479841/video.zip)

**Comment by DanCuber** [comment]
Disable "portals"

**Comment by FrenchyFryy404** [comment]
I can't join servers or worlds at all it just keeps the logging in message on the screen
