### ISSUE TITLE
Impact latest version,1.12.2 crashing on the second try

### ISSUE THREAD

**Issue by noobsplicer** [ImpactDevelopment/ImpactClient#1517]
ok so when i first installed impact, it worked normally, but when i logged off and logged back on it crashed. it seems that its a problem with the texture. i tried replacing the texture, deleting the files and reinstalling, but it didn't work. i dont have optifine installed. my launcher log is long so ill just attach the file

**To Reproduce**
idk it only seems to happen to me

**Expected behavior**
i expected it to work

 

- Impact Version: 4.7.2, 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: none because I can't open it
- Operating System: Windows 10 64bit
[launcher_log.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3488712/launcher_log.txt)

**Additional context**
it works the same with optifine

[crash-2019-08-10_23.14.38-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3489262/crash-2019-08-10_23.14.38-client.txt)

**Comment by EmeraldSnorlax** [comment]
> tried replacing the logo

or whatever file `2378311fabbccae299383fa84b1c8126b4c497ce` points to ^^

**Comment by RelievedStudios** [comment]
have you deleted and reinstalled the instance?

**Comment by noobsplicer** [comment]
i deleted and reinstalled all the files, and minecraft included

**Comment by RelievedStudios** [comment]
maybe try setting a different game dir? 
![image](https://user-images.githubusercontent.com/46948241/62823493-a065d580-bbd4-11e9-8862-290ff9d5d767.png)

**Comment by noobsplicer** [comment]
worked on the first try but didnt on the second try

**Comment by RelievedStudios** [comment]
do you have any other mods installed or resource packs?

**Comment by noobsplicer** [comment]
i have 2 shaders and stratum 128x128 resource pack

**Comment by RelievedStudios** [comment]
try without optifine?

**Comment by noobsplicer** [comment]
![image](https://user-images.githubusercontent.com/53967412/62823770-88bf2a80-bb9d-11e9-8864-d12d337bf0d8.png)
if you mean this part i already installed it without of

**Comment by RelievedStudios** [comment]
> > tried replacing the logo
> 
> or whatever file `2378311fabbccae299383fa84b1c8126b4c497ce` points to ^^

what did this file point to?

**Comment by noobsplicer** [comment]
.minecraft/Impact/assets

**Comment by noobsplicer** [comment]
there's multiple files with similar names to that

**Comment by RelievedStudios** [comment]
`impact.4k` try deleting that

**Comment by noobsplicer** [comment]
where's that

**Comment by RelievedStudios** [comment]
wait never mind, have you tried setting more then 2G ram?

**Comment by noobsplicer** [comment]
i wanted to do that but i dont know how to do that in this launcher

**Comment by RelievedStudios** [comment]
![nRblWWUWMk](https://user-images.githubusercontent.com/46948241/62823869-a6aa8080-bbd9-11e9-84c7-3fc79ef5d275.gif)

**Comment by noobsplicer** [comment]
set it to 5g now, ill try

**Comment by RelievedStudios** [comment]
how much does your system have?

**Comment by noobsplicer** [comment]
16

**Comment by RelievedStudios** [comment]
might as well set it for 8

**Comment by noobsplicer** [comment]
okay, also 5 didnt work aswell

**Comment by noobsplicer** [comment]
nope 8 doesnt work

**Comment by RelievedStudios** [comment]
I cant seem to find the error exactly

**Comment by noobsplicer** [comment]
im dumb basically so you should try looking for the easy problems to solve

**Comment by rdmir3** [comment]
Delete `impact/assets` on every launch.

**Comment by noobsplicer** [comment]
bruh.

**Comment by StijnSimons** [comment]
Can we have the full log? Not just the crash

**Comment by noobsplicer** [comment]
the launcher log and crash log is there, what more can i add? if its gonna help i will

**Comment by StijnSimons** [comment]
`%appdata%\.minecraft\latest.log`. The launcher log still contains launcher stuff.

**Comment by noobsplicer** [comment]
what does the latest.log contain?

**Comment by StijnSimons** [comment]
The game's log??

**Comment by noobsplicer** [comment]
ok editing it in now

**Comment by StijnSimons** [comment]
thats a log without running impact...

**Comment by noobsplicer** [comment]
i deleted it and tried to play with impact again

**Comment by noobsplicer** [comment]
how do i put useful information in it lmao

**Comment by StijnSimons** [comment]
run impact and wait till it crashes, then put in the log

**Comment by noobsplicer** [comment]
ok im deleting latest.log and running mc with impact and then editing the latest.log in again

**Comment by noobsplicer** [comment]
[latest.log](https://github.com/ImpactDevelopment/ImpactClient/files/3492313/latest.log)

i hope this is it

**Comment by noobsplicer** [comment]
[latest.log](https://github.com/ImpactDevelopment/ImpactClient/files/3492360/latest.log)

**Comment by StijnSimons** [comment]
Still the same but aight doesnt matter, i'll do it with this

**Comment by noobsplicer** [comment]
im retarded

**Comment by StijnSimons** [comment]
Its pretty much up to Impact developers to fix this. Noone has access to the source.

**Comment by noobsplicer** [comment]
bruh is it that hard lmao

**Comment by noobsplicer** [comment]
who's the best dev so i can ask for help

**Comment by StijnSimons** [comment]
No need to ask. They read issues so just keep this open. Don't start asking them cause that would annoy them.

**Comment by noobsplicer** [comment]
ok good, when do u think i will get a fix tho

**Comment by LeafHacker** [comment]
Duplicate of #1460

**Comment by rdmir3** [comment]
Before every launch of the game, open command prompt and paste the following and press enter:

```
rmdir %appdata%\.minecraft\impact\assets /s /q
```

**Comment by noobsplicer** [comment]
it doesnt work, system cannot find the file specified

**Comment by noobsplicer** [comment]
ooh new update but still no progress

**Comment by clerickx** [comment]
reinstall minecraft

**Comment by clerickx** [comment]
might work

**Comment by clerickx** [comment]
or delete mod files

**Comment by l1ving** [comment]
This is over a year old 🗿
