### ISSUE TITLE
Night module

### ISSUE THREAD

**Issue by thegamerx1** [ImpactDevelopment/ImpactClient#1526]
A module to set the time to night so the people that cheat at night wont get their eyes fked

**Comment by StijnSimons** [comment]
[Windows](https://www.howtogeek.com/241771/how-to-adjust-your-pcs-screen-brightness-manually-and-automatically/)
[Ubuntu](https://help.ubuntu.com/stable/ubuntu-help/display-brightness.html.en)
[MacOS](https://support.apple.com/kb/PH25444?locale=en_US)

**Comment by Thunder33345** [comment]
i think they meant to hack that make it always night, dont we have time hack?

**Comment by StijnSimons** [comment]
> wont get their eyes fked


> [Windows](https://www.howtogeek.com/241771/how-to-adjust-your-pcs-screen-brightness-manually-and-automatically/)
> [Ubuntu](https://help.ubuntu.com/stable/ubuntu-help/display-brightness.html.en)
> [MacOS](https://support.apple.com/kb/PH25444?locale=en_US)

**Comment by thegamerx1** [comment]
@Thunder33345 yeah theres time hack but not time just weather also im not on a laptop and my monitor brightness is always at 0 i also use the windows night light so i dont need that program
