### ISSUE TITLE
Macros

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#153]
We should add back the option to trigger commands using keybinds, iirc @ZeroMemes had a fancy "advanced macros" system planned.

**Comment by Fluffbuck3t** [comment]
i would love the ability to /kill with a single key press

**Comment by ZeroMemes** [comment]
Might look into a lua implementation.

**Comment by SuperOP535** [comment]
"""l u a"""

**Comment by LeafHacker** [comment]
Proposing moving the "advanced" stuff to #629 and having this issue track a more simplified system of simply assigning keybinds to a list of chat lines

**Comment by ZeroMemes** [comment]
> Might look into a lua implementation.

I removed the lua system from ClientAPI, for now we're going to stick with the chat commands for macros, and maybe create a script system in the future.

**Comment by LeafHacker** [comment]
Added a GUI in 4.5, so considering this closed.

A chat command could still be added, feel free to open an new request for this.

The Add/Edit GUI could be improved by allowing lines to be rearranged or removed with buttons. Currently you can empty a text box, but it won't be removed fully until saving the macro (when empty lines get removed).

**Comment by EpicGuy547** [comment]
...its broken again.

**Comment by Cerbiac** [comment]
This is issue is old, a suggestion, and closed.
Your bug report should go under #954.
