### ISSUE TITLE
A option to toggle the "." command

### ISSUE THREAD

**Issue by iamyou** [ImpactDevelopment/ImpactClient#1537]
Like someone ask you how to use the command,i usually say "./command arg1 arg2"
It's very annoy to see the "Unknown command"
And It's very cumbersome to imput the \ first..
That's all,thanks!

**Comment by StijnSimons** [comment]
`.prefix`

**Comment by iamyou** [comment]
> `.prefix`

thanks!And how to modify the prefix of Baritone
