### ISSUE TITLE
a couple of dupes

### ISSUE THREAD

**Issue by Maghster2** [ImpactDevelopment/ImpactClient#1543]
First, placing a block, dying with toud (totem of undying) and breaking an item and losing stuff in general will not lose anything like having a 64 stack of block placing 1 or more will stay at 64

second, chest, and shulker will have a feature where you can edit them they wont change in inv but when they are placed down they will have the item, but ender chests also have some but it edits all

third, dupe set item it will drop in front of you with 2 settings: basic or classic: summon the entity of an item drop and mob will summon a zombie holding it with a 100% drop rate

if you guys have any suggestions or questions let me know.

**Comment by Maghster2** [comment]
ya hoo

**Comment by StijnSimons** [comment]
🤡

**Comment by Maghster2** [comment]
> 🤡

heck you

**Comment by StijnSimons** [comment]
> > 🤡
> 
> heck you

🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡
