### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by eatmedaddy** [ImpactDevelopment/ImpactClient#1547]
**Is your feature request related to a problem? Please describe.**
Whenever im loading up a new server such as 2b2t im always wondering if suddenly the client will go beserk and bunny hop the s h i t out of some poor spawning player, but I dont want to disable everything and slowly ease it in, i want to suddenly slap a preset of 500 cheats without doing it manually

**Describe the solution you'd like**
press button. a preset of cheats enabled. uwu hacker man.

**Describe alternatives you've considered**
easier keybinding

**Additional context**
idk lol

**Comment by leijurv** [comment]
Use presets. `.preset save epichackerman` then turn everything off, then when you're ready do`.preset load epichackerman`
