### ISSUE TITLE
AutoRespawn should hook into GuiGameOver

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#155]
Similar to how AutoReconnect works, AutoRespawn could hook into `GuiGameOver` and display a respawn timeout/toggle. This would also completely remove the need to use the (broken) `EntityDeathEvent`, since we would just trigger logic from the `GuiGameOver` screen.

**Comment by ZeroMemes** [comment]
This has been fixed by the latest ClientAPI commit https://github.com/ImpactDevelopment/ClientAPI/commit/279381961ff8f66d2c951dabf478d5e315a1ada0.

**Comment by MattSturgeon** [comment]
Um really? ClientAPI adds a **GUI** like auto reconnect for respawning?

**Comment by ZeroMemes** [comment]
Apparently I can't read

**Comment by LeafHacker** [comment]
Added in 4.1
