### ISSUE TITLE
[1.14] #goto coordinate issue

### ISSUE THREAD

**Issue by RoonGoon** [ImpactDevelopment/ImpactClient#1559]
When using #goto or .b goal with x y z coordinates, it swaps the y and z coordinates and completely removes the y coordinate

1. Type in a set of coordinates in-game using x y z
2. The chat will show a different z coordinate and no y coordinate

![bug](https://user-images.githubusercontent.com/54225169/63219625-ede9c180-c143-11e9-9a9c-99a2b090f3fd.png)
 
- Impact Version: 4.8 nightly for 1.14.4 <20190817>
- Using Optifine? <!No>
- Enabled mods: <Middle Click Friend, Auto Cheat, Auto Reconnect, Enchant Color, Weather, Auto Totem, Auto Weapon, Item Saver, Nametags, Auto Tool, Auto Eat, Light>
- Operating System: <Windows 10 64bit>

If you put the z coordinate as the y and z coordinates, it will take you to the correct spot, but will remove the y coordinate. This was also done on a Realms server. I tested on singleplayer and it seemed to work as intended.

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/3f38abb96412884011523743b901e23e2cc37b58

will be in a nightly

for now, as a workaround, use relative coords for `z` when it's negative (using `~`). if you're at 10,20,30 and want to go to 420,69,1337 you should do `goto 420 69 ~1307`
