### ISSUE TITLE
Impact crashes upon looking on water

### ISSUE THREAD

**Issue by bigbullet638** [ImpactDevelopment/ImpactClient#156]
I was just chilling on my singleplayer world and I was using Impact. I had decided to go look for an ocean monument so i built a boat and went to the ocean but as soon as i was a few blocks away from the ocean and was going to place the boat the screen had just went black and my game had crashed. I am using optifine and have intel hd graphics. The only mods i had on at the time were criticals,liquid interact rainbowenchant, velocity, storage esp, noslow and hitbox.
![image](https://user-images.githubusercontent.com/31348933/29716909-23070202-89a5-11e7-8103-574542b38eef.png)

**Comment by zPeanut** [comment]
maybe try to turn off liquidinteract

**Comment by ZeroMemes** [comment]
"LiquidInteract" was the issue, this has been fixed in 4.1.
