### ISSUE TITLE
Donator Penis

### ISSUE THREAD

**Issue by MagicSenpai** [ImpactDevelopment/ImpactClient#1565]
Donators should get a penis that is sized relative to how much they've donated so the more they donate the bigger it is. $10 and you can change it black imo.

This will help fund the future development of my favorite utility mod!!

**Comment by zPeanut** [comment]
sorry we wont add this because we dont wanna have any competition for our developers :)

**Comment by leijurv** [comment]
<img width="153" alt="Screen Shot 2019-08-18 at 2 21 35 PM" src="https://user-images.githubusercontent.com/3837873/63230590-7e1b1b80-c1c3-11e9-88fa-bb133c1707eb.png">

**Comment by StijnSimons** [comment]
![image](https://user-images.githubusercontent.com/17461028/63230608-6c5f6580-c20f-11e9-9cc3-6ed74fb50800.png)
R.I.P Lavender @MagicSenpai

**Comment by MagicStarIsntGay** [comment]
Add anime
