### ISSUE TITLE
.setvalue or similar

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#157]
Sometimes when you want an EXACT value like timer 4.31 it can be hard with the current seekbar.. An .setvalue <mod> <value name> <value> would be good or just like .timer <value>

Thanks.

**Comment by LeafHacker** [comment]
Added a `.set <module> <property> <value>` command, (untested and probably completely broken) in 4.1, so closing for now.

**Comment by SuperOP535** [comment]
Okay thanks

**Comment by SuperOP535** [comment]
Weird, did you edit my comment?

**Comment by v0idst4r** [comment]
No you're just autistic
