### ISSUE TITLE
Better AntiAFK

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#158]
Add an extra mode to send a message every x seconds

**Comment by LeafHacker** [comment]
This may be better implemented as a separate configurable spammer mod

**Comment by Fanngg** [comment]
agreed

**Comment by Fanngg** [comment]
this sould happpen but it sould be able to be set to times and such

**Comment by Fanngg** [comment]
not like only specific 1s
like a somewhere between 5min-10min send /

**Comment by ZeroMemes** [comment]
Added in the form of a chat spammer that can be configured with a new ``spam`` command in 4.2
