### ISSUE TITLE
AutoWeapon

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#159]
Automatically select the best weapon in inventory (add checkboxes so you can choose which weapons are included)

**Comment by n00ses** [comment]
autotool does that

**Comment by LeafHacker** [comment]
@n00ses autotool uses the "correct" tool to mine blocks, this is about choosing the most powerful melee weapon.

**Comment by ZeroMemes** [comment]
Added in 4.2
