### ISSUE TITLE
Don't toggle when you do for example F3+G

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#166]
I have G as my Flight keybind, when I do F3+G (to see chunk boundaries) my Flight enables...

**Comment by hugohindi** [comment]
Change the bind then.

**Comment by SuperOP535** [comment]
It shouldn't toggle when F3 is held

**Comment by LeafHacker** [comment]
The module manager could check for modifier keys being down before toggling
modules. Though then you have to decide which modifiers (e.g. Ctrl and
Shift probably shouldn't block toggling).

For now impact can inject into the capi mod manager, longer term it should
be fixed upstream.

**Comment by ZeroMemes** [comment]
Fixed in 4.2
