### ISSUE TITLE
Allow opening clickgui from the main menu

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#169]
Click GUI should support rendering over the main menu.

Perhaps take in a parent object and if the parent's class is on a whitelist (i.e. main menu, plus maybe a few other menus), draw the parent before drawing clickgui.

User input (key/mouse/action events) should **not** propagate to the parent.

**Comment by SuperOP535** [comment]
This can be good to disable mods that don't allow you to join like nuker

**Comment by kekkekek** [comment]
Agreed

**Comment by LeafHacker** [comment]
Got this pretty much working, but for some reason my implementation causes each category window to exist twice when in-game

**Comment by LeafHacker** [comment]
Figured out the issue, added to 4.3

**Comment by LeafHacker** [comment]
![image](https://user-images.githubusercontent.com/23565638/39098777-9dbe7604-4667-11e8-94ae-0cb38923d7e9.png)
![screenshot from 2018-04-22 19-59-31](https://user-images.githubusercontent.com/23565638/39098783-ba2619f0-4667-11e8-964d-847f996f418e.png)
