### ISSUE TITLE
Team ESP

### ISSUE THREAD

**Issue by 6BytesIn** [ImpactDevelopment/ImpactClient#172]
Lately my autismo has been going through the roof because i see too many boxes, i think there should be an option to do team esp e.g. team today, team tomorrow. You're on team tomorrow and you don't want to see your team boxes, so add esp checks.

**Comment by zPeanut** [comment]
:thonk:

**Comment by zPeanut** [comment]
probably 4.2 to be honest

**Comment by LeafHacker** [comment]
isn't there already a team EntityFilter @ZeroMemes?

**Comment by ZeroMemes** [comment]
I don't believe so

**Comment by ZeroMemes** [comment]
My bad, it appears that there is. But it is limited to only filtering out entities if they are on your team.

**Comment by ZeroMemes** [comment]
Added in 4.2
