### ISSUE TITLE
Add a Changelog back to Impact

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#174]
just like the one in 0.2, but   i m p r o v e d

![screenshot_2](https://user-images.githubusercontent.com/25800857/29752121-612c20b2-8b58-11e7-9bec-fe36bde116d7.png)

**Comment by 6BytesIn** [comment]
we also need jars back

**Comment by LeafHacker** [comment]
Implying @ZeroMemes would ever write a changelog! He doesn't even do that for ClientAPI

**Comment by LeafHacker** [comment]
Duplicate of #179
