### ISSUE TITLE
FORCEOP

### ISSUE THREAD

**Issue by 6BytesIn** [ImpactDevelopment/ImpactClient#175]
i need to make this for greifign servers thjx

**Comment by zPeanut** [comment]
IMPACT 4.0 FORCE OP™™™™™™™™™™™™™™™™™™™™™™™™™™™™™™™™™

**Comment by zPeanut** [comment]
oh shit my mouse flipped and now its on invalid sorry gonna fix in about uhhhhhhhhhhhhhhhhhh never cause thats impossible to make kthxbye

**Comment by 6BytesIn** [comment]
thx

**Comment by zPeanut** [comment]
np

**Comment by LeafHacker** [comment]
Marking as wont fix instead of invalid. While a valid request, it is still impossible (AFAIK)
