### ISSUE TITLE
Make "real" chams a mode and keep old chams

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#176]
The new 4.1 "real" chams is nice and all, but completely different to how old chams looks.

![2017-08-27_23 17 07](https://user-images.githubusercontent.com/23565638/29754500-4bcc44ce-8b7e-11e7-9ff1-0541dcfd9e6c.png)

IMO this would work better by keeping the old polygon offset one and making each a chams mode, "solid" vs "texture"

**Comment by ZeroMemes** [comment]
Implemented in 4.1
