### ISSUE TITLE
Minestrike Glitch

### ISSUE THREAD

**Issue by daggerdig** [ImpactDevelopment/ImpactClient#178]
In minestrike some players i see are not highlighted in the minestrike ESP. The aimbot does not shoot at entities that are not highlighted.

**Comment by Discoli** [comment]
Yea, I reported this to brady a whiiiiiiiiiile back before 4.0, I get this too.

**Comment by ZeroMemes** [comment]
@Discoli That was caused by another issue. This is different.

I believe that the issue has been fixed, after I made a modification to the code the issue hasn't been occurring anymore. Closing for now.

**Comment by ZeroMemes** [comment]
Also duplicate of #143
