### ISSUE TITLE
Elytra Slope.

### ISSUE THREAD

**Issue by EternalEmrys** [ImpactDevelopment/ImpactClient#180]
So like,you plug in coordinates for the console, then it calculates the sope you need to be at for you to get there without touching the ground, how many rockets you would have to use when reaching at certain height, then using rockets at the height you set, so it can get you to your destination at once so you can AFK elytra fly there.

------------------------------------------------------------------------------------------------------------------------------------

Also, just making it to use the rockets at a certain Y level would be good enough for me \-_-/

**Comment by zPeanut** [comment]
# **TYPE MORE LIKE THIS IT WONT ANNOY ANYBODY**

**Comment by EternalEmrys** [comment]
Annoys me actually.

**Comment by zPeanut** [comment]
then stop putting the suggestion into bold and semi-header

**Comment by EternalEmrys** [comment]
idk why it did that honestly :/ could be because i put a line -------- like that all the way under it, i was using the line to separate the suggestions..

**Comment by LeafHacker** [comment]
GitHub uses markdown

Underlining is one method to denote a heading. The other method being to prefix the line with `#`.

I'll edit and tidy up the comments

**Comment by ZeroMemes** [comment]
Added to 4.2 as an option called ``Auto Boost``. The firework activation height can be set by using ``.elytraplus height <value>`` where ``value`` is the Y coordinate at which the fireworks will be launched.
