### ISSUE TITLE
AntiLevitation

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#181]
Please add this mod I hate the shulker effect, yes I can fly down but still I don't like it..

**Comment by zPeanut** [comment]
probably will not bypass on all servers tbh

**Comment by SuperOP535** [comment]
me playz on a server with no anticheat :P

**Comment by SuperOP535** [comment]
I play on a server with no anticheat :P

**Comment by LeafHacker** [comment]
Shouldn't be impossible, iirc some flights work ok while levitating. Some
flag when going down, but level/up might be ok.

**Comment by kekkekek** [comment]
I would like this feature as well

**Comment by ZeroMemes** [comment]
Added as "LevitationControl" in 4.1

**Comment by SuperOP535** [comment]
Yay thanks Brady
