### ISSUE TITLE
KillAura setting to attack shulker bullet

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#182]
Make a setting so I killaura can attack shulker bullets (these green stuff they shoot)

**Comment by ZeroMemes** [comment]
Added as "Anti Bullet" option for the LevitationControl module in 4.2

**Comment by LeafHacker** [comment]
Hm, feels kinda odd being a levitation option..  It might be better as an EntityFilter or a option on aura
