### ISSUE TITLE
Xray makes blocks darker

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#186]
I used `end_stone` as an example. I'm using the mod Light on both screenshots.

![bild](https://user-images.githubusercontent.com/27556391/29994849-3f246a16-8fda-11e7-96db-4c983e815788.png)
without xray 

![bild](https://user-images.githubusercontent.com/27556391/29994851-50176a12-8fda-11e7-98b8-5dc3222607a6.png)
with xray

**Comment by ZeroMemes** [comment]
Fixed in 4.2
