### ISSUE TITLE
Minestrike hack doesn't shoot through smoke

### ISSUE THREAD

**Issue by 6BytesIn** [ImpactDevelopment/ImpactClient#187]
Does not shoot through smoke.

**Comment by ZeroMemes** [comment]
What block is put in the place of smoke?

**Comment by 6BytesIn** [comment]
How do i find out?

**Comment by ZeroMemes** [comment]
If you didn't already know don't worry about it. I'll take a look at the resource pack

**Comment by ZeroMemes** [comment]
Added option in 4.2
