### ISSUE TITLE
Client freezes when I do anything (MAC)

### ISSUE THREAD

**Issue by kdogisgr8** [ImpactDevelopment/ImpactClient#19]
Normal minecraft functions properly, but I press rshift and it freezes for 30 seconds, it shows the menu and then I rclick a button, or press escape, and it freezes for another 30 seconds. This client worked fine before 1.11 . Literally unusable, fix your client it's the only public working speedhack for NCP. FIX YOUR SHIT

**Comment by ili-codes** [comment]
Fix: use arrows to get to Render > ClickGUI on tabgui and then choose in Mode: Para. Now it works.

**Comment by ZeroMemes** [comment]
Cause still unidentified (Inconsistent results). The only current fix is to set the click gui mode to para.

**Comment by ili-codes** [comment]
It's probably because of the Mac's rendering engine.

**Comment by ZeroMemes** [comment]
This issue has finally been fixed in 4.0
