### ISSUE TITLE
Speed Vanilla bug

### ISSUE THREAD

**Issue by nasfinasfinasfi1** [ImpactDevelopment/ImpactClient#192]
If you are in a 1x2 block area and you have placed torches or fire the Speed (vanilla) will start glitching you out (unless you're pressing shift).

**Comment by LeafHacker** [comment]
Can you clarify the steps to reproduce? If I stand stationary within a non-solid block (e.g. torch or fire) with Speed enabled I will glitch out? Or do I need to be moving through these blocks?

**Comment by VitorISs** [comment]
I think he is saying that vanilla speed glitch the player if he passes through a block that has no collision. (such as torches, fire, grass, etc.)

**Comment by LeafHacker** [comment]
iirc those blocks might make anticheat detection easier, which isn't a bug in the speed mod.

Generally, if you can't reproduce the issue on single player or a vanilla server, it is an anticheat plugin not a bug

**Comment by VitorISs** [comment]
?
