### ISSUE TITLE
Murder Mystery minigame

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#199]
Make this a widget or something with the titles Murderer: and Archers: change the Murderer as soon as a player holds an iron sword and change the Archers when a player holds a bow.. If possible make the names visible again..

**Comment by ZeroMemes** [comment]
I'll implement this as an addition to the already existing "Murder" module.

**Comment by ZeroMemes** [comment]
Added in 4.2
