### ISSUE TITLE
Exception in Client thread; ignored args --nativeLauncherVersion

### ISSUE THREAD

**Issue by GrassyPlayz** [ImpactDevelopment/ImpactClient#2]
Every time I try to open Impact, this shit happens.
![capture](https://cloud.githubusercontent.com/assets/10326788/21080903/2e5fd748-bf91-11e6-9fae-cc3822c67176.PNG)
I've tried to reinstalling the version, and deleted the "Impact" file in ".minecraft".
Someone, please help. I don't want to play with Wurst cuz it's a piece of sh*t.

**Comment by Rookie001MC** [comment]
I also having the same problem.

**Comment by ZeroMemes** [comment]
There seems to be an issue with the OptiFine release that the client is using. Can you try deleting the "shaders" folder and see if that works?

**Comment by Rookie001MC** [comment]
It works. Thanks!

**Comment by LeafHacker** [comment]
re-opening until fix is released

**Comment by ZeroMemes** [comment]
Fixed in latest OptiFine

**Comment by usereewrjrjeejr** [comment]
First
