### ISSUE TITLE
Option to show bearing beside coordinate info

### ISSUE THREAD

**Issue by Thunder33345** [ImpactDevelopment/ImpactClient#202]
adding option to show currently facing +/- X/Z or North South East West,
option for off or X/Z or NSEW or both beside current cords

begin able to display that would be helpful and would save me how many times opening F3 just to get that

**Comment by LeafHacker** [comment]
Added in 4.2

![image](https://user-images.githubusercontent.com/23565638/30082775-e270fb0c-9283-11e7-9cc0-140cf5d5747e.png)
![image](https://user-images.githubusercontent.com/23565638/30083236-a236aa76-9285-11e7-926c-d7c06eb8d383.png)

**Comment by TheOhioan1** [comment]
tbh that looks weirdly aligned, hopefully you fix that in 4.20

**Comment by LeafHacker** [comment]
It is right aligned text, as the widget is on the right of the screen.

I don't have any ideas for how to cleanly aline it other than moving to the left (where chat would get in the way).
