### ISSUE TITLE
Better scaling for click gui

### ISSUE THREAD

**Issue by ygyuuffut** [ImpactDevelopment/ImpactClient#206]
I am hoping you guys, the devs could do some slightly modification on the client click gui part for the low resolution screens, something like zoom out. because I (and possibly other peoples) have a display that is 1366*768 instead of 1920*1080.

*hope this got improved in some future hot fixes 😃

**Comment by LeafHacker** [comment]
Maybe we could use the scaled resolution, if we don't already. Thoughts @ZeroMemes ?

**Comment by ZeroMemes** [comment]
@LeafHacker Scaling based on the actual resolution, rather than scaled would work better for all resolutions.

**Comment by LeafHacker** [comment]
Adjusting the height of elements to ensure they don't overflow the screen
skid be relatively simple, but ensuring the element position is on screen
might be more complex, though probably not too bad

**Comment by ygyuuffut** [comment]
Considering add a scroll-able click-gui would help a lot, display less options at a time and make it scroll-able. that would be the fastest way to fix the problem. *maybe?*

**Comment by LeafHacker** [comment]
Adding scroll bars to the main GUI screen would be a bad solution.

It would be better to simply always render on screen by checking if
positions/sizes will overflow.

A perfect solution might also have some scaling, and/or an alternative
(mobile inspired?) interface for smaller resolutions.

**Comment by leijurv** [comment]
Added in 4.5 or 4.6 i dont remember
