### ISSUE TITLE
Black screen on start

### ISSUE THREAD

**Issue by Duskwriter97** [ImpactDevelopment/ImpactClient#21]
I recently reinstalled Impact after it randomly stopped working. Whenever I ran it though, it black screened and then stopped responding. I tried leaving it alone for a while to see if anything changed but to no avail. I'm fairly certain it's because I have NVIDIA drivers or something, as it interferes with my standalone optifine client as well. Do you know a way to fix it so I can play Impact with the drivers I have? Or some other recommendation in order to successfully use my client again?

Edit: this is the message I get on launch

Couldn't get hash for Impact 1.11.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/Impact 1.11.2/Impact 1.11.2.jar.sha1: HTTP 403: Forbidden

**Comment by ZeroMemes** [comment]
This appears to be an issue with the usage of the new launcher, as it is trying to download Impact from Minecraft's official download servers. Try using the old launcher https://minecraft.net/en-us/download/alternative

**Comment by Duskwriter97** [comment]
I got it to work after a few tries. Would you recommend continuing to use the old launcher or would it work with the new one now that I've gotten it to work again?

**Comment by ZeroMemes** [comment]
Stick with the old launcher, the new one seems to have compatibility issues with all kinds of modded versions, even Forge. The next update for Impact will fix this issue because there will be a custom launcher. I'm going to close this issue for now because it appears to be resolved.
