### ISSUE TITLE
Particles isn't always aligned correctly with cursor

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#210]
Note the gap between the cursor and the vertex

![image](https://user-images.githubusercontent.com/23565638/30080010-16033c5a-927a-11e7-9786-82a17aa4e493.png)

![image](https://user-images.githubusercontent.com/23565638/30080064-3a1cecee-927a-11e7-987f-2a5612f0bced.png)

**Comment by ZeroMemes** [comment]
Ah, after making the positioning dynamic based on the position of the cursor, I forgot to compensate for the cursor target.

**Comment by ZeroMemes** [comment]
Fixed in 4.2
