### ISSUE TITLE
Glitched TTF rendering at higher font sizes

### ISSUE THREAD

**Issue by hugohindi** [ImpactDevelopment/ImpactClient#217]
![Photo](https://i.imgur.com/DK4eacv.png)
WHY IS THERE A DOT THERE NOW I CANT USE IMPACT ANYMORE

**Comment by ZeroMemes** [comment]
Caused by bad TTF rendering. It was covered up by a rectangle for the 4.0 release, Leaf accidentally removed it for 4.1

**Comment by ZeroMemes** [comment]
Fixed in 4.2

**Comment by VitorISs** [comment]
nice, impact will be playable again
