### ISSUE TITLE
.nuker list

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#220]

**Comment by zPeanut** [comment]
???????

**Comment by Thunder33345** [comment]
.nuker list will list all the block nukerid will break/target

**Comment by SuperOP535** [comment]
Just like Thunder3345 said

**Comment by LeafHacker** [comment]
In future when you create issues please attempt to describe them in detail

**Comment by ZeroMemes** [comment]
Added in 4.2
