### ISSUE TITLE
Add certain 3.0/2.x things back+Auto mine bug

### ISSUE THREAD

**Issue by TheForgottenKing** [ImpactDevelopment/ImpactClient#222]
Notably:

ItemESP

Separate Jesus module (Maybe add .t <module> <setting> like Wurst)

Packet fly/NCP Mode Flight

Also, Auto mine keeps mining even after being deactivated until the mouse button is clicked.

**Comment by ZeroMemes** [comment]
Please make separate issues for separate things.

**Comment by SuperOP535** [comment]
item is in esp settings are you blind? .t alredy exist
