### ISSUE TITLE
new mod:silent chest

### ISSUE THREAD

**Issue by 1999MapleSyrup** [ImpactDevelopment/ImpactClient#223]
hi. i recently discovered that when you world download a dupestash, you also download the items in the chests, shulkers, and all other containers. i was wondering if u guys can make the user see the items in the container but not opening it. because when i downloaded the dupe stash i never opened any containers. that means the server sent the info about the chest to the user without us opening it right? i think you can use this to check if there is any ilegal items in the container on 2b. that way you wont lose any items by opening a chest accidentally,(because 2b deletes the items if u interact with the container)the mod can be called silent chest and it can be activated when u middleclick on a container.

**Comment by zPeanut** [comment]
lol 2 years and no comment and or label

**Comment by Aaron2550** [comment]
Does the server send another players inventory to you? Would be nice to have a inventory thing next to their nametag

**Comment by mrphax0r** [comment]
Oof

**Comment by mrphax0r** [comment]
@Brady pls add

**Comment by ZeroMemes** [comment]
The client is not told about inventory contents of chests or players. Chest contents are sent once they are opened by the player, and only other player’s held items and equipped armor are sent. The best way this could be implemented is that when you walk near chests it tells the server it wants to open them, and then displays the response information describing the item contents.

**Comment by 0-x-2-2** [comment]
This is not possible.
