### ISSUE TITLE
Suggestion: Hit delay according to new PvP introduced after 1.8

### ISSUE THREAD

**Issue by RogerFK** [ImpactDevelopment/ImpactClient#224]
There is no "Cooldown" setting for the new PvP system and it sucks when you want to do frame perfect hits to deal the most damage possible, or am I missing it?

**Comment by ZeroMemes** [comment]
You're missing it. There's a "Delay" mode for Kill Aura.

**Comment by VitorISs** [comment]
Set the kill aura mode as Delay.
