### ISSUE TITLE
Couple suggestions

### ISSUE THREAD

**Issue by SwiftSilverYT** [ImpactDevelopment/ImpactClient#228]
So I think you should make a hack that allows you to place pumpkins on the side of blocks. Probally gonna be rejected but this would be nice becuz i could easily make stuff out of pumpkins. 

Also you should be able to make it so aura wont hit certain mobs and have certain tracers for mobs red. EX: red tracer for a ghast.

**Comment by ZeroMemes** [comment]
Marking as invalid for multiple topics

**Comment by Dr0verbuild** [comment]
You didn't mark invalid.

**Comment by Dr0verbuild** [comment]
Nvm im stupid
