### ISSUE TITLE
Click-TP module

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#232]
If you right-click in the block that you are aiming (even if that's not on your reach), you get teleported to this block. 
Would be good for servers that has no anticheat.

**Comment by VitorISs** [comment]
i think the "ClickTP" won't teleport you farther than 10 blocks in 1.12+ :/

**Comment by ZeroMemes** [comment]
Added in 4.2

**Comment by VitorISs** [comment]
awesome :D
