### ISSUE TITLE
"MLG" option for NoFall

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#234]
Would be nice if there's a option for NoFall that uses a water bucket that is on your hotbar to make a "MLG"... 
Then the water would absorb the fall damage :D

**Comment by hugohindi** [comment]
Could be useful if you are trying to look legit.

**Comment by olibols** [comment]
yes

**Comment by SwiftSilverYT** [comment]
*cough*turnonfastplace*cough*

**Comment by ZeroMemes** [comment]
Added in 4.2
