### ISSUE TITLE
Particles option on homescreen does not save on restart of client

### ISSUE THREAD

**Issue by TheForgottenKing** [ImpactDevelopment/ImpactClient#237]
Pretty self explanatory, turn on particles, when you reboot client it turns off which makes me sad and continues my depression

Please help

**Comment by LeafHacker** [comment]
Could've sworn I already added this...

**Comment by ZeroMemes** [comment]
@LeafHacker You did it on September 5th, there just hasn't been a release since then.

**Comment by SuperOP535** [comment]
:thonk:
