### ISSUE TITLE
Aerial Control

### ISSUE THREAD

**Issue by Cookie-Kurokami** [ImpactDevelopment/ImpactClient#2418]
I'm not sure if anyone else has suggested this before, but most if not all clients that I've used prior to switching to Impact had a feature that allowed users to move freely while in the air without the separation from the ground causing a reduction in movement speed. In doing so, it also enabled players to make use of the benefits of Step while in the air, by which I mean: Let's say you've got your Step value set to two, but you want to get over a wall that's three blocks high. You can't simply walk over it like you could if it were two blocks high, so what do you do? Well, with this, simply jumping one block high would enable you to rise over the wall via the two block high Step. 

A mod like this would not require the creation of a separate module. In my experience, most of the time it was integrated into Air Jump and I think it would be wonderful if the same applied here as it allowed for incredible ease of movement. I understand something like this isn't exactly priority, but please at least consider my request? I would be most grateful.

**Comment by zPeanut** [comment]
even if it doesnt work on modern anticheats, people can still suggest features on github. you shouldnt be hostile to new ideas or to new people who just want to express their suggestion and maybe find a reasoning on why this should be added @dominikaaaa .

**Comment by Cookie-Kurokami** [comment]
Thank you, zPeanut.
