### ISSUE TITLE
Xray issues

### ISSUE THREAD

**Issue by dasher865** [ImpactDevelopment/ImpactClient#243]
I can't see much of anything when I use xray

### What happens?
everything a few blocks away from me is too dark to see

### When does this happen?
Anytime I use xray to search for something

### Exact steps to reproduce?

Go underground
enable xray
try and see ores

- Impact Version:4.1 for 1.12.1
- Using Optifine?No
- Enabled mods: xray
- Operating System: Windows 10

**Comment by hugohindi** [comment]
Holy shit someone actually followed the bug layout, anyways try enabling fullbright and see if that works.

**Comment by SuperOP535** [comment]
Duplicate of #186

**Comment by SuperOP535** [comment]
Please use the search function
