### ISSUE TITLE
FastUse Module

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#244]
FastUse is a module that makes you drink/eat consumable items faster. It's pretty useful.
There's a way to make a FastUse bypass for NCP... (i don't know how... just saying.. if you want to try to develop this bypass)

**Comment by ZeroMemes** [comment]
Due to the way 1.9+ handles client-player ticking, this is no longer possible.

**Comment by VitorISs** [comment]
oh.. :/
