### ISSUE TITLE
.plugins & .pl not working

### ISSUE THREAD

**Issue by ACA30** [ImpactDevelopment/ImpactClient#247]
So, when I attempt to type .pl or .plugins the command says that there is an error in the syntax. It then says to do .help plugins, so I do that, and it says that there is no syntax needed. As far as I know, this worked on the previous versions, and I don't know why it's happening now.

### What happens?
It doesn't work (shows a syntax error and tells you to do .help plugins)

### When does this happen?
When I type .pl or .plugins

### Exact steps to reproduce?

- Do .plugins or .pl

### Game output?

```
N/A
```

### Crash report?

```
N/A
```

- Impact Version: 4.1
- Using Optifine? No
- Enabled mods: Nothing
- Operating System: MacOS Sierra

**Comment by ZeroMemes** [comment]
Fixed in 4.2
