### ISSUE TITLE
1.12.1 

### ISSUE THREAD

**Issue by ItsYoungDaddy** [ImpactDevelopment/ImpactClient#248]
Opening Impact 1.12.1 after installing 1.12.2 opens 1.12.2

### What happens?
running 1.12.1 impact runs 1.12.2 instead

### When does this happen?
when I run 1.12.1

### Exact steps to reproduce?
-Step 1: download impact 1.12.2 
-Step 2 drop 1.12.2 folder into versions
-Step 3 run 1.12.2
-Step 4 close 1.12.2
-Step 5 run 1.12.1

### Game output?

```

```

### Crash report?

```

```

- Impact Version: <4.1 for 1.12.1>
- Using Optifine? <no>
- Enabled mods: 
- Operating System: <Windows 10 64bit>

**Comment by ZeroMemes** [comment]
Fixed download.
