### ISSUE TITLE
Add scaffold walk

### ISSUE THREAD

**Issue by ItsYoungDaddy** [ImpactDevelopment/ImpactClient#249]
<Readd scaffold walk like 3.0 and previous versions had. I don't like having to use another client just for scaffold walk.>

**Comment by VitorISs** [comment]
what ? '-'
there's already a Scaffold Walk...
is on the "World" tab
and its called "Scaffold"

**Comment by ItsYoungDaddy** [comment]
Holy fuck I'm blind, sorry
