### ISSUE TITLE
"Flowing Water" option for Jesus

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#254]
I know that was removed to prevent NCP to flag, (as was said in the #191 issue), but i think would be better if there's an option for jesus... 
Because is pretty annoying when you're on a server that has no anticheat and just "drown" by stepping in a flowing water..

**Comment by LeafHacker** [comment]
I was trying to figure out a way to float up while in flowing water but not while above it, but couldn't get it to work well. Not looked at this for a few months now.

**Comment by VitorISs** [comment]
@ZeroMemes ~ When i tested, NCP only flagged me when i stepped on the 5th Flowing Water Block(1)... i could walk nicely in the first 4 flowing water blocks(2) without getting flagged
And... the impact jesus only enable you to walk on the FIRST flowing water block(3)

I think it should get updated... like: normal jesus makes you walk until the 4th Flowing Water blocks(4) without flags and the issue option makes you walk on every Flowing Water blocks(5)..

**Comment by ZeroMemes** [comment]
Added in 4.2
