### ISSUE TITLE
XCarry Module

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#257]
A module that enables you to store items in your crafting slots.
And if you close the inventory, the items won't get dropped.

(i think that only works on servers without anticheat... but still useful)

**Comment by ZeroMemes** [comment]
Could be an addition to the existing ``Inventory`` module...

**Comment by ZeroMemes** [comment]
Added as ``Extra Slots`` option for the ``Inventory`` module.
