### ISSUE TITLE
Re add ScreenshotUploader

### ISSUE THREAD

**Issue by n00ses** [ImpactDevelopment/ImpactClient#260]
Uploads screenshot to imgur if a screenshot is taken
![Example](https://user-images.githubusercontent.com/30820756/30767997-b2121166-9fc7-11e7-9e7b-02ac3d76da8b.gif)

**Comment by VitorISs** [comment]
good idea :v

**Comment by zPeanut** [comment]
would like that too

**Comment by LeafHacker** [comment]
Now that clickable links work, this may actually work ok if re-added

**Comment by ZeroMemes** [comment]
Added in 4.2
