### ISSUE TITLE
Deadly Jesus

### ISSUE THREAD

**Issue by fameroyal** [ImpactDevelopment/ImpactClient#261]
Sometimes i take damage or die when i walk on water using jessus(solid and dolphin) in version 4.1.That never happend on server i play(2b2t) but it happens alot in singleplayer.When i turn off all hacks but jessus that does not happen.Is there some hacks i cant use in the same time with jessus or thats just a glitch?

**Comment by zPeanut** [comment]
which hacks do you have activated?

**Comment by fameroyal** [comment]
well i have killaura,velocity,anti-hunger,speed,esp,chams,tracers,nametags and noslow.Sometimes no-fall but that doesnt really work.

**Comment by zPeanut** [comment]
probably try to turn off anti hunger

**Comment by fameroyal** [comment]
Yeah thats right.It doesnt kill me without anti-hunger.Thank you.
