### ISSUE TITLE
Taking fall damage after flying and then going into Water. (not my video)

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#262]
hj

**Comment by VitorISs** [comment]
?!

**Comment by LeafHacker** [comment]
Wtf happened to this issue @zPeanut ?

**Comment by LeafHacker** [comment]
For the record, the video originally linked showed a server quirk where fall damage built up during nofall/flight/antihunger gets applied on contact with water. AFAIK there is nothing that the client can do to avoid this (other than not using those mods or not blocking fall damage)

**Comment by zPeanut** [comment]
this was already suggested thats why i took this down
