### ISSUE TITLE
Extra HP in "Nametags"

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#267]
When a player has absorption, the extra HP doesn't show up in nametags, the maximum hp is 20 (even if the player has 11+ hearts).
I think would be better if it shows up.

**Comment by hugohindi** [comment]
Yeah, and the extra hearts should be shown separately (see proffesionally made example below)
separately
![mspaint_2017-09-24_00-30-35](https://user-images.githubusercontent.com/8309816/30777294-16dda7c4-a0c0-11e7-8be8-5cecc00d4df4.png)

**Comment by VitorISs** [comment]
Professionalism™

**Comment by ZeroMemes** [comment]
Nametags **do** display extra health, just not in the way depicted with the "+"

**Comment by ZeroMemes** [comment]
Added in 4.2

**Comment by LeafHacker** [comment]
@ZeroMemes nametags still aren't showing the absorption, even after the changes in 4.2.

In 4.3 I've fixed this to actually take player absorption into account.
