### ISSUE TITLE
WaterSpeed Module

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#269]
A module that speed you up ONLY in water. (like depth strider, but you don't need boots.. and is faster)
There's a way to bypass latest AACs

I think would be better as a separate module, not as a speed mode.. in case the player wanna use both.

**Comment by VitorISs** [comment]
i think would be good if there's a option to change how fast you'll swim, like: 
"Speed: 0.1-----[]------20"

**Comment by ZeroMemes** [comment]
Added to NoSlowDown in 4.2

**Comment by VitorISs** [comment]
hm... good idea
