### ISSUE TITLE
PortalGUI Module

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#271]
A module that enables you to open inventory/chat/etc while in a portal.

(i got it from here: http://prntscr.com/gokrjm , thanks househousehouse1)

**Comment by zPeanut** [comment]
probably all ready being added since i guess its pinned in the former suggestions channel

**Comment by VitorISs** [comment]
it was pinned 5 months ago... i don't think someone remember it lol

**Comment by LeafHacker** [comment]
The pins are essentially forgotten. If you see something there that isn't
already here, feel free to make an issue requesting it.

The whole point of the issue tracker is to keep this stuff centralised and
easily managed.

**Comment by ZeroMemes** [comment]
Added in 4.2
