### ISSUE TITLE
my tracers and nametags dead

### ISSUE THREAD

**Issue by bigbullet638** [ImpactDevelopment/ImpactClient#272]
inb4 i be told to turn off my fast render i never had it on in the first place. the only performance setting i have on is smooth fps. i even tried toggling fast render on and off. pls help

**Comment by zPeanut** [comment]
try deleting the mods.cfg file or something in the impact directory

**Comment by LeafHacker** [comment]
Github is for tracking issues/tasks in the project, not for asking questions and support tickets.

As soon as you include phrases like "please help" the issue is invalid, the conversation moves from _fixing a bug in the project_ to _helping an individual work around the issue_.

**Comment by bigbullet638** [comment]
err maybe i got blanked when i asked in the help channel
