### ISSUE TITLE
Diferent modes for antiafk

### ISSUE THREAD

**Issue by Fanngg** [ImpactDevelopment/ImpactClient#274]
so if your playing a server that doesnt allow afk pools or antiafk hacks and moving every 5 mins is pretty obvious there sould be a mode for antiafk that makes you run the command / every 4-5 mins (just to seem non robotic though u might be)

**Comment by Fanngg** [comment]
i forget if impact even has antiafk but they sould add it if not

**Comment by VitorISs** [comment]
duplicate of #158

**Comment by zPeanut** [comment]
^
