### ISSUE TITLE
suggestion: clientside /r

### ISSUE THREAD

**Issue by jefferyw08** [ImpactDevelopment/ImpactClient#276]
a lot of servers don't have /r and it is incredibly annoying having to type the full /msg (player)..

thanks

**Comment by 6BytesIn** [comment]
How can /msg (name) be that hard. Minecraft even has the function to press tab to autofill the name.

**Comment by LordQuadrato** [comment]
Label needed. This issue is not labelled yet, would be `Enhancement`

**Comment by VitorISs** [comment]
:(
