### ISSUE TITLE
Download Taken Down 

### ISSUE THREAD

**Issue by TACOCAT1** [ImpactDevelopment/ImpactClient#30]
I was trying to download Impact for minecraft 1.11.2  on my PC and I got to MediaFire link and it told me

 "The file you requested has been removed from MediaFire for a violation of our Terms of Service. 

This file has been taken down on 2017-06-02 by:

File Name: Impact 3.0 for MC 1.11.2.zip (14.9 MB)

Company: Mojang AB and Mojang Synergies AB
Email: enforcement@mojang.com

Still have questions, or think we've made a mistake? Please contact support for further assistance."

Could anyone help me download impact minecraft 1.11.2 for my PC?

**Comment by LeafHacker** [comment]
As explained in the DMCA notice you quoted, the file was taken down because it contained copyrighted materials belonging to Mojang.

This is a known issue and we cannot help you to illegally download copyrighted material here.
