### ISSUE TITLE
Storage ESP glows storages gray

### ISSUE THREAD

**Issue by WrityGD** [ImpactDevelopment/ImpactClient#3451]
When I download Impact for the official launcher, I don't have this problem, but I need to use impact with forge. When I download it as a Forge mod, the problem is back. How do i download Impact for official launcher with forge?
![2022-11-17_21 01 11](https://user-images.githubusercontent.com/118527005/202695569-d76a2f8d-695d-4fc8-9902-22bb8f6eded1.png)

**Comment by CesiumCs** [comment]
I think there are known incompatibilities with KAMI Blue like these visual bugs. If this happens without KB, try updating your drivers or if you have optifine, making sure shaders are disabled or just disabling optifine altogether cause optifine isnt compatible with anything on earth

**Comment by WrityGD** [comment]
Thank you, now I fixed this bug by deleting KB, but I need something like this client. Can you tell me the best alternative?
