### ISSUE TITLE
3FPS if i dont press f3

### ISSUE THREAD

**Issue by SiGMA051** [ImpactDevelopment/ImpactClient#3452]
When I go into 2b2t or just create my own world, i have 3fps at most, but when I press f3 and open that hud, i have over 200fps. I want to know solution for how to fix it? I have allocated 5gb of ram to minecraft launcer, I installed optifine, have all settings turned low and I'm not in fullscreen. Help pls I want to go play

**Comment by SiGMA051** [comment]
EDIT: I tried impact for minecraft version 1.16.5 and 1.12.2 and both do same thing so it has to do something with impact and not minecraft sided help me fix

**Comment by CesiumCs** [comment]
This is already mentioned in #3441. Could you go over there and comment a few things? I've been trying to find a fix for this without having access to src but I can't even reproduce the issue on my end. Over there could you comment your graphics driver version, and os type and version?
