### ISSUE TITLE
Redstone crash 

### ISSUE THREAD

**Issue by rgreig2** [ImpactDevelopment/ImpactClient#37]
Every time I'm around a bunch of redstone and it's fired my game crashes and i get the message you are using an unsupported version of minecraft. Any ideas?

**Comment by ZeroMemes** [comment]
What version of Impact are you using?

**Comment by rgreig2** [comment]
Impact 3.0 on 1.11.2

**Comment by ZeroMemes** [comment]
Are you able to reproduce this crash on vanilla 1.11 or 1.11.2?

**Comment by rgreig2** [comment]
I cannot reproduce it because whenever I play factions we use pistons to crush people but I cannot use them because the amount will cause the game to crash, but when I use vanilla 1.11.2 it works fine and I have no problems

**Comment by w-o-a-h** [comment]
what version is the server

**Comment by w-o-a-h** [comment]
because on a 1.11.2 server we have a machine that has 15k redstone dust all it does is lag the game really bad

**Comment by LeafHacker** [comment]
Can this be reproduced in the latest version ([4.0](https://impactdevelopment.github.io/#download))?

**Comment by w-o-a-h** [comment]
If it is its a vanilla bug or a server bug

**Comment by zPeanut** [comment]
Since the release of 4.0, 3.0 is no longer supported. Thanks for participating.
