### ISSUE TITLE
impact 4.0

### ISSUE THREAD

**Issue by jefferyw08** [ImpactDevelopment/ImpactClient#38]
I am looking for a download of the impact client version 4.0 for minecraft 1.12 but i cannot find it

**Comment by zPeanut** [comment]
Impact 4.0 is not released. When it is released, you will get a notification on our Discord Server. Be sure to join it! 

discord.gg/YFhR2Ab

- zPeanut

**Comment by w-o-a-h** [comment]
u can download the hake impaker v4.0 at https://impactdevelopment.github.io/impasta.exe

**Comment by w-o-a-h** [comment]
what the heck @ZeroMemes
