### ISSUE TITLE
Running Impact 1.11 doesn't work!

### ISSUE THREAD

**Issue by OliverBoy** [ImpactDevelopment/ImpactClient#39]
**Launch Failed:** _The version you are trying to play inherits properties from unknown version._

(When opening Impact 1.11 from #downloads in the Discord)

**Comment by LeafHacker** [comment]
@ZeroMemes is 3.0 for 1.11 still supported after 4.0's release? Closing for now on the assumption that it is not.

**Comment by ZeroMemes** [comment]
3.0 will no longer be supported
