### ISSUE TITLE
Cosmetic: Minecraft version shows as 1.10 in 1.11 (3.0) main menu

### ISSUE THREAD

**Issue by sudofox** [ImpactDevelopment/ImpactClient#4]
It's all in the title, really

**Comment by 6BytesIn** [comment]
We know already, its been fixed.

**Comment by LeafHacker** [comment]
For anyone that is really bothered by this and wants a work around, it is possible to patch strings in the jar very easily with [JBytedit](https://github.com/QMatt/JBytedit/releases). In this case you would replace the string "Minecraft 1.10" with "Minecraft 1.11" (there is a tool that can search for strings)

**Comment by ZeroMemes** [comment]
Fixed in 3.0 for 1.11.2 release

**Comment by LeafHacker** [comment]
4.0 has the correct version number for both 1.11.2 and 1.12.

Marking this as WONTFIX since this issue is specific to 3.0, which is no longer supported.
