### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by ghost** [ImpactDevelopment/ImpactClient#414]
### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

### Game output?

```

```

### Crash report?

```

```

- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System:

**Comment by LeafHacker** [comment]
FYI, github does have a block feature...

**Comment by zPeanut** [comment]
goodbye IAmNoice
