### ISSUE TITLE
"Safe" option for Scaffold

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#416]
If you turn scaffold on, it automatically makes you hold the blocks that are in your hotbar... (and you can't change the slot).
An option that enable us to change if the player will only place blocks IF he's holding the blocks or not, then you can use scaffold even if you're holding a sword, pickaxe, etc. You just need the blocks on your hotbar.

**Comment by hugohindi** [comment]
I believe Impact does this to not get detected by anti-cheats, for example WatchDog.
I think there should be a "Safe" option in the scaffold menu that locks the item you're holding to the blocks, but when it's disabled you just need them in your hotbar. But i'm not sure if i'm right about the detection thing so i'll wait for a dev to respond.

**Comment by VitorISs** [comment]
Using scaffold without holding the block works on NCP/Watchdog.. (i don't know about AAC/Spartan/etc)
This option would be GREAT.


(And i think Brady or Leaf should add the NCP Tower as an option for scaffold in 4.2 :3)

**Comment by zPeanut** [comment]
![screenshot_3](https://user-images.githubusercontent.com/25800857/31049235-37ffb5e0-a62f-11e7-9306-b0e445f51d21.png)

the fuck?

**Comment by ZeroMemes** [comment]
It locks the item due to inconsistent placing of blocks when I tried "silent" holding the blocks. I'll add it as an option.

**Comment by ZeroMemes** [comment]
Added in 4.2.
