### ISSUE TITLE
Watermark goes Weird when Unicode Font turned off

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#42]
When the MC Font is turned on (unicode off), the Watermark goes into weird bold Letters.

![screenshot](https://image.prntscr.com/image/PzozPH4qQmOG7Lel4UHngw.png)

**Comment by SupremeChancellorPalpatine** [comment]
this can be fixed by not being a pussy

**Comment by kekkekek** [comment]
I have had this issue as well

**Comment by LeafHacker** [comment]
Does this only affect the watermark (“Impact 4.0” ingame), no other text?

**Comment by ZeroMemes** [comment]
Able to reproduce, fixed in 4.1
