### ISSUE TITLE
more options for xRay, also macros for commands such as /tpaccept

### ISSUE THREAD

**Issue by tspierer2** [ImpactDevelopment/ImpactClient#420]
I just want to edit every single block in my xray, idc about opacity. Also I would love macros to work, im sure u are working on it tho. 

### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

### Game output?

```

```

### Crash report?

```

```

- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System:

**Comment by VitorISs** [comment]
. . . . .

**Comment by 6BytesIn** [comment]
So is this a bug or suggestion?

**Comment by tspierer2** [comment]
suggestion

**Comment by ZeroMemes** [comment]
Multiple topics covered, please re-open issues with individual topics.
