### ISSUE TITLE
A Bundle of Suggestions and a Bug! :)

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#424]
I have some pretty useful suggestions to add to the impact client. Surely adding some of these will avoid some bans, and accidents when using the client. As well as being generally useful to people who use the client.

First of all, I would like to start with the ones to do with chat/commands. Some of these used to be a thing on former versions, but you got rid of it for some reason. Please, please, please add back .bind reset. I get that there are some risks such as accidentally removing all your binds, but I have a solution to that, just keep reading. When you are typing a '.' command (Ex. .bind) there should be an outline to the insert text bar in chat (color should be changeable in the gui, or set to rainbow :>). Also, if the command is an actual command it should pop up suggestions of what to type, and information related to the suggestions should be displayed to the right of the chat box. When your username is said in chat, you should hear a ding, and have a highlight in chat highlighting your name. That will make it easier to know if people are talking about you in chat, or talking to you. This should also be slightly customizable. As in, you should be able to set certain words/phrases to be highlighted when in chat. My concept art:
![2017-10-07_13 41 31](https://user-images.githubusercontent.com/30992296/31570306-4e65c3a8-b037-11e7-9380-9795ca8cb253.png)
![chat](https://user-images.githubusercontent.com/30992296/31570307-4e7b0560-b037-11e7-853d-e77898428d70.png)

Now, some features and a bug that are unrelated. Please please PLEASE add lock view back to Kill Aura. It was so useful, why did you get rid of it. Please fix Kill Aura targeting or fov ( idk which one is broken). When I set my fov to 10, and my mode to single, I attack multiple mobs around me in 360. Add Speed Reconnect, this is a hack that when enabled will quickly disconnect, and reconnect to the server you were on.

That’s all for now! I will be sure to post again soon with some more suggestions and bug reports.

**Comment by VitorISs** [comment]
Please, make one issue for EACH suggestion/bug.

**Comment by SuperOP535** [comment]
Do like vitorsIss said

**Comment by zPeanut** [comment]
Pretty good art, gotta give probs. However please (as stated by @VitorISs ) Please make one Issue for each Suggestion or bug.
