### ISSUE TITLE
"OnlyChests" option for ChestStealer

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#425]
An option that makes the module ChestStealer ONLY steal items from chests.
Because is really annoying when you open some items menu (compass, etc) and the module steals the option item, then you get teleported or whatever..

**Comment by SuperOP535** [comment]
Not sure if these items are counted as non chests tho.

Servers modify chests/hoppers etc. to allow you to click on the items and not steal them

**Comment by VitorISs** [comment]
I know..
But when the cheststealer steals these items, it's as if you clicked on them.. and them activate or whatever..

There IS a way to make this option work.

**Comment by ZeroMemes** [comment]
Added in 4.2
