### ISSUE TITLE
Missing "say" command

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactClient#427]
I think this is pretty simple to add. One day I was just using the latest version of Impact (4.1)  regularly until I noticed .say was missing. Seeing that this is a very important feature, please add this in the next version of Impact.

**Comment by ZeroMemes** [comment]
The effect of a "say" command can be achieved by appending the prefix ``\`` onto a message.

Example:
``\.legit`` will send the message ``.legit``

**Comment by SuperOP535** [comment]
yeah but not everyone knows that so you should send a tutorial like "append `\` onto your message to send this to chat please" @ZeroMemes and you should maybe add .say for noobs tho

**Comment by LeafHacker** [comment]
You know append and affix mean add at the end, right?

You are prepending or prefixing when you add before.

It's also worth clarifying whether you are prefixing the entire message or
just a character and whether or not the escape prefix works with other
characters (e.g. \/ and \\). Also how does it behave when used incorrectly
(e.g. \$ or \foo) or used at other positions in the message?
