### ISSUE TITLE
Font not placed Right

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#43]
In the killaura section of the weepcraft gui, the font is offset to the left, ending up outside of it's menu box.

![screenshot](https://image.prntscr.com/image/TMvr5fdOSKC414qDiF4vHA.png)

**Comment by SupremeChancellorPalpatine** [comment]
yeah I think it's because you're a commie

**Comment by LeafHacker** [comment]
I'm probably being blind, but I don't see any obvious issue with the font in the screenshot.

Can you try and describe the issue in more detail? Is there a small rendering bug somewhere? Is the wrong font being used somewhere?

**Comment by zPeanut** [comment]
Do you see how the font is not in the Box? Its out side the box and in the main Box where the Modules are listed.

**Comment by LeafHacker** [comment]
> Do you see how the font is not in the Box

Doh! Told you I was probably being blind! Thanks for adding the explanation

**Comment by ZeroMemes** [comment]
Fixed in 4.1
