### ISSUE TITLE
Crosshair+ only partially rendered

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#44]
Crosshair on Crosshair+ Module is missing the bottom right bits:

![Crosshair screenshot](https://image.prntscr.com/image/UPR_d4_-TrGqWo7GXle1ZQ.png)

**Comment by ZeroMemes** [comment]
Fixed by ZeroMemes/ClientAPI@e051ce261701b7153f3dc246a8cd60747bc1cf19
