### ISSUE TITLE
Impact Installer

### ISSUE THREAD

**Issue by ZeroMemes** [ImpactDevelopment/ImpactClient#440]
Create a basic installer with the functionality to add Impact onto other tweakers. (Optifine, Forge, Liteloader, etc.)

**Comment by BoxOfFlex** [comment]
I get that I'm doing this the completely wrong way but, I tried with MultiMC cause it's easier that way and can't get Imapct to run at all ontop of Forge or Liteloader.

Liteloader has conflicting signatures on the Mixin classes

Forge can't find `net.minecraft.client.main.Main`

So without direct implementation of the two, its not gonna work easily.

**Comment by zPeanut** [comment]
IS IT TEXT BASED

**Comment by ZeroMemes** [comment]
LiteLoader compatibility was fixed in https://github.com/ImpactDevelopment/ClientAPI/commit/f221799fdcc16013dd300631c95aa18b1e607ba2.

Forge compatibility should be as simple as using an SRG obfuscated Impact jar, it doesn't appear to like deobfuscating Impact's references to notch-named members.

**Comment by leijurv** [comment]
XD
