### ISSUE TITLE
Squake as a BHop alternative

### ISSUE THREAD

**Issue by BoxOfFlex** [ImpactDevelopment/ImpactClient#441]
https://minecraft.curseforge.com/projects/squake

Works much better and more fluent then the current BHop mode in the Speed module but requires a tiny bit more skill (none at all if you're used to Quake, GoldSrc and Source Engine movement)

**Comment by ZeroMemes** [comment]
Speed is intended to provide a way to move faster on servers that are using anticheat plugins. This modifies the way that movement works in its entirety. Future updates will have forge support, so I find no need to integrate this feature directly into impact.
