### ISSUE TITLE
Better Function for Chest Stealer

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#442]
Chest Stealer right now is honestly pretty bad. If you could make it happen faster, and only take out items from the chest instead of wasting time trying to take things out of empty slots. There should also be a "Steal" button at the top right corner of the screen, as well as a function where if you close a chest, it will abort the stealing operation so you don't mess up your inventory, or another chest.

Would be cool if added! :)

**Comment by ZeroMemes** [comment]
Empty slots are already ignored. I've just fixed the issue with incorrect aborting of the stealing operation.

**Comment by InstantReflex** [comment]
Oh ok sorry, didn't know.

**Comment by ZeroMemes** [comment]
Added in 4.2
