### ISSUE TITLE
Block ESP

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#443]
My idea is to add a esp for blocks, alongside with x-ray. With x-ray, yes you can choose which ores you can see, but it would be very helpful if there was an outline, and a tracer (optional) pointing to the block you need. This could be activated without x-ray to JUST see a outline and/or tracer. This would be helpful for things like finding spawners, or things that are hard to spot even with x-ray.

**Comment by ZeroMemes** [comment]
Duplicate of #241
