### ISSUE TITLE
Crosshair prioritization for Cops and Crims

### ISSUE THREAD

**Issue by ppp123ppp** [ImpactDevelopment/ImpactClient#446]
Cops and crims hack is great, but the fov slider just isnt that useful. If you could give an option for the targeting system to only target players in front of you that would make it look a lot more legit, dont make it target the closest player near you but only the closest players in your line of sight no matter the distance.

**Comment by 6BytesIn** [comment]
Turn down the fov then.

**Comment by hugohindi** [comment]
Issue can be fixed by simply turning down the FOV.

**Comment by VitorISs** [comment]
in 4.1 you can't just turn down the fov...
because in 4.1 there's a bug: if your fov is in 30, 40, 60, etc, the "aimbot" will keep locking on people behind you... that was already fixed in 4.2, just wait for the update

**Comment by 6BytesIn** [comment]
Nice maths hehehehehe.

**Comment by ZeroMemes** [comment]
Added in 4.2
