### ISSUE TITLE
Cape Problem..?

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#448]
![hlnwhdl](https://user-images.githubusercontent.com/25800857/32142983-06507784-bca3-11e7-805a-ec1ff524e6e8.png)

the support cape does still not show. is this a client side or a hacked client bug?

**Comment by VitorISs** [comment]
is this duplicate of #98 ? :v

**Comment by ZeroMemes** [comment]
Duplicate, closing. Will look more into original.
