### ISSUE TITLE
Please add autocomplete suggestions for commands

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#45]
I dont know if this is a bug, or Brady removed it on purpose, but in the pre-3.0, there was a Rect that would appear with the information to a command if you would type it out, in 4.0, he removed that Rect.

**Comment by LeafHacker** [comment]
For missing commands from 3.0/2.7 please add separate issues like #47 and #48

**Comment by LeafHacker** [comment]
Comments about missing commands moved to #47 and #48

**Comment by LeafHacker** [comment]
Are you talking about an autocomplete feature? It would be really helpful if you could better describe/screenshot the missing feature

**Comment by zPeanut** [comment]
![screenshot_2](https://user-images.githubusercontent.com/25800857/29003656-fdb33b0e-7aba-11e7-91b7-43c68802f07b.png)
pre-4.0

![screenshot_3](https://user-images.githubusercontent.com/25800857/29003660-20579998-7abb-11e7-9151-e00584a45ae5.png)
after 4.0

**Comment by LeafHacker** [comment]
I've reworded the title accordingly. This is likely a missing feature from ClientAPI's command system.

This is probably something that will wait for 1.13 to take advantage of the command completion system Dinnerbone has been working on.

**Comment by ZeroMemes** [comment]
This is encompassed by a larger suggestion, #484, so I'm closing this.

**Comment by LeafHacker** [comment]
Removing milestone since this isn't fully added yet in 4.2, see checklist in #484
