### ISSUE TITLE
Multiple Configuration Profiles

### ISSUE THREAD

**Issue by ZeroMemes** [ImpactDevelopment/ImpactClient#450]
Multiple config profiles should be supported, allowing users to create profiles for specific purposes, such as bypass configs. Not to be confused with #219. Profiles should be in the same format as the current ``mods.json`` file, and should be saved in separate files under ``Impact/config``.

**Comment by VitorISs** [comment]
just like "presets" ?

**Comment by ZeroMemes** [comment]
@VitorISs Not exactly. Presets would not be included, but would probably be made available on the Impact website.

**Comment by ZeroMemes** [comment]
Base has been implemented in 4.2, pushing to 4.3.

**Comment by LeafHacker** [comment]
It would be interesting if in addition to having mutable profiles you can switch between and change settings in, we could also have immutable "saves" (or some better name) where you save the current state and can load it in as many times as you like without it changing.

Essentially the same as configurable presets.

**Comment by ZeroMemes** [comment]
> Not to be confused with #219.

Not sure what I was talking about here. This is pretty much the same thing as 219.

> It would be interesting if in addition to having mutable profiles you can switch between and change settings in, we could also have immutable "saves" (or some better name) where you save the current state and can load it in as many times as you like without it changing.
> 
> Essentially the same as configurable presets.

Yeah immutable profiles should be an option

**Comment by LeafHacker** [comment]
>>     Not to be confused with #219.
>
> Not sure what I was talking about here. This is pretty much the same thing as 219.

My understanding was that this issue was for immutable presets and #219 was for mutable profiles.
