### ISSUE TITLE
Xray not rendering everything

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactClient#452]
Ok so basically when you turn xray on and look around it doesnt render everything. For example, a diamond ore is right in front of you but you can't see it until you move your character around or look at it from a different angle. In comparison to X-Wurst (Wurst's xray hack), Impact's xray pales. Before anyone asks, yes I have the latest graphics driver availible and am using Impact version 4.1, 1.12.2.

**Comment by WaffleTraits** [comment]
Nevermind this is a duplicate post

**Comment by GlitchHead** [comment]
Actually the other posts talk about the darkness caused by xray. I'm sure they already noticed the horrible rendering issues with xray already though.
