### ISSUE TITLE
Freecam does not render surrounding caves when inside wall.

### ISSUE THREAD

**Issue by GlitchHead** [ImpactDevelopment/ImpactClient#454]
### What happens?

Cannot see all surrounding caves while inside blocks with Freecam. Some caves just disappear randomly unless you move closer to them.
### When does this happen?

When flying into a wall with freecam.
### Exact steps to reproduce?
Enable Freecam and fly into a wall. You will see some caves render but some do not and you need to move or turn your player to make the cave appear.

- Impact Version: 
4.1 1.12.2
- Using Optifine? 
No.
- Enabled mods: 
Nothing but freecam
- Operating System: 
Windows 10 64bit

**Comment by GlitchHead** [comment]
@ZeroMemes You might be able to trick the client into thinking its in spectator mode.

**Comment by ZeroMemes** [comment]
Fixed in 4.2
