### ISSUE TITLE
CameraClip does not render surrounding caves when inside wall.

### ISSUE THREAD

**Issue by GlitchHead** [ImpactDevelopment/ImpactClient#455]
### What happens?

Cannot see all surrounding caves while inside blocks with Cameraclip. Some caves just disappear randomly unless you move closer to them.
### When does this happen?

When clipping the camera through a wall with camera clip.
### Exact steps to reproduce?
Try going into a small tunnel underground. You will see that many of the caves will not render when using CameraClip

- Impact Version: 
4.1 1.12.2
- Using Optifine? 
No.
- Enabled mods: 
Nothing but CameraClip
- Operating System: 
Windows 10 64bit

**Comment by ZeroMemes** [comment]
Fixed in 4.2
