### ISSUE TITLE
The Macro 

### ISSUE THREAD

**Issue by FreeSpy443** [ImpactDevelopment/ImpactClient#456]
Macros are gone from the impact client for 1.12.2 and I don't know if they are supposed to be gone or its a bug. I use macros to dupe on servers that are pay to win. Its an important part of impact that is original and lets us dupe with .leave damageself;.drop macro

### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

### Game output?

```

```

### Crash report?

```

```

- Impact Version: 4.1 for 1.12.2 
- Using Optifine? 
- Enabled mods: 
- Operating System:

**Comment by VitorISs** [comment]
"duplicate" of #153
