### ISSUE TITLE
FOV Slider on all mods targets entites behind you with FOV settings that should not allow it.

### ISSUE THREAD

**Issue by GlitchHead** [ImpactDevelopment/ImpactClient#458]
If you set your FOV to 180 it ends up acting like a FOV of 360 for all mods. This also breaks The AimBot mods in the client causing them to randomly have seizures

### What happens?

Setting your FOV to a low value makes your client think that your facing behind yourself also so if you set your FOV to 50 you will target mobs in that range in front of you and also behind you.
### When does this happen?

On any mods that use FOV.
### Exact steps to reproduce?
Enable SmoothAimBot Set the FOV to 180 you will then target mobs behind you even though they are out of your FOV range.

- Impact Version: 
4.1 1.12.2
- Using Optifine? 
No.
- Enabled mods: 
Nothing but any mod that uses FOV.
- Operating System: 
Windows 10 64bit

**Comment by VitorISs** [comment]
#226
I don't know if brady only fixed this in the "Cops and Crims" module or also in all other modules...

**Comment by ZeroMemes** [comment]
The issue should be fixed for all mods.

**Comment by GlitchHead** [comment]
for 4.2?
