### ISSUE TITLE
When I enable X-Ray I cant see any blocks, All the blocks are dark and you can only see black blocks

### ISSUE THREAD

**Issue by harvo900** [ImpactDevelopment/ImpactClient#459]
### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

### Game output?

```

```

### Crash report?

```

```

- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System:

**Comment by VitorISs** [comment]
Duplicate of #186 
Issue already fixed in 4.2
