### ISSUE TITLE
Bad Spacing in the Hud

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#46]
There's bad spacing in the Hud. That's pretty much all there's too it.

![image](https://user-images.githubusercontent.com/23565638/28997718-1adeb88c-7a13-11e7-8952-91821b1f0250.png)

**Comment by LeafHacker** [comment]
What do you mean? Are you saying the letter spacing is too narrow and overlaps with the text-shadow? I don't see anything obviously buggy in the screenshot.

**Comment by ZeroMemes** [comment]
Pixel distance between text isn't consistent @LeafHacker

**Comment by ZeroMemes** [comment]
Fixed in 4.1
