### ISSUE TITLE
AutoMine: ability to mine out area

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactClient#461]
So you know how you can specify an area for blocks to be placed with that autobuild hack? It would be awesome to have a hack that could automatically mine out a selected area. Combined with autotool and scaffold it would be perfect. (Although scaffold would need to be re-worked because it locks your selection to a block when enabled)

**Comment by zPeanut** [comment]
i guess this is added now since 4.4 was released with baritone.

closing, reopen brady if im wrong

**Comment by ZeroMemes** [comment]
This is like an "area" mine. Can be done with Baritone, but not currently implemented.

**Comment by SylveonBottle** [comment]
I remember a previous mod having this feature, although I cannot remember the name of said mod.

I believe the module was named "Excavator", though. It would scan for all blocks in an area, attempt to min them all, then re-scan in case of any dropped sand or new changes.

**Comment by leijurv** [comment]
Area clear was added to Baritone here  https://github.com/cabaletta/baritone/commit/d5b393d6bdd9ca265e61f3e8833854b145467040

Builder branch will probably end up in 4.5

**Comment by ZeroMemes** [comment]
Builder won't end up in 4.5 unless it's merged into master tbh, but by the time 4.5 comes around that should too.

**Comment by ZeroMemes** [comment]
Changing Milestone to be inline with my previous comment.

**Comment by leijurv** [comment]
oh yeah this was added lol

`.b cleararea` and `.b click`

**Comment by TheKrishanlal** [comment]
How do I specify when using .b cleararea ?

**Comment by SylveonBottle** [comment]
I can use `.b click` but `.b cleararea` never works.

Can you give an example command of its usage? Nothing's working, always giving me a format error.

**Comment by Thunder33345** [comment]
go to pos2, use .b goal
go to pos1, use .b cleararea
