### ISSUE TITLE
Anti-GhostBlock

### ISSUE THREAD

**Issue by GlitchHead** [ImpactDevelopment/ImpactClient#462]
Saw a few clients with this mod. Its extremely helpful when using something like a efficiency V pickaxe that creates many ghostblocks when mining blocks very fast. Ghostblocks are blocks that are not visible and you cannot walk into them. They are also blocks that appear on your screen but are not server-side.

**Comment by ZeroMemes** [comment]
Will look into a method to prevent client/server de-synchronization. I'll try and prioritize this because it would be very useful.

**Comment by SuperOP535** [comment]
yay

**Comment by ZeroMemes** [comment]
Added in 4.2
