### ISSUE TITLE
Advanced TriggerBot

### ISSUE THREAD

**Issue by GlitchHead** [ImpactDevelopment/ImpactClient#465]
A form of TriggerBot that you just hold down your attack button and it will attack enemies with delay when your looking at them. You could also add a legit option so it will not attack if your blocking with a shield, eating or using a item thats in a state that you cannot normally attack in. It should also have distance sliders like killaura.

**Comment by ZeroMemes** [comment]
Will implement into autoclicker.

**Comment by ZeroMemes** [comment]
Added in 4.2
