### ISSUE TITLE
Blocking with a shield doesn't work while holding a sword.

### ISSUE THREAD

**Issue by ILikeTrains27** [ImpactDevelopment/ImpactClient#467]
fix this glitch pls

**Comment by SquidingTin** [comment]
what are you talking about? explain better please?

**Comment by RonIsBest** [comment]
Nocheatplus blocks you from using a shield and hitting with a sword.

**Comment by VitorISs** [comment]
that's not exactly a glitch... NCP just patched it..
probably (idk actually) there's no way to fix this

**Comment by SuperOP535** [comment]
he never said that he tried attacking but I guess he means that lol

**Comment by ZeroMemes** [comment]
Please elaborate

**Comment by LeafHacker** [comment]
Closing as it sounds like an anticheat is preventing op from blocking and hitting simultaneously.

**Comment by SquidingTin** [comment]
this was in my spam box >.>

**Comment by SquidingTin** [comment]
Hey, can you sign this petition? https://chn.ge/2QF7tnl

Thanks! - Trace

**Comment by MightyKnight** [comment]
This is still an issue and easy to reproduce even in singleplayer.
