### ISSUE TITLE
Better XRAY

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#474]
Pls add an option to xray that instead of unrendering everything renders a "overlay" on selected blocks, something like ESP on players, but instead on blocks.

**Comment by WaffleTraits** [comment]
I once used a similar-functioning mod and it was incredibly laggy. I think an overall rework of the xray hack shouls be reworked rather than your suggested idea, becuase clearly it is possible to make a better xray (just look at Wurst).

**Comment by ThatGrzegorzB** [comment]
If its coded poorly, yea it would be laggy, but tbh i could do it myself, its simple and not laggy at all if done correctly

**Comment by InstantReflex** [comment]
Copy of #241

**Comment by ZeroMemes** [comment]
Valid duplicate of #241.
