### ISSUE TITLE
Bring back the old impact guis and font as an alternative option to the new style

### ISSUE THREAD

**Issue by TheOhioan1** [ImpactDevelopment/ImpactClient#479]
honestly, some people including me like the 3.0 layout and font better than 4.0/4.1, here are some examples.
![image](https://user-images.githubusercontent.com/32405904/33298800-8de84044-d3b6-11e7-8902-38c335f1e8d6.png)
![image](https://user-images.githubusercontent.com/32405904/33298938-33feb882-d3b7-11e7-92b6-155ed42b5e1b.png)

**Comment by TheOhioan1** [comment]
also if you are re-adding clickgui, make your "4.0+" style and add the old one as another option. 
![image](https://user-images.githubusercontent.com/32405904/33299335-1901afec-d3b9-11e7-89a7-0f404fc8d618.png)

**Comment by InstantReflex** [comment]
You can already switch through them. Im pretty sure you just go to "Click GUI" in the hack menu, and switch between them. I'm not sure about the Minecraft front screen though, I think you are stuck with the new one.

**Comment by TheOhioan1** [comment]
yeah you can change the clickgui but there's no option from the one used in 3.0

**Comment by LeafHacker** [comment]
Brady has removed all old ClickGUI versions in 4.2 (26/01/2018), so I guess this is Won't Fix
