### ISSUE TITLE
.toggle command missing from 4.0

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#48]

**Comment by LeafHacker** [comment]
From @zPeanut:

> Also, the .xray command is missing, which makes it difficult to add ores while ingame since you cant use .xray like you would before. Hope it gets added back.

**Comment by LeafHacker** [comment]
From @zPeanut

> Also, the .toggle Command is missing which means you cant just toggle a module by name, you have to look it up on the clickgui and find it which is not the easiest thing. Hope it gets added back.

**Comment by ZeroMemes** [comment]
Added in 4.1
