### ISSUE TITLE
Re-Add Lockview

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#485]
Please please PLEASE add lock view back to Kill Aura. It was so useful, and worked perfectly fine. What was the reason of getting rid of it?

**Comment by ZeroMemes** [comment]
Added in 4.2

**Comment by LeafHacker** [comment]
I may be missing something, but isn't locking the view more general than just kill aura? e.g. can be used in combo with setting yaw to walk straight.
