### ISSUE TITLE
Speed Reconnect

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#486]
Add Speed Reconnect, this is a hack that when enabled will quickly disconnect, and reconnect to the server you were on. I know you have an auto reconnect, but it would also be useful to just have a button that you can press to automatically, and instantly do this.

**Comment by Thunder33345** [comment]
maybe the new[soon] macro system can do it

**Comment by ZeroMemes** [comment]
Added as a command in 4.3 (``.reconnect``)
