### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ZeroMemes** [ImpactDevelopment/ImpactClient#489]
A changelog should be made for each release, formatted as seen here: http://keepachangelog.com/en/1.0.0/

**Comment by SuperOP535** [comment]
Duplicate of #179

**Comment by InstantReflex** [comment]
oh mu dude you just got *pranked*

**Comment by ZeroMemes** [comment]
Created a new file in the resources repo to hold the changelog.

https://github.com/ImpactDevelopment/Resources/blob/master/data/changelog.txt

**Comment by LeafHacker** [comment]
Personally I prefer having a changelog within the repo the changes happen in. That way when you make a commit you update the changelog as part of your commit.
