### ISSUE TITLE
Freecam cant go into Blocks.

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#49]

**Comment by babbaj** [comment]
dumb nerd forgot to noclip

**Comment by LeafHacker** [comment]
It should be as simple as setting `noClip` on each player update:

```java
mc.player.capabilities.isFlying = true;
mc.player.capabilities.setFlySpeed(this.speed.getFloat());
mc.player.noClip = true;
mc.player.onGround = false;
mc.player.fallDistance = 0.0F;
```

**Comment by w-o-a-h** [comment]
@LeafHacker last time I checked noclip to true does nothing in vanilla

**Comment by LeafHacker** [comment]
hm, the above code worked in forge pepsimod, but that was 1.11 iirc

**Comment by w-o-a-h** [comment]
yeah noclip seems to work in forge but in normal mcp it acts like a slow fly but you don't go through blocks

**Comment by LeafHacker** [comment]
You could just disable block collision, but in singleplayer that would lead to all entities falling out of the world (didn't that used to happen on 2.7?)

**Comment by w-o-a-h** [comment]
Only Items on Multi-Player but I think setting noclip to true for them might work

**Comment by LeafHacker** [comment]
I guess we could look into what forge change to get noClip to work since that might be a cleaner solution

**Comment by LeafHacker** [comment]
The problem with noclip appears to be caused by `EntityPlayer.onUpdate` setting `this.noClip = this.isSpectator()`. ClientAPI will need to add a hook to override `noClip` without `EntityPlayer` changing it back.

**Comment by ZeroMemes** [comment]
Fixed.
