### ISSUE TITLE
Team ESP

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#491]
A good feature to add would be to have a switch near the color editor to activate team colors. This would make all outlines the color of the team the player is. Useful for TDM style mini-games.

**Comment by ZeroMemes** [comment]
Added in 4.4.

The placement of the "Color" option in ESP has been replaced with a *Multi Value* type that has 3 options: **Custom**, **Team** and **Health**. The multi value contains a single sub-option used to define the custom color, the other 2 options are self explanatory.
