### ISSUE TITLE
Donator capes are still visible even after self-destruct.

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#495]
After self-destruct, donator capes are still visible.

**Comment by w-o-a-h** [comment]
they cape will be there till the entity is destroyed. plus I don't think the unload is really suppose to keep you undetected from screen shares or anything since traces can be easily found without looking at in-game.

**Comment by InstantReflex** [comment]
> I don't think the unload is really suppose to keep you undetected from screen shares
It's supposed to eliminate the client from in-game, while you clean up your Minecraft folder (I think). So it's a big part of being undetected by screen shares. Either way, it's still a bug.

**Comment by LeafHacker** [comment]
>     I don't think the unload is really suppose to keep you undetected from screen shares

While Impact isn't a ghost client, 👻 the whole point of Self Destruct is to disable all modifications. Any modification that remains is therefore a bug.

**Comment by ZeroMemes** [comment]
Fixed in 4.5
