### ISSUE TITLE
new ClickGUI crashes when on mac

### ISSUE THREAD

**Issue by krabbypattified** [ImpactDevelopment/ImpactClient#5]
Right shift crashes Minecraft. Not sure what's causing it, but it only happens for this specific client.

If it matters, I'm on a Mac, and I was in single player creative mode.

**Comment by LeafHacker** [comment]
this is caused by some opengl stuff in the new clickgui menu that for some unknown reason crashes on macs.

A work around is to use a different clickgui mode, like classic or para. You can use tha tabgui or the json config file to change the clickgui mode.

**Comment by oscarmartian** [comment]
Where would one find the json config file? Is it just the file that appears next to the .jar, or is it somewhere else?

**Comment by ZeroMemes** [comment]
Issue fixed in 4.0

**Comment by oscarmartian** [comment]
Did someone say 4.0?
