### ISSUE TITLE
.Unbind

### ISSUE THREAD

**Issue by xraying4diamonds** [ImpactDevelopment/ImpactClient#504]
Unbinding dosen't work when i try .unbind [mod] NONE 
it dosen't work need help on how to unbind mods
- Impact Version: 4.1 for 1.12.2
- Using Optifine: No
- Enabled mods: Light,Sprint,Nametag,Tracers
- Operating System:  Windows 10 64bit

**Comment by SuperOP535** [comment]
.bind [mod] none

**Comment by SuperOP535** [comment]
You can also open the gui, open extra menu of the mod, click keybind and press DELETE button

**Comment by xraying4diamonds** [comment]
@SuperOP535 thank you .bind [mod] none didnt work it said "unable to find key with name "none"

**Comment by InstantReflex** [comment]
Yeah its broken rn, it will be fixed next update

**Comment by LeafHacker** [comment]
Looking at the git log, this was fixed by @ZeroMemes in 4.2 a couple days ago. I don't know how @InstantReflex knew that, seeing as he commented it'll be fixed before it was, but meh.
