### ISSUE TITLE
Rainbow renderables

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#506]
Title.
Currently not too many things have rainbow settings, which would be nice to see in stuff like tracers esp etc.

**Comment by ZeroMemes** [comment]
A color picker with this kind of functionality should be used for everything with colors.

**Comment by ZeroMemes** [comment]
Here's a demonstration of the color picker in action. Now I just need to add options like "Rainbow". https://streamable.com/92lj8

**Comment by ZeroMemes** [comment]
Added in 4.4, all modules with customizable colors have been given the color picker, and the color picker now has an added "Rainbow" toggle.

https://streamable.com/dynkf
