### ISSUE TITLE
Small improvements to the Minestrike module

### ISSUE THREAD

**Issue by MSGOD** [ImpactDevelopment/ImpactClient#509]
I have used the minestrike module for a while (Made a new account and farmed 610 wins on it so far) and I have found a few issues, along with some good ideas. 

- [x] First issue with the module, and an idea to fix it : 
The aimbot will often pick the wrong target, I usually put the aimlock FOV at 26 (for more control over who it aims at), but it seems to often aim for illogical players. For example, I peak around a corner with a sniper, my crosshair is almost on a player aiming at me, but the aimlock snaps to an afk player further away from my crosshair. My idea would be to add options on the Minestrike module tab to toggle "Target closest player to your crosshair first". This would allow a lot more control over what the aimbot does when you peak a corner.

- [x] Second issue with the module, and an idea to fix it:
When peaking around a corner with a sniper, I often find myself in situations where two guys are running towards me, I can see both, one is closer than the other. What the aimlock will usually do, is aim for the second enemy, which is further, then, the closest enemy will have time to get closer to me and kill me. My idea to fix this would be to add an option on the Minestrike module tab to toggle "Target closest player first". This would be really useful and give a lot more control on the aimlock.

- [x] Third issue / Idea : 
In minetrike, there's no recoil paterns like in CvC, and currently, if use a rifle, the minestrike module will automatically shoot whenever it has a possibility to hit a player, but it will just spray the weapon. Spraying can be very inaccurate and in many situations leads to death because you were not able to hit the opponent. Adding a toggle in the Minestirke module tab to toggle off the auto-shoot would be really handy. 

- [x] Fourth issue / idea (kinda) : 
This is related to the third issue, but it's an idea. Having a toggle in the minestrike module tab such as "only aim when shooting" which would work like most of the smooth aimbots on ghost clients which only aim when you're clicking. This would allow a lot more precision. 

- [ ] Last issue / idea : 
 When holding a corner with a sniper, the autoshoot will often blatantly pre-fire anyone who peaks, I am not sure if there would be a possible way to add this but, maybe adding an option for how long to wait before shooting a player who peaks could be useful. It would be pretty useful for players who try to use the module on "legit" settings.

That's all, you can contact me via discord if needed : NoWallsHere#0567

**Comment by Pabsb** [comment]
With your first point it makes more sense to have a modes like the following: Target closest player, Target player aiming at you, And one that's both. Also adding on a bone scan so it would hit any body part not just locking onto one specific part to help out in situations where you have head lock but see there feet only or etc.

**Comment by 6BytesIn** [comment]
You must be shit if you have to use hacks.

**Comment by ZeroMemes** [comment]
I would usually mark a post like this as invalid, as multiple subjects are being covered, but since they are all related I'll make an exception. I've edited the post to have checkboxes for each idea so that I can keep track of what has been done.

**Comment by ZeroMemes** [comment]
Added all 5 things in 4.4
