### ISSUE TITLE
Suggestion: Module to turn off lighting updates

### ISSUE THREAD

**Issue by TheOhioan1** [ImpactDevelopment/ImpactClient#510]
On 2b2t and other anarchy servers there's FPS lag machines involving lighting updates where it can crash your game or lag it down to 1 fps. If you add a module to reverse this in 4.3 it'd be great.
Here's a video to show this by BarrenDome: https://www.youtube.com/watch?v=L8pQj7fSnNs

**Comment by MSGOD** [comment]
doesn't "light" already do that? or am I crazy

**Comment by 6BytesIn** [comment]
@MSGOD "light" aka Brightness _(brady has to be different)_

**Comment by ZeroMemes** [comment]
@6BytesIn It's called Light because it also gives control over how lighting behaves with the monochrome feature.

**Comment by ZeroMemes** [comment]
Added as a "Skylight" option for the "Light" module. If the option is on, then skylight updates will be run, if off, they won't, fixing the lag issue.

**Comment by VitorISs** [comment]
niceee
