### ISSUE TITLE
New Texturepack and SSG553 Mechanics??

### ISSUE THREAD

**Issue by Ezwario** [ImpactDevelopment/ImpactClient#511]
Texture pack:

This client to be honest is one of the best minestrike ones out there ad i use this all the time. 
I love playing with guns however the default minestrike texture pack looks awfully boring. Which drags the interest away. I mean seriously pixel guns. I was wondering whether we could add more **smooth**
 and **realistic** skins such as the ones provided in podcrash. 

The thing is i don't want to go over to podcrash just for this so pls make one. It will grab the attention of the user making it more enjoyable. You might be like what is this guy rambling on othey are just skins they don't matter. Well at first that is everyone's opinion when playing the game for the first time. However, as time passes by you would want the urge to get new skins. To do this however you need 10k SHARDS. That takes a lot of grinding to do especially an unranked player on mineplex. Therefore adding a nice texture pack would be great.

SSG Gun update:

I love how the awp works in this client however the SSG doesn't lock on like the awp does unfortunately so it is much more harder to use SSG. To be frank i don't use the SSG however when i do I find it harder to do so. So if you make the SSG lock on quickly like the AWP does that would be great

Thanks for reading!

Also the texture pack point is something I think of as high priority compared to the SSG mechanics. It would be great if you guys could work on it!

**Comment by MSGOD** [comment]
Podcrash doesn’t provide new skins. Podcrash has a feature called « no srp » which means « no server ressourcepack ». This allows you to use your own custom minestrike pack without having to type /rpoff everytime you join a game to turn the default pack off. The no srp feature disables the default server ressourcepack from loading without getting you kicked for failure to download the pack.

The SSG mechanics are the exact same as the awp currently. If your shots miss, then the issue will also happen with the awp. Both guns lock on exactly the same, you just have to scope (sneak).

**Comment by MSGOD** [comment]
But yes I do agree that a feature to disable the default pack from downloading would be quite useful

**Comment by ZeroMemes** [comment]
The title says SSG553 (which isn't an actual gun however the SG 553 and SSG 08 are) but you're talking about the AWP so I assume you mean the SSG 08 (the sniper).

The SSG 08 and the AWP both use the same movement prediction rules to determine where to shoot. Is the issue the prediction distance or the actual locking on itself?

As for the No SRP feature, that should be easy and I don't have any questions about that.

**Comment by LeafHacker** [comment]
op seems to have lost interest, closing for now.
