### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by CuriousGamerFTW** [ImpactDevelopment/ImpactClient#513]
Whenever I disconnect in a server it gives me this error and I have to close the client for 5 minutes then reconnect and it works. Never does this on normal MC

### What happens?
http://prntscr.com/iprr78

### When does this happen?
When I join a server

### Game output?

```
18:33:31 | bjb | [CHAT] waduhekistan joined the game
```

- Impact Version: 
4.1 for 1.12.2
- Using Optifine? 
Yes
- Enabled mods: 
Non
- Operating System: 
Windows 7 but also does on my windows 10 machine

**Comment by WomasL** [comment]
Just try to restart the game. It is a usual problem. This can solve the problem.

**Comment by CuriousGamerFTW** [comment]
Did restart.

**Comment by WomasL** [comment]
Search cmd and run it as adminstrator, type `netsh winsock reset`. This should be fixed if restart doesn't work.

**Comment by CuriousGamerFTW** [comment]
It is not a connection issue.

**Comment by CuriousGamerFTW** [comment]
Any more support? It now crashes when I have typed that command.

**Comment by LeafHacker** [comment]
It is possible there is a bug in a mod, so as soon as the mod starts running the game crashes. Without a crash report and Brady taking the time to deobfuscate it there's not much we can do to investigate this issue.

Instead, I'd reccomend deleting the `Impact` folder in your mc profile. You can get to this folder by opening Impact, navigating to the Impact menu and clicking on "Impact Files".

I am closing this for now until a crash report is provided. Feel free to continue discussion if needed.
