### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by poppoppo** [ImpactDevelopment/ImpactClient#518]
I tested out Jigsaw client and saw some really cool features that you guys should add, i would rather use impact than jigsaw because jigsaw isnt as user friendly as impact, so please add some of the things i suggest

### What happens?

You skid shit from jigsaw
### When does this happen?

Whenever you feel like actually working on impact 4.2
### Exact steps to reproduce?

- Step one 
Download jigsaw, if you dont have it yet, https://www.jigsawclient.net/
- Another step
Skid the fuck out of it
  - Note about "Another step"
Make sure to skid things like: ServerCrasher, ArrowPerspective, and other shit you might like
- A third step
Skid some more
- etc

**Comment by MastaNub** [comment]
Really feel like they should rip off more things from clients such as spectate from Wurst and other things like path finder (but that takes time ugh).

**Comment by LeafHacker** [comment]
This is not a valid issue. Please feel free to open issues regarding _specific_ and _singular_ ideas or issues.

For example "Implement Spectate" is a valid issue, however "Implement x, y and z" is three issues combined into an invalid issue. This issue doesn't even go as far as to name _any_ specific idea.
