### ISSUE TITLE
Nuker and Autotool dont work correctly together

### ISSUE THREAD

**Issue by Ace2Race** [ImpactDevelopment/ImpactClient#523]
When using autotool nuker will not respect autotool and use whatever tool/item selected

### What happens?
uses tool in your hand that if trying to destroy many blocks fast can cause unwanted use on wrong blocks

### When does this happen?
while using nuker and autotool together

### Exact steps to reproduce?

1.turn on autotool
2.turn on nuker
3. break blocks and your tools eventually if you dont watch what your breaking 

### Additional Client Info
- Impact Version:4.1 for 1.12.1
- Using Optifine? Yes and No "works in both"
- Enabled mods: nuker autotool 
- Operating System: Windows 10 64bit

**Comment by ZeroMemes** [comment]
Fixed in 4.3
