### ISSUE TITLE
Macros not working.

### ISSUE THREAD

**Issue by DanisDGK** [ImpactDevelopment/ImpactClient#525]
When I click the Impact button, the Macros tab is greyed out.

**Comment by DanisDGK** [comment]
Impact 4.1 1.12.2 Version

**Comment by SuperOP535** [comment]
blame brady, he just put the button but did not implement anything

**Comment by LeafHacker** [comment]
There isn't a Macros GUI (well, there isn't macros at all atm), hence why the button is disabled. The button is left over from when there _was_ a Macros system before Impact got rewritten for ClientAPI.

Closing this as a duplicate of #153
