### ISSUE TITLE
FallDamageCalc

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#526]
Make a module that calculates the fall damage to the block where the crosshair points to

**Comment by Ilomantis** [comment]
Also include if the player is wearing feather falling into the damage equation if possible

**Comment by ZeroMemes** [comment]
Added in 4.4 as a command, executing either ``falldamage`` or ``falldmg`` works.

**Comment by LeafHacker** [comment]
I've updated this to also take into account jump boost, resistance, enchantments, hay bails and slime blocks. The only thing affecting fall damage not taken into account are beds, water and lava.

May be worth having a sub command that gives the raw damage before armour, etc. Also, hay and slime might be confusing if you land next to them and take a lot more damage...

**Comment by SuperOP535** [comment]
Why not a gui widget that automatically updates or maybe a number preview on the block you look at

**Comment by LeafHacker** [comment]
Could add a fall damage HUD widget I guess. Feel free to suggest it in a new issue
