### ISSUE TITLE
Scaffold breaks on mineplex cake wars

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactClient#528]
### What happens?

Scaffold places one block, then does nothing.

### When does this happen?

When using scaffold on Mineplex Cake Wars, with safe mode on.

### Additional Client Info
- Impact Version: 4.2
- Using Optifine? No
- Enabled mods: https://gyazo.com/6ebfc78538cc414366ea6cd4e4d514dc + safewalk
- Operating System: Windows 10 64bit

**Comment by VitorISs** [comment]
eat?antich

**Comment by VitorISs** [comment]
MY BAD.

**Comment by ZeroMemes** [comment]
Likely caused by the anticheat blocking Scaffold. Will test.

**Comment by ZeroMemes** [comment]
Works fine on latest version at least
