### ISSUE TITLE
ignite should break blocks preventing it from igniting targets

### ISSUE THREAD

**Issue by DerpedCrusader** [ImpactDevelopment/ImpactClient#529]
when the entity is standing on snow, it won't ignite them

suggestion: have it break snow/torches/carpet so it can light the enitites up

**Comment by Pabsb** [comment]
If its a snow block it won't ignite it.

**Comment by DerpedCrusader** [comment]
no, just the flat snow thing that goes over the grass

**Comment by ZeroMemes** [comment]
Added in 4.4
