### ISSUE TITLE
Scaffold doesn't replace liquid blocks when placing

### ISSUE THREAD

**Issue by AbstractOG** [ImpactDevelopment/ImpactClient#531]
I cant use the jesus mod on the server im on (2b2t.org) and im making a big platform on the water and want to use scaffold to place the blocks as i walk around but if the blocks are being placed at water level it seems like scaffold will not work. 
- Impact Version: 4.1
- Using Optifine? No
- Enabled mods: Scaffold only
- Operating System: Windows 10 Pro 64-bit

**Comment by VitorISs** [comment]
nice suggestion, but... i don't think impact's scaffold works in AAC.. (currently 2b2t ac)

**Comment by ZeroMemes** [comment]
Fixed in 4.3
