### ISSUE TITLE
NoSlow (Water) doesn't allow the player to swim up.

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#535]
Even if i hold the spacebar, i'm not able to swim up. And when i'm in water, a sound (like the sound when you jump in water) keeps repeating very fast.

<details> <summary>Active modules</summary>

![modules](https://image.prntscr.com/image/yqic9MuRRLihqZvbGiIcHg.png)

</details>
Version: 4.2 for 1.12.2

**Comment by ZeroMemes** [comment]
4.3 released, bumping to 4.4.

**Comment by VitorISs** [comment]
ops

**Comment by ZeroMemes** [comment]
Fixed in 4.4
