### ISSUE TITLE
Jesus (flowing) doesn't work properly.

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#536]
When the option is enabled, i can't walk further than 1 flowing water block without sink in water.
And when the option isn't enabled, if i step in a flowing water block, i start to bounce in water, even if i go back to a standing water block.. and  if i try to get out of the water and step in a solid block, i take some damage.

**Comment by ZeroMemes** [comment]
Fixed in 4.4

**Comment by VitorISs** [comment]
YEEEEE
