### ISSUE TITLE
The Alt GUI is affected by entity render mods

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#540]
Since `63a6dc "Fix entity shadows in chams and shader esp"` (4.3 commit) having chams enabled crashes the Alt manager. Luckily this didn't make it into the 4.2 release, however it shows that the **player model rendered within the GUI is affected by render mods** when it probably shouldn't be.

**Comment by ZeroMemes** [comment]
The player model was only affected because the chams hooks into the entity render method, I've fixed this in 4.3.
