### ISSUE TITLE
ClickGui should force windows to remain on-screen.

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#547]
If you resize the game window, ClickGUI windows can end up unreachable, because the windows keeps their positioning even if they don't appear on the screen.
Making the windows remain on-screen would avoid problems and would make easier to use the ClickGUI.

**Comment by LeafHacker** [comment]
Looks like we already limit the height of each window to not overflow, we just need to also do this for the position.

**Comment by LeafHacker** [comment]
Added in 4.3
