### ISSUE TITLE
ClickCycler doesn't render the tooltip

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#549]
Despite calling the tooltip method, it doesn't get drawn for multi value cyclers... Likely either an issue with checking if the mouse is inside<sup>[1]</sup> or an early return I missed in the ClickCycler render method.

<sup>[1]</sup> The tooltip timer gets reset whether the mouse isn't inside

**Comment by ZeroMemes** [comment]
Caused by the description not being set in the first place. Fixed in 4.3.
