### ISSUE TITLE
Tracers glitch out when you are close to someone

### ISSUE THREAD

**Issue by TFall** [ImpactDevelopment/ImpactClient#55]
[video demonstration](https://i.gyazo.com/e675514ee0552d6e9cf8c7f8e3b59142.mp4)

**Comment by ZeroMemes** [comment]
Still unable to find a solution.

**Comment by leijurv** [comment]
Fixed :sunglasses:

**Comment by usereewrjrjeejr** [comment]
took you long enough

**Comment by ZeroMemes** [comment]
LOL
