### ISSUE TITLE
Movement speed widget for HUD

### ISSUE THREAD

**Issue by BradleyCrazy** [ImpactDevelopment/ImpactClient#554]
Add A Module That Shows The Speed Of The Player. It Will Help People Find The Best Horse ect. 

- Bradley

**Comment by SuperOP535** [comment]
Very Nice Suggestion You Got There

**Comment by VitorISs** [comment]
just like:
![speed](https://user-images.githubusercontent.com/30983029/39273743-0d5a6c8e-48b6-11e8-8c16-5ae12919a76c.png)

**Comment by SuperOP535** [comment]
what? i would prefer blocks per second

**Comment by VitorISs** [comment]
its just an example.. it could be like "3.0Bp/s" (blocks per second)

**Comment by 0-x-2-2** [comment]
24km/h would be 6.66667m/s aka b/s

**Comment by BradleyCrazy** [comment]
Do Both Speed Of The Horse And The Player
-Bradley

**Comment by ZeroMemes** [comment]
Added in 4.3. You will have the ability to change the distance unit and the time unit (Default is m/s).

**Comment by VitorISs** [comment]
nice :D

**Comment by BradleyCrazy** [comment]
Thanks 👍👍👍
