### ISSUE TITLE
New chunks module

### ISSUE THREAD

**Issue by BradleyCrazy** [ImpactDevelopment/ImpactClient#555]
Shows Unloaded Chunks

-Bradley

**Comment by SuperOP535** [comment]
Explain more please

**Comment by ZeroMemes** [comment]
Please elaborate on the functionality @BradleyCrazy

**Comment by BradleyCrazy** [comment]
On Future There Is A Module That Highlights New Chunks In Your Render Distance. The Chunks Have A Red 
Outline At The Bottom Of The Chunk. It Just Shows The Chunks That Haven't Been Loaded. 
-Bradley

**Comment by LordQuadrato** [comment]
**Note:** It only highlights chunks that are generated _the first time_ (they have never been generated before, also not by the server). It is useful for basefinding, as you can rule out some directions.

**Comment by gwsm1992** [comment]
Yeah its not an unloaded chunk module. It detects chunks loaded for the first time. It can be used on servers to find bases and such, based on detecting if someone has been somewhere before.

**Comment by GlitchHead** [comment]
The ability to save new chunks generated by your player to file per server would help avoid getting your new chunks confused with the player you are tracking.

**Comment by leijurv** [comment]
Added in 65b058c69771727d3a55cfddfed23d8e7b6facd2

**Comment by 9ineOff** [comment]
I hope its also an options to better see previously loaded chunks for various application that could be quite useful...

**Comment by SylveonBottle** [comment]
I just realized that this could totally be used to literally follow someone who ran off in a far off direction in most servers.

What's the visual on this? Can there be a sorta wall/border between old/new chunks so that we know where the borders of the old chunks are - so that we can stay within the orders if we're trailing somebody?

**Comment by ZeroMemes** [comment]
@SylveonBottle Yeah that's why there's "high demand" for it. It only works on Spigot servers though AFAIK

**Comment by leijurv** [comment]
@ZeroMemes close since added in 4.5?

**Comment by ZeroMemes** [comment]
A method of highlighting new chunks has technically not been added yet, just the code to discover new ones.

**Comment by leijurv** [comment]
unepic wtf

**Comment by ZeroMemes** [comment]
Added in 4.5
