### ISSUE TITLE
Friend system for Minestrike module 

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactClient#556]
Have a friend mode for Minestrike module where targeting doesn't target anyone added to friends either separate from normal friends list or normal friends list or option to choose either or or both.
Lets you still damage them if you manually click to shoot or knife.

### Additional Client Info
- Impact Version: 4.2
- Using Optifine? <No
- Enabled mods: 
- Operating System: Windows 10 64bit

**Comment by ZeroMemes** [comment]
Added in 4.3
