### ISSUE TITLE
NoFall Bucket should implement cobweb module

### ISSUE THREAD

**Issue by MightyKnight** [ImpactDevelopment/ImpactClient#557]
### The problem
NoFall Bucket needs an extension:
1. Using Nofall Bucket in **the nether** will **not** work (of course, because the water would evaporate immediately). This renders the module kind of useless for survival gameplay.
2. Use of water buckets may be **restricted** on some servers or the player needs an alternative because he has **no access** to/doesn't want to use water buckets.

### Suggestion to fix
>As demonstrated [in this video](https://www.youtube.com/watch?v=Mi1BYLoYDQk), a player is able to cancel his fall damage by **placing a cobweb** right before landing on the ground. I tested this in the current minecraft version (1.12.2) and it still works as expected.

I suggest adding this as an option to the `NoFall Bucket Module` (Note: Not as a seperate module):
- Option to activate/deactivate both buckets and cobwebs
- in case both are enabled **water buckets are preferred** over cobwebs, but if no buckets are available anymore, the cobwebs should be used

### Further improvement
Some blocks (beds, soulsand and haybales) reduce damage from falling by a significant amount. They could also be added to this module.

**Comment by Thunder33345** [comment]
dont forget lava too!!!
we should have a absorption type(water lava haybales things that absorb the fall without bouncing you back) and a bounce negate type(slime, bed that bounces you up to netage it)
while these are suboptimal these are better than melting your water bucket

**Comment by ZeroMemes** [comment]
Added in 4.4.

As for the lava bucket and other fall damage reduction blocks, I'll consider them and keep it updated in this thread as well as on the [changelog](https://github.com/ImpactDevelopment/Resources/blob/master/data/changelog.md).
