### ISSUE TITLE
Improvements for Log Position

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#558]
### Better Log Position Module
* _Currently Log Position doesn't really log (save in a file) the position a player logged out._
I would like to see something similar to "Save Coords" in the Respawn module, propably called "Save Log Position". It should save **`time, playername and coords`**.
* _If you didn't see a player logging out, you may find yourself unable to find out which player it was_.
I suggest that the name of the player should be **drawn above the log out marker when hovering** over it.

Should be really simple, i would love to see this in 4.3 already  :smile:

**Comment by Thunder33345** [comment]
i suggest in verbose players seen locations optionally logged when seen and before unseen

**Comment by ZeroMemes** [comment]
Just added a save option in 4.3. Positions are stored in json format as follows
```js
{
  "name": "Player",
  "uuid": "a8c03d12-ecc6-4a41-bde9-34436e342e1b",
  "time": "2018-05-03 09:46:50",
  "pos": {
    "x": 1232,
    "y": 76,
    "z": 943
  }
}
```

**Comment by LordQuadrato** [comment]
Wow, thanks. I'll like it. Keep up the good work  :smile:  :+1:

**Comment by ZeroMemes** [comment]
Just added an option to label logout positions that show the username and the time since logout.

**Comment by ZeroMemes** [comment]
![example photo](https://i.imgur.com/UiR1kPI.png)

**Comment by VitorISs** [comment]
awesome :ok_hand: :joy:

**Comment by LeafHacker** [comment]
Should probably also log which server/world they logged off of

**Comment by LordQuadrato** [comment]
@LeafHacker That would be nice to have, possibly for 4.3 already. Are you just going to reopen this issue or should i create a new one?

@ZeroMemes I really like that the positions are stored in `json`, as it allows quick access and I can make my own log position viewer for the file really easy  👍
