### ISSUE TITLE
Alt manager Bugs

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactClient#560]
### What happens?
https://gyazo.com/7b7e6fce5273aa79d4258cf7aea875e1
https://gyazo.com/1e5a6b89fe23c09f3dd0d1fa4d8c3a63
All the emails and everything is off center. When logged into an account it sometimes shows the skin but most of the time doesn't. Also when it does show the skin and you log onto another account the skin doesn't update. The logged in alts that show usernames after there log in worked doesn't save after you close impact and re open it up.

### Game output?

```

```

### Crash report?

```

```

### Additional Client Info
- Impact Version: 4.2
- Using Optifine? No
- Enabled mods: 
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
This issue is covering multiple topics (4?). I will move the screenshots of misaligned text over to #577 as that issue is more specific. Please open separate bug reports so we can properly track each issue, thanks!
