### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactClient#562]
Few features in here would be nice:
1. Mineplex flight whether it bypasses or just able to use it long enough to not get kicked within x amount of seconds. I've done experimenting with their anti-cheat and it seems the flight checks are the old 3.8 NCP flight checks for when 1.8 just came out as how I'm able to fly up 1-2 blocks sometimes, and how any non full block I can fly up and down without any kick or flagging.
2. A Mineplex step with adjustable block height values(I know there is a high jump in the client but it works at a max of 1.15 blocks). I've used metros newest and been able to step up to ~15 blocks without a kick or flagging. 
3. Mineplex blink that lets you go farther distances than current one. You are able to blink as far as your render distance moves but once you toggle off it only moves you a max of 10 blocks give or take without a kick or flag. It would be nicer if it could move maybe 20 or 30 or just more than it can move current. 
4. Antibot update GWEN. Antibot sometimes masks players or doesn't render them in when they respawn in a game like cake wars making the player invisible to you and only killaura set to hit invisibles able to hit them but at times also hitting gwen bots causing you to be flagged by gwen and banned wave.

### Additional Client Info
- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System:

**Comment by zPeanut** [comment]
please make a seperate issue for everything
