### ISSUE TITLE
Bug: Weird freecam behaviour while on rideable entity

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#563]
### What happens?
`Freecam `will **not dismount** the fake player from ridden entity if activated. This leads to several issues:
- The player is able to control the entity
- Pressing sneak (to dismount) while in freecam will dismount the actual player entity too

### When does this happen?
When using `Freecam `while riding an entity (e.g. horse, minecart, pig, boat...)

#### First Problem
**1.** Hop onto a horse (or another rideable entity)
**2.** Activate your `Freecam`
**3.** You'll notice that you are able to control the horse even though you are in `Freecam `mode
**4.** Move (while in `Freecam `and on the horse) to another location that you can clearly distinguish from the spot you activated the module.
**5.** Turn off freecam
 :arrow_right: You'll end up in the place you deactivated it (teleportation?)
#### Second Problem
Repeat steps 1 and 2 from above. Then press your sneak control (`c`by deafult). Now deactivate `Freecam`.
 :arrow_right: You'll end up dismounted

### Additional Client Info
- Impact Version: 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Freecam (default)
- Operating System: Windows 10 64-bit

**Comment by SuperOP535** [comment]
This bug is old and I like it lol

**Comment by LeafHacker** [comment]
[Fixed in 4.3](https://youtu.be/ZxsDVKc55FQ)
