### ISSUE TITLE
Bug: Lava overlay option not dependent on Anti Overlay module

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#564]
### What happens?
Even though **Anti Overlay** is disabled, the lava overlay is still not being rendered.
The `Lava` toggle in Anti Overlay affects gameplay even if the module is disabled.

![2018-04-27_23 17 34](https://user-images.githubusercontent.com/38622942/39385760-1375e5d6-4a72-11e8-9db0-e8fb92a8de1a.png)

Notice: No modules are enabled in both pictures

![2018-04-27_23 17 41](https://user-images.githubusercontent.com/38622942/39385759-1350f9c4-4a72-11e8-8a00-b5943c92f96e.png)

### When does this happen?
When I jump into lava with all modules disabled.

### Exact steps to reproduce?
1. Deactivate all modules, but make sure, that for Anti Overlay the `Lava` option is checked.
2. Jump into lava and watch how you can see everything clearly
3. Uncheck the `Lava` option (without enabling the module) and the lava overlay will be rendered

This does not affect other overlays, only lava

### Additional Client Info
- Impact Version: 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Nothing
- Operating System: Windows 10 64bit

**Comment by ZeroMemes** [comment]
Fixed in 4.3
