### ISSUE TITLE
Coords not shown

### ISSUE THREAD

**Issue by AbstractOG** [ImpactDevelopment/ImpactClient#565]
the coords mod in the hub mod show the over world coords in the overworld but not the nether coords but in the nether it shows both nether and over world coords can you make it so you can see the nether coords while you are in the over world? please and thank you 

### Additional Client Info
- Impact Version: impact 4.2 for 1.12.2
- Using Optifine? not that i know of
- Enabled mods: Hud
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
Literally the same guy from the first issue :-1:
