### ISSUE TITLE
Bug: False positives when playing Murder Mystery on Hypixel

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#567]
### What happens?
Players are marked as the murderer even though they aren't.

### When does this happen?
When i play Murder Mystery on Hypixel. The bug only occurs in a specific map: Mountain Map. You are able to buy wooden shovels on this map from an npc.

### Exact steps to reproduce?
1. Join on the Hypixel Server (hypixel.net)
2. Activate Murder module
3. Join a Murder Mystery game on the Mountain Map
4. Watch how people holding a wooden shovel are marked red

![false positive](https://user-images.githubusercontent.com/38622942/39407409-0a6c8b84-4bc6-11e8-8bbc-5ad554d8bb4d.png)

### Proposed fix
The murderer is propably marked red if he holds a sword or a knife skin.
But a wooden shovel is **not** a knife skin, as shown in the picture below (all knife skins currently available).
_Fix schould be as easy: Only mark the murderer if he is wielding one of these skins_
![knife skins](https://user-images.githubusercontent.com/38622942/39407439-66a0e1a2-4bc6-11e8-86f9-ac7519c6c9e2.png)

### Additional Client Info
- Impact Version: 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Murder (Hypixel Mode)
- Operating System: Windows 10 64bit

Btw thanks for the fast and good support. I really love your client and i consider donating soon :wink:

**Comment by LeafHacker** [comment]
I've implemented your suggestion (untested) for hypixel in 4.3. However there's still a few suspicious bits sticking around in the code:

- On MCPZ any material Hoe is considered a gun
- On MCPZ and PlayMCM any material Sword is considered a knife
  - (PlayMCM also considers Eye of Ender a knife)

Would be appreciated if more specific items could be found for those cases too.

Assigned @ZeroMemes for testing/checking other modes.

**Comment by ZeroMemes** [comment]
Just reviewed the PlayMCM items and fixed them accordingly. The MCPZ ones look fine.

**Comment by ZeroMemes** [comment]
Tested the new changes to Hypixel murder weapon definitions, works as expected, closing.
