### ISSUE TITLE
Enable Scaffold to use blocks held in the offhand

### ISSUE THREAD

**Issue by LordQuadrato** [ImpactDevelopment/ImpactClient#568]
### What happens?
When you have blocks in your offhand slot, scaffold won't place them. As soon as you switch them back into the hotbar it works again.

### Exact steps to reproduce?
1. Put some blocks into your Offhand slot
2. Activate scaffold
-> No blocks are being placed

### Additional Client Info
- Impact Version: 4.2 for 1.12.2
- Using Optifine? No
- Enabled mods: Scaffold
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
Reworded as a feature since afaik this is not a bug, it's simply not implemented yet

**Comment by VitorISs** [comment]
i accidently added the BUG label lol

**Comment by ZeroMemes** [comment]
Added in 4.3 as well as an option to prioritize the offhand over the hotbar.
