### ISSUE TITLE
Font Utilities

### ISSUE THREAD

**Issue by gwsm1992** [ImpactDevelopment/ImpactClient#570]
This is another new feature that would be cool.

I have seen it on a bunch of multiplayer servers. People are chatting, then that one person comes on and their font is totally different from everyone else's. Basically, all this does is make a letter look different from the default minecraft font when it gets typed into a multiplayer game. It in a lot of different hacked clients. Not sure if its in Wurst, but I know its in Future.

**Comment by LeafHacker** [comment]
Pretty sure this is just people using the alternative Latin charsets in unicode (e.g. small caps, full width). Not really related to fonts other than that the default font probably doesn't have them, so it falls back to an alternative font. You could probably do this in vanilla using an online text converter and copy-paste

**Comment by zPeanut** [comment]
i mean why not

**Comment by ZeroMemes** [comment]
Added in 4.4 as **Fancy Chat**

There are 3 modes at the moment: **Full Width**, **Parenthesis**, and **Circle**, which are displayed below.

![An example image](https://i.imgur.com/hrqK4BG.png)
