### ISSUE TITLE
Spammer

### ISSUE THREAD

**Issue by gwsm1992** [ImpactDevelopment/ImpactClient#571]
And my last feature idea: Spammer

Every once in a while, one gets the urge to be a troll. I get that urge every once in a while. Wurst has a spammer feature just for that. You set up a file before hand that contains all the text that you want to post and the client then automatically posts one line of text every so often, pre-determined by the length of a pause before posting. Sometimes I will play the text from Lord of the Rings. I have seen people play Sherlock Holmes as well.

The Wurst one has its own file format for text to be posted. Future just uses .txt documents. This has no real use other than being a troll, but isn't that part of what hacked clients are about?

**Comment by LordQuadrato** [comment]
**Impact already has Spammer as a feature.**
Use `.spam setup` to set the delay and add messages.
The spammer even supports multiple configurations by id.
To start the spammer use `.spam set <id>` and then `.spam start` (to stop `.spam stop`)

_But sadly it uses a JSON-File, so you can't just copy/paste some text from the internet. Maybe I'll open a seperate issue for that. The spammer feature needs improvements!_

**Comment by gwsm1992** [comment]
Huh cool. I didn't know that. Yeah it would be easier to be able to copy something from the internet and do it that way

**Comment by VitorISs** [comment]
#158 already added to the client
