### ISSUE TITLE
Alt Manager Ingame, Scaling Bad

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#575]
![javaw_2018-04-30_13-52-47](https://user-images.githubusercontent.com/25800857/39425909-e433ac32-4c7d-11e8-8b19-882b5bb098d2.png)

basically the picture says anything

**Comment by LeafHacker** [comment]
Looks as intended to me. The width is fixed and shouldn't scale.

**Comment by SuperOP535** [comment]
ugly

**Comment by LeafHacker** [comment]
the transparent background looks odd next to the non-transparent gui, maybe that will sort it. There's not much that can be done about the width, other than finding a compromise that looks good at all scales. You'll notice all mc GUIs have a fixed width.

**Comment by LeafHacker** [comment]
better? (still ingame, just now it isn't transparent)

![image](https://user-images.githubusercontent.com/23565638/39454977-0f7cc790-4cd6-11e8-8a05-ed0761fe600e.png)
