### ISSUE TITLE
Bug: Soup completely broken

### ISSUE THREAD

**Issue by MightyKnight** [ImpactDevelopment/ImpactClient#580]
### What happens?
- A soup is trying to be consumed even though your health is alright
- Your selection is **locked** to a soup and you can't hold any other item (like a sword),
sometimes it will switch between two soups
- You **can't deactivate** Soup without a client restart

### When does this happen?
When I activate/deactivate Soup mod.
Happens on single- and multiplayer, both in Vanilla and with the serverside soup addition.

### Exact steps to reproduce?
1. Get a few soups and make sure to have full health
2. Try to activate Soup mod **->** Notice weird switching
That means you can't switch to any other item as long as you have soups in your inventory. It tries to eat soups but can't
3. Try to deactivate the module **->** Will not get deactivated

### Additional Client Info
- Impact Version: 4.2 for 1,12,2
- Using Optifine? No
- Enabled mods: `Soup` (Health: 7.0 | Speed 60 | Random 20)
- Operating System: Windows 10 64bit

**Comment by SuperOP535** [comment]
last time i used soup it was like u bind it to something and when u press that button it eats soup

**Comment by LeafHacker** [comment]
Intended behaviour.

When enabled, Soup checks the hotbar for soup; if found, it switches to it and drinks it; if no soup is found, if health is above the threshold or if it has finished drinking, it disables itself ready to be used again later.

**Comment by LordQuadrato** [comment]
The problem is that it tries to eat a soup even if my health is **above the treshold** and it **can't be turned off** so I need to restart the whole client to allow me to use any other item _(because it aways switches to soups)_

**Comment by LeafHacker** [comment]
My bad, didn't read through thoroughly enough after seeing @SuperOP535's comment.

**Comment by ZeroMemes** [comment]
Functions as expected.
