### ISSUE TITLE
EntitySpeed doesnt work on boats.

### ISSUE THREAD

**Issue by Gastlt** [ImpactDevelopment/ImpactClient#581]
When I try to use EntitySpeed to go faster on a boat, nothing happens

**Comment by babbaj** [comment]
Seems to work fine on my machine?
I just get in a boat and turn it on and i go zoom zoom

**Comment by LeafHacker** [comment]
babbaj using forgehax?

**Comment by ZeroMemes** [comment]
Fixed in 4.3
