### ISSUE TITLE
NoPush hack.

### ISSUE THREAD

**Issue by TheCookCola** [ImpactDevelopment/ImpactClient#585]
The NoPush disables when I join the game.

### What happens?
Every time that I join Minecraft, the NoPush disables itself.

### When does this happen?
Every time I open Minecraft.

### Exact steps to reproduce?

  Toggle on NoPush
  Quit Minecraft
  Rejoin Minecraft
   No Push is disabled

**Comment by VitorISs** [comment]
duplicate of #258 
already fixed in 4.2
