### ISSUE TITLE
Bug: Disconnect times.

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactClient#587]
### Exact steps to reproduce?

- Log on to a server e.g Mineplex
- Go to Minestrike game mode
- leave using /hub or clock
- you lag out and disconnect
- Tends to happen a lot with server resource packs game modes

 

- Impact Version: 4.2
- Using Optifine? No
- Enabled mods: Tried with no mods on
- Operating System: Windows 10 64bit

**Comment by ZeroMemes** [comment]
This isn't a client issue, this is caused by the game taking too long to change resource packs and therefore the connection between the client and server times out.

**Comment by Pabsb** [comment]
@ZeroMemes This is the only client that causes it to happen. Default MC 12.2.2, 12.2.1, 11.1.2, 10.x.x, 9.x.x, 1.8.9, 1.8.8, 1.8 all work perfectly fine with no problems with that
