### ISSUE TITLE
Xray and Freecam freeze

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactClient#588]
### What happens?
When toggling off Freecam or Xray the client freezes for a few seconds

### Exact steps to reproduce?

- Log onto a server or single player
- toggle xray or freecam
- Toggle off
 

- Impact Version: 4.2
- Using Optifine? No
- Enabled mods: Only the one toggled
- Operating System: Windows 10 64bit

**Comment by LeafHacker** [comment]
@ZeroMemes is this wontfix or is there stuff we could move to a new thread? Assuming this is some kind of synchronous loading issue.

**Comment by LeafHacker** [comment]
Closing due to age, inactivity and the fact that it (kinda) covers multiple topics.
