### ISSUE TITLE
Click gui compressed

### ISSUE THREAD

**Issue by CJGlitter** [ImpactDevelopment/ImpactClient#592]
### What happens?

The click interface menus are compressed beyond the possibility of use.
Screenshot: 
<img width="1280" alt="screen shot 2018-05-20 at 7 06 08 pm" src="https://user-images.githubusercontent.com/39471344/40285450-b1da1a98-5c61-11e8-986d-d0eda1afe94a.png">

### Exact steps to reproduce?
I just open the interface and it is too squished to use.
Screenshot attached.
<details>

- Impact Version: 4.2 for 1.12.2
- Operating System: macOS Sierra 10.12.4
</details>

**Comment by ZeroMemes** [comment]
Opening and closing the panel fixes it. We're working on a fix.

**Comment by CJGlitter** [comment]
@ZeroMemes thanks!  How do I open and close the panels?

**Comment by LeafHacker** [comment]
Fixed in 4.3
