### ISSUE TITLE
Suggestion:Freecam Chest Viewer

### ISSUE THREAD

**Issue by MNLegoBoy** [ImpactDevelopment/ImpactClient#595]
Suggestion: Make it so when you are in freecam you could see the insides of chests, but not be able to take the items out or interact with them

**Comment by LeafHacker** [comment]
Have you tried doing this? Currently there should be nothing in our code preventing you from interacting with chests. You should even be able to move items in and out.

The only potential problem is servers/anticheats preventing interaction with blocks you aren't looking at/close enough to.

**Comment by MNLegoBoy** [comment]
Also this might be a thing but i still use 4.1 and it isn't there

**Comment by 0-x-2-2** [comment]
You can't see whats inside of chests till you open them what you are asking is not possible.

**Comment by Pabsb** [comment]
@LeafHacker He wants to be able to see in any chest that is rendered in for him regardless of how close he is to it

**Comment by 0-x-2-2** [comment]
Indeed this is not possible

**Comment by MNLegoBoy** [comment]
So i wanted something like the Chest Previewer mod, but as a hack for in free cam to see the contents of a chest like this https://www.youtube.com/watch?time_continue=53&v=JzaO7toizhY

**Comment by Thunder33345** [comment]
you will need to open the chest to be able to "preview" the chest content
and the content wont be updated until it's open again

**Comment by LeafHacker** [comment]
The server will not let you open chests out of a certain range. You cannot view the content of a chest without opening it. Therefore it is impossible to have any mod show you the content of a chest while in freecam without also modifying the server.
