### ISSUE TITLE
Always Crit Doesnt Seem To Hit Half The Time

### ISSUE THREAD

**Issue by JadonZufall** [ImpactDevelopment/ImpactClient#599]
The always crit option doesn't seem to really help,  It only works when jumping you don't get the sweeping edge effect (I think that applys to crits in general though) and half the time it doesnt even hit also you have to be jumping for it to do any damage otherwise you just get the effects and nothing happens although to be fair I play on a low tps server and that may be part of the problem but when testing this the tps was 20 so I am not sure.  Kill aura seems to help and I hit half of my hits with that enabled but still not all of them even when it obviously clicked on them

**Comment by LeafHacker** [comment]
@JadonZufall why was this closed?
