### ISSUE TITLE
Outline Chest ESP causes chests lids to become invisible

### ISSUE THREAD

**Issue by Chzconey** [ImpactDevelopment/ImpactClient#6]
The Chests in my game don't have tops to them.

**Comment by ZeroMemes** [comment]
Issue identified - Outline Chest ESP
Solution not yet found.

**Comment by Chzconey** [comment]
K hopefully 3.1 has a fix for it.

**Comment by TheForgottenKing** [comment]
Doesn't happen for me. Whats your system spec?

**Comment by ZeroMemes** [comment]
Outline chest ESP has been removed in 4.0 until further notice.

**Comment by LeafHacker** [comment]
Closing as invalid because Outline ESP was removed in 4.0
