### ISSUE TITLE
Elytra+ prevents water from removing kinetic energy

### ISSUE THREAD

**Issue by lmaolmao123123** [ImpactDevelopment/ImpactClient#60]
I just almost died crashing into WATER with an ELYTRA while using ELYTRA+ on VANILLA... Rip..

**Comment by MagicSenpai** [comment]
OMG SAME!?!?!?!?!?!?!?1

**Comment by MagicSenpai** [comment]
BUT I DID DIE

**Comment by LeafHacker** [comment]
Can't reproduce. Pretty sure moderator oli and magic are spamming...............

Closing for now

**Comment by LeafHacker** [comment]
Managed to reproduce by flying into stone at a funny angle through the edge of water with elytra+.
