### ISSUE TITLE
ClickGUI tooltip is ugly

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#602]
![tooltip](https://cdn.discordapp.com/attachments/208753003996512258/451091049822289920/unknown.png)

Fix plz

**Comment by 9ineOff** [comment]
- Optional ability to change font

**Comment by LeafHacker** [comment]
> Optional ability to change font

There's not going to be a font setting just for tooltips, lol. It should be using the same font as ClickGUI, which currently is the same font we use for almost all non-vanilla text and isn't configurable. If you want custom fonts open/look for an issue specific to that.



> line break support

Not related to the aestetics of tooltips (this issue), however explicit line-break support has been added (not automagic line wrapping).

**Comment by LeafHacker** [comment]
Increased the background padding and the distance from the mouse while working on line break support, seems to have made a big difference so far.

**Comment by LeafHacker** [comment]
I'm closing this since 1. it's kinda vague and 2. tweaking the padding has improved the situation.
