### ISSUE TITLE
StorageESP Color change / RGB Slider option

### ISSUE THREAD

**Issue by JellyDonut6** [ImpactDevelopment/ImpactClient#606]
The current default colors for StorageESP are really hard to see, especially in certain biomes.

Boating in the ocean? You probably wont see that default blue.
Even a couple blocks away, you still have to "look" for the chest.
[Examples](https://imgur.com/a/wtXOoBv)

I'd like to be able to change the colors of certain chests with an RGB slider option or something similar

**Comment by ZeroMemes** [comment]
iirc this was added in 4.5
