### ISSUE TITLE
 "Only shoot while sneaking (sniper)" option for MineStrike

### ISSUE THREAD

**Issue by randonoob** [ImpactDevelopment/ImpactClient#612]
This is a suggestion for a possible and likely easy addition to the Minestrike module.

There is a glitch where if you activate the "Sneak" module while holding a scoped weapon in Minestrike (e.g. AWP, SSG 08, or Steyr Aug) where the scope will be stuck on you. I have tried this with a macro and found the issue to be server side, which is no matter because the glitch is good. It essentially allows for easier and more accurate Sniper shots, as previously, you would have to scope for the snipers to be accurate. Not having to scope is an enormous help.

However, in Impact, by default, the snipers (AWP and SSG 08) only fire if you are crouching with them. This is to prevent inaccurate shots with them I presume, something useful if you aren't using the scope glitch. However, if you are, the weapon won't auto-fire/auto-aim. I'm guessing that the trigger or precondition for an SSG 08 or AWP to be used with the aimbot is only if you are sneaking with them. 

My suggestion is to make an "Only shoot while sneaking (sniper))" option or something of the like for the Minestrike module. This way, if you want to play without the scope glitch, you won't randomly fire when you aren't crouching/scoped, which is useful. However, when using the scope glitch, I have to manually aim, which is annoying. That is why I suggest this idea. I profess to know in no way how impact works, but if the precondition to use the aimbot with awp/ssg08 is to crouch before you fire, I feel like this could be a potentially easy thing to add.

Thank you very much for your time and consideration.

**Comment by ZeroMemes** [comment]
Added in 4.3

**Comment by SuperOP535** [comment]
in 4.3, added

**Comment by Pabsb** [comment]
@ZeroMemes @LeafHacker @SuperOP535 Put an option to toggle it on and off. As I know many people like having the scope stay on as you don't need to shift to aim and can run sprint with perfect aim.

**Comment by Pabsb** [comment]
@randonoob Only person I ever met that doesn't like this. Easily can fix it by buying a helm in spawn or dying.

**Comment by ZeroMemes** [comment]
@Pabsb I've made it toggleable don't worry toggleable don't worry
