### ISSUE TITLE
Gapple Health

### ISSUE THREAD

**Issue by Gastlt** [ImpactDevelopment/ImpactClient#613]
It would be very useful for the "Nametag" mod to display the extra health  you get from golden apples instead of "20". so you can see the total health of your enemies instead of the cap of "20"

**Comment by LeafHacker** [comment]
This is actually a bug, as @ZeroMemes [seemed to think](https://github.com/ImpactDevelopment/ImpactClient/issues/267#issuecomment-338852019) this was already working (at least in 4.1).

This is [already fixed](https://github.com/ImpactDevelopment/ImpactClient/issues/267#issuecomment-394123527) in [4.3](https://github.com/ImpactDevelopment/Resources/blob/master/data/changelog.md)
