### ISSUE TITLE
Hidden Impact folder in .minecraft, or name change, or way to put it somewhere else and have client find it.

### ISSUE THREAD

**Issue by 110Hacking** [ImpactDevelopment/ImpactClient#614]
Suggestion to have a way to hide client completely if being screen shared and going through .minecraft folder. Maybe either hide it in resource pack folder, or have an option in client to find configs somewhere else on computer.

**Comment by LeafHacker** [comment]
The only viable option I can see is a cli argument, since you obviously can't save it to a config file. Something like `-ImpactConfig "%appdata%\Impact"`

**Comment by 110Hacking** [comment]
Is that something I can do fairly easy on my side, short cut to the folder? Or does it need to be coded by you guys.

**Comment by ZeroMemes** [comment]
We'll need to implement it so that it accepts the CLI argument.

**Comment by leijurv** [comment]
If they go through your minecraft folder then they can see your versions/Impact where the CLI argument would go.

Change your minecraft directory or use multimc tbh. There's no possible way to hide Impact if they are looking through the minecraft dir, moving the main Impact folder is just a surface level band aid, versions & libraries will always be there.

**Comment by 0-x-2-2** [comment]
>multimc 
🤡
