### ISSUE TITLE
SmoothAim makes you aim the complete opposite direction

### ISSUE THREAD

**Issue by 110Hacking** [ImpactDevelopment/ImpactClient#615]
On 1.12.2 servers and on Hypixel, the smooth aim makes me aim 180 degrees from where the player is. Can send video if need be, but Brady's video on 4.3 looked nice and not buggy.

**Comment by SuperOP535** [comment]
Probably a bot, try to mess with antibot and target stuff

**Comment by ZeroMemes** [comment]
Forgot that this issue has been solved in 4.3, Closing.
