### ISSUE TITLE
.spam suggestion

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#621]
.spam ["message"] [amount of messages] [delay between messages in seconds]
.spam stop

Would spam the message in chat with random numbers/characters at the start/end to bypass chat filters. 
Quotation marks for message just in case if message would contain a number.

**Comment by LordQuadrato** [comment]
#158 already added to the client.
If you propose a change to how the spammer system currently works, please elaborate and change your report accordingly.
