### ISSUE TITLE
[Feature Request] Boost and Packet Elytra+ Mode

### ISSUE THREAD

**Issue by TheForgottenKing** [ImpactDevelopment/ImpactClient#622]
Looking at Future Client, they have a nice Elytra+ mode where pressing space increases elytra velocity, and a packet mode which allows for standing flight. Obviously hard to implement but it would be nice. Thanks Daddy Brady

**Comment by SuperOP535** [comment]
Braddy Dady

**Comment by LeafHacker** [comment]
This looks like a duplicate of #133 and #108. If you have any further comments related to those, please make them there. Any different suggestions please make clear and separate issues.

**Comment by TheForgottenKing** [comment]
Sort of, Future has a mode where pressing space increases speed in whatever direction, similar to Impact's but instead of pressing W moving the player at a constant rate, pressing space increases speed. I will try to upload a video Soom™

**Comment by LeafHacker** [comment]
As above, please make any additional suggestions in their own issue. Or on the relevant feature request if your suggestion applies to a feature yet to be added.
