### ISSUE TITLE
Suggestion: Mob Nametags, Item Nametags, & X-Ray Brightness

### ISSUE THREAD

**Issue by UnidentifiedFuzzy** [ImpactDevelopment/ImpactClient#623]
#### Mob Nametags
Mob Nametags would be extremely helpful in picking out specific mobs to attack. With these nametags, one would be able to see mobs' armor and the enchantments on it, similar to the player Nametags mod. Another application for this mod would be in servers with plugins such as [MythicDrops](https://www.spigotmc.org/resources/mythicdrops.5649/) , which allow mobs to spawn with enchanted armor and tools. (Creepers, Witches, and Spiders carry items, even though they don't show up in game). 
#### Item Nametags
When mining, it would be very useful to see item drops from a distance. It is hard to see specific items at a distance. If items were given simple nametags, it would be very helpful. (If you can enable color on the nametags for item names with color, please do!)
#### X-ray Brightness
I noticed that when using X-ray, the blocks are dimmed. Enabling Light does help, but it does not light up the blocks entirely. Not quite sure if it is something I don't have toggled, but after an hour of searching, I'm stumped. I recommend that X-ray be brighter, or for Light to have a brightness slider.

Thank you for what you already have!
(I support adding macros back into the client)

**Comment by ZeroMemes** [comment]
Please create separate issues for each suggestion.
