### ISSUE TITLE
Suggestion: Item Nametags

### ISSUE THREAD

**Issue by UnidentifiedFuzzy** [ImpactDevelopment/ImpactClient#625]
When mining, it would be very useful to see item drops from a distance. It is hard to see specific items at a distance. If items were given simple nametags, it would be very helpful. (If you can enable color on the nametags for item names with color, please do!)

**Comment by LordQuadrato** [comment]
Could go hand in hand with a seperate ItemESP (e.g. #225), preferably as an option.

**Comment by leijurv** [comment]
Was added in 4.6
