### ISSUE TITLE
ChestESP blocks reading text on signs.

### ISSUE THREAD

**Issue by TheMrPancake** [ImpactDevelopment/ImpactClient#627]
![2018-06-22_19 36 16](https://user-images.githubusercontent.com/40334355/41769984-44bc5c16-7654-11e8-9f1e-224704eff713.png)

**Comment by LordQuadrato** [comment]
Happens either when the ESP blocks are _far away_ from the sign or if _3 or more_ chests are **overlaying** each other when looking at the sign. Easier to reproduce when fade option is off.

**Comment by LeafHacker** [comment]
Without looking too much into it, one potential "fix" would be to only draw one layer of esp. Not sure if that would look ok or not. May not work well with the Fade option...

Perhaps rendering all esp stuff to an FBO using a depth write/test before drawing the FBO to the screen @ZeroMemes?

**Comment by ZeroMemes** [comment]
If imma be real this is a won’t fix
