### ISSUE TITLE
Freecam vertical speed is too slow

### ISSUE THREAD

**Issue by 12Me21** [ImpactDevelopment/ImpactClient#630]
Freecam moves much faster horizontally than vertically. I assume this is intentional, but I think it would be better if it moved at the same speed in all directions.

**Comment by LeafHacker** [comment]
Perhaps renaming the current `speed` option to `horizontal speed` and adding a `vertical speed` option?

**Comment by Pabsb** [comment]
@LeafHacker He has sprint on which makes horizontal move faster.

@12Me21 Use something like logic next time

**Comment by ZeroMemes** [comment]
Made the change that @LeafHacker proposed. There are now separate options for "Vertical" and "Horizontal" speed.
