### ISSUE TITLE
Triggerbot 1.9+ cooldown

### ISSUE THREAD

**Issue by Dimitriblyater** [ImpactDevelopment/ImpactClient#635]
Hi, please make the triggerbot compatible with MC 1.9+ attack speed

**Comment by LordQuadrato** [comment]
> being able to bind \ to say stuff with a click of a button

Duplicate of  #153

Also, please only report **one** suggestion per issue. I edited your issue to make it valid.

**Comment by LordQuadrato** [comment]
Also an option to synchronize the hit delay with server tps (like in killaura) would be nice.

**Comment by ZeroMemes** [comment]
Added in 4.4.
