### ISSUE TITLE
Keep dying or losing health next to water's edge (where block meets water block)

### ISSUE THREAD

**Issue by prioxis** [ImpactDevelopment/ImpactClient#636]
### What happens?
Anytime I stand on a block/edge of a block next to water I lose health or die instantly, same when standing on lily pads, if you lose health and then try walking to the block again you won't lose anymore health unless you were to run a significant distance away and then run back you would then lose health again.

This will still happen if using jesus as you walk onto water

### Exact steps to reproduce?

- Step on block next to water
- move towards water block
- Die

<details> 
  <summary><strong>Game output</strong></summary>
 

```
"Name" fell from a high place
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.2
- Using Optifine? No
- Enabled mods: None
- Operating System: Windows 10 64bit 

</details>

**Comment by LeafHacker** [comment]
This sounds like a quirk of how AntiHunger behaves on some servers. Are you sure you have no modules enabled?

**Comment by 0-x-2-2** [comment]
Dupe of #242?

**Comment by prioxis** [comment]
you know what it may just be Anti-Hunger and I didn't realize it was still on, this makes sense, thank you.
