### ISSUE TITLE
Unable to download Impact 4.0 for 1.11.2

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#64]
When using the launcher to run 1.11.2-Impact_4.0 I get the following error:

```
Failed to download file. Impact-4.0-1.11.2.jar:

Name: Impact-4.0-1.11.2.jar
URL: https://impactdevelopment.github.io/maven/com/github/Impactdevelopment/Impact/4.0-1.11.2/Impact-4.0-1.11.2.jar
Error details: HTTP 404: 
Filename on disk: e3ba-3edc-db12-ad52
Path: /tmp/e3ba-3edc-db12-ad52
Exists: file
```

The json file is also deleted by the launcher (perhaps in an attempt to remove corrupted versions).

---

This is caused by github-pages' case-sensitive URLs, changing `com.github.Impactdevelopment` to `com.github.ImpactDevelopment` in the json file and then restarting the launcher fixes the issue.

**Comment by LeafHacker** [comment]
Sounds the same as #40 but for 1.11.2 instead of 1.12

**Comment by ZeroMemes** [comment]
Looks like the archive wasn't updated, issue has been fixed!
