### ISSUE TITLE
Suggestion: ToggleTab

### ISSUE THREAD

**Issue by sonothingatall** [ImpactDevelopment/ImpactClient#642]
- ***Current tab menu requires the user to hold the tab button to stay on***
*I would like to see a feature for it to be toggled instead of holding the tab button like the ToggleTab (or the TabToggle, idk) mod.*
*It would be nice to just press tab once and have it on until you press it again.*
*It would save a lot of hassle when you need to read things in tab menu while doing other things.*
**TL;DR: I would like to see a feature where the tab menu stays on until you press tab again.**

Thanks. :)
**EDIT:** To clarify, I don't mean the TabGUI, I mean the [menu which displays all players](https://i.imgur.com/XDSbeDw.png).

**Comment by LeafHacker** [comment]
_goodidea_

**Comment by ZeroMemes** [comment]
Added in 4.4

``.gui toggletab <enable/disable>``
