### ISSUE TITLE
no jar in 4.3???

### ISSUE THREAD

**Issue by Unknown** [ImpactDevelopment/ImpactClient#647]
### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System: 

</details>

brady bait us with fake 4.3 release???? jar when??????????????????????????????

**Comment by ZeroMemes** [comment]
fuck you

**Comment by Unknown** [comment]
i demand this to be fixed

**Comment by Unknown** [comment]
like why are you baiting us??
