### ISSUE TITLE
"New" and "classic" ClickGUI should support tooltips like the older "para" mode

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#65]
In `para` mode, ClickGUI shows tooltips when hovering over a mod:

![tooltip](https://user-images.githubusercontent.com/23565638/28998728-144b4866-7a2a-11e7-923c-a132506b6f14.png)

However this has not been implemented in `new` or `classic` mode yet.

**Comment by w-o-a-h** [comment]
I think the new or classic mode are not suppose to have it.

**Comment by LeafHacker** [comment]
@w-o-a-h that's why this is a feature request not a bug report.

**Comment by w-o-a-h** [comment]
oh my bad

**Comment by LeafHacker** [comment]
I put together a mock-up branch showing how this could be approached. While it functions it is barely usable due to just copy-pasting the para opengl for the test.

![image](https://user-images.githubusercontent.com/23565638/29490942-2336aa44-8544-11e7-9733-d2a9411d3d04.png)

Assigning to @ZeroMemes for now. I'm personally happy to leave this until 4.2, but I think Brady said he wanted it for 4.1.

**Comment by ZeroMemes** [comment]
Added in 4.1
