### ISSUE TITLE
Screen turns black when using ESP Shader

### ISSUE THREAD

**Issue by jehmeme** [ImpactDevelopment/ImpactClient#655]
### What happens?
My screen turns black when I turn on the ESP hack and use the "Shader" option. I'm still able to see my inventory and chat.

### Exact steps to reproduce?

- Open the ClickGUI (Default: `RSHIFT`)
- Open the "Render" tab and navigate to ESP
- Turn on ESP and set it to the setting "Shader"

<details>
  <summary><strong>Additional Client Info</strong></summary>

- Impact Version: 4.3 for 1.12.2
- Using Optifine? Yes
- Enabled mods: ESP in Shader Mode
- Operating System: Windows 10 64bit
</details>

**Comment by Gabgab2003** [comment]
Is fastrender activated?

**Comment by Gabgab2003** [comment]
In video settings

**Comment by Gabgab2003** [comment]
If so then turn it off and try again

**Comment by VitorISs** [comment]
@Gabgab2003 please, don't post a lot of unnecessary replies

**Comment by LordQuadrato** [comment]
This can be reproduced by having Fast Render activated, causing `OpenGL Error: 1282 (Invalid operation)`.
For reference, this bug was already mentioned in #477.

**Comment by jehmeme** [comment]
ooooh ok. thank you!

**Comment by LordQuadrato** [comment]
According to @ZeroMemes in #490 the only solution is to disable Fast Render, should this be closed?

**Comment by VitorISs** [comment]
if the only solution is to disable fast render, it should be closed

**Comment by VitorISs** [comment]
also: duplicate of #490
literally the same thing
