### ISSUE TITLE
Impact 4.3 keeps crashing

### ISSUE THREAD

**Issue by bramblestar2** [ImpactDevelopment/ImpactClient#657]
![image](https://user-images.githubusercontent.com/24534180/42919799-3c41e724-8ad9-11e8-80a5-ac740eaf881f.png)
Everytime i try and start minecraft impact 4.3 it crashes, heres the errors

**Comment by SuperOP535** [comment]
Please use the issue template.

**Comment by ZeroMemes** [comment]
Fixed in 4.4
