### ISSUE TITLE
ClickGUI should pass on key events when not setting binds

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#66]
When not using the `keybind` button to set a bind, keyevents should be passed on to Impact/ClientAPI's normal key event handler to handle macro and toggle binds.

This would enable users to close ClickGUI using RSHIFT (or their configured bind) and toggle any other mods using the keyboard even while ClickGUI is open.

It may also have unforeseen consequences if `super` handles something that is also passed onto Impact to handle. So be careful.

**Comment by ZeroMemes** [comment]
Added in 4.1
