### ISSUE TITLE
Disappearance of nametags upon the enabling of the Nametags hack

### ISSUE THREAD

**Issue by VincentCCandela** [ImpactDevelopment/ImpactClient#665]
### What happens?
 When I turn on the Nametags all of the nametags in game disappear. This happens no matter the combination of options that are enabled/disabled.

### Exact steps to reproduce?

-Turn on the Nametags hack

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.3 for 1.12.2
- Using Optifine? Yes
- Enabled mods: Antiblind, Chams, Clickgui, esp, hud, light, main menu , storageesp, trajectories, auto totem, criticals, prophunt, sneaky assassins, autocheat, inventory, portal gui,unpack,
- Operating System: Xubuntu 18.04

</details>

**Comment by cattts** [comment]
I am having this issue as well with the updated version. **(Impact 4.3 with Optifine)**

**Comment by LeafHacker** [comment]
This sounds like another OptiFine Fast Render bug. It may have already been reported too for a previous version.

**Comment by VitorISs** [comment]
Duplicate of #137
