### ISSUE TITLE
New NoBreakDelay hack

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactClient#668]
If you pay close attention to the game while mining, you'll see that there's a break delay between blocks. A NoBreakDelay hack would remove this delay and essentially speed up mining. Pretty good idea if you ask me.

**Comment by ZeroMemes** [comment]
I am almost certain that there isn't a Vanilla block break transfer delay, can you please confirm?

**Comment by WaffleTraits** [comment]
https://imgur.com/a/DTWyFFv

**Comment by WaffleTraits** [comment]
Clip of Jigsaw's no break delay hack https://streamable.com/u2n23

**Comment by ZeroMemes** [comment]
I'm dumb, this is already a feature in Impact. If you toggle on the **Fast Interact** module under **Player** and enable the **Fast Break** option, you will achieve this effect.

**Comment by VitorISs** [comment]
LUL

**Comment by ZeroMemes** [comment]
Disregard previous comments

**Comment by ZeroMemes** [comment]
Added in 4.4.

The **Fast Break** option for **Fast Interact** has been replaced with the functionality described in this post.
