### ISSUE TITLE
ClickGui is listed as "disabled" even when it is open

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#67]
ClickGui always shows up greyed out/disabled in the ClickGui menu.

Instead it should show as enabled while it is open, and toggling it from the menu should close/disable it.

This would work well with #66, as that would allow toggling clickgui _off_ using it's bind in addition to on. But this could also be added as a special case for only clickgui, if #66 is decided WONTFIX

**Comment by ZeroMemes** [comment]
Fixed in 4.1
