### ISSUE TITLE
Hotbar switcher

### ISSUE THREAD

**Issue by Thunder33345** [ImpactDevelopment/ImpactClient#671]
Allow you to set other inventory rows as hotbar, and switching between them
for example setting row 1 and 4(from bottom 1 to top 4, 0 begin the normal bar)
which means now you can switch from 0(default) to 1 and 4

you can use hotkeys to scroll over, or mousewheel scroll over edge to auto next page or mousewheel+hold button to scroll between pages of hotbars

Internally the client will rearrange the item with server side when say you stayed on X page for > X second or attempt to use a usable item/placeable a block

the client could instant rearrange, or rearrange with waiting period, the client can also animate rearrange for stricter servers that dont allow rearrange while moving, client can also auto stop when movement detected, or only rearrange when player is stopping/force stop to rearrange

**Comment by SuperOP535** [comment]
a mod like this exists, not this advanced but if impact ever gets support for liteloader http://www.liteloader.com/mod/exthotbar

**Comment by LeafHacker** [comment]
> if impact ever gets support for liteloader

Impact has support for liteloader. See [here](https://github.com/ImpactDevelopment/ImpactClient/blob/master/LiteLoader.md).

**Comment by ZeroMemes** [comment]
Welp

**Comment by Thunder33345** [comment]
rip i guess we are stuck with a crappier version but fair enough
