### ISSUE TITLE
Crash when left clicking with autowalk

### ISSUE THREAD

**Issue by ChristoferMinestar** [ImpactDevelopment/ImpactClient#677]
So when I left click to break something while autowalk is on I crash, I am on 2b2t, so coords can't be shown. It looks like an entity related thing. 
[crash-2018-08-03_18.43.06-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2258995/crash-2018-08-03_18.43.06-client.txt)

**Comment by ChristoferMinestar** [comment]
[Critical] [Crash]

**Comment by ChristoferMinestar** [comment]
Ok, I noticed I was able to break a melon with an axe, and once I tried breaking a carrot with my fist it crashed. Same with a flower earlier.

**Comment by LordQuadrato** [comment]
Try disabling `AutoTool`(#653). Otherwise try to find out which module causes your error.

**Comment by ChristoferMinestar** [comment]
Yeah I just tried without autotool, that's the problem. Hope there is a fix soon

**Comment by LordQuadrato** [comment]
Is already fixed in 4.4
