### ISSUE TITLE
Scaffold does not work with slabs

### ISSUE THREAD

**Issue by ChristoferMinestar** [ImpactDevelopment/ImpactClient#678]
Title is enough. Select slabs in hotbar, even after getting rid of all blocks it's not placing them with scaffold on and walking off an edge

**Comment by ChristoferMinestar** [comment]
[Bug]

**Comment by LordQuadrato** [comment]
No need to comment which lables to add

**Comment by ZeroMemes** [comment]
Fixed in 4.4
