### ISSUE TITLE
AntiAFK doesn't disable its AutoWalk (when AutoWalk mod is disabled)

### ISSUE THREAD

**Issue by S-B99** [ImpactDevelopment/ImpactClient#679]
After I turn off anti-afk it keeps autowalking until I turn auto walk ON, then off, in that order.

**Comment by ChristoferMinestar** [comment]
[Bug

**Comment by ChristoferMinestar** [comment]
I did some more testing, sorry for late reply. I am using keybinds and I never open the click GUI. So the only solution is to turn autowalk on and off again.

**Comment by ZeroMemes** [comment]
Should be fixed in 4.7
