### ISSUE TITLE
Item Frames may be considered "storage"

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#683]
StorageESP does not have an option for showing Item Frame entities, however they _do_ store item~~s~~.

Originally reported by @12Me21 in #667

**Comment by includereserved** [comment]
So why did you duplicate if you knew another issue was still open?

**Comment by 0-x-2-2** [comment]
more then one thing in the same issue @includereserved

**Comment by ZeroMemes** [comment]
Added in 4.5 with the option of excluding item frames that don't contain items.
