### ISSUE TITLE
NoFall (Hypixel) causes the player to hit critical hits.

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#684]
If i have NoFall (Packet mode, Hypixel option active), every time i hit something, it's a critical hit, even if "Criticals" is disabled.

(only tried in a vanilla server, i don't know if this is some kind of criticals bypass for hypixel, but looks more like a bug)

**Comment by includereserved** [comment]
It's not a criticals bypass, nor is it a bug. The Hypixel No Fall mode modifies packets to say that you never are on the ground, therefore the server never gives you damage. This is also why (server side) breaking speed is decreased, you don't mine as fast when you're in the air.

**Comment by 0-x-2-2** [comment]
What it does is intended and this is the side effect of using it on vanilla.

**Comment by VitorISs** [comment]
got it, ty
