### ISSUE TITLE
Solid Jesus Flowing "Dolphin" mode

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#688]
Recently (in 4.4?) `Solid` mode `Jesus` added a `flowing` toggle that dictates whether or not `Jesus` should be active while over flowing liquid. This is useful as bouncing around on top of flowing liquid is easily detected by many anticheats and is often harder to navigate than simply swimming!

I think, instead of completely disabling `Jesus`, it would be useful to fallback to a simpler `Jesus` method like `dolphin`; i.e. telling the game the player is jumping/swimming up.

That way you still swim up flowing water automatically and end up walking on top of it.

**Comment by takabakouti** [comment]
nice!!

**Comment by ZeroMemes** [comment]
Added in 4.4
