### ISSUE TITLE
Hiding the Impact button doesn't adjust button positions

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#69]
In the in-game (pause) menu, pressing `LShift` to hide the Impact menu's visability doesn't update the positions of other buttons in the menu:

![menu](https://user-images.githubusercontent.com/23565638/28998977-e4e8c6b0-7a2f-11e7-822e-4588cc79c28e.png)

**Comment by ZeroMemes** [comment]
There's a gap naturally there. I don't adjust positioning in any way.

**Comment by LeafHacker** [comment]
Oh yeah!

**Comment by SuperOP535** [comment]
Lol
