### ISSUE TITLE
Make Riding work with boats

### ISSUE THREAD

**Issue by koraseeq** [ImpactDevelopment/ImpactClient#690]
Make Riding work with boats

**Comment by ChristoferMinestar** [comment]
It does... Just really buggy on servers

**Comment by SuperOP535** [comment]
Duplicate of #654

**Comment by SuperOP535** [comment]
Actually, I'm unsure because of the amount of information given

**Comment by VitorISs** [comment]
some bugs about boats and riding have already been fixed, i think in 4.4 it's everything fine
i can't really see the point of this issue

**Comment by ChristoferMinestar** [comment]
Wait kinda unrelated but does Impact have a beta? Because 4.4 fixes a lot of bugs that would be the only reason I'm tempted to get future.

**Comment by LeafHacker** [comment]
This seems like a duplicate as above. Even if not it doesn't have enough detail to be useful, so closing either way.
