### ISSUE TITLE
Commands stopped working for me at impact 4.1 but still not working in 4.2 and 4.3

### ISSUE THREAD

**Issue by Perry1900** [ImpactDevelopment/ImpactClient#697]
One day, when I used Impact 4.1, the commands just stopped working. I thought it will get fixed with a new version of Impact but after 2 updates it's still not working. What can I do and did this happen to anyone else?

### What happens?
The client thinks the command is just a _normal chat message_, so it just says it in chat.
I attached a [zip file with a video](https://github.com/ImpactDevelopment/ImpactClient/files/2301752/impact.commands.doesn.t.work.for.me.zip) that shows it.

### Exact steps to reproduce?

 Try to type an Impact command for example ".help" or ".xray".

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: **4.3 for 1.12.2** (4.2 for 1.12.2, 4.1 for 1.12.2)
- Using Optifine? No
- Enabled mods: It doesn't matter, I tried with no enabled mods too
- Operating System: Windows 10 64bit

</details>

**Comment by LordQuadrato** [comment]
_Thinking more about it, you may have accidentally changed the command **prefix**! Please comment if this solution works_

To find your current prefix, go into the Impact menu and click `Impact Files`. View the file `config.cfg`.
**There, change the value of "prefix" to to a dot.**

<img src="https://user-images.githubusercontent.com/38622942/44336261-3ad68180-a477-11e8-8166-60cee6f8065b.png">

**Comment by Perry1900** [comment]
it worked, thanks
