### ISSUE TITLE
World update when i walk left

### ISSUE THREAD

**Issue by Hameij** [ImpactDevelopment/ImpactClient#698]
I have a major issue with My 4.3 client.  When I click a the world updates for some weird reason does someone know how to fix this.

### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Enabled mods: 
- Operating System: 

</details>

**Comment by MightyKnight** [comment]
Your issue is very difficult to comprehend.
Please provide a more detailed description of your problem _(e.g. what do you mean by "world update"?, when does it occur?, how? etc.)_ and add reproduction steps.
