### ISSUE TITLE
Open impact credits when clicking "Created by ..." text

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#70]
Same as #56, but for the Impact credits gui (Impact menu -> Credits) instead of `GuiWinGame`.

Clicking the _"Created by Brady, Whispers and Kato"_ should open the Impact Credits GUI.

The link could possibly be reworded to _"Created by Brady"_ or _"Created by Brady and contributes"_ since the credits page goes into the full details, they may not be required on the main menu.

**Comment by ZeroMemes** [comment]
Added in 4.1
