### ISSUE TITLE
Ability to place End Crystals at sky limit.

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#701]
If you try to place an end crystal by clicking at the top of an obsidian that's on the sky limit, the message "Height limit for building is 256 blocks" will appear. You can only place the crystal if you click at the sides or under the obsidian.
 With that option, you would be able to place the crystals at the sky limit even if you click at the top of the obsidian (and even if you can't see the sides of it).

 (That would be really useful for crystal pvp on anarchy servers that have those giant obsidian platforms over the spawn)

**Comment by LeafHacker** [comment]
This should work for anything that can be done by right clicking (except placing blocks).

IIRC there is a vanilla bug that all right clicks when the player's Y-position is over build limit get blocked, even for things other than building.

Entities like Crystals, Armour Stands, Item Frames, Spawn Eggs, etc should all be usable above build height if we can "fix" this bug for Mojang

**Comment by ZeroMemes** [comment]
This only works with Crystals because of the placement behavior.

**Comment by ZeroMemes** [comment]
Fixed in 4.4
