### ISSUE TITLE
Crash when opening Impact Files

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#71]
Clicking the "Impact Files" button in the Impact Menu causes an `IllegalArgumentException` trying to access `./Impact`.

This may be caused by the fact my game profile doesn't use the default `.minecraft` working directory. It is likely that the config uses `mc.mcDataDir` while the button incorrectly uses `"./"`.

See the game [output](https://github.com/ImpactDevelopment/ImpactClient/files/1202718/game-output-2017-08-05.txt) and [crash report](https://github.com/ImpactDevelopment/ImpactClient/files/1202717/crash-2017-08-05.txt)

**Comment by ZeroMemes** [comment]
Fixed in 4.1
