### ISSUE TITLE
When Anti AFK is on, hitting space while typing a message in chat also makes the player jump. 

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#713]
When Anti AFK is on, hitting space while typing a message in chat also makes the player jump. Only noticeable if you turn off Jump under Anti AFK.

**Comment by MightyKnight** [comment]
Basically key presses get passed on from chat.
Also happens for `Walk` in AntiAFK, open chat and press one of the movement keys and the player walks.

**Comment by ZeroMemes** [comment]
Fixed in 4.4
