### ISSUE TITLE
In-game world downloader

### ISSUE THREAD

**Issue by 9NONAGON** [ImpactDevelopment/ImpactClient#716]
A great feature of Impact would be to be able to download the chunks you're walking through into a singleplayer world. It is a big inconvenience to switch to another profile just to world download something, so why not combine it into impact?

Some features might include:
- Container support
- Ability to name singleplayer world after completion
- (Cosmetic) Stats like how many chunks, blocks, or the file size of the section you just downloaded
- ...

This could be a long term goal because of the complexity I guess, im not sure how hard it would be to make.

**Comment by ZeroMemes** [comment]
Not sure if I'll ever get around to this, as the World Downloader mod already supports this. Liteloader should work fine with 4.3 *right now* so I'll get to testing that.

**Comment by ZeroMemes** [comment]
Can confirm that LiteLoader *does* work with 4.3. Here are the steps required:

### Download the LiteLoader installer

You can find the downloads for LiteLoader [here](https://www.liteloader.com/download)

### Run the LiteLoader installer

Run the LiteLoader installer and create a new profile, extending Impact's

![Installer](https://i.imgur.com/8NnyH1a.png)

### Modify the extended JSON

Find the new Impact+LiteLoader combo JSON that the installer created, and modify the last argument to read as follows:

![Modify](https://i.imgur.com/6AFFegt.png)

### Run the new Profile

Now you can open the Minecraft launcher and run the combo profile as normal.

![Run](https://i.imgur.com/J5wWJt9.png)

**Comment by SuperOP535** [comment]
This should be closed?

**Comment by Thunder33345** [comment]
there's ways that can block liteloader's world downloader by abusing the fact that the mod sends out some requests
maybe impact can patch and block these request so the mod wont be detected by server?

**Comment by LeafHacker** [comment]
@Thunder33345 if you want that please open a separate request, thanks
