### ISSUE TITLE
Impact 4.3 crashes when launching

### ISSUE THREAD

**Issue by Serbian037** [ImpactDevelopment/ImpactClient#717]
4.1 and 4.2 work just fine but when i start 4.3 launcher just crashes.
I think u need this: 

00:52:44	launcher	main	info	Preparing to launch minecraft client for 1.12.2-Impact_4.3
00:52:44	launcher	main	warn	Couldn't get hash for org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar from http://dl.liteloader.com/versions/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar.sha1: HTTP 404: Not Found
00:52:45	launcher	main	warn	Have local file C:/Users\Marko Petrovic\AppData\Roaming\.minecraft\libraries\org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar but don't know what size or hash it should be. Have to assume it's good.
00:52:45	launcher	main	warn	Couldn't get hash for 1.12.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar.sha1: HTTP 403: Forbidden
00:52:45	launcher	main	warn	Have local file C:/Users\Marko Petrovic\AppData\Roaming\.minecraft\versions\1.12.2/1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
00:52:45	launcher	main	info	Checking installations.
00:52:45	launcher	main	info	Minecraft client 1.12.2-Impact_4.3 is ready to start.
00:52:45	launcher	main	info	Starting!
00:52:45	launcher	main	info	Using default game log configuration client-1.12.xml (outputs XML)
00:52:47	LaunchWrapper	main	info	Loading tweak class name clientapi.load.ClientTweaker
00:52:47	LaunchWrapper	main	info	Using primary tweak class name clientapi.load.ClientTweaker
00:52:47	LaunchWrapper	main	info	Calling tweak class clientapi.load.ClientTweaker
00:52:47	ClientAPI	main	info	Injecting into ClassLoader
00:52:47	launcher	main	info	
Exception in thread "main" java.lang.NoClassDefFoundError: org/spongepowered/asm/launch/MixinBootstrap
	at clientapi.load.ClientTweaker.injectIntoClassLoader(ClientTweaker.java:66)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinBootstrap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
Picked up _JAVA_OPTIONS: -Xmx512M
02:52:47	monitor	Process Monitor	fatal	Process crashed with exit code 1

idk if i posted that right, if u need anything more, just let me know

**Comment by ZeroMemes** [comment]
Looks like an issue with the integrity of the Mixin dependency. Try deleting the ``0.7.8-SNAPSHOT``folder, located here:

![Folder Location](https://i.imgur.com/rSyAukD.png)

**Comment by Serbian037** [comment]
It worked, thanks. That was a fast response :D

**Comment by skepep** [comment]
yo mine crashes with the 4.8 one when im tryna launch hmo
