### ISSUE TITLE
About the chest cheats...

### ISSUE THREAD

**Issue by TheGamingTitan11** [ImpactDevelopment/ImpactClient#718]
Can you guys please add a way to remove the "steal" and "store" from the chests? It gets pretty annoying but more importantly when people and server mods screenshare me, they can easily discover it and ban me.Please consider it, thanks.

**Comment by ZeroMemes** [comment]
Yes, if you press the ``Right Shift`` key while in a chest inventory, it will hide the button. You can press it again to reveal.
