### ISSUE TITLE
The Open Resource Pack Folder button doesn't work

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#72]
When clicking the button, nothing visable happens. In vanilla this works fine, opening the system default file manager. I am using gnome on linux, but this may not be platform specific.

The following is outputted to stderr (game output):

time |  class | output  
-- | -- | --
23:30:29 | cig | Couldn't open link
23:30:29 | cig | Opening via system class!
23:30:29 | nm | [STDERR]: java.io.IOException: Cannot run program "sensible-browser": error=2, No such file or directory
23:30:29 | nm | [STDERR]: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
23:30:29 | nm | [STDERR]: 	at java.lang.Runtime.exec(Runtime.java:620)
23:30:29 | nm | [STDERR]: 	at java.lang.Runtime.exec(Runtime.java:485)
23:30:29 | nm | [STDERR]: 	at org.lwjgl.LWJGLUtil$1.run(LWJGLUtil.java:406)
23:30:29 | nm | [STDERR]: 	at org.lwjgl.LWJGLUtil$1.run(LWJGLUtil.java:404)
23:30:29 | nm | [STDERR]: 	at java.security.AccessController.doPrivileged(Native Method)
23:30:29 | nm | [STDERR]: 	at org.lwjgl.LWJGLUtil.execPrivileged(LWJGLUtil.java:404)
23:30:29 | nm | [STDERR]: 	at org.lwjgl.LinuxSysImplementation.openURL(LinuxSysImplementation.java:78)
23:30:29 | nm | [STDERR]: 	at org.lwjgl.Sys.openURL(Sys.java:257)
23:30:29 | nm | [STDERR]: 	at cig.a(SourceFile:848)
23:30:29 | nm | [STDERR]: 	at bnu.a(SourceFile:111)
23:30:29 | nm | [STDERR]: 	at bli.a(SourceFile:334)
23:30:29 | nm | [STDERR]: 	at bnu.a(SourceFile:141)
23:30:29 | nm | [STDERR]: 	at bli.k(SourceFile:397)
23:30:29 | nm | [STDERR]: 	at bnu.k(SourceFile:77)
23:30:29 | nm | [STDERR]: 	at bli.q(SourceFile:374)
23:30:29 | nm | [STDERR]: 	at bhz.t(SourceFile:1625)
23:30:29 | nm | [STDERR]: 	at bhz.az(SourceFile:1000)
23:30:29 | nm | [STDERR]: 	at bhz.a(SourceFile:419)
23:30:29 | nm | [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
23:30:29 | nm | [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:30:29 | nm | [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
23:30:29 | nm | [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:30:29 | nm | [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:498)
23:30:29 | nm | [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
23:30:29 | nm | [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
23:30:29 | nm | [STDERR]: Caused by: java.io.IOException: error=2, No such file or directory
23:30:29 | nm | [STDERR]: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
23:30:29 | nm | [STDERR]: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
23:30:29 | nm | [STDERR]: 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
23:30:29 | nm | [STDERR]: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
23:30:29 | nm | [STDERR]: 	... 25 more

**Comment by w-o-a-h** [comment]
Vanilla bug fixed in 1.12.1

**Comment by LeafHacker** [comment]
This is an upstream bug affecting 1.12, fixed in 1.12.1
