### ISSUE TITLE
Magma option in Anti Hazard still damages player

### ISSUE THREAD

**Issue by MightyKnight** [ImpactDevelopment/ImpactClient#720]
### What happens?

Anti Hazards `Magma` option still allows damage under specific conditions, when walking **near and over** a block-edge to _non-magma blocks_.

It happens (see [picture](https://user-images.githubusercontent.com/38622942/46082390-46684700-c19f-11e8-86ac-2add4eb5f8a6.png)) when walking...

- WEST to EAST, from _non_-magma onto magma
- EAST to WEST, from magma to _non_-magma
- NORTH to SOUTH, from _non_-magma to magma
- SOUTH to NORTH, from magma to _non_-magma

![2018-09-26_15 08 28](https://user-images.githubusercontent.com/38622942/46082390-46684700-c19f-11e8-86ac-2add4eb5f8a6.png)

### Exact steps to reproduce?
- Enable `Anti Hazard` and make sure **Magma** is checked
- Build a 3x3 square of magma blocks
- Walk over it from different directions

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.3
- Using Optifine? Yes
- Enabled mods: Anti Hazard
- Operating System: Windows 64bit

</details>

**Comment by ZeroMemes** [comment]
Fixed in 4.5
