### ISSUE TITLE
Ability to see real date/time in the game's HUD

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#722]
It could be an option for the "HUD" module.
This option would display the actual time/date of where you are playing. (So you wouldn't have to do TAB+ALT)

Could be like this(in the corner of the hud):

30/09/2018
10:00PM - Night (or maybe a moon symbol)

**Comment by VitorISs** [comment]
or 09/30/2018, depending on where you live

**Comment by LeafHacker** [comment]
Should be [fairly simple](https://stackoverflow.com/questions/5058880/date-and-time-formatting-depending-on-locale)

**Comment by ZeroMemes** [comment]
Added in 4.4
