### ISSUE TITLE
Give credit to more staff

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#723]
Currently Brady and myself are credited as developers in the repo README (along with a link to ClientAPI). There's also a few people mentioned in the client's in-game credits menu.

Given how active and helpful some of the other community members are, particularly in #help and here on GitHub.

Of course I'm not suggesting we list a hundred names on the README, on the other hand if we do name individuals based on merit some will inevitably feel unappreciated. Perhaps have a list of current past and present contributors that we link to?

Then again, someone would have to maintain such a list... perhaps i should just mark this as WONTFIX 😂

**Comment by SuperOP535** [comment]
*marks as wontfix*

**Comment by leijurv** [comment]
ayy lmao me too thanks

**Comment by VitorISs** [comment]
:thinking:

**Comment by MightyKnight** [comment]
Thanks for noticing our contributions :facepunch:
I like the idea of a seperate list. As for maintenance, we (the contributors) could manage it perhaps?

**Comment by LeafHacker** [comment]
Yeah that works for me. Any issues moderator should have write access to this repo already, so that kinda simplifies community maintenance.

If anyone has a spare half hour feel free to knock up a PR or remind me over the weekend

**Comment by zPeanut** [comment]
doing this tomorrow

**Comment by zPeanut** [comment]
done.
