### ISSUE TITLE
Velocity Bug

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#725]
There isn't a way to reduce KB from explosions, only turn it off which is kinda bs

**Comment by VitorISs** [comment]
i don't think this is a bug :thinking:

**Comment by MightyKnight** [comment]
You can reduce it by using the sliders going from 0% to 100% of knockback.

**Comment by VitorISs** [comment]
@MightyKnight hmm that separate slider would be a really nice addition

**Comment by ZeroMemes** [comment]
The options for horizontal and vertical velocity now apply to explosions rather than fully cancelling them.
