### ISSUE TITLE
Tunneler

### ISSUE THREAD

**Issue by Perry1900** [ImpactDevelopment/ImpactClient#728]
I think you should add a tunneler module with an option of putting blocks behind you as you walk, it is gonna be like automine, autowalk and scaffold together but automine will only mine the blocks in front of you and you will have an option to hide your path by telling the client a block to put behind you.
I think you should add this because it you be good for mining (except for the lava problem) and for making bases. For example, in 2b2t you will be able to turn left or right on a highway and turn it on for a few minutes/hours and you will have a place to make a base in.

**Comment by SylveonBottle** [comment]
Maybe a simple option to disable placing blocks behind you, as well as a width/height/distance option for automating tunnels. Could possibly use #461.

**Comment by Thunder33345** [comment]
could possibly use baritone too
like a `mine ahead also put blocks back` command

**Comment by SylveonBottle** [comment]
If the feature suggestion is to just tunnel forward and replace blocks, I'd suggest naming it in some sorts of a "trail hider". 

Simply have Baritone place blocks back that it broke, and break blocks that it places.

Having an auto-tunneler would be nice for creating long tunnels in itself, though. Maybe we could place minecart tracks along the path to create a long track, then come back when you run out so that the user can restock.

**Comment by leijurv** [comment]
Baritone could Maybe do this. But it wouldn't be pretty LOL. 

Maybe PathExecutor refers to a Baritone Setting<Boolean> for patching up the path behind it? Just when a traverse finishes, if the previous one was a traverse, and it's in the nether, and it has netherrack, it'll patch it up?
Maybe it could refer to the cached chunk to see whether it was originally netherrack or if it's moving through a cave system? Could be fancy. IDK.

**Comment by devcat** [comment]
any updates on this feature? it would be useful to afk dig 1x2/2x2/3x3/5x5 tunnels

**Comment by MonstahGames** [comment]
This would be a great feature

**Comment by Matt4499** [comment]
please add. thanks.

**Comment by EvilSourcerer** [comment]
Yes I need(ed) this 2 months ago

**Comment by leijurv** [comment]
This is added with `.b tunnel` and `.b backfill`
