### ISSUE TITLE
When a target is being engaged, pause Baritone

### ISSUE THREAD

**Issue by ZeroMemes** [ImpactDevelopment/ImpactClient#729]
Whenever a combat module engages a target, Baritone should pause path execution.

**Comment by ZeroMemes** [comment]
Should be an option that defaults to ``true``.

**Comment by leijurv** [comment]
agreed epic style

**Comment by ZeroMemes** [comment]
Added in 4.4 to KillAura, bumping to 4.5 for additional combat modules which will require a bit more work.

**Comment by leijurv** [comment]
crystal aura should pause it too i guess? not sure

**Comment by ZeroMemes** [comment]
Closing because of modular processes integration
