### ISSUE TITLE
Use GuiConfirmOpenLink when opening links

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#73]
Impact should use `GuiConfirmOpenLink` when opening links (e.g. "Youtube Channel") to give the user a chance to view the link, and either open or copy to clipboard.

`GuiConfirmOpenLink` can be configured for either trusted or untrusted links. Set the 4th parameter to `true` for trusted links. You can optionally also run the `disableSecurityWarning()` method to disable rendering the warning message.

**Comment by ZeroMemes** [comment]
Added in 4.1
