### ISSUE TITLE
Save all Baritone Settings

### ISSUE THREAD

**Issue by ZeroMemes** [ImpactDevelopment/ImpactClient#735]
At the moment, the only settings that are saved are ones that are configurable in the GUI. All of Baritone's settings should be saved. This could also be done on the Baritone-side of things, where Baritone is responsible for saving settings.

**Comment by leijurv** [comment]
no u

**Comment by leijurv** [comment]
https://github.com/cabaletta/baritone/commit/0f1edba5f1b2c74078a9bb6acce54815ac4503fa
ok fine i did this
