### ISSUE TITLE
Add a feature to let you climb hanging vines

### ISSUE THREAD

**Issue by daytona22** [ImpactDevelopment/ImpactClient#740]
Normally, you can't climb a vine when there isn't a block behind it, you just sort of float down. Maybe a hack could be added that tricks the client into thinking there's a block behind the vine. If that isn't possible, maybe it could be so when you jump onto a vine, a block is placed behind it. This would be very useful in servers like 2b2t, where spawn has a ton of hanging vines.

**Comment by VitorISs** [comment]
hmmm i don't think this would bypass AAC/NCP :thinking:

**Comment by zPeanut** [comment]
already proven to not be possible by 0x22 in discord

closed

**Comment by ZeroMemes** [comment]
Technically possible but wouldn't work on any servers with an anti cheat. And if the server doesn't have an anti cheat u can just fly lol.

**Comment by daytona22** [comment]
In that case, couldn't a block just be placed behind any hanging vine if its inside a certain radius? this would be immune to anti cheat and still be useful.

**Comment by 0-x-2-2** [comment]
no it would not be immune unless you did it the slow legit way
