### ISSUE TITLE
How to install Impact with MultiMc

### ISSUE THREAD

**Issue by KGriss** [ImpactDevelopment/ImpactClient#749]
Hello,
I want install Impact using MultiMc but I don't know how do it.
I have already install Wurst by drop the Wurst "core" from :
_.minecraft\versions\Wurst MC 1.12 OF\Wurst MC 1.12 OF.jar_

But Impact don't have this file.

Help me please.

**Comment by WaffleTraits** [comment]
Here's an Impact instance for MultiMC, just extract and move to instances folder for MultiMC.
[Impact 4.3 MultiMC.zip](https://github.com/ImpactDevelopment/ImpactClient/files/2475750/Impact.4.3.MultiMC.zip)

**Comment by MightyKnight** [comment]
I created a **wiki** entry: ([Installing Impact with MultiMC](https://github.com/ImpactDevelopment/ImpactClient/wiki/Installation#installing-impact-with-multimc)) :heavy_check_mark:

**Comment by KGriss** [comment]
Thank you very much ^^

**Comment by 132ikl** [comment]
@MightyKnight That seems to be a dead link, and it looks like your contributions were removed from the commit history as well.
@WaffleTraits How did you create this zip?

**Comment by LeafHacker** [comment]
For some reason the wiki got disabled. Should be working fine again now.

**Comment by 132ikl** [comment]
Great, thanks!

**Comment by 0akz** [comment]
> 

hey so i followed ur steps but the impact folder gets added in the .minecraft folder and when i use multimc to create a new instance it dosnt show up
