### ISSUE TITLE
Please add entity speed and auto totem

### ISSUE THREAD

**Issue by Fluffbuck3t** [ImpactDevelopment/ImpactClient#76]
in the past i have really enjoyed impact but switched to clients like xdolf and future for these features. i would really like to see them added because i find these essential for any client i use frequently

**Comment by LeafHacker** [comment]
Can you please create separate issues for each feature? Thanks

**Comment by Fluffbuck3t** [comment]
just a separate post for each?

**Comment by LeafHacker** [comment]
Yep, issue trackers work best when each issue/feature is separate.

If an issue covers multiple topics, it is harder to keep track of whether it is fixed/implemented.

**Comment by Fluffbuck3t** [comment]
okay i will make 2 separate ones
