### ISSUE TITLE
Module Mode settings don't load properly

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#763]
If you enable Speed: Strafe: NCP and restart your game it will reset to Speed: Strafe: Vanilla not NCP

**Comment by VitorISs** [comment]
Yea, and if you enable the "Jump" option and then restart the game, the option will get disabled

**Comment by MightyKnight** [comment]
Should be ez to fix, adding to 4.5 milestone.

**Comment by ZeroMemes** [comment]
This likely applies to the settings for all Modes.

**Comment by ZeroMemes** [comment]
> And also, is the Strafe speed slower than the vanilla bunny hopping (w+espace+sprint) on purpose ? because it is

Yes the Strafe speed mode is just to have an absolute directional movement with normal movement speed.

**Comment by ZeroMemes** [comment]
Fixed in 4.5
