### ISSUE TITLE
Rework Ladder Speed

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#764]
If you stand in the area of a ladder and press space you get launched into the air

**Comment by MightyKnight** [comment]
You're report is very vague and it's difficult to understand what you mean. You should do the following for issues you create:

- Describe the problem **detailed** and with **as much information as possible**.
- Please use the ISSUE TEMPLATE, picture below _(that pops up when you create a new issue)_
<img src="https://user-images.githubusercontent.com/38622942/47177785-ade66200-d319-11e8-8a64-24d59139de50.png" height="400" />

**Comment by MightyKnight** [comment]
### Regarding this specific bug, please elaborate on:
- How to create the setup for this (Where to place the ladder, do you need blocks around, etc...)
- What you mean by _"getting launched in the air"_ (a few blocks, 100 blocks or jump height?)
- :exclamation: **What modules you have enabled**
- :exclamation: What **settings** for these modules are active

**Comment by ThatGrzegorzB** [comment]
> ### Regarding this specific bug, please elaborate on:
> * How to create the setup for this (Where to place the ladder, do you need blocks around, etc...)
> * What you mean by _"getting launched in the air"_ (a few blocks, 100 blocks or jump height?)
> * ❗️ **What modules you have enabled**
> * ❗️ What **settings** for these modules are active

https://www.youtube.com/watch?v=ojmSNuZtads
ladder speed min settings

**Comment by ZeroMemes** [comment]
I think a proper approach for Ladder Speed would to have a "multiplier" option, rather than have a vague "speed" setting.

**Comment by ZeroMemes** [comment]
"Fixed" in 4.5
