### ISSUE TITLE
Minestrike hack not working

### ISSUE THREAD

**Issue by NoHax2018** [ImpactDevelopment/ImpactClient#772]
I have used Impact 4.2 for a while and suddenly the minestrike hack stopped working. I hadn't changed anything on the day. I updated to Impact 4.3 to see if it would work but nothing happened, the next day I did the 4.4 update for Impact and the minestrike hack still doesn't seem to work. (I used 1.12.2 version for it)

**Comment by ZeroMemes** [comment]
Caused by a change brought by the Mineplex halloween update it appears.

**Comment by ZeroMemes** [comment]
Fixed in 4.5

**Comment by ZeroMemes** [comment]
I've released a patch update for 4.4 fixing this.
