### ISSUE TITLE
Strafe speed mode multiplier

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#774]
Add a mode for strafe: custom where you can set the base speed and speed multiplier. Base speed shouldn't allow for a lot of room just so you can use it accurately for some better anti-cheats and speed multiplier could be used for the worse ones

**Comment by ZeroMemes** [comment]
The point of the base speed is to provide a constant speed value that is precise. A slider does not provide that.

**Comment by ZeroMemes** [comment]
Added in 4.5
