### ISSUE TITLE
Walking through a nether portal closes clickgui

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#781]

**Comment by VitorISs** [comment]
?

**Comment by MightyKnight** [comment]
??

**Comment by leijurv** [comment]
yeah never mind lol

**Comment by 0-x-2-2** [comment]
was user error man

**Comment by leijurv** [comment]
yes I am idiot I had portals on but portals->gui off idk how that happened 0x22 helped me through my stupidity and showed me the light of portal gui
