### ISSUE TITLE
Velocity Improvement Ideas

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#785]
- A No-Reset option for velocity would be nice, after getting hit/moved your velocity would be reset to 0
- Values over 100% so you can have increased amounts of velocity

**Comment by ZeroMemes** [comment]
> A No-Reset option for velocity would be nice, after getting hit/moved your velocity would be reset to 0

I'm sorry, I don't think I understand what you mean by this?

**Comment by VitorISs** [comment]
maybe a "reverse" option? :thinking:
so if you get hit, instead of going backwards, you'll go forwards (in the direction of the thing that hit you)

idk why would you use it, but it exists and it's interesting lol

**Comment by ThatGrzegorzB** [comment]
> maybe a "reverse" option? 🤔
> so if you get hit, instead of going backwards, you'll go forwards (in the direction of the thing that hit you)
> 
> idk why would you use it, but it exists and it's interesting lol

yes that is indeed what values over 100% would do.....

**Comment by ZeroMemes** [comment]
>when you get hit while running or receive a velocity packet when moving and your velocity is set to 0 your movement speed will reset to 0 and you will start running again, so essentially getting hit a lot makes you barely able to move

OOOhhh, damage velocity reduction.

**Comment by ZeroMemes** [comment]
Added **Reverse** and **Multiplier** sub-options for both **Horizontal** and **Vertical** as well as a **Damage Fix** option to prevent velocity/sprint reset (Also achieved with Sprint's **Keep** option.)
