### ISSUE TITLE
Speed: Boost improvement idea

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#786]
Would be nice to see an option like "disable on jump" for speed: boost, because most ac's flag you when you jump/step up a block with boost on, possibly a "only on flat" option that would make boost only take effect on constantly flat ground, and it would stop when a player jumped/stepped up a block/stair

**Comment by ZeroMemes** [comment]
Right now multiple checks are in place to prevent y position offsets in situations where they shouldn't happen. Just don't use it when going up stairs.
