### ISSUE TITLE
The Friends filter doesn't work as expected on Tracers

### ISSUE THREAD

**Issue by ShadyTheDragon** [ImpactDevelopment/ImpactClient#787]
### What happens?
Tracer renders lines to all players, including ones marked as friends regardless if friends are set to show up on tracers or not.

### Exact steps to reproduce?

- Turn on tracers
- Add a player as a friend

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.4 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Tracers, Light
- Operating System: Windows 8 64bit

</details>

**Comment by ZeroMemes** [comment]
There is also an issue with **Teammates** in **ESP**. I think that both **Teammates** and **Friends** should be in both **ESP** and **Tracers** and have 3 modes: ``Include``, ``Restrict`` and ``Only``.
- **Include**: Teammates/Friends will be included in the targeted players.
- **Restrict**: Teammates/Friends will be excluded from the targeted players.
- **Only**: Teammates/Friends will be the only valid players to be targeted.

**Comment by leijurv** [comment]
maybe ill be tracers

**Comment by LeafHacker** [comment]
Probably makes sense to make `Teammates` and `Friends` children of `Players` then.

**Comment by ZeroMemes** [comment]
Fixed for ESP and Tracers in 4.5
