### ISSUE TITLE
.gui blur syntax error even when no error

### ISSUE THREAD

**Issue by AlexiDoesCode** [ImpactDevelopment/ImpactClient#80]
When i do run `.gui blur enable` it first says it has been enabled, but then says the syntax is incorrect.

**Comment by LeafHacker** [comment]
For clarity, gui blur works fine, but the command returns `syntax error` even when it completed successfully.

![image](https://user-images.githubusercontent.com/23565638/28999807-9c7d655c-7a4d-11e7-968d-1221b75f5634.png)

**Comment by ZeroMemes** [comment]
Fixed in 4.1
