### ISSUE TITLE
Proper AutoJump

### ISSUE THREAD

**Issue by SylveonBottle** [ImpactDevelopment/ImpactClient#810]
Make AutoJump jump whenever the player is on ground, instead of just holding the jump button.

Currently, if you stand underneath a block, your player will just jump every half second when you could be manually jumping faster.

This new method would also allow you to climb upwards a bit faster instead of normally holding spacebar.

Also, if this was added, maybe a sub-option to only activate this if you're holding spacebar? That way you can use it as a bunnyhop 'script' of some sorts, spam-jumping when you need it and not when you don't.

**Comment by ZeroMemes** [comment]
This was changed in 4.6, forgot to close it.
