### ISSUE TITLE
AutoWalk - Random Quotation mark

### ISSUE THREAD

**Issue by SylveonBottle** [ImpactDevelopment/ImpactClient#811]
### What happens?

Enabling "AutoJump" for the first time will print out a message, the message appears to have a random quotation mark before the last blue name/link.

### Exact steps to reproduce?

- Enable AutoWalk for the first time

## Image:

![](https://i.lensdump.com/i/AERoKz.png)

**Comment by ZeroMemes** [comment]
Fixed in 4.5
