### ISSUE TITLE
Freecam: Accept ALL server movement packets

### ISSUE THREAD

**Issue by SylveonBottle** [ImpactDevelopment/ImpactClient#821]
While in Freecam, your actual body should still be able to move from gravity/knockback/explosions/water/etc. 

It looks super suspicious for a player to suddenly start taking no knockback because they're freecaming a base. 

Pretty sure a certain smoking mod has this.

~~[Would be really awesome to be able to freecam around while Baritone is navigating.][681]~~

[681]: https://github.com/ImpactDevelopment/ImpactClient/issues/681

**Comment by MightyKnight** [comment]
Relates to #681

**Comment by LeafHacker** [comment]
Serverside movement should be accepted (and visible on the avatar), however I was pretty lazy and only handles the main movement packet, not others like explosions and velocity. Therefore this is a bug.

The idea of baritone continuing to work while in freecam is a much bigger (separate) issue which should be tracked under #681, not here.

**Comment by leijurv** [comment]
Pretty much a duplicate of #912

**Comment by SylveonBottle** [comment]
> Pretty much a duplicate of #912

This issue has a lower id number.
Doesn't that mean 912 is a duplicate of this one?

**Comment by leijurv** [comment]
generally you close the one with less information, but point taken lol
