### ISSUE TITLE
Regular flying not working

### ISSUE THREAD

**Issue by De-Martian** [ImpactDevelopment/ImpactClient#841]
### What happens?
If the server allows flying in survival mode, you cant fly at all in 4.4, even if you're not using any hacks

### Exact steps to reproduce?

- Join a server where you can normaly fly in survival mode
  - Using Impact 4.4
- You can't fly

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.4 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: None
- Operating System: MacOS 10.13.6

</details>

**Comment by 0-x-2-2** [comment]
baritowned

**Comment by ZeroMemes** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/ed1941abdb7f153b6ca8a3ac5ea946532d72f0e5

**Comment by ZeroMemes** [comment]
Not putting on the **4.5** milestone because this was technically a Baritone issue.

**Comment by 0-x-2-2** [comment]
THIS IS EPIC
