### ISSUE TITLE
[Baritone] Improved pathfinding (Carpets & Stairs)

### ISSUE THREAD

**Issue by 9NONAGON** [ImpactDevelopment/ImpactClient#843]
While I was messing around with baritone, I noticed that 1, it sort of completely disregards carpets, and 2, when going up stairs, it treats them as normal blocks and attempts to jump up them.
[https://youtu.be/iB0ZD_f3kfk](url)

**Comment by ZeroMemes** [comment]
Issues like this (where it is a Baritone issue and not the specialized integration with Baritone that Impact provides) should go on [Baritone's GitHub Repo](https://www.github.com/cabaletta/baritone)
