### ISSUE TITLE
'Save Coord's' Folder Location

### ISSUE THREAD

**Issue by Shadowbandits** [ImpactDevelopment/ImpactClient#844]
### What happens?
I just can't find the folder where 'Save Coords' is located. I asked on this discord but never revived a response.
<details> 
  <summary><strong>Client Info</strong></summary>
 

- Impact Version: 4.4 for 1.12.2
- Using Optifine: No
- Using LiteLoader: No
- Enabled mods: Respawn (Save Coords)
- Operating System: Windows 10

</details>

**Comment by LeafHacker** [comment]
It'll be somewhere in the `.minecraft/Impact` folder. You can get to this folder by opening Impact and going to the `Impact` menu and choosing `Impact Folder` (or Impact Files or whatever it's called).

**Comment by Shadowbandits** [comment]
Okay, thank you. I completely looked over the Impact folder in there when I was trying to figure it out myself :/
