### ISSUE TITLE
Show in the HUD if Baritone is paused, and if so, which utility module is doing it

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#845]
If Baritone isn't pathing don't show anything, if it's pathing and unpaused show `Baritone: running` or something, if it's pathing and paused maybe have something like `Baritone: paused by Kill Aura`.

Perhaps it could also show which utility module is using Baritone, so it would be `Baritone: in use by Auto Walk (Smart)` when unpaused?

**Comment by ZeroMemes** [comment]
![image](https://user-images.githubusercontent.com/24485393/48380040-e882b680-e69b-11e8-9322-7c9b880948b3.png)

**Comment by LeafHacker** [comment]
Ew calculus

**Comment by leijurv** [comment]
bread man did this in 4.5
