### ISSUE TITLE
Fix help for .b

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#847]
With this commit https://github.com/cabaletta/baritone/commit/20405716bc97587225683144463fdc7350507cbe, Baritone has functional help when you do `.b help`

If the user puts in `.b help` or `.b ?` it properly displays this help message.

It should also display this message if they put in `.b` or `.help b` or `.help baritone` or if the put in an invalid command after `.b`. Currently an invalid `.b` command links to ExampleBaritoneControl.java which is..... okay, but it should instead print this. `.help b` just shows the varargs hack.

**Comment by ZeroMemes** [comment]
Added in 4.5
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
baritone syntax when? (:
