### ISSUE TITLE
Add Legit Mine GUI option for Baritone

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#851]
Even though it's technically a global setting, should obviously go under Auto Mine IMO. Also if I add some options to make it not suck, those too. 

https://www.youtube.com/watch?v=UKe_bz1jtFI

**Comment by leijurv** [comment]
`legitMine`, `legitMineYLevel`, and `legitMineIncludeDiagonals`

**Comment by ZeroMemes** [comment]
Added in 4.5
