### ISSUE TITLE
Triggering MineBehavior manually (.b mine) when Auto Mine is off causes strange behavior

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#854]
I've tested the same Baritone build standalone and with Impact 4.4 (auto mine off), and only in standalone does `mine web` and `mine diamond_ore` actually function. In Impact, after it mines one it remains a goal (even though it's air now), so it never progresses onto the next diamond ore or cobweb. It's as if mineGoalUpdateInterval is disabled, regardless of whether Auto Mine is on or off (it's not that specifically, I checked the setting and it's still enabled).

**Comment by SylveonBottle** [comment]
Can confirm that this is broken, unable to state how to produce it.  
Sometimes digging up some dirt makes it work for mining logs, but it still doesn't work properly for other ores. 

![image](https://user-images.githubusercontent.com/17802843/47958967-3bc27e00-dfa5-11e8-9246-2bb2d639517d.png)

**Comment by leijurv** [comment]
Yeah I was testing alongside you in Baritone standalone, I should have been using Impact 4.4 + Baritone lol

**Comment by leijurv** [comment]
Fixed by https://github.com/cabaletta/baritone/commit/c614d7ec6a81ff2d23708dfd30e4a497c2304483

@ZeroMemes is this worth hotfixing 4.4's baritone? idk. `.b mine` doesn't work, it fails after mining the first block, but auto mine works fine.

**Comment by ZeroMemes** [comment]
Fixed in 4.4 by Baritone hotfix LUL

**Comment by MightyKnight** [comment]
Brady's release schedule:
```
  while(true) {
    hotfix();
  }
...
releaseNewVersion(4.5);
```
Seriously how many hotfixes are there for 4.4??

**Comment by leijurv** [comment]
uhHHhhHHHhhHHhhHHHhhh 

TEN HOTFIXES

INCLUDING DEPENDENCIES LIKE BARITONE

LMFAO

https://github.com/impactDevelopment/maven/commits
