### ISSUE TITLE
AntiAFK doesn't turn off until you exit ClickGUI

### ISSUE THREAD

**Issue by jeffrey2000hk** [ImpactDevelopment/ImpactClient#86]
AntiAFK requires exiting the whole GUI to be actually turned off.

**Comment by LeafHacker** [comment]
Can you clarify: Which GUI? ClickGUI? Any GUI (chat, inventory, pause menu, etc)? What method are you using to disable AntiAFK?

**Comment by jeffrey2000hk** [comment]
Click GUI
Disable by clicking the button "antiafk" toggling it from on to off

**Comment by jeffrey2000hk** [comment]
The one which opens up when you press right shift

**Comment by ZeroMemes** [comment]
Fixed in 4.1
