### ISSUE TITLE
Murder Mystery Hypixel not detecting murderer

### ISSUE THREAD

**Issue by ghost** [ImpactDevelopment/ImpactClient#861]
### What happens?
Hypixel Murder Mystery ESP does not detect someone as murderer if they hold a cookie.

### Exact steps to reproduce?
- Turn on the murder module with hypixel mode on hypixel.net
- Have a murderer hold a cookie as their sword
- They won't be detected as murderer

Maybe have it so that if anyone holds anything but a bow, arrow, map, or gold, mark them as murderer to support future sword type updates.

<details>
<summary><strong>Additional client info</strong></summary>

- Impact Version: 4.4 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Murder (Hypixel)
- Operating System: Windows 10 64 bit

</details>

**Comment by MightyKnight** [comment]
Related to #567.
I like your idea, **but** it has the same flaws as the current implementation.
Non-murderer items get updated too, sometimes with new maps. Currently there are:
- Bow, arrow
- Gold ingot
- Map
- Wood shovel, snowball
- String

Here's the dilemma:
1. Either detect for items he can hold -> _If Hypixel updates murderer is not shown_
2. Or detect for items except the ones innocents can hold -> _If Hypixel updates false murderers are shown_

**Comment by LeafHacker** [comment]
I suppose we could find some kind of middle ground by highlighting players holding items we didn't expect either class to hold, but I'm not too keen on that as it promotes us ignoring changes to items.

A better solution might be to store the items in JSON on the resources repo, so they can be updated without having to update Impact.

Either way that's probably a separate issue as this issue is primarily discussing cookies not being recognised as murderers.

**Comment by ZeroMemes** [comment]
I'll keep the fix with this issue, and create a new issue for a json on the resources repo.

**Comment by tyuop077** [comment]
@LeafHacker @leijurv @ZeroMemes 

**List of murder's items:**
iron_sword
stone_sword
iron_shovel
stick
wooden_axe
wooden_sword
stone_shovel
blaze_rod
diamond_shovel
feather
pumpkin_pie
golden_pickaxe
carrot_on_a_stick
bone
carrot
golden_carrot
cookie
diamond_axe
golden_sword
diamond_sword
diamond_hoe
shears
fish:1

![Murder's Items Page 1](https://user-images.githubusercontent.com/30123136/61798435-f8a98300-ae31-11e9-8a95-a9f2b8802210.png)
![Murder's Items Page 2](https://user-images.githubusercontent.com/30123136/61798469-07903580-ae32-11e9-84b3-000c83f1e8a3.png)
