### ISSUE TITLE
Kill Aura on impact for 1.9 pvp not working

### ISSUE THREAD

**Issue by CustomKKK** [ImpactDevelopment/ImpactClient#862]
### Exact steps to reproduce?

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Comment by CustomKKK** [comment]
if you see this please tell me what im doing wrong and settings to make it work. Thanks! :)

**Comment by LeafHacker** [comment]
a) you've provided literally no information: how is Aura behaving? How did you expect it to behave? How is Aura configured? Do you have any other modules enabled? What steps are you using to get the behaviour you are seeing?
b) This isn't a place to get support on how to use Impact, this is a place to report bugs and file suggestions (hence closing as a question). That said if you can provide the above information, either here or in #help on discord,I'm sure someone will try and help.
