### ISSUE TITLE
Suggestion: Better speedhack

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#866]
Back in the day I used to use Huzuni on Minecraft, and I remember it had a Speed module that allowed players to slightly increase the velocity(like 1.02~1.05) without being detected on several servers(even on huge networks). Please add it! It's the only thing I miss.

**Comment by VitorISs** [comment]
maybe you can use the speed slider on the vanilla speed, or the boost speed.. or maybe even timer on a small multiplier..

the speed you said looks pretty easy to be detected by anticheats.. and back when huzuni was relevant, anticheats weren't very good.. it's different nowadays

**Comment by SigmaRS** [comment]
Maybe it's possible to discover how Huzuni implemented Speed hacks?

**Comment by LeafHacker** [comment]
The problem isn't that impact has bad speed hacks. The problem is that anticheats have better detection for speed hacks now.

**Comment by ThatGrzegorzB** [comment]
> The problem isn't that impact has bad speed hacks. The problem is that anticheats have better detection for speed hacks now.

impact could use slowhop tho

**Comment by LeafHacker** [comment]
If you'd like a specific feature, please [open](https://github.com/ImpactDevelopment/ImpactClient/issues/new) a feature request describing how _exactly_ it should behave.
