### ISSUE TITLE
Suggestion: Change command prefix

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#867]
### What is your suggestion?

Change the prefix for using commands or an option to disable commands.
Example:
.b mine iron_ore ---> ;b mine iron_ore
.b mine iron_ore ---> &b mine iron_ore

### Why is it useful?

Some admins are smart enough to ask possible cheaters to send in chat a message starting with "."
I know you can use self-destruct, but what if there's a plugin that asks players to type a message on join?

**Comment by MightyKnight** [comment]
1. Already a feature, use `.prefix set`
2. If you want to send a message starting with a dot put `\` (backslash) in front of it

**Comment by SigmaRS** [comment]
Thanks!!!
