### ISSUE TITLE
Add an option under Pots [SUGGESTION]

### ISSUE THREAD

**Issue by blackcooper** [ImpactDevelopment/ImpactClient#87]
When you throw a pot ex: instant health it replaces the pot with another, or if its like instant damage, you can spam right click and it will throw a ton down.

**Comment by LeafHacker** [comment]
This issue is somewhat unclear. What is the exact functionality of the feature you are suggesting?

What do you mean by throwing a potion replaces it? Is the spam potion thing a different feature? If so it should have a separate feature request.

Closing as invalid until more info is provided.
