### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by wholesomeduck** [ImpactDevelopment/ImpactClient#870]
### What is your suggestion?
Overall better cheat bypass. Recommended to put in LONG_TERM milestone. Could be worked on a little every update.

### Why is it useful?
Impact at the moment is very detectable, and even on servers like 2b2t, you can't use certain modules.

**Comment by VitorISs** [comment]
Impact's prioritization at the moment is NCP, and the client already works pretty well on it.
2b2t is using AAC, which is much harder to make functional bypasses and whatever.

**Comment by ZeroMemes** [comment]
The AAC developer patches bypasses very fast, Impact is targeted towards NCP and anything that you would expect to bypass pretty much does. There can't be a general expectation for things to just bypass better, please open a specific issue like "AAC speed" or "AAC aura" with **specifics**

**Comment by wholesomeduck** [comment]
Okay
