### ISSUE TITLE
Crystal Aura with placement

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#872]
### What is your suggestion?

I think it would be dank to have the crystal aura be able to place crystals as well as setting them off.

### Why is it useful?

pvp

**Comment by VitorISs** [comment]
Like, set it to spam crystals as close as possible to a player that's not on the friends list? It would need to be highly configurable, to set distance, place crystals according to your Y level, etc.

That would be really useful on pvp at the bedrock layer..

**Comment by leijurv** [comment]
Yeah I'm not saying skid kami bc it's garbo (jkjkjk) but do something similar and maybe more configurable =)

I. E. Place crystals to maximize damage to them while minimizing damage to you (and also minimizing damage to friends / alts? could be cool too)

**Comment by leijurv** [comment]
@ZeroMemes can close?

Minimizing damage to friends would be cool but I realize it's not that plausible =)

**Comment by leijurv** [comment]
This was added for 4.5, but there's something else that I'd like to suggest: apply the same filters to setting off crystals as placing them (i.e. not just "don't place a crystal that would kill me if i set it off" but literally "don't set off crystals that would kill me")

**Comment by ZeroMemes** [comment]
![image](https://user-images.githubusercontent.com/24485393/53263310-9855c000-369e-11e9-8fc9-61c59069c7e9.png)

**Comment by ZeroMemes** [comment]
Correction: **Commit** will literally place and hit crystals that can kill you

**Comment by ZeroMemes** [comment]
This is perhaps the BEST setting that Impact has to offer

**Comment by leijurv** [comment]
LOL
