### ISSUE TITLE
Optifine support

### ISSUE THREAD

**Issue by satroyyy** [ImpactDevelopment/ImpactClient#88]
is it possible to add optifine? pls its makes the game smoother

**Comment by LeafHacker** [comment]
Impact is built using ClientAPI, which is [currently working](https://github.com/ZeroMemes/ClientAPI/commit/8fc8c7da3bea273bcbf50d84d0a1b5195c613962) on being compatible with Optifine.

Other clients that _include_ Optifine as part of the download are not complient with Optifine's license (and probably also Mojang's EULA).

Keeping this issue open to track Optifine compatibility.

**Comment by ZeroMemes** [comment]
An Installer will be made in the future, which will allow you to "extend" existing profiles. Impact will not have OptiFine included, as leaf said. However, here is a tutorial for manual installation of OptiFine into Impact 4.0. https://www.youtube.com/watch?v=o1LHq6L0ibk

**Comment by LeafHacker** [comment]
Closing since Impact _is_ Optifine compatible and can be easily modified to `inheritFrom` and add optifine tweaker to the CLI args.
