### ISSUE TITLE
add a search bar lol

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#880]
This needs to be a thing. It's been a while since someone has raised the question and I swear nearly all my friends who use impact ask under which category a hack is located. This is a serious issue. If you are going to bring up the framework and the clickGUI's limitations, i would say rewrite that too. Impact's GUI is crumbling infrastructure if it's difficult to highlight certain modules.

**Comment by MightyKnight** [comment]
Duplicate of #160
