### ISSUE TITLE
Add option for different tracer colors by type?

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#892]
Players one color, hostiles another?

**Comment by LeafHacker** [comment]
This kinda thing may be almost doable now that clickgui supports suboptions; maybe each filter toggle could have a colour suboption or something along these lines?

**Comment by leijurv** [comment]
Yeah as in #893, perhaps each category (Players, Hostiles) could expand to a color and a maximum distance that it'll render to?

**Comment by leijurv** [comment]
😎

**Comment by ZeroMemes** [comment]
Added (by leijurv) in 4.5
