### ISSUE TITLE
EntityFilter still doesn't test for all mobs

### ISSUE THREAD

**Issue by MarvelDC** [ImpactDevelopment/ImpactClient#9]
ESP doesn't show for Snowmen, Iron golems, Ender dragon, probably more.
-- Enabled all of the targets for ESP, rest show like Pigs, Players and Spiders

**Comment by ZeroMemes** [comment]
Fixed by ClientAPI commit: https://github.com/ZeroMemes/ClientAPI/commit/b83367b8635030f8454af7f062815f265ab2a375

**Comment by ZeroMemes** [comment]
Fixed by https://github.com/ZeroMemes/ClientAPI/commit/b83367b8635030f8454af7f062815f265ab2a375
