### ISSUE TITLE
AutoEat doesn't always work

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#900]
### What happens?
AutoEat sometimes pauses baritone and does not eat at all (just stands and does nothing)

### Exact steps to reproduce?

- Start baritone
- Enable autoeat
- Wait for a while
<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.4 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Baritone with costHeuristic 20, No Slow, AutoEat
- Operating System: Windows 10 64bit

</details>

**Comment by leijurv** [comment]
Will be fixed by @ZeroMemes adding processes <-> modules integrations in 4.5 =D
