### ISSUE TITLE
Raytrace causing serious FPS lag

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#903]
### What happens?
Extreme FPS lag

### Exact steps to reproduce?
Go into a game with a lot of players/entities. (Hypixel duels lobby)
Turn killaura on.
Enable raytrace in killaura.

- Impact Version: 4.4 1.12.2 (Latest)
- Using Optifine? Yes, sir
- Using LiteLoader? No, sir
- Enabled mods: Killaura with raytrace on.

**Comment by ZeroMemes** [comment]
I see the only viable fix is by giving the filter for Kill Aura range a higher priority/order than the filter that performs a raytrace check.

**Comment by MastaNub** [comment]
Just reduce raytrace distance; no need for it to raytrace all visible entities. Matching it with set killaura reach should do the trick, or even just setting it to a constant value, like 6 or 10.

**Comment by ZeroMemes** [comment]
Exactly what I said

**Comment by MastaNub** [comment]
Glad we agree. Now we just need to wait for 4.6 :pray:

**Comment by ZeroMemes** [comment]
Sorry that this issue kind of got lost, thank you @zPeanut for recovering it. This has been fixed in 4.7.
