### ISSUE TITLE
Impact 4.4 with Forge in MultiMC 5

### ISSUE THREAD

**Issue by Xan-Kun** [ImpactDevelopment/ImpactClient#905]
I am trying to use Impact 4.4 with Forge and MultiMC 5

Actually, I am not sure if this is supposed to work at all, I wanted to mark it as question but can't find out how to add that label.

If it should work, I would be happy to help, post stacktraces and write a wiki article about it.

### What happens?
Game doesn't start/crashes.

### Exact steps to reproduce?
- Install Impact 4.4 with the instructions given in 
https://github.com/ImpactDevelopment/ImpactClient/wiki/Installation#installing-impact-with-multimc
- Add forge from within MultiMC.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.4 for 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Fresh install, no mods so far
- Operating System: Windows 10 64bit

</details>

**Comment by leijurv** [comment]
Forge is indeed not supported with any version of Impact

**Comment by MightyKnight** [comment]
Duplicate of #651

**Comment by Xan-Kun** [comment]
Isn't that about 4.3?

**Comment by MightyKnight** [comment]
It was created for 4.3, but is still a bug.
Issue titles shouldn't contain version numbers, I'll change that now.
