### ISSUE TITLE
Draw the fr*cking fonts scaled

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#906]
dont scale up fonts in the gui, just draw them at a larger size.

im making this issue so that brady remembers without me harassing him to do it every day or two

draw the text of clickgui and hud at a different point in the frame where it goes directly to the screen at native resolution (not gui upscaled). multiply the x, y, and height by the gui scaling factor so it goes to the same place and size as it would otherwise.

**Comment by LeafHacker** [comment]
I remember looking into this one (late) night ~~while being pestered by leijurv~~. Looked like creating a larger bitmap when loading the TTF into a texture (`ui.font.FontData.setFont()`) and then tweaking the xy multiplier and/or GL scaling in `ui.font.BasicFontRenderer.drawString()` _might_ work? Should probably be contributed back upstream to CFont if it works too...

**Comment by leijurv** [comment]
<img width="1059" alt="screen shot 2019-02-25 at 12 50 13 pm" src="https://user-images.githubusercontent.com/3837873/53368850-b1f54280-38fe-11e9-8739-c512c7969ab5.png">
<img width="809" alt="screen shot 2019-02-25 at 12 50 24 pm" src="https://user-images.githubusercontent.com/3837873/53368859-b3bf0600-38fe-11e9-9c36-3359cc256d1d.png">

**Comment by usereewrjrjeejr** [comment]
Brooooooooooooo
