### ISSUE TITLE
Impact will download, but won't show up as a version when placed into version folder

### ISSUE THREAD

**Issue by an-old-friend** [ImpactDevelopment/ImpactClient#907]
I download the client, open up the .minecraft folder, open up versions, drop the client into the folder, and then open up minecraft. when I go to choose the version, it does not appear. I am on a mac, if that helps.

**Comment by LeafHacker** [comment]
Are you extracting the correct folder from the `.zip` download?

**Comment by LeafHacker** [comment]
That is the zip file you downloaded. If you double click that you should see a file called `README` and a folder called `1.12.2-Impact_4.4`.

`1.12.2-Impact_4.4` is what you want to copy to your `versions` folder. The `README` file that was next to it explains the install process in a little more detail if you get stuck.
