### ISSUE TITLE
Suggestion: show mob owner

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#909]
### What is your suggestion?

WWE Client has this feature, using .mobowner you can discover who tamed a wolf or a horse, for example. My suggestion is to add this feature to the Nametags module(an addition to [this suggestion](https://github.com/ImpactDevelopment/ImpactClient/issues/624)) or add a similar command to Impact.

### Why is it useful?

It may help to find bases of specific players on 2b2t, since you can know the axis people travel. I made a draw of how it should work:
https://vgy.me/u6ojtF.png

**Comment by leijurv** [comment]
Added in 4.6

https://github.com/ImpactDevelopment/Impact/commit/e325d50ff031fdcdaf769b7f53a26962bd1d77d9

**Comment by usereewrjrjeejr** [comment]
404

**Comment by leijurv** [comment]
yes that is because impact is private the link is for the benefit of bread man and leaf and i

**Comment by usereewrjrjeejr** [comment]
F
