### ISSUE TITLE
Does this client have a Remote Adminstration tool targetted against the users?

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#91]
Does this client have a Remote Adminstration tool targetted against the users? I have asked this in the impact chat but I get very unclear/unrelated answers. I basically want an clear answer that says if it have  a Remote Adminstration tool targetted against the users.

**Comment by olibols** [comment]
You are very very very braindead and you probably have a tumour that needs checking if you can't tell its a JOKE

**Comment by zPeanut** [comment]
Depends on how you fly the Boeing 747-400 from Berlin to New York so if you have an 45° Degree angle, you should use the Concorde which was built in 1972 to fly directly to the site which leads to a Error in which the Player.

**Comment by SuperOP535** [comment]
Thanks for this clear answer, I'm just making sure. (not zpeanuts answer)
