### ISSUE TITLE
Better pseudorandom block rotation

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#910]
https://www.youtube.com/watch?v=6__hO4cc1pA

So that screenshots don't get rekt by this =)

Replacing all orientations with the same one for each block might look a little weird, it should instead be "truly" random instead of based on coordinates. =D

**Comment by SuperOP535** [comment]
or simply use a texture pack to remove the different textures completely

**Comment by 0-x-2-2** [comment]
or use the setting in optifine???

**Comment by SuperOP535** [comment]
yes i forgot about that

**Comment by leijurv** [comment]
impact should make it default on for the skids lol

**Comment by SuperOP535** [comment]
optifine should make it default on for the skids lol

**Comment by leijurv** [comment]
need to figure out if optifine defaults this on now, and if not, if it's plausible for impcat to turn it on maybe
