### ISSUE TITLE
Make Freecam create a new render view entity while leaving mc.player as the real player

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#912]
have been talking about this for forever, just gonna make an issue because its so epic

Render view entity should be a new player, maybe in spectator mode.

Reasons why this would be epic:

- All utility modules would continue to work on the main player while you just move your camera around
  - Baritone continues pathing, kill aura continues killing, auto eat continues eating, etc
- Less detectable since it actually sends movement packets and behaves just like a normal player
- Stability improvements to interactions/integrations with other utility modules since mc.player is no longer faked

Some cool things that could be tacked on:
- Right click a block while in freecam, your real player paths to it? Kind of like a RTS game
  - If you have ender pearls, it could also throw an ender pearl to get there lol
- Break or place blocks while in freecam, the real player realizes those changes using the structure builder or something. I guess it would be creative instead of spectator mode then? 
- lol left click an entity while in freecam, it enables kill aura and starts following

Tricky parts (as I see it):
- While rendering the frame, mc.player stays as mc.player (i'm told it pretty much has to). This has upsides and downsides. For example, it's good that it'll continue to show current health, armor status, etc. A downside is that this makes it harder to have a creative-style or spectator-style UI. 
- Freelook. I'm not sure how this will integrate, it's possible that it'll be no issue at all.
- objectMouseOver needs to stay as the primary player's view, we can just raytrace and render a second selection box for the freecam player I guess
- Mouse movement changes the pitch and yaw of mc.player, not the render view entity.
    - EntityRenderer.java #L1081
    - need to override that
- Sprint keybind? no idea
- Any game input the freecam player performs should not be carried out by the main player. WASD input and clicking behave differently here
  - For WASD: game input for the mc.player is overridden by Baritone [here](https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/utils/InputOverrideHandler.java#L114). Freecam should leave this as-is when Baritone is pathing. When Baritone is not pathing, it needs to override mc.player.movementInput itself to something that ignores all input.
    -  Perhaps something simple like check if mc.player.movementInput is an instance of MovementInputFromOptions, and if so, replace it. This is tricky though, because creating a new MovementInputFromOptions every tick causes the double tap W sprint timer to always activate. Perhaps this could cause the primary player to report that they're sprinting to the server even when they're stationary? I'm not sure. 
    - The freecam player can just use a vanilla MovementInputFromOptions, that'll work fine.
  - For mouse input, it's trickier. Baritone currently suppresses all mouse button input [here](https://github.com/cabaletta/baritone/blob/master/src/launch/java/baritone/launch/mixins/MixinKeyBinding.java#44) while pathing. This will likely need to stay like this. Minecraft's rightClickMouse and related functions will apply to the mc.player, which we don't want (except when pathing calls for it). Therefore we can't allow those keybinds to be pressed, from Minecraft.java's point of view, at any time. Therefore, I suppose any left or right click input while in freecam would have to come from [here](https://github.com/cabaletta/baritone/blob/master/src/launch/java/baritone/launch/mixins/MixinKeyBinding.java#62), where it detects if the button would have been pressed otherwise. This is again compounded by the fact that Baritone only takes control of left and right click while pathing is active,  while freecam wants to disable those all of the time. Not sure how that would work =/

Sort of related to #833, very related to #681. 
Would probably fix #891.

**Comment by SuperOP535** [comment]
Ok now this is epic, reacting with a thumbs up is not enough

**Comment by leijurv** [comment]
Bug because some server packets (like knockback) are not accepted by the player, making it behave abnormally

**Comment by ZeroMemes** [comment]
Okay now this is epic.

(Added in 4,5)

**Comment by leijurv** [comment]
this is so awesome!!!!!!!!!!!
