### ISSUE TITLE
Auto Cheat should set Baritone's allowJumpAt256 to false only on NCP

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#914]
https://github.com/cabaletta/baritone/blob/master/src/api/java/baritone/api/Settings.java#L107

NCP will not allow you to jump over a gap of any length while standing on top of y=256 blocks, it will freeze you midair and make you fall through the gap. It just doesn't allow your y to be above 256 for any reason. Baritone doesn't have auto cheat so it can't really detect this. When auto cheat is off, this setting should default to off, only turn it on if you're sure it's not NCP.

**Comment by 0-x-2-2** [comment]
this is wrong???

**Comment by 0-x-2-2** [comment]
Is [this](https://github.com/NoCheatPlus/NoCheatPlus/blob/f7b2c017fd66838ed2542fba483d7268ff01c2cf/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/moving/MovingListener.java#L2649) what you are talking about.

**Comment by leijurv** [comment]
1.  go on constantiam
2.  go up to y=256
3.  try and jump over a gap
4.  notice you fall every time

**Comment by 0-x-2-2** [comment]
that is not ncp lol

**Comment by leijurv** [comment]
ok bro then i have no idea what im talking about

**Comment by leijurv** [comment]
no?? in the overworld it just makes you fail the jump and fall. no damage

**Comment by 0-x-2-2** [comment]
that is because ur not going over it????

**Comment by 0-x-2-2** [comment]
[proof.zip](https://github.com/ImpactDevelopment/ImpactClient/files/2796400/proof.zip)

**Comment by leijurv** [comment]
yes thats exactly what i mean, you try and jump over a gap at y=256 but it just sets you right back to 256 without dealing damage?? and makes you fail the jump??

**Comment by 0-x-2-2** [comment]
yeah anyways this is not a ncp thing??? this is a custom plugin on cuckstantiam
