### ISSUE TITLE
AutoTool Inventory Management

### ISSUE THREAD

**Issue by TheForgottenKing** [ImpactDevelopment/ImpactClient#921]
### What is your suggestion?

Make it so that AutoTool can move tools from your inventory

### Why is it useful?

So I can dig highways overnight without setting up system-side scripts

**Comment by leijurv** [comment]
Baritone has this rn https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/behavior/InventoryBehavior.java just turn on "inventory" so next impact version should too

**Comment by Thunder33345** [comment]
make it optional too, like replace broken tool, find other tools
like maybe i hid my pickaxe because i dont wanna accidently mine it so options will be nice

**Comment by TheForgottenKing** [comment]
@leijurv so current Impact does not have this, but next version might?

**Comment by leijurv** [comment]
correct, i'm adding the baritone label since baritone has the `allowInventory` setting which will keep your best pick in the first spot on your hotbar, and throwaway blocks on the end of your hotbar. this is in baritone master, so it should be included in 4.5 with no extra effort.

**Comment by leijurv** [comment]
might as well close lol
