### ISSUE TITLE
[Suggestion] Nametags showing advantage %

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#923]
### What is your suggestion?

An option for nametags that calculates armor protection and sword damage to display if you have the advantage in a fight. And maybe an option to display the number on TAB?

### Why is it useful?

It provides advantage on PVP and minigames.

**Comment by leijurv** [comment]
This is hard to calculate since some anticheats (like hypixel) have begun reporting any enchanted items as just "unbreaking 1" to your client so that you get the enchanted render effect, but don't actually know the sharpness / prot level

**Comment by leijurv** [comment]
I don't think this is plausible so I'm adding these labels, but maybe someone else has a different perspective?

**Comment by VitorISs** [comment]
shouldn't this be closed ? it has the "won't add" label :thinking:

**Comment by LeafHacker** [comment]
I mean, by that logic there's no point displaying the enchantments at all... Plenty of servers don't obfuscate the enchants, so there's no reason we can't continue to assume they are correct. Besides, it's not exactly hard for the user to spot if every player has `Unbreaking I`.
