### ISSUE TITLE
Try to fix banbooks for players who use the client

### ISSUE THREAD

**Issue by Perry1900** [ImpactDevelopment/ImpactClient#928]
I want to try to dupe in 2b2t but as I know, the only working dupe as of now is using banbooks.
I think I have an idea of how to prevent banbooks from banning players on the client: before sending packets, check if they are bigger then the max a server can handle before kicking and if they are instead of sending them, send only a drop item packet (I am not sure this will work but why not try)

**Comment by 0-x-2-2** [comment]
You are kicked the same tick as you join before any of the packets you send are processed.

**Comment by Perry1900** [comment]
So how do some clients have this feature and I think it says something about too big packet size when you get bookbanned (it didn't happen to me so im not sure)

**Comment by 0-x-2-2** [comment]
Yeah it has not worked in over a year on 2b2t
