### ISSUE TITLE
Speed compatability with baritone

### ISSUE THREAD

**Issue by Perry1900** [ImpactDevelopment/ImpactClient#929]
As of now, if you turn a hop speed hack on when you use baritone, it walks like norma speed unless you walk normally (I didn't check with other speed hacks).
I tried this on 2b2t but it wasn't the anticheat that prevented me from doing it (I didn't lag back), it was like I held w for half a second and then stopped for half a second.

**Comment by MastaNub** [comment]
Suggest it on baritone github and not here. I like it nonetheless.

**Comment by Perry1900** [comment]
Isn't britone just a feature in impact client?

**Comment by leijurv** [comment]
I'm directing this back to the Impact repo since I have no way of fixing this baritone-side, since Impact is closed source.

**Comment by Perry1900** [comment]
I guess only impact dev team can fix this...

**Comment by ZeroMemes** [comment]
Duplicate of #730.

**Comment by leijurv** [comment]
Okay. In that case the workaround would be to disable baritone's freelook I think?
