### ISSUE TITLE
Impact Client randomly crashes on Ubuntu 18.04

### ISSUE THREAD

**Issue by RobertLBusby** [ImpactDevelopment/ImpactClient#932]
Error: java.util.ConcurrentModificationException

**Comment by ZeroMemes** [comment]
Please provide the full stacktrace/crash log

**Comment by leijurv** [comment]
probably anti vanish lol

**Comment by RobertLBusby** [comment]
Likely so, I have that among other things enabled, the launcher doesnt give me crash info anymore

**Comment by partridge420x** [comment]
speaking of which, when i was using anti vanish i would randomly crash too, and im on windows. so its not just happening on one os

**Comment by leijurv** [comment]
yeah just turn off anti vanish it crashes lol

**Comment by RobertLBusby** [comment]
Very well, everything else works fine, i thought it was just the Ubuntu Launcher, it is my primary OS (my only OS lol)
