### ISSUE TITLE
Over on the website...

### ISSUE THREAD

**Issue by Mik2G** [ImpactDevelopment/ImpactClient#933]
the download, after going through two ad.fly pages, ONLY INCLUDES THE JSON FILE. there is nothing else in the download, only a json file. here's what I got:

[Impact 4.4 for Minecraft 1.12.2.zip](https://github.com/ImpactDevelopment/ImpactClient/files/2874217/Impact.4.4.for.Minecraft.1.12.2.zip)

If it makes any difference, I run windows 8.1

**Comment by MastaNub** [comment]
Just launch the game. It's supposed to be JUST the .json file. There's no .jar.

**Comment by Mik2G** [comment]
that doesnt make sense to me. where should i put the json file

**Comment by MastaNub** [comment]
http://prntscr.com/mmk2bp

**Comment by Mik2G** [comment]
I already tried that. I couldn't find it on the list of versions when I tried to launch the game.

**Comment by Mik2G** [comment]
I'm stupid, thank you
