### ISSUE TITLE
Auto Farm

### ISSUE THREAD

**Issue by Tutuq** [ImpactDevelopment/ImpactClient#936]
### What is your suggestion?

I was wondering if an Auto farm feature would be added to Impact. Basically the same thing that Wurst has for auto farming. In more detail it makes a aura around you that picks and replant crops around you without you having to do anything other then walking around.

**Comment by ZeroMemes** [comment]
This would probably be best implemented in a Baritone process.

**Comment by leijurv** [comment]
when github nitro i want :woke emoji

**Comment by 0-x-2-2** [comment]
![image](https://user-images.githubusercontent.com/9968651/53306365-4b1e4d80-385a-11e9-98cf-6a6521d2ca60.png)

**Comment by leijurv** [comment]
thanks there we go

**Comment by DeeFeeCee** [comment]
This could be applied to nether warts, sugarcane, pumpkins, cocoa beans, plumpkins, trees (replant saplings), those End thingies, & chickens (throw down eggs as they spawn—not the best use of Baritone, but IDK).

I'm not sure if this already exists, but an auto-pickup tool. This way, whatever falls onto the ground will be picked up (or at the very least, the player model will move close enough to the dropped item to be able to pick it up, while respecting the time it takes to "ripen" after being dropped by self or other thing). This is especially helpful for when Baritone leaves mined objects on the ground or when #mine log results in trees dropping apples & saplings.

Also, straight-up making 9x9 tilled farmland with a hole in the middle for water—maximum laziness.

**Comment by DeeFeeCee** [comment]
On second thought, just plug the villager code into Baritone with some fancy tweaks to make it less dumb.

**Comment by 0-x-2-2** [comment]
🦍 🦍 🦍 🦍

**Comment by leijurv** [comment]
Added, `.b farm`
