### ISSUE TITLE
Left or right clicking in freecam happens to your main player

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#938]
ree

**Comment by SuperOP535** [comment]
i don't think that's bad, make an option tm

**Comment by leijurv** [comment]
```Cooper! ♡Today at 12:31 AM
im trying to do that old freecam break block dupe glitch on some server
how tf do i make the freecam on this client work lmfao
it justs makes my players hit when im in free cam
im trying to break blocks in freecam mode```

for example, i think that left and right click should raytrace from the freecam player then act like that, to preserve previous functionality as my dude cooper was complaining

**Comment by LeafHacker** [comment]
Previous functionality was that click actions were performed _by_ the freecam, so in theory you could hit blocks the avatar isn't looking at (although in practice this often doesn't work due to anticheat stuff).

Are you suggesting we should raytrace from the avatar to the interacted-with block and then try and interact with it from the avatar's perspective?

**Comment by aomajn** [comment]
> Previous functionality was that click actions were performed _by_ the freecam, so in theory you could hit blocks the avatar isn't looking at (although in practice this often doesn't work due to anticheat stuff).
> 
> Are you suggesting we should raytrace from the avatar to the interacted-with block and then try and interact with it from the avatar's perspective?

https://youtu.be/ILAUw60-6JM bring back old freecam ree

**Comment by leijurv** [comment]
`Are you suggesting we should raytrace from the avatar to the interacted-with block and then try and interact with it from the avatar's perspective?` yeah

**Comment by LeafHacker** [comment]
The issue is caused by a hook we have that tells the game to raytrace to blocks/entities from the player instead of the camera. This is done so that baritone can interact with stuff from the player's perspective while in Freecam. Unfortunatly it affects everything, not just baritone...

**Comment by leijurv** [comment]
https://youtu.be/dwALd9TLyt0

Quick fix I just applied is to just comment out the Redirect of Minecraft.getRenderViewEntity as called from  EntityRenderer.getMouseOver shrug
Obviously doesn't work with anticheat, but this adds back the previous functionality where you could break/place blocks, open chests, place crystals etc through walls on servers with crappy anticheat.

**Comment by LeafHacker** [comment]
Does this break baritone or is the on-the-fly raytracing fix applied too?

**Comment by leijurv** [comment]
Doesn't break baritone as long as you have latest which raytraces its own objectmouseover =)

**Comment by leijurv** [comment]
ok imma close this; it'll be in hotfix 4 (which is whenever anti hazard is fixed lel)

**Comment by ZeroMemes** [comment]
(Cursed)
