### ISSUE TITLE
Dying should exit freecam

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#940]
If you die, it takes over your screen with the respawn window, but when you click it your camera stays where it was and is all black and you have to realize that its still in dummy freecam xd

**Comment by ZeroMemes** [comment]
Will try and get this out in a hotfix for 4.5

**Comment by leijurv** [comment]
hey at least it isnt #891 ill take this any day =)

**Comment by ZeroMemes** [comment]
Fixed in 4.5, will patch shortly.
