### ISSUE TITLE
Auto Walk doesn't properly handle onLostControl

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#943]
1. be auto walking
2. be freecamming
3. do `.b come`
4. notice that it just stops and doesn't come
5. notice that you have to do `.b come` again for it to do it

**Comment by ZeroMemes** [comment]
`CustomGoalProcess` has a higher priority than `AutoWalkProcess` this is an interesting one.

**Comment by leijurv** [comment]
Btw this works fine for auto mine, doing .b come stops it and makes it come over, only auto walk needs to be told twice

**Comment by ZeroMemes** [comment]
Fixed by Leijurv in 4.6
