### ISSUE TITLE
KillAura

### ISSUE THREAD

**Issue by ItsYoungDaddy** [ImpactDevelopment/ImpactClient#95]
killaura doesnt have a delay and does no damage to mobs

**Comment by hugohindi** [comment]
Right click killaura in the right shift menu and change the mode to delay. Then it has a delay. And that may fix your damage problem too.

**Comment by ItsYoungDaddy** [comment]
It's set to delay

**Comment by LeafHacker** [comment]
Does it hit mobs and do no damage, or not hit them at all? Are mobs enabled under killaura settings?

How fast is "no delay"? Is it slower than Tick mode?

Delay should use the exact weapon cooldown, which varies depending on weapon type - for example fists have a much faster cooldown than swords.

**Comment by ItsYoungDaddy** [comment]
well after messing with the settings i figured out it was the Hit/Miss Ratio
