### ISSUE TITLE
Macros not working

### ISSUE THREAD

**Issue by Tyson-Chicken-Nuggets** [ImpactDevelopment/ImpactClient#954]
Despite /kill working on the server, when a macro is created it won’t work.

**Comment by ZeroMemes** [comment]
1) What server are you trying to use it in
2) Can you post the full macro config file?

**Comment by LeafHacker** [comment]
Do other commands work (which ones do/don't?)

**Comment by Tyson-Chicken-Nuggets** [comment]
I was playing on 2b2t, and now more information, I discovered macros in general don’t work. I wonder if it has something to do with my OS? I’m playing on a MacBook Air from 2015 running Mojave. I don’t think that would cause any problems though.

**Comment by LeafHacker** [comment]
OS shouldn't affect anything.

1. Can you use macros to send /slash commands in a singleplayer creative world?
    - (This definitely works for me)
2. Can you use macros to send normal chat messages? (on 2b, & singleplayer?)
3. Can you use macros for .dot commands? (again, on 2b, & singleplayer?)

**Comment by Tyson-Chicken-Nuggets** [comment]
As I said earlier, it appears as if no macros work at all, at least while I’m on 2b2t. I can’t remember if I’ve tested impact commands, but regular chat messages and /commands don’t seem to work. I haven’t tested it on singleplayer or another multiplayer world yet though, I’ll do that as soon as I have the opportunity.

**Comment by LeafHacker** [comment]
On the 2b queue (assuming same behaviour once logged in) I can't use macros for chat messages of vanilla commands however .commands work.

I wonder if spigot is somehow blocking our usage of `mc.player.sendChatMessage()` 🤔

**Comment by Tyson-Chicken-Nuggets** [comment]
That’s certainly a possibility. I know for a fact that the 2b queue blocks messages and commands, but even within the server no macros seem to work whatsoever. Again, further troubleshooting is still needed, I’ll do it later today if possible.

**Comment by Cerbiac** [comment]
> OS shouldn't affect anything.
> 
> 1. Can you use macros to send /slash commands in a singleplayer creative world?
>    
>    * (This definitely works for me)
> 2. Can you use macros to send normal chat messages? (on 2b, & singleplayer?)
> 3. Can you use macros for .dot commands? (again, on 2b, & singleplayer?)

Tried all of the above, but instead of 2B2T, I used a dedicated server on my computer.
Nothing works for me.

> 1. What server are you trying to use it in
> 2. Can you post the full macro config file?

```
[
  {
    "key": "i",
    "macro": "/summon Zombie"
  },
  {
    "key": "o",
    "macro": "test"
  },
  {
    "key": "p",
    "macro": ".help"
  }
]
```

**Comment by LeafHacker** [comment]
_Possibly_ fixed (in the next version) by using the same keybind system as modules

**Comment by ulysserevient** [comment]
Hi,
same problem here ! Nothing to do to make macros work !
Is there a solution

Minecraft 1.13.2
Impact 4.6
