### ISSUE TITLE
Automine Issue

### ISSUE THREAD

**Issue by willemiscool99** [ImpactDevelopment/ImpactClient#955]
### What happens?
After enabling and disabling Automine the green outlines that it creates around diamond ore stays even after disabling it. 

### Exact steps to reproduce?
-Enable Automine
-Disable Automine

  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.5
- Using Optifine? no
- Using LiteLoader? no
- Enabled mods: none
- Operating System: Windows 10

</details>

**Comment by leijurv** [comment]
I think this has always been the case... you can use `.b goal clear` to remove the goals once, or you can do `.b rendergoal` to turn off their rendering entirely (even when auto mine is active)

**Comment by leijurv** [comment]
oh this is fixed btw
