### ISSUE TITLE
Kill Aura + totem issue

### ISSUE THREAD

**Issue by aomajn** [ImpactDevelopment/ImpactClient#958]
### What happens?
Totem is moving up and down in offhand while using Kill Aura.
[Example](https://youtu.be/VM5if90Cxxk)

### Exact steps to reproduce?
-Toggle Kill Aura while having totem in offhand
-Attack random player

<strong>Additional Client Info</strong>
 

- Impact Version: 4.4 & 4.5
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Kill Aura, Anti Hunger, Auto Reconnect, Criticals, Velocity, Trajectories, Anti Overlay, ESP, Auto Armor, CameraClip, Inventory, Nametags, Anti Blind, No Push, Weather, No Slow, Portals, Light
- Operating System: Windows 8

**Comment by 0-x-2-2** [comment]
The totem is moving because the inventory is being updated probably due to a server plugin.

**Comment by 0-x-2-2** [comment]
This seems to be just visual anyways.
