### ISSUE TITLE
Freecam should show your correct health and hunger

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#959]
HUD in general, like the hurt screen animation, or hearts being black w/ withering, or the hunger bar wobbling, etc

currently it just shows full health / hunger =/

**Comment by ZeroMemes** [comment]
This should be work fine if we just copy the local player stats into the freecam player's LMAO

**Comment by ZeroMemes** [comment]
Fixed all of the things mentioned in 4.5 (Hotfix 3).

**Comment by LeafHacker** [comment]
Added absorption too (missed the hotfix :( )
