### ISSUE TITLE
[Minor Bug?] Inconsistant Spacing

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#96]
![screenshot_1](https://user-images.githubusercontent.com/25800857/29071036-23074bce-7c42-11e7-9087-4f8a53641638.png)

in the main menu the name of the client has inconsistant spacing between the name and the version

**Comment by hugohindi** [comment]
its a feature™

**Comment by LeafHacker** [comment]
Inconsistent with what? There's only one space character, what are you comparing it to?

**Comment by zPeanut** [comment]
it seems like Brady wrote "Impact  4.0"

**Comment by ZeroMemes** [comment]
There is a single spacing character in between "Impact" and the build "4.0". Marking as invalid
