### ISSUE TITLE
It would look cooler in freecam if the pathing player looked forward. turn off freelook when freecam is on?

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#960]
lol

**Comment by ZeroMemes** [comment]
Fixed in 4.5 Hotfix 3

**Comment by leijurv** [comment]
![image](https://user-images.githubusercontent.com/3837873/53394035-dda21800-3952-11e9-958d-734ce600a239.png)

this was a really bad idea and im sorry for suggesting it D=

i really hope theres a hotfix 4 beacuse i do not want you guys to be stuck with this trash

**Comment by LeafHacker** [comment]
What a rollercoaster!
