### ISSUE TITLE
Scaling support for fixed-resolution features

### ISSUE THREAD

**Issue by GG12NoGapple** [ImpactDevelopment/ImpactClient#964]
Hi

**Nametags:**
I'm not sure if this is an issue that only I am experiencing but the nametags are way too small to be read. Even when I try to zoom (optifine zoom) up to the nametags, the nametag gets smaller as I zoom up. They also get smaller when I walk up closer to them. So they basically stay at one constant size. The slider isn't big enough I don't think.
I also have a 4k monitor so I'm not sure if that has anything to do with it.

**Click GUI Scaling:**
So when I try to make the GUI scale bigger in the click gui, the click gui gets huge and half the tabs are off the screen. And when I turn it off, the click gui gets really small. Barely readable. Again, not sure if this is just me but it is pretty annoying. 
I have my vanilla gui scale set to x5. (I have a really big monitor)

Also one more thing. Why can't I interact with blocks while in freecam. I use this feature quite often. Not sure if this is intentional or not.

Thank you :)

GG12NoGapple

**Comment by LeafHacker** [comment]
Relates to #206 

Have to agree, there's a lot of stuff that doesn't handle high dpi monitors - pretty much everything that bypasses minecraft's gui scaling.....

**Comment by leijurv** [comment]
Funny, I had *just* changed the max value of the nametags scale slider from 2 to 4 since I was annoyed by it too.

ClickGUI is separate, not sure how to fix that lol

Interacting with blocks in freecam will probably be added back soon https://github.com/ImpactDevelopment/ImpactClient/issues/938#issuecomment-468004099

**Comment by LeafHacker** [comment]
Just remembered I actually added an option to clickgui that enables Minecraft's GUI scaling. It doesn't work great atm so bug reports would be appreciated

**Comment by leijurv** [comment]
Added in 4.5 and 4.6
