### ISSUE TITLE
Weird NullPointerException which happens only when I try to join 2b

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#983]
Disconnect error : https://pastebin.com/ms1zHVu0

Modules enabled : https://cdn.discordapp.com/attachments/514880901629607947/553358369499643934/unknown.png

**Comment by EvilSourcerer** [comment]
to reproduce just try to connect 2b with the modules i have enabled sorry for having you to enable modules hopefully the disconnect error is helpful

**Comment by LeafHacker** [comment]
Could you attach your `Impact/config/default.json` as this will give us your exact config?

**Comment by EvilSourcerer** [comment]
sure
[default.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2943809/default.txt)

**Comment by FliegendeWurst** [comment]
I'm also getting this error sometimes. It's usually enough to reconnect a few times.

**Comment by EvilSourcerer** [comment]
but why is this... It's been a thing for literally years.

**Comment by ZeroMemes** [comment]
God I'm an idiot, fixed in 4.6, caused by log position!

**Comment by leijurv** [comment]
log position be like
