### ISSUE TITLE
Misc>Inventory>Extra Slots is cleared/dropped upon going through portals.

### ISSUE THREAD

**Issue by Caketaco** [ImpactDevelopment/ImpactClient#989]
When Extra Slots is enabled under Inventory (What allows you to store stuff in your inventory crafting grid) is enabled, and you have items stored in it, they are removed after going through portals.

### What happens?

Your items are removed in your extra slots.
### Exact steps to reproduce?

- Enable Extra Slots in Inventory
- Store preferably unimportant items in your extra slots
- Go through a nether portal
- Ding Dong your items are gone (in your extra slots)

  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.5 for 12.2.2
- Using Optifine?  Yes
- Using LiteLoader?  Yes
- Enabled mods:  Inventory with Shulker Collate, Extra Slots, and Move Around enabled. Nothing else.
- Operating System:  Windows 8.1 64bit

</details>

This was tested in Singleplayer as well as Multiplayer, same result.

[Inventory Diagram](https://cdn.discordapp.com/attachments/514880901629607947/553990283587747840/unknown.png)

### Additional Notes
Depending on what you have enabled, sometimes the items aren't deleted, but just dropped right before you travel through the portal. Here's a recording of that happening: [Video](https://streamable.com/ubo29)

Chances are this might be unpreventable, but you might be able to hotfix a system where if you have 4 empty slots in your main inventory, the items are temporarily moved before traveling through. But hey, I'm not the impact dev here so no clue if that's an easy thing to do ¯\\\_(ツ)\_/¯

**Comment by LeafHacker** [comment]
This sounds like a serverside thing, so Impact probably can't fix it, but still worth investigating.

**Comment by Caketaco** [comment]
> This was tested in **Singleplayer** as well as Multiplayer, same result.

**Comment by LeafHacker** [comment]
> Chances are this might be unpreventable, but you might be able to hotfix a system where if you have 4 empty slots in your main inventory, the items are temporarily moved before traveling through. But hey, I'm not the impact dev here so no clue if that's an easy thing to do ¯\_(ツ)_/¯

Something along these lines is likely the only solution, try to move stuff to the main inventory/offhand, if that fails drop it to prevent deletion.

> > This was tested in **Singleplayer** as well as Multiplayer, same result.

Singleplayer is essentially just multiplayer with the server running locally, there is still a client-side thread and server-side thread. Impact only touches client-side code.

**Comment by Caketaco** [comment]
> Singleplayer is essentially just multiplayer with the server running locally, there is still a client-side thread and server-side thread. Impact only touches client-side code.
oh shoot, gotcha, my bad

**Comment by ZeroMemes** [comment]
This is not something that is effectively preventable, the only reason to use extra slots is if your inventory is full, so allocating **x** amount of slots to throw the items in before you teleport makes no sense. Marking as invalid.
