### ISSUE TITLE
Invisibility hack

### ISSUE THREAD

**Issue by magfag** [ImpactDevelopment/ImpactClient#990]
A way to make your held item and armor not show when you have the invisibility effect. Also maybe a way to have permanent invisibility?

**Comment by lemonsucks** [comment]
i also want this feature

**Comment by 0-x-2-2** [comment]
yes you take off the armor and don't hold a item 👍

**Comment by LeafHacker** [comment]
Maybe a module could avoid telling the server about stuff in your hand/armour until you go to use the item or take damage, but tbh it would be easily detected and probably not worth it to develop
