### ISSUE TITLE
Totems crashing game

### ISSUE THREAD

**Issue by Acedropthebase** [ImpactDevelopment/ImpactClient#993]
When a hopper with Shulker on top (Shulker emptying into hopper). with this set up the totems should be entering the hopper from the Shulker with impact 4.5 take a totem shift click it then boom game crashes. I’ve used this to crash some new kids on 2b who were streaming but please fix.

**Comment by leijurv** [comment]
Hmm, so it does

**Comment by leijurv** [comment]
Fixed in 4.6
