### ISSUE TITLE
Change 4.6 to 5.0

### ISSUE THREAD

**Issue by wholesomeduck** [ImpactDevelopment/ImpactClient#996]
### What is your suggestion?
I think that since Impact is changing to 1.13, it should change versions as well (4.6 changed to 5.0).

### Why is it useful?
Would make it more reasonable, since putting some Impact versions with some Minecraft versions just makes sense.

**Comment by EvilSourcerer** [comment]
bad idea chungus

**Comment by NCBPFluffyBear** [comment]
We should ask Mojang to follow the version of Java because it just makes sense too. Actually, why don't all versions follow the age of the Wirld wide web?

**Comment by ZeroMemes** [comment]
4.6 will likely be a parallel release with both versions for 1.12.2 and 1.13.2

**Comment by 0-x-2-2** [comment]
🦍

**Comment by wholesomeduck** [comment]
I should change my profile pic tbh
